package com.hd.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbApplySealRecordEntityExample {
    /**
     * tb_apply_seal_record
     */
    protected String orderByClause;

    /**
     * tb_apply_seal_record
     */
    protected boolean distinct;

    /**
     * tb_apply_seal_record
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_apply_seal_record
     */
    protected Integer limitStart;

    /**
     * tb_apply_seal_record
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_apply_seal_record
     *
     * @mbg.generated
     */
    public TbApplySealRecordEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_apply_seal_record
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_apply_seal_record
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_apply_seal_record
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_apply_seal_record
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_apply_seal_record
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_apply_seal_record
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_apply_seal_record
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_apply_seal_record
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_apply_seal_record
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_apply_seal_record
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_apply_seal_record
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_apply_seal_record
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_apply_seal_record
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_apply_seal_record
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_apply_seal_record null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRecordIdIsNull() {
            addCriterion("record_id is null");
            return (Criteria) this;
        }

        public Criteria andRecordIdIsNotNull() {
            addCriterion("record_id is not null");
            return (Criteria) this;
        }

        public Criteria andRecordIdEqualTo(String value) {
            addCriterion("record_id =", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotEqualTo(String value) {
            addCriterion("record_id <>", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThan(String value) {
            addCriterion("record_id >", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThanOrEqualTo(String value) {
            addCriterion("record_id >=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThan(String value) {
            addCriterion("record_id <", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThanOrEqualTo(String value) {
            addCriterion("record_id <=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLike(String value) {
            addCriterion("record_id like", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotLike(String value) {
            addCriterion("record_id not like", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdIn(List<String> values) {
            addCriterion("record_id in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotIn(List<String> values) {
            addCriterion("record_id not in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdBetween(String value1, String value2) {
            addCriterion("record_id between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotBetween(String value1, String value2) {
            addCriterion("record_id not between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdIsNull() {
            addCriterion("process_inst_id is null");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdIsNotNull() {
            addCriterion("process_inst_id is not null");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdEqualTo(String value) {
            addCriterion("process_inst_id =", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdNotEqualTo(String value) {
            addCriterion("process_inst_id <>", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdGreaterThan(String value) {
            addCriterion("process_inst_id >", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdGreaterThanOrEqualTo(String value) {
            addCriterion("process_inst_id >=", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdLessThan(String value) {
            addCriterion("process_inst_id <", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdLessThanOrEqualTo(String value) {
            addCriterion("process_inst_id <=", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdLike(String value) {
            addCriterion("process_inst_id like", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdNotLike(String value) {
            addCriterion("process_inst_id not like", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdIn(List<String> values) {
            addCriterion("process_inst_id in", values, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdNotIn(List<String> values) {
            addCriterion("process_inst_id not in", values, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdBetween(String value1, String value2) {
            addCriterion("process_inst_id between", value1, value2, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdNotBetween(String value1, String value2) {
            addCriterion("process_inst_id not between", value1, value2, "processInstId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyIsNull() {
            addCriterion("delegate_task_key is null");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyIsNotNull() {
            addCriterion("delegate_task_key is not null");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyEqualTo(String value) {
            addCriterion("delegate_task_key =", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyNotEqualTo(String value) {
            addCriterion("delegate_task_key <>", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyGreaterThan(String value) {
            addCriterion("delegate_task_key >", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyGreaterThanOrEqualTo(String value) {
            addCriterion("delegate_task_key >=", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyLessThan(String value) {
            addCriterion("delegate_task_key <", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyLessThanOrEqualTo(String value) {
            addCriterion("delegate_task_key <=", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyLike(String value) {
            addCriterion("delegate_task_key like", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyNotLike(String value) {
            addCriterion("delegate_task_key not like", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyIn(List<String> values) {
            addCriterion("delegate_task_key in", values, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyNotIn(List<String> values) {
            addCriterion("delegate_task_key not in", values, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyBetween(String value1, String value2) {
            addCriterion("delegate_task_key between", value1, value2, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyNotBetween(String value1, String value2) {
            addCriterion("delegate_task_key not between", value1, value2, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdIsNull() {
            addCriterion("delegate_task_id is null");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdIsNotNull() {
            addCriterion("delegate_task_id is not null");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdEqualTo(String value) {
            addCriterion("delegate_task_id =", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdNotEqualTo(String value) {
            addCriterion("delegate_task_id <>", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdGreaterThan(String value) {
            addCriterion("delegate_task_id >", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("delegate_task_id >=", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdLessThan(String value) {
            addCriterion("delegate_task_id <", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdLessThanOrEqualTo(String value) {
            addCriterion("delegate_task_id <=", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdLike(String value) {
            addCriterion("delegate_task_id like", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdNotLike(String value) {
            addCriterion("delegate_task_id not like", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdIn(List<String> values) {
            addCriterion("delegate_task_id in", values, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdNotIn(List<String> values) {
            addCriterion("delegate_task_id not in", values, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdBetween(String value1, String value2) {
            addCriterion("delegate_task_id between", value1, value2, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdNotBetween(String value1, String value2) {
            addCriterion("delegate_task_id not between", value1, value2, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIsNull() {
            addCriterion("apply_user_id is null");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIsNotNull() {
            addCriterion("apply_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdEqualTo(String value) {
            addCriterion("apply_user_id =", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotEqualTo(String value) {
            addCriterion("apply_user_id <>", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdGreaterThan(String value) {
            addCriterion("apply_user_id >", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("apply_user_id >=", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdLessThan(String value) {
            addCriterion("apply_user_id <", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdLessThanOrEqualTo(String value) {
            addCriterion("apply_user_id <=", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdLike(String value) {
            addCriterion("apply_user_id like", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotLike(String value) {
            addCriterion("apply_user_id not like", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIn(List<String> values) {
            addCriterion("apply_user_id in", values, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotIn(List<String> values) {
            addCriterion("apply_user_id not in", values, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdBetween(String value1, String value2) {
            addCriterion("apply_user_id between", value1, value2, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotBetween(String value1, String value2) {
            addCriterion("apply_user_id not between", value1, value2, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyReasonIsNull() {
            addCriterion("apply_reason is null");
            return (Criteria) this;
        }

        public Criteria andApplyReasonIsNotNull() {
            addCriterion("apply_reason is not null");
            return (Criteria) this;
        }

        public Criteria andApplyReasonEqualTo(String value) {
            addCriterion("apply_reason =", value, "applyReason");
            return (Criteria) this;
        }

        public Criteria andApplyReasonNotEqualTo(String value) {
            addCriterion("apply_reason <>", value, "applyReason");
            return (Criteria) this;
        }

        public Criteria andApplyReasonGreaterThan(String value) {
            addCriterion("apply_reason >", value, "applyReason");
            return (Criteria) this;
        }

        public Criteria andApplyReasonGreaterThanOrEqualTo(String value) {
            addCriterion("apply_reason >=", value, "applyReason");
            return (Criteria) this;
        }

        public Criteria andApplyReasonLessThan(String value) {
            addCriterion("apply_reason <", value, "applyReason");
            return (Criteria) this;
        }

        public Criteria andApplyReasonLessThanOrEqualTo(String value) {
            addCriterion("apply_reason <=", value, "applyReason");
            return (Criteria) this;
        }

        public Criteria andApplyReasonLike(String value) {
            addCriterion("apply_reason like", value, "applyReason");
            return (Criteria) this;
        }

        public Criteria andApplyReasonNotLike(String value) {
            addCriterion("apply_reason not like", value, "applyReason");
            return (Criteria) this;
        }

        public Criteria andApplyReasonIn(List<String> values) {
            addCriterion("apply_reason in", values, "applyReason");
            return (Criteria) this;
        }

        public Criteria andApplyReasonNotIn(List<String> values) {
            addCriterion("apply_reason not in", values, "applyReason");
            return (Criteria) this;
        }

        public Criteria andApplyReasonBetween(String value1, String value2) {
            addCriterion("apply_reason between", value1, value2, "applyReason");
            return (Criteria) this;
        }

        public Criteria andApplyReasonNotBetween(String value1, String value2) {
            addCriterion("apply_reason not between", value1, value2, "applyReason");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIsNull() {
            addCriterion("apply_time is null");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIsNotNull() {
            addCriterion("apply_time is not null");
            return (Criteria) this;
        }

        public Criteria andApplyTimeEqualTo(Date value) {
            addCriterion("apply_time =", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotEqualTo(Date value) {
            addCriterion("apply_time <>", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeGreaterThan(Date value) {
            addCriterion("apply_time >", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("apply_time >=", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeLessThan(Date value) {
            addCriterion("apply_time <", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeLessThanOrEqualTo(Date value) {
            addCriterion("apply_time <=", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIn(List<Date> values) {
            addCriterion("apply_time in", values, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotIn(List<Date> values) {
            addCriterion("apply_time not in", values, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeBetween(Date value1, Date value2) {
            addCriterion("apply_time between", value1, value2, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotBetween(Date value1, Date value2) {
            addCriterion("apply_time not between", value1, value2, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameIsNull() {
            addCriterion("apply_user_name is null");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameIsNotNull() {
            addCriterion("apply_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameEqualTo(String value) {
            addCriterion("apply_user_name =", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotEqualTo(String value) {
            addCriterion("apply_user_name <>", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameGreaterThan(String value) {
            addCriterion("apply_user_name >", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("apply_user_name >=", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameLessThan(String value) {
            addCriterion("apply_user_name <", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameLessThanOrEqualTo(String value) {
            addCriterion("apply_user_name <=", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameLike(String value) {
            addCriterion("apply_user_name like", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotLike(String value) {
            addCriterion("apply_user_name not like", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameIn(List<String> values) {
            addCriterion("apply_user_name in", values, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotIn(List<String> values) {
            addCriterion("apply_user_name not in", values, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameBetween(String value1, String value2) {
            addCriterion("apply_user_name between", value1, value2, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotBetween(String value1, String value2) {
            addCriterion("apply_user_name not between", value1, value2, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameIsNull() {
            addCriterion("approve_user_name is null");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameIsNotNull() {
            addCriterion("approve_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameEqualTo(String value) {
            addCriterion("approve_user_name =", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameNotEqualTo(String value) {
            addCriterion("approve_user_name <>", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameGreaterThan(String value) {
            addCriterion("approve_user_name >", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("approve_user_name >=", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameLessThan(String value) {
            addCriterion("approve_user_name <", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameLessThanOrEqualTo(String value) {
            addCriterion("approve_user_name <=", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameLike(String value) {
            addCriterion("approve_user_name like", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameNotLike(String value) {
            addCriterion("approve_user_name not like", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameIn(List<String> values) {
            addCriterion("approve_user_name in", values, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameNotIn(List<String> values) {
            addCriterion("approve_user_name not in", values, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameBetween(String value1, String value2) {
            addCriterion("approve_user_name between", value1, value2, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameNotBetween(String value1, String value2) {
            addCriterion("approve_user_name not between", value1, value2, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdIsNull() {
            addCriterion("approve_user_id is null");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdIsNotNull() {
            addCriterion("approve_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdEqualTo(String value) {
            addCriterion("approve_user_id =", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdNotEqualTo(String value) {
            addCriterion("approve_user_id <>", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdGreaterThan(String value) {
            addCriterion("approve_user_id >", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("approve_user_id >=", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdLessThan(String value) {
            addCriterion("approve_user_id <", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdLessThanOrEqualTo(String value) {
            addCriterion("approve_user_id <=", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdLike(String value) {
            addCriterion("approve_user_id like", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdNotLike(String value) {
            addCriterion("approve_user_id not like", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdIn(List<String> values) {
            addCriterion("approve_user_id in", values, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdNotIn(List<String> values) {
            addCriterion("approve_user_id not in", values, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdBetween(String value1, String value2) {
            addCriterion("approve_user_id between", value1, value2, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdNotBetween(String value1, String value2) {
            addCriterion("approve_user_id not between", value1, value2, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIsNull() {
            addCriterion("approve_time is null");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIsNotNull() {
            addCriterion("approve_time is not null");
            return (Criteria) this;
        }

        public Criteria andApproveTimeEqualTo(Date value) {
            addCriterion("approve_time =", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotEqualTo(Date value) {
            addCriterion("approve_time <>", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeGreaterThan(Date value) {
            addCriterion("approve_time >", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("approve_time >=", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeLessThan(Date value) {
            addCriterion("approve_time <", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeLessThanOrEqualTo(Date value) {
            addCriterion("approve_time <=", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIn(List<Date> values) {
            addCriterion("approve_time in", values, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotIn(List<Date> values) {
            addCriterion("approve_time not in", values, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeBetween(Date value1, Date value2) {
            addCriterion("approve_time between", value1, value2, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotBetween(Date value1, Date value2) {
            addCriterion("approve_time not between", value1, value2, "approveTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeIsNull() {
            addCriterion("complete_time is null");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeIsNotNull() {
            addCriterion("complete_time is not null");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeEqualTo(Date value) {
            addCriterion("complete_time =", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeNotEqualTo(Date value) {
            addCriterion("complete_time <>", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeGreaterThan(Date value) {
            addCriterion("complete_time >", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("complete_time >=", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeLessThan(Date value) {
            addCriterion("complete_time <", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeLessThanOrEqualTo(Date value) {
            addCriterion("complete_time <=", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeIn(List<Date> values) {
            addCriterion("complete_time in", values, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeNotIn(List<Date> values) {
            addCriterion("complete_time not in", values, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeBetween(Date value1, Date value2) {
            addCriterion("complete_time between", value1, value2, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeNotBetween(Date value1, Date value2) {
            addCriterion("complete_time not between", value1, value2, "completeTime");
            return (Criteria) this;
        }

        public Criteria andVerifyStateIsNull() {
            addCriterion("verify_state is null");
            return (Criteria) this;
        }

        public Criteria andVerifyStateIsNotNull() {
            addCriterion("verify_state is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyStateEqualTo(String value) {
            addCriterion("verify_state =", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateNotEqualTo(String value) {
            addCriterion("verify_state <>", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateGreaterThan(String value) {
            addCriterion("verify_state >", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateGreaterThanOrEqualTo(String value) {
            addCriterion("verify_state >=", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateLessThan(String value) {
            addCriterion("verify_state <", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateLessThanOrEqualTo(String value) {
            addCriterion("verify_state <=", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateLike(String value) {
            addCriterion("verify_state like", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateNotLike(String value) {
            addCriterion("verify_state not like", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateIn(List<String> values) {
            addCriterion("verify_state in", values, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateNotIn(List<String> values) {
            addCriterion("verify_state not in", values, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateBetween(String value1, String value2) {
            addCriterion("verify_state between", value1, value2, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateNotBetween(String value1, String value2) {
            addCriterion("verify_state not between", value1, value2, "verifyState");
            return (Criteria) this;
        }

        public Criteria andRejectReasonIsNull() {
            addCriterion("reject_reason is null");
            return (Criteria) this;
        }

        public Criteria andRejectReasonIsNotNull() {
            addCriterion("reject_reason is not null");
            return (Criteria) this;
        }

        public Criteria andRejectReasonEqualTo(String value) {
            addCriterion("reject_reason =", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonNotEqualTo(String value) {
            addCriterion("reject_reason <>", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonGreaterThan(String value) {
            addCriterion("reject_reason >", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonGreaterThanOrEqualTo(String value) {
            addCriterion("reject_reason >=", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonLessThan(String value) {
            addCriterion("reject_reason <", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonLessThanOrEqualTo(String value) {
            addCriterion("reject_reason <=", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonLike(String value) {
            addCriterion("reject_reason like", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonNotLike(String value) {
            addCriterion("reject_reason not like", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonIn(List<String> values) {
            addCriterion("reject_reason in", values, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonNotIn(List<String> values) {
            addCriterion("reject_reason not in", values, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonBetween(String value1, String value2) {
            addCriterion("reject_reason between", value1, value2, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonNotBetween(String value1, String value2) {
            addCriterion("reject_reason not between", value1, value2, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdIsNull() {
            addCriterion("seal__type_id is null");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdIsNotNull() {
            addCriterion("seal__type_id is not null");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdEqualTo(String value) {
            addCriterion("seal__type_id =", value, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdNotEqualTo(String value) {
            addCriterion("seal__type_id <>", value, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdGreaterThan(String value) {
            addCriterion("seal__type_id >", value, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("seal__type_id >=", value, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdLessThan(String value) {
            addCriterion("seal__type_id <", value, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdLessThanOrEqualTo(String value) {
            addCriterion("seal__type_id <=", value, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdLike(String value) {
            addCriterion("seal__type_id like", value, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdNotLike(String value) {
            addCriterion("seal__type_id not like", value, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdIn(List<String> values) {
            addCriterion("seal__type_id in", values, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdNotIn(List<String> values) {
            addCriterion("seal__type_id not in", values, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdBetween(String value1, String value2) {
            addCriterion("seal__type_id between", value1, value2, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdNotBetween(String value1, String value2) {
            addCriterion("seal__type_id not between", value1, value2, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andIsPagingSealIsNull() {
            addCriterion("is_paging_seal is null");
            return (Criteria) this;
        }

        public Criteria andIsPagingSealIsNotNull() {
            addCriterion("is_paging_seal is not null");
            return (Criteria) this;
        }

        public Criteria andIsPagingSealEqualTo(Integer value) {
            addCriterion("is_paging_seal =", value, "isPagingSeal");
            return (Criteria) this;
        }

        public Criteria andIsPagingSealNotEqualTo(Integer value) {
            addCriterion("is_paging_seal <>", value, "isPagingSeal");
            return (Criteria) this;
        }

        public Criteria andIsPagingSealGreaterThan(Integer value) {
            addCriterion("is_paging_seal >", value, "isPagingSeal");
            return (Criteria) this;
        }

        public Criteria andIsPagingSealGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_paging_seal >=", value, "isPagingSeal");
            return (Criteria) this;
        }

        public Criteria andIsPagingSealLessThan(Integer value) {
            addCriterion("is_paging_seal <", value, "isPagingSeal");
            return (Criteria) this;
        }

        public Criteria andIsPagingSealLessThanOrEqualTo(Integer value) {
            addCriterion("is_paging_seal <=", value, "isPagingSeal");
            return (Criteria) this;
        }

        public Criteria andIsPagingSealIn(List<Integer> values) {
            addCriterion("is_paging_seal in", values, "isPagingSeal");
            return (Criteria) this;
        }

        public Criteria andIsPagingSealNotIn(List<Integer> values) {
            addCriterion("is_paging_seal not in", values, "isPagingSeal");
            return (Criteria) this;
        }

        public Criteria andIsPagingSealBetween(Integer value1, Integer value2) {
            addCriterion("is_paging_seal between", value1, value2, "isPagingSeal");
            return (Criteria) this;
        }

        public Criteria andIsPagingSealNotBetween(Integer value1, Integer value2) {
            addCriterion("is_paging_seal not between", value1, value2, "isPagingSeal");
            return (Criteria) this;
        }

        public Criteria andAttachmentNameIsNull() {
            addCriterion("attachment_name is null");
            return (Criteria) this;
        }

        public Criteria andAttachmentNameIsNotNull() {
            addCriterion("attachment_name is not null");
            return (Criteria) this;
        }

        public Criteria andAttachmentNameEqualTo(String value) {
            addCriterion("attachment_name =", value, "attachmentName");
            return (Criteria) this;
        }

        public Criteria andAttachmentNameNotEqualTo(String value) {
            addCriterion("attachment_name <>", value, "attachmentName");
            return (Criteria) this;
        }

        public Criteria andAttachmentNameGreaterThan(String value) {
            addCriterion("attachment_name >", value, "attachmentName");
            return (Criteria) this;
        }

        public Criteria andAttachmentNameGreaterThanOrEqualTo(String value) {
            addCriterion("attachment_name >=", value, "attachmentName");
            return (Criteria) this;
        }

        public Criteria andAttachmentNameLessThan(String value) {
            addCriterion("attachment_name <", value, "attachmentName");
            return (Criteria) this;
        }

        public Criteria andAttachmentNameLessThanOrEqualTo(String value) {
            addCriterion("attachment_name <=", value, "attachmentName");
            return (Criteria) this;
        }

        public Criteria andAttachmentNameLike(String value) {
            addCriterion("attachment_name like", value, "attachmentName");
            return (Criteria) this;
        }

        public Criteria andAttachmentNameNotLike(String value) {
            addCriterion("attachment_name not like", value, "attachmentName");
            return (Criteria) this;
        }

        public Criteria andAttachmentNameIn(List<String> values) {
            addCriterion("attachment_name in", values, "attachmentName");
            return (Criteria) this;
        }

        public Criteria andAttachmentNameNotIn(List<String> values) {
            addCriterion("attachment_name not in", values, "attachmentName");
            return (Criteria) this;
        }

        public Criteria andAttachmentNameBetween(String value1, String value2) {
            addCriterion("attachment_name between", value1, value2, "attachmentName");
            return (Criteria) this;
        }

        public Criteria andAttachmentNameNotBetween(String value1, String value2) {
            addCriterion("attachment_name not between", value1, value2, "attachmentName");
            return (Criteria) this;
        }

        public Criteria andAttachmentPathIsNull() {
            addCriterion("attachment_path is null");
            return (Criteria) this;
        }

        public Criteria andAttachmentPathIsNotNull() {
            addCriterion("attachment_path is not null");
            return (Criteria) this;
        }

        public Criteria andAttachmentPathEqualTo(String value) {
            addCriterion("attachment_path =", value, "attachmentPath");
            return (Criteria) this;
        }

        public Criteria andAttachmentPathNotEqualTo(String value) {
            addCriterion("attachment_path <>", value, "attachmentPath");
            return (Criteria) this;
        }

        public Criteria andAttachmentPathGreaterThan(String value) {
            addCriterion("attachment_path >", value, "attachmentPath");
            return (Criteria) this;
        }

        public Criteria andAttachmentPathGreaterThanOrEqualTo(String value) {
            addCriterion("attachment_path >=", value, "attachmentPath");
            return (Criteria) this;
        }

        public Criteria andAttachmentPathLessThan(String value) {
            addCriterion("attachment_path <", value, "attachmentPath");
            return (Criteria) this;
        }

        public Criteria andAttachmentPathLessThanOrEqualTo(String value) {
            addCriterion("attachment_path <=", value, "attachmentPath");
            return (Criteria) this;
        }

        public Criteria andAttachmentPathLike(String value) {
            addCriterion("attachment_path like", value, "attachmentPath");
            return (Criteria) this;
        }

        public Criteria andAttachmentPathNotLike(String value) {
            addCriterion("attachment_path not like", value, "attachmentPath");
            return (Criteria) this;
        }

        public Criteria andAttachmentPathIn(List<String> values) {
            addCriterion("attachment_path in", values, "attachmentPath");
            return (Criteria) this;
        }

        public Criteria andAttachmentPathNotIn(List<String> values) {
            addCriterion("attachment_path not in", values, "attachmentPath");
            return (Criteria) this;
        }

        public Criteria andAttachmentPathBetween(String value1, String value2) {
            addCriterion("attachment_path between", value1, value2, "attachmentPath");
            return (Criteria) this;
        }

        public Criteria andAttachmentPathNotBetween(String value1, String value2) {
            addCriterion("attachment_path not between", value1, value2, "attachmentPath");
            return (Criteria) this;
        }

        public Criteria andIsSignaturedIsNull() {
            addCriterion("is_signatured is null");
            return (Criteria) this;
        }

        public Criteria andIsSignaturedIsNotNull() {
            addCriterion("is_signatured is not null");
            return (Criteria) this;
        }

        public Criteria andIsSignaturedEqualTo(String value) {
            addCriterion("is_signatured =", value, "isSignatured");
            return (Criteria) this;
        }

        public Criteria andIsSignaturedNotEqualTo(String value) {
            addCriterion("is_signatured <>", value, "isSignatured");
            return (Criteria) this;
        }

        public Criteria andIsSignaturedGreaterThan(String value) {
            addCriterion("is_signatured >", value, "isSignatured");
            return (Criteria) this;
        }

        public Criteria andIsSignaturedGreaterThanOrEqualTo(String value) {
            addCriterion("is_signatured >=", value, "isSignatured");
            return (Criteria) this;
        }

        public Criteria andIsSignaturedLessThan(String value) {
            addCriterion("is_signatured <", value, "isSignatured");
            return (Criteria) this;
        }

        public Criteria andIsSignaturedLessThanOrEqualTo(String value) {
            addCriterion("is_signatured <=", value, "isSignatured");
            return (Criteria) this;
        }

        public Criteria andIsSignaturedLike(String value) {
            addCriterion("is_signatured like", value, "isSignatured");
            return (Criteria) this;
        }

        public Criteria andIsSignaturedNotLike(String value) {
            addCriterion("is_signatured not like", value, "isSignatured");
            return (Criteria) this;
        }

        public Criteria andIsSignaturedIn(List<String> values) {
            addCriterion("is_signatured in", values, "isSignatured");
            return (Criteria) this;
        }

        public Criteria andIsSignaturedNotIn(List<String> values) {
            addCriterion("is_signatured not in", values, "isSignatured");
            return (Criteria) this;
        }

        public Criteria andIsSignaturedBetween(String value1, String value2) {
            addCriterion("is_signatured between", value1, value2, "isSignatured");
            return (Criteria) this;
        }

        public Criteria andIsSignaturedNotBetween(String value1, String value2) {
            addCriterion("is_signatured not between", value1, value2, "isSignatured");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNull() {
            addCriterion("is_del_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNotNull() {
            addCriterion("is_del_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgEqualTo(String value) {
            addCriterion("is_del_flg =", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotEqualTo(String value) {
            addCriterion("is_del_flg <>", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThan(String value) {
            addCriterion("is_del_flg >", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_del_flg >=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThan(String value) {
            addCriterion("is_del_flg <", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThanOrEqualTo(String value) {
            addCriterion("is_del_flg <=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLike(String value) {
            addCriterion("is_del_flg like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotLike(String value) {
            addCriterion("is_del_flg not like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIn(List<String> values) {
            addCriterion("is_del_flg in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotIn(List<String> values) {
            addCriterion("is_del_flg not in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgBetween(String value1, String value2) {
            addCriterion("is_del_flg between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotBetween(String value1, String value2) {
            addCriterion("is_del_flg not between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }
    }

    /**
     * tb_apply_seal_record
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_apply_seal_record null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}