package com.hd.common.entity;

import java.util.ArrayList;
import java.util.List;

public class TbDictSealEntityExample {
    /**
     * tb_dict_seal
     */
    protected String orderByClause;

    /**
     * tb_dict_seal
     */
    protected boolean distinct;

    /**
     * tb_dict_seal
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_dict_seal
     */
    protected Integer limitStart;

    /**
     * tb_dict_seal
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_seal
     *
     * @mbg.generated
     */
    public TbDictSealEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_seal
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_seal
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_seal
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_seal
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_seal
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_seal
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_seal
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_seal
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_seal
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_seal
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_seal
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_seal
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_seal
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict_seal
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_dict_seal null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSealTypeIdIsNull() {
            addCriterion("seal__type_id is null");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdIsNotNull() {
            addCriterion("seal__type_id is not null");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdEqualTo(String value) {
            addCriterion("seal__type_id =", value, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdNotEqualTo(String value) {
            addCriterion("seal__type_id <>", value, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdGreaterThan(String value) {
            addCriterion("seal__type_id >", value, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("seal__type_id >=", value, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdLessThan(String value) {
            addCriterion("seal__type_id <", value, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdLessThanOrEqualTo(String value) {
            addCriterion("seal__type_id <=", value, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdLike(String value) {
            addCriterion("seal__type_id like", value, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdNotLike(String value) {
            addCriterion("seal__type_id not like", value, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdIn(List<String> values) {
            addCriterion("seal__type_id in", values, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdNotIn(List<String> values) {
            addCriterion("seal__type_id not in", values, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdBetween(String value1, String value2) {
            addCriterion("seal__type_id between", value1, value2, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeIdNotBetween(String value1, String value2) {
            addCriterion("seal__type_id not between", value1, value2, "sealTypeId");
            return (Criteria) this;
        }

        public Criteria andSealTypeTextIsNull() {
            addCriterion("seal_type_text is null");
            return (Criteria) this;
        }

        public Criteria andSealTypeTextIsNotNull() {
            addCriterion("seal_type_text is not null");
            return (Criteria) this;
        }

        public Criteria andSealTypeTextEqualTo(String value) {
            addCriterion("seal_type_text =", value, "sealTypeText");
            return (Criteria) this;
        }

        public Criteria andSealTypeTextNotEqualTo(String value) {
            addCriterion("seal_type_text <>", value, "sealTypeText");
            return (Criteria) this;
        }

        public Criteria andSealTypeTextGreaterThan(String value) {
            addCriterion("seal_type_text >", value, "sealTypeText");
            return (Criteria) this;
        }

        public Criteria andSealTypeTextGreaterThanOrEqualTo(String value) {
            addCriterion("seal_type_text >=", value, "sealTypeText");
            return (Criteria) this;
        }

        public Criteria andSealTypeTextLessThan(String value) {
            addCriterion("seal_type_text <", value, "sealTypeText");
            return (Criteria) this;
        }

        public Criteria andSealTypeTextLessThanOrEqualTo(String value) {
            addCriterion("seal_type_text <=", value, "sealTypeText");
            return (Criteria) this;
        }

        public Criteria andSealTypeTextLike(String value) {
            addCriterion("seal_type_text like", value, "sealTypeText");
            return (Criteria) this;
        }

        public Criteria andSealTypeTextNotLike(String value) {
            addCriterion("seal_type_text not like", value, "sealTypeText");
            return (Criteria) this;
        }

        public Criteria andSealTypeTextIn(List<String> values) {
            addCriterion("seal_type_text in", values, "sealTypeText");
            return (Criteria) this;
        }

        public Criteria andSealTypeTextNotIn(List<String> values) {
            addCriterion("seal_type_text not in", values, "sealTypeText");
            return (Criteria) this;
        }

        public Criteria andSealTypeTextBetween(String value1, String value2) {
            addCriterion("seal_type_text between", value1, value2, "sealTypeText");
            return (Criteria) this;
        }

        public Criteria andSealTypeTextNotBetween(String value1, String value2) {
            addCriterion("seal_type_text not between", value1, value2, "sealTypeText");
            return (Criteria) this;
        }
    }

    /**
     * tb_dict_seal
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_dict_seal null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}