package com.hd.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbExpertOpinionRelationEntityExample {
    /**
     * tb_expert_opinion_relation
     */
    protected String orderByClause;

    /**
     * tb_expert_opinion_relation
     */
    protected boolean distinct;

    /**
     * tb_expert_opinion_relation
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_expert_opinion_relation
     */
    protected Integer limitStart;

    /**
     * tb_expert_opinion_relation
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    public TbExpertOpinionRelationEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_expert_opinion_relation null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andExpertOpinionIdIsNull() {
            addCriterion("expert_opinion_id is null");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionIdIsNotNull() {
            addCriterion("expert_opinion_id is not null");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionIdEqualTo(String value) {
            addCriterion("expert_opinion_id =", value, "expertOpinionId");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionIdNotEqualTo(String value) {
            addCriterion("expert_opinion_id <>", value, "expertOpinionId");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionIdGreaterThan(String value) {
            addCriterion("expert_opinion_id >", value, "expertOpinionId");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionIdGreaterThanOrEqualTo(String value) {
            addCriterion("expert_opinion_id >=", value, "expertOpinionId");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionIdLessThan(String value) {
            addCriterion("expert_opinion_id <", value, "expertOpinionId");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionIdLessThanOrEqualTo(String value) {
            addCriterion("expert_opinion_id <=", value, "expertOpinionId");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionIdLike(String value) {
            addCriterion("expert_opinion_id like", value, "expertOpinionId");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionIdNotLike(String value) {
            addCriterion("expert_opinion_id not like", value, "expertOpinionId");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionIdIn(List<String> values) {
            addCriterion("expert_opinion_id in", values, "expertOpinionId");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionIdNotIn(List<String> values) {
            addCriterion("expert_opinion_id not in", values, "expertOpinionId");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionIdBetween(String value1, String value2) {
            addCriterion("expert_opinion_id between", value1, value2, "expertOpinionId");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionIdNotBetween(String value1, String value2) {
            addCriterion("expert_opinion_id not between", value1, value2, "expertOpinionId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("task_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("task_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(String value) {
            addCriterion("task_id =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(String value) {
            addCriterion("task_id <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(String value) {
            addCriterion("task_id >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("task_id >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(String value) {
            addCriterion("task_id <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(String value) {
            addCriterion("task_id <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLike(String value) {
            addCriterion("task_id like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotLike(String value) {
            addCriterion("task_id not like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<String> values) {
            addCriterion("task_id in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<String> values) {
            addCriterion("task_id not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(String value1, String value2) {
            addCriterion("task_id between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(String value1, String value2) {
            addCriterion("task_id not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andPurchaserIsNull() {
            addCriterion("purchaser is null");
            return (Criteria) this;
        }

        public Criteria andPurchaserIsNotNull() {
            addCriterion("purchaser is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaserEqualTo(String value) {
            addCriterion("purchaser =", value, "purchaser");
            return (Criteria) this;
        }

        public Criteria andPurchaserNotEqualTo(String value) {
            addCriterion("purchaser <>", value, "purchaser");
            return (Criteria) this;
        }

        public Criteria andPurchaserGreaterThan(String value) {
            addCriterion("purchaser >", value, "purchaser");
            return (Criteria) this;
        }

        public Criteria andPurchaserGreaterThanOrEqualTo(String value) {
            addCriterion("purchaser >=", value, "purchaser");
            return (Criteria) this;
        }

        public Criteria andPurchaserLessThan(String value) {
            addCriterion("purchaser <", value, "purchaser");
            return (Criteria) this;
        }

        public Criteria andPurchaserLessThanOrEqualTo(String value) {
            addCriterion("purchaser <=", value, "purchaser");
            return (Criteria) this;
        }

        public Criteria andPurchaserLike(String value) {
            addCriterion("purchaser like", value, "purchaser");
            return (Criteria) this;
        }

        public Criteria andPurchaserNotLike(String value) {
            addCriterion("purchaser not like", value, "purchaser");
            return (Criteria) this;
        }

        public Criteria andPurchaserIn(List<String> values) {
            addCriterion("purchaser in", values, "purchaser");
            return (Criteria) this;
        }

        public Criteria andPurchaserNotIn(List<String> values) {
            addCriterion("purchaser not in", values, "purchaser");
            return (Criteria) this;
        }

        public Criteria andPurchaserBetween(String value1, String value2) {
            addCriterion("purchaser between", value1, value2, "purchaser");
            return (Criteria) this;
        }

        public Criteria andPurchaserNotBetween(String value1, String value2) {
            addCriterion("purchaser not between", value1, value2, "purchaser");
            return (Criteria) this;
        }

        public Criteria andAgentOrgIsNull() {
            addCriterion("agent_org is null");
            return (Criteria) this;
        }

        public Criteria andAgentOrgIsNotNull() {
            addCriterion("agent_org is not null");
            return (Criteria) this;
        }

        public Criteria andAgentOrgEqualTo(String value) {
            addCriterion("agent_org =", value, "agentOrg");
            return (Criteria) this;
        }

        public Criteria andAgentOrgNotEqualTo(String value) {
            addCriterion("agent_org <>", value, "agentOrg");
            return (Criteria) this;
        }

        public Criteria andAgentOrgGreaterThan(String value) {
            addCriterion("agent_org >", value, "agentOrg");
            return (Criteria) this;
        }

        public Criteria andAgentOrgGreaterThanOrEqualTo(String value) {
            addCriterion("agent_org >=", value, "agentOrg");
            return (Criteria) this;
        }

        public Criteria andAgentOrgLessThan(String value) {
            addCriterion("agent_org <", value, "agentOrg");
            return (Criteria) this;
        }

        public Criteria andAgentOrgLessThanOrEqualTo(String value) {
            addCriterion("agent_org <=", value, "agentOrg");
            return (Criteria) this;
        }

        public Criteria andAgentOrgLike(String value) {
            addCriterion("agent_org like", value, "agentOrg");
            return (Criteria) this;
        }

        public Criteria andAgentOrgNotLike(String value) {
            addCriterion("agent_org not like", value, "agentOrg");
            return (Criteria) this;
        }

        public Criteria andAgentOrgIn(List<String> values) {
            addCriterion("agent_org in", values, "agentOrg");
            return (Criteria) this;
        }

        public Criteria andAgentOrgNotIn(List<String> values) {
            addCriterion("agent_org not in", values, "agentOrg");
            return (Criteria) this;
        }

        public Criteria andAgentOrgBetween(String value1, String value2) {
            addCriterion("agent_org between", value1, value2, "agentOrg");
            return (Criteria) this;
        }

        public Criteria andAgentOrgNotBetween(String value1, String value2) {
            addCriterion("agent_org not between", value1, value2, "agentOrg");
            return (Criteria) this;
        }

        public Criteria andPurchaserTypeIsNull() {
            addCriterion("purchaser_type is null");
            return (Criteria) this;
        }

        public Criteria andPurchaserTypeIsNotNull() {
            addCriterion("purchaser_type is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaserTypeEqualTo(String value) {
            addCriterion("purchaser_type =", value, "purchaserType");
            return (Criteria) this;
        }

        public Criteria andPurchaserTypeNotEqualTo(String value) {
            addCriterion("purchaser_type <>", value, "purchaserType");
            return (Criteria) this;
        }

        public Criteria andPurchaserTypeGreaterThan(String value) {
            addCriterion("purchaser_type >", value, "purchaserType");
            return (Criteria) this;
        }

        public Criteria andPurchaserTypeGreaterThanOrEqualTo(String value) {
            addCriterion("purchaser_type >=", value, "purchaserType");
            return (Criteria) this;
        }

        public Criteria andPurchaserTypeLessThan(String value) {
            addCriterion("purchaser_type <", value, "purchaserType");
            return (Criteria) this;
        }

        public Criteria andPurchaserTypeLessThanOrEqualTo(String value) {
            addCriterion("purchaser_type <=", value, "purchaserType");
            return (Criteria) this;
        }

        public Criteria andPurchaserTypeLike(String value) {
            addCriterion("purchaser_type like", value, "purchaserType");
            return (Criteria) this;
        }

        public Criteria andPurchaserTypeNotLike(String value) {
            addCriterion("purchaser_type not like", value, "purchaserType");
            return (Criteria) this;
        }

        public Criteria andPurchaserTypeIn(List<String> values) {
            addCriterion("purchaser_type in", values, "purchaserType");
            return (Criteria) this;
        }

        public Criteria andPurchaserTypeNotIn(List<String> values) {
            addCriterion("purchaser_type not in", values, "purchaserType");
            return (Criteria) this;
        }

        public Criteria andPurchaserTypeBetween(String value1, String value2) {
            addCriterion("purchaser_type between", value1, value2, "purchaserType");
            return (Criteria) this;
        }

        public Criteria andPurchaserTypeNotBetween(String value1, String value2) {
            addCriterion("purchaser_type not between", value1, value2, "purchaserType");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionIsNull() {
            addCriterion("expert_opinion is null");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionIsNotNull() {
            addCriterion("expert_opinion is not null");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionEqualTo(String value) {
            addCriterion("expert_opinion =", value, "expertOpinion");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionNotEqualTo(String value) {
            addCriterion("expert_opinion <>", value, "expertOpinion");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionGreaterThan(String value) {
            addCriterion("expert_opinion >", value, "expertOpinion");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionGreaterThanOrEqualTo(String value) {
            addCriterion("expert_opinion >=", value, "expertOpinion");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionLessThan(String value) {
            addCriterion("expert_opinion <", value, "expertOpinion");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionLessThanOrEqualTo(String value) {
            addCriterion("expert_opinion <=", value, "expertOpinion");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionLike(String value) {
            addCriterion("expert_opinion like", value, "expertOpinion");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionNotLike(String value) {
            addCriterion("expert_opinion not like", value, "expertOpinion");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionIn(List<String> values) {
            addCriterion("expert_opinion in", values, "expertOpinion");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionNotIn(List<String> values) {
            addCriterion("expert_opinion not in", values, "expertOpinion");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionBetween(String value1, String value2) {
            addCriterion("expert_opinion between", value1, value2, "expertOpinion");
            return (Criteria) this;
        }

        public Criteria andExpertOpinionNotBetween(String value1, String value2) {
            addCriterion("expert_opinion not between", value1, value2, "expertOpinion");
            return (Criteria) this;
        }

        public Criteria andExpertSignIsNull() {
            addCriterion("expert_sign is null");
            return (Criteria) this;
        }

        public Criteria andExpertSignIsNotNull() {
            addCriterion("expert_sign is not null");
            return (Criteria) this;
        }

        public Criteria andExpertSignEqualTo(String value) {
            addCriterion("expert_sign =", value, "expertSign");
            return (Criteria) this;
        }

        public Criteria andExpertSignNotEqualTo(String value) {
            addCriterion("expert_sign <>", value, "expertSign");
            return (Criteria) this;
        }

        public Criteria andExpertSignGreaterThan(String value) {
            addCriterion("expert_sign >", value, "expertSign");
            return (Criteria) this;
        }

        public Criteria andExpertSignGreaterThanOrEqualTo(String value) {
            addCriterion("expert_sign >=", value, "expertSign");
            return (Criteria) this;
        }

        public Criteria andExpertSignLessThan(String value) {
            addCriterion("expert_sign <", value, "expertSign");
            return (Criteria) this;
        }

        public Criteria andExpertSignLessThanOrEqualTo(String value) {
            addCriterion("expert_sign <=", value, "expertSign");
            return (Criteria) this;
        }

        public Criteria andExpertSignLike(String value) {
            addCriterion("expert_sign like", value, "expertSign");
            return (Criteria) this;
        }

        public Criteria andExpertSignNotLike(String value) {
            addCriterion("expert_sign not like", value, "expertSign");
            return (Criteria) this;
        }

        public Criteria andExpertSignIn(List<String> values) {
            addCriterion("expert_sign in", values, "expertSign");
            return (Criteria) this;
        }

        public Criteria andExpertSignNotIn(List<String> values) {
            addCriterion("expert_sign not in", values, "expertSign");
            return (Criteria) this;
        }

        public Criteria andExpertSignBetween(String value1, String value2) {
            addCriterion("expert_sign between", value1, value2, "expertSign");
            return (Criteria) this;
        }

        public Criteria andExpertSignNotBetween(String value1, String value2) {
            addCriterion("expert_sign not between", value1, value2, "expertSign");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andProveTimeIsNull() {
            addCriterion("prove_time is null");
            return (Criteria) this;
        }

        public Criteria andProveTimeIsNotNull() {
            addCriterion("prove_time is not null");
            return (Criteria) this;
        }

        public Criteria andProveTimeEqualTo(Date value) {
            addCriterion("prove_time =", value, "proveTime");
            return (Criteria) this;
        }

        public Criteria andProveTimeNotEqualTo(Date value) {
            addCriterion("prove_time <>", value, "proveTime");
            return (Criteria) this;
        }

        public Criteria andProveTimeGreaterThan(Date value) {
            addCriterion("prove_time >", value, "proveTime");
            return (Criteria) this;
        }

        public Criteria andProveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("prove_time >=", value, "proveTime");
            return (Criteria) this;
        }

        public Criteria andProveTimeLessThan(Date value) {
            addCriterion("prove_time <", value, "proveTime");
            return (Criteria) this;
        }

        public Criteria andProveTimeLessThanOrEqualTo(Date value) {
            addCriterion("prove_time <=", value, "proveTime");
            return (Criteria) this;
        }

        public Criteria andProveTimeIn(List<Date> values) {
            addCriterion("prove_time in", values, "proveTime");
            return (Criteria) this;
        }

        public Criteria andProveTimeNotIn(List<Date> values) {
            addCriterion("prove_time not in", values, "proveTime");
            return (Criteria) this;
        }

        public Criteria andProveTimeBetween(Date value1, Date value2) {
            addCriterion("prove_time between", value1, value2, "proveTime");
            return (Criteria) this;
        }

        public Criteria andProveTimeNotBetween(Date value1, Date value2) {
            addCriterion("prove_time not between", value1, value2, "proveTime");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNull() {
            addCriterion("is_del_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNotNull() {
            addCriterion("is_del_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgEqualTo(String value) {
            addCriterion("is_del_flg =", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotEqualTo(String value) {
            addCriterion("is_del_flg <>", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThan(String value) {
            addCriterion("is_del_flg >", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_del_flg >=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThan(String value) {
            addCriterion("is_del_flg <", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThanOrEqualTo(String value) {
            addCriterion("is_del_flg <=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLike(String value) {
            addCriterion("is_del_flg like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotLike(String value) {
            addCriterion("is_del_flg not like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIn(List<String> values) {
            addCriterion("is_del_flg in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotIn(List<String> values) {
            addCriterion("is_del_flg not in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgBetween(String value1, String value2) {
            addCriterion("is_del_flg between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotBetween(String value1, String value2) {
            addCriterion("is_del_flg not between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }
    }

    /**
     * tb_expert_opinion_relation
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_expert_opinion_relation null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}