package com.hd.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbProMeetingEntityExample {
    /**
     * tb_pro_meeting
     */
    protected String orderByClause;

    /**
     * tb_pro_meeting
     */
    protected boolean distinct;

    /**
     * tb_pro_meeting
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_pro_meeting
     */
    protected Integer limitStart;

    /**
     * tb_pro_meeting
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_meeting
     *
     * @mbg.generated
     */
    public TbProMeetingEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_meeting
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_meeting
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_meeting
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_meeting
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_meeting
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_meeting
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_meeting
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_meeting
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_meeting
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_meeting
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_meeting
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_meeting
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_meeting
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_meeting
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_pro_meeting null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMeetingIdIsNull() {
            addCriterion("meeting_id is null");
            return (Criteria) this;
        }

        public Criteria andMeetingIdIsNotNull() {
            addCriterion("meeting_id is not null");
            return (Criteria) this;
        }

        public Criteria andMeetingIdEqualTo(String value) {
            addCriterion("meeting_id =", value, "meetingId");
            return (Criteria) this;
        }

        public Criteria andMeetingIdNotEqualTo(String value) {
            addCriterion("meeting_id <>", value, "meetingId");
            return (Criteria) this;
        }

        public Criteria andMeetingIdGreaterThan(String value) {
            addCriterion("meeting_id >", value, "meetingId");
            return (Criteria) this;
        }

        public Criteria andMeetingIdGreaterThanOrEqualTo(String value) {
            addCriterion("meeting_id >=", value, "meetingId");
            return (Criteria) this;
        }

        public Criteria andMeetingIdLessThan(String value) {
            addCriterion("meeting_id <", value, "meetingId");
            return (Criteria) this;
        }

        public Criteria andMeetingIdLessThanOrEqualTo(String value) {
            addCriterion("meeting_id <=", value, "meetingId");
            return (Criteria) this;
        }

        public Criteria andMeetingIdLike(String value) {
            addCriterion("meeting_id like", value, "meetingId");
            return (Criteria) this;
        }

        public Criteria andMeetingIdNotLike(String value) {
            addCriterion("meeting_id not like", value, "meetingId");
            return (Criteria) this;
        }

        public Criteria andMeetingIdIn(List<String> values) {
            addCriterion("meeting_id in", values, "meetingId");
            return (Criteria) this;
        }

        public Criteria andMeetingIdNotIn(List<String> values) {
            addCriterion("meeting_id not in", values, "meetingId");
            return (Criteria) this;
        }

        public Criteria andMeetingIdBetween(String value1, String value2) {
            addCriterion("meeting_id between", value1, value2, "meetingId");
            return (Criteria) this;
        }

        public Criteria andMeetingIdNotBetween(String value1, String value2) {
            addCriterion("meeting_id not between", value1, value2, "meetingId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("project_id like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("project_id not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andEditDateIsNull() {
            addCriterion("edit_date is null");
            return (Criteria) this;
        }

        public Criteria andEditDateIsNotNull() {
            addCriterion("edit_date is not null");
            return (Criteria) this;
        }

        public Criteria andEditDateEqualTo(Date value) {
            addCriterion("edit_date =", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateNotEqualTo(Date value) {
            addCriterion("edit_date <>", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateGreaterThan(Date value) {
            addCriterion("edit_date >", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateGreaterThanOrEqualTo(Date value) {
            addCriterion("edit_date >=", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateLessThan(Date value) {
            addCriterion("edit_date <", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateLessThanOrEqualTo(Date value) {
            addCriterion("edit_date <=", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateIn(List<Date> values) {
            addCriterion("edit_date in", values, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateNotIn(List<Date> values) {
            addCriterion("edit_date not in", values, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateBetween(Date value1, Date value2) {
            addCriterion("edit_date between", value1, value2, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateNotBetween(Date value1, Date value2) {
            addCriterion("edit_date not between", value1, value2, "editDate");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andMeetingThemeIsNull() {
            addCriterion("meeting_theme is null");
            return (Criteria) this;
        }

        public Criteria andMeetingThemeIsNotNull() {
            addCriterion("meeting_theme is not null");
            return (Criteria) this;
        }

        public Criteria andMeetingThemeEqualTo(String value) {
            addCriterion("meeting_theme =", value, "meetingTheme");
            return (Criteria) this;
        }

        public Criteria andMeetingThemeNotEqualTo(String value) {
            addCriterion("meeting_theme <>", value, "meetingTheme");
            return (Criteria) this;
        }

        public Criteria andMeetingThemeGreaterThan(String value) {
            addCriterion("meeting_theme >", value, "meetingTheme");
            return (Criteria) this;
        }

        public Criteria andMeetingThemeGreaterThanOrEqualTo(String value) {
            addCriterion("meeting_theme >=", value, "meetingTheme");
            return (Criteria) this;
        }

        public Criteria andMeetingThemeLessThan(String value) {
            addCriterion("meeting_theme <", value, "meetingTheme");
            return (Criteria) this;
        }

        public Criteria andMeetingThemeLessThanOrEqualTo(String value) {
            addCriterion("meeting_theme <=", value, "meetingTheme");
            return (Criteria) this;
        }

        public Criteria andMeetingThemeLike(String value) {
            addCriterion("meeting_theme like", value, "meetingTheme");
            return (Criteria) this;
        }

        public Criteria andMeetingThemeNotLike(String value) {
            addCriterion("meeting_theme not like", value, "meetingTheme");
            return (Criteria) this;
        }

        public Criteria andMeetingThemeIn(List<String> values) {
            addCriterion("meeting_theme in", values, "meetingTheme");
            return (Criteria) this;
        }

        public Criteria andMeetingThemeNotIn(List<String> values) {
            addCriterion("meeting_theme not in", values, "meetingTheme");
            return (Criteria) this;
        }

        public Criteria andMeetingThemeBetween(String value1, String value2) {
            addCriterion("meeting_theme between", value1, value2, "meetingTheme");
            return (Criteria) this;
        }

        public Criteria andMeetingThemeNotBetween(String value1, String value2) {
            addCriterion("meeting_theme not between", value1, value2, "meetingTheme");
            return (Criteria) this;
        }

        public Criteria andContentSummaryIsNull() {
            addCriterion("content_summary is null");
            return (Criteria) this;
        }

        public Criteria andContentSummaryIsNotNull() {
            addCriterion("content_summary is not null");
            return (Criteria) this;
        }

        public Criteria andContentSummaryEqualTo(String value) {
            addCriterion("content_summary =", value, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryNotEqualTo(String value) {
            addCriterion("content_summary <>", value, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryGreaterThan(String value) {
            addCriterion("content_summary >", value, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryGreaterThanOrEqualTo(String value) {
            addCriterion("content_summary >=", value, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryLessThan(String value) {
            addCriterion("content_summary <", value, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryLessThanOrEqualTo(String value) {
            addCriterion("content_summary <=", value, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryLike(String value) {
            addCriterion("content_summary like", value, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryNotLike(String value) {
            addCriterion("content_summary not like", value, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryIn(List<String> values) {
            addCriterion("content_summary in", values, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryNotIn(List<String> values) {
            addCriterion("content_summary not in", values, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryBetween(String value1, String value2) {
            addCriterion("content_summary between", value1, value2, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryNotBetween(String value1, String value2) {
            addCriterion("content_summary not between", value1, value2, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andParticipatoryUnitIsNull() {
            addCriterion("participatory_unit is null");
            return (Criteria) this;
        }

        public Criteria andParticipatoryUnitIsNotNull() {
            addCriterion("participatory_unit is not null");
            return (Criteria) this;
        }

        public Criteria andParticipatoryUnitEqualTo(String value) {
            addCriterion("participatory_unit =", value, "participatoryUnit");
            return (Criteria) this;
        }

        public Criteria andParticipatoryUnitNotEqualTo(String value) {
            addCriterion("participatory_unit <>", value, "participatoryUnit");
            return (Criteria) this;
        }

        public Criteria andParticipatoryUnitGreaterThan(String value) {
            addCriterion("participatory_unit >", value, "participatoryUnit");
            return (Criteria) this;
        }

        public Criteria andParticipatoryUnitGreaterThanOrEqualTo(String value) {
            addCriterion("participatory_unit >=", value, "participatoryUnit");
            return (Criteria) this;
        }

        public Criteria andParticipatoryUnitLessThan(String value) {
            addCriterion("participatory_unit <", value, "participatoryUnit");
            return (Criteria) this;
        }

        public Criteria andParticipatoryUnitLessThanOrEqualTo(String value) {
            addCriterion("participatory_unit <=", value, "participatoryUnit");
            return (Criteria) this;
        }

        public Criteria andParticipatoryUnitLike(String value) {
            addCriterion("participatory_unit like", value, "participatoryUnit");
            return (Criteria) this;
        }

        public Criteria andParticipatoryUnitNotLike(String value) {
            addCriterion("participatory_unit not like", value, "participatoryUnit");
            return (Criteria) this;
        }

        public Criteria andParticipatoryUnitIn(List<String> values) {
            addCriterion("participatory_unit in", values, "participatoryUnit");
            return (Criteria) this;
        }

        public Criteria andParticipatoryUnitNotIn(List<String> values) {
            addCriterion("participatory_unit not in", values, "participatoryUnit");
            return (Criteria) this;
        }

        public Criteria andParticipatoryUnitBetween(String value1, String value2) {
            addCriterion("participatory_unit between", value1, value2, "participatoryUnit");
            return (Criteria) this;
        }

        public Criteria andParticipatoryUnitNotBetween(String value1, String value2) {
            addCriterion("participatory_unit not between", value1, value2, "participatoryUnit");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andMeetingFilePathIsNull() {
            addCriterion("meeting_file_path is null");
            return (Criteria) this;
        }

        public Criteria andMeetingFilePathIsNotNull() {
            addCriterion("meeting_file_path is not null");
            return (Criteria) this;
        }

        public Criteria andMeetingFilePathEqualTo(String value) {
            addCriterion("meeting_file_path =", value, "meetingFilePath");
            return (Criteria) this;
        }

        public Criteria andMeetingFilePathNotEqualTo(String value) {
            addCriterion("meeting_file_path <>", value, "meetingFilePath");
            return (Criteria) this;
        }

        public Criteria andMeetingFilePathGreaterThan(String value) {
            addCriterion("meeting_file_path >", value, "meetingFilePath");
            return (Criteria) this;
        }

        public Criteria andMeetingFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("meeting_file_path >=", value, "meetingFilePath");
            return (Criteria) this;
        }

        public Criteria andMeetingFilePathLessThan(String value) {
            addCriterion("meeting_file_path <", value, "meetingFilePath");
            return (Criteria) this;
        }

        public Criteria andMeetingFilePathLessThanOrEqualTo(String value) {
            addCriterion("meeting_file_path <=", value, "meetingFilePath");
            return (Criteria) this;
        }

        public Criteria andMeetingFilePathLike(String value) {
            addCriterion("meeting_file_path like", value, "meetingFilePath");
            return (Criteria) this;
        }

        public Criteria andMeetingFilePathNotLike(String value) {
            addCriterion("meeting_file_path not like", value, "meetingFilePath");
            return (Criteria) this;
        }

        public Criteria andMeetingFilePathIn(List<String> values) {
            addCriterion("meeting_file_path in", values, "meetingFilePath");
            return (Criteria) this;
        }

        public Criteria andMeetingFilePathNotIn(List<String> values) {
            addCriterion("meeting_file_path not in", values, "meetingFilePath");
            return (Criteria) this;
        }

        public Criteria andMeetingFilePathBetween(String value1, String value2) {
            addCriterion("meeting_file_path between", value1, value2, "meetingFilePath");
            return (Criteria) this;
        }

        public Criteria andMeetingFilePathNotBetween(String value1, String value2) {
            addCriterion("meeting_file_path not between", value1, value2, "meetingFilePath");
            return (Criteria) this;
        }

        public Criteria andMeetingFileNameIsNull() {
            addCriterion("meeting_file_name is null");
            return (Criteria) this;
        }

        public Criteria andMeetingFileNameIsNotNull() {
            addCriterion("meeting_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andMeetingFileNameEqualTo(String value) {
            addCriterion("meeting_file_name =", value, "meetingFileName");
            return (Criteria) this;
        }

        public Criteria andMeetingFileNameNotEqualTo(String value) {
            addCriterion("meeting_file_name <>", value, "meetingFileName");
            return (Criteria) this;
        }

        public Criteria andMeetingFileNameGreaterThan(String value) {
            addCriterion("meeting_file_name >", value, "meetingFileName");
            return (Criteria) this;
        }

        public Criteria andMeetingFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("meeting_file_name >=", value, "meetingFileName");
            return (Criteria) this;
        }

        public Criteria andMeetingFileNameLessThan(String value) {
            addCriterion("meeting_file_name <", value, "meetingFileName");
            return (Criteria) this;
        }

        public Criteria andMeetingFileNameLessThanOrEqualTo(String value) {
            addCriterion("meeting_file_name <=", value, "meetingFileName");
            return (Criteria) this;
        }

        public Criteria andMeetingFileNameLike(String value) {
            addCriterion("meeting_file_name like", value, "meetingFileName");
            return (Criteria) this;
        }

        public Criteria andMeetingFileNameNotLike(String value) {
            addCriterion("meeting_file_name not like", value, "meetingFileName");
            return (Criteria) this;
        }

        public Criteria andMeetingFileNameIn(List<String> values) {
            addCriterion("meeting_file_name in", values, "meetingFileName");
            return (Criteria) this;
        }

        public Criteria andMeetingFileNameNotIn(List<String> values) {
            addCriterion("meeting_file_name not in", values, "meetingFileName");
            return (Criteria) this;
        }

        public Criteria andMeetingFileNameBetween(String value1, String value2) {
            addCriterion("meeting_file_name between", value1, value2, "meetingFileName");
            return (Criteria) this;
        }

        public Criteria andMeetingFileNameNotBetween(String value1, String value2) {
            addCriterion("meeting_file_name not between", value1, value2, "meetingFileName");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNull() {
            addCriterion("is_del_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNotNull() {
            addCriterion("is_del_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgEqualTo(String value) {
            addCriterion("is_del_flg =", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotEqualTo(String value) {
            addCriterion("is_del_flg <>", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThan(String value) {
            addCriterion("is_del_flg >", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_del_flg >=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThan(String value) {
            addCriterion("is_del_flg <", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThanOrEqualTo(String value) {
            addCriterion("is_del_flg <=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLike(String value) {
            addCriterion("is_del_flg like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotLike(String value) {
            addCriterion("is_del_flg not like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIn(List<String> values) {
            addCriterion("is_del_flg in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotIn(List<String> values) {
            addCriterion("is_del_flg not in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgBetween(String value1, String value2) {
            addCriterion("is_del_flg between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotBetween(String value1, String value2) {
            addCriterion("is_del_flg not between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }
    }

    /**
     * tb_pro_meeting
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_pro_meeting null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}