package com.hd.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbProTenderEntityExample {
    /**
     * tb_pro_tender
     */
    protected String orderByClause;

    /**
     * tb_pro_tender
     */
    protected boolean distinct;

    /**
     * tb_pro_tender
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_pro_tender
     */
    protected Integer limitStart;

    /**
     * tb_pro_tender
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_tender
     *
     * @mbg.generated
     */
    public TbProTenderEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_tender
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_tender
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_tender
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_tender
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_tender
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_tender
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_tender
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_tender
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_tender
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_tender
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_tender
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_tender
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_tender
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_tender
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_pro_tender null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTenderIdIsNull() {
            addCriterion("tender_id is null");
            return (Criteria) this;
        }

        public Criteria andTenderIdIsNotNull() {
            addCriterion("tender_id is not null");
            return (Criteria) this;
        }

        public Criteria andTenderIdEqualTo(String value) {
            addCriterion("tender_id =", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdNotEqualTo(String value) {
            addCriterion("tender_id <>", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdGreaterThan(String value) {
            addCriterion("tender_id >", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdGreaterThanOrEqualTo(String value) {
            addCriterion("tender_id >=", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdLessThan(String value) {
            addCriterion("tender_id <", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdLessThanOrEqualTo(String value) {
            addCriterion("tender_id <=", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdLike(String value) {
            addCriterion("tender_id like", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdNotLike(String value) {
            addCriterion("tender_id not like", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdIn(List<String> values) {
            addCriterion("tender_id in", values, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdNotIn(List<String> values) {
            addCriterion("tender_id not in", values, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdBetween(String value1, String value2) {
            addCriterion("tender_id between", value1, value2, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdNotBetween(String value1, String value2) {
            addCriterion("tender_id not between", value1, value2, "tenderId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("project_id like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("project_id not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andTenderNumIsNull() {
            addCriterion("tender_num is null");
            return (Criteria) this;
        }

        public Criteria andTenderNumIsNotNull() {
            addCriterion("tender_num is not null");
            return (Criteria) this;
        }

        public Criteria andTenderNumEqualTo(String value) {
            addCriterion("tender_num =", value, "tenderNum");
            return (Criteria) this;
        }

        public Criteria andTenderNumNotEqualTo(String value) {
            addCriterion("tender_num <>", value, "tenderNum");
            return (Criteria) this;
        }

        public Criteria andTenderNumGreaterThan(String value) {
            addCriterion("tender_num >", value, "tenderNum");
            return (Criteria) this;
        }

        public Criteria andTenderNumGreaterThanOrEqualTo(String value) {
            addCriterion("tender_num >=", value, "tenderNum");
            return (Criteria) this;
        }

        public Criteria andTenderNumLessThan(String value) {
            addCriterion("tender_num <", value, "tenderNum");
            return (Criteria) this;
        }

        public Criteria andTenderNumLessThanOrEqualTo(String value) {
            addCriterion("tender_num <=", value, "tenderNum");
            return (Criteria) this;
        }

        public Criteria andTenderNumLike(String value) {
            addCriterion("tender_num like", value, "tenderNum");
            return (Criteria) this;
        }

        public Criteria andTenderNumNotLike(String value) {
            addCriterion("tender_num not like", value, "tenderNum");
            return (Criteria) this;
        }

        public Criteria andTenderNumIn(List<String> values) {
            addCriterion("tender_num in", values, "tenderNum");
            return (Criteria) this;
        }

        public Criteria andTenderNumNotIn(List<String> values) {
            addCriterion("tender_num not in", values, "tenderNum");
            return (Criteria) this;
        }

        public Criteria andTenderNumBetween(String value1, String value2) {
            addCriterion("tender_num between", value1, value2, "tenderNum");
            return (Criteria) this;
        }

        public Criteria andTenderNumNotBetween(String value1, String value2) {
            addCriterion("tender_num not between", value1, value2, "tenderNum");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeIsNull() {
            addCriterion("treaty_type is null");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeIsNotNull() {
            addCriterion("treaty_type is not null");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeEqualTo(String value) {
            addCriterion("treaty_type =", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeNotEqualTo(String value) {
            addCriterion("treaty_type <>", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeGreaterThan(String value) {
            addCriterion("treaty_type >", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeGreaterThanOrEqualTo(String value) {
            addCriterion("treaty_type >=", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeLessThan(String value) {
            addCriterion("treaty_type <", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeLessThanOrEqualTo(String value) {
            addCriterion("treaty_type <=", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeLike(String value) {
            addCriterion("treaty_type like", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeNotLike(String value) {
            addCriterion("treaty_type not like", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeIn(List<String> values) {
            addCriterion("treaty_type in", values, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeNotIn(List<String> values) {
            addCriterion("treaty_type not in", values, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeBetween(String value1, String value2) {
            addCriterion("treaty_type between", value1, value2, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeNotBetween(String value1, String value2) {
            addCriterion("treaty_type not between", value1, value2, "treatyType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeIsNull() {
            addCriterion("undertake_type is null");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeIsNotNull() {
            addCriterion("undertake_type is not null");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeEqualTo(String value) {
            addCriterion("undertake_type =", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeNotEqualTo(String value) {
            addCriterion("undertake_type <>", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeGreaterThan(String value) {
            addCriterion("undertake_type >", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("undertake_type >=", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeLessThan(String value) {
            addCriterion("undertake_type <", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeLessThanOrEqualTo(String value) {
            addCriterion("undertake_type <=", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeLike(String value) {
            addCriterion("undertake_type like", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeNotLike(String value) {
            addCriterion("undertake_type not like", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeIn(List<String> values) {
            addCriterion("undertake_type in", values, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeNotIn(List<String> values) {
            addCriterion("undertake_type not in", values, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeBetween(String value1, String value2) {
            addCriterion("undertake_type between", value1, value2, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeNotBetween(String value1, String value2) {
            addCriterion("undertake_type not between", value1, value2, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andTenderNameIsNull() {
            addCriterion("tender_name is null");
            return (Criteria) this;
        }

        public Criteria andTenderNameIsNotNull() {
            addCriterion("tender_name is not null");
            return (Criteria) this;
        }

        public Criteria andTenderNameEqualTo(String value) {
            addCriterion("tender_name =", value, "tenderName");
            return (Criteria) this;
        }

        public Criteria andTenderNameNotEqualTo(String value) {
            addCriterion("tender_name <>", value, "tenderName");
            return (Criteria) this;
        }

        public Criteria andTenderNameGreaterThan(String value) {
            addCriterion("tender_name >", value, "tenderName");
            return (Criteria) this;
        }

        public Criteria andTenderNameGreaterThanOrEqualTo(String value) {
            addCriterion("tender_name >=", value, "tenderName");
            return (Criteria) this;
        }

        public Criteria andTenderNameLessThan(String value) {
            addCriterion("tender_name <", value, "tenderName");
            return (Criteria) this;
        }

        public Criteria andTenderNameLessThanOrEqualTo(String value) {
            addCriterion("tender_name <=", value, "tenderName");
            return (Criteria) this;
        }

        public Criteria andTenderNameLike(String value) {
            addCriterion("tender_name like", value, "tenderName");
            return (Criteria) this;
        }

        public Criteria andTenderNameNotLike(String value) {
            addCriterion("tender_name not like", value, "tenderName");
            return (Criteria) this;
        }

        public Criteria andTenderNameIn(List<String> values) {
            addCriterion("tender_name in", values, "tenderName");
            return (Criteria) this;
        }

        public Criteria andTenderNameNotIn(List<String> values) {
            addCriterion("tender_name not in", values, "tenderName");
            return (Criteria) this;
        }

        public Criteria andTenderNameBetween(String value1, String value2) {
            addCriterion("tender_name between", value1, value2, "tenderName");
            return (Criteria) this;
        }

        public Criteria andTenderNameNotBetween(String value1, String value2) {
            addCriterion("tender_name not between", value1, value2, "tenderName");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeIsNull() {
            addCriterion("plan_start_time is null");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeIsNotNull() {
            addCriterion("plan_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeEqualTo(Date value) {
            addCriterion("plan_start_time =", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeNotEqualTo(Date value) {
            addCriterion("plan_start_time <>", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeGreaterThan(Date value) {
            addCriterion("plan_start_time >", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("plan_start_time >=", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeLessThan(Date value) {
            addCriterion("plan_start_time <", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("plan_start_time <=", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeIn(List<Date> values) {
            addCriterion("plan_start_time in", values, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeNotIn(List<Date> values) {
            addCriterion("plan_start_time not in", values, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeBetween(Date value1, Date value2) {
            addCriterion("plan_start_time between", value1, value2, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("plan_start_time not between", value1, value2, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeIsNull() {
            addCriterion("plan_end_time is null");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeIsNotNull() {
            addCriterion("plan_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeEqualTo(Date value) {
            addCriterion("plan_end_time =", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeNotEqualTo(Date value) {
            addCriterion("plan_end_time <>", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeGreaterThan(Date value) {
            addCriterion("plan_end_time >", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("plan_end_time >=", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeLessThan(Date value) {
            addCriterion("plan_end_time <", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("plan_end_time <=", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeIn(List<Date> values) {
            addCriterion("plan_end_time in", values, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeNotIn(List<Date> values) {
            addCriterion("plan_end_time not in", values, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeBetween(Date value1, Date value2) {
            addCriterion("plan_end_time between", value1, value2, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("plan_end_time not between", value1, value2, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andContractTypeIsNull() {
            addCriterion("contract_type is null");
            return (Criteria) this;
        }

        public Criteria andContractTypeIsNotNull() {
            addCriterion("contract_type is not null");
            return (Criteria) this;
        }

        public Criteria andContractTypeEqualTo(String value) {
            addCriterion("contract_type =", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotEqualTo(String value) {
            addCriterion("contract_type <>", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeGreaterThan(String value) {
            addCriterion("contract_type >", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeGreaterThanOrEqualTo(String value) {
            addCriterion("contract_type >=", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeLessThan(String value) {
            addCriterion("contract_type <", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeLessThanOrEqualTo(String value) {
            addCriterion("contract_type <=", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeLike(String value) {
            addCriterion("contract_type like", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotLike(String value) {
            addCriterion("contract_type not like", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeIn(List<String> values) {
            addCriterion("contract_type in", values, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotIn(List<String> values) {
            addCriterion("contract_type not in", values, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeBetween(String value1, String value2) {
            addCriterion("contract_type between", value1, value2, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotBetween(String value1, String value2) {
            addCriterion("contract_type not between", value1, value2, "contractType");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayIsNull() {
            addCriterion("purchaser_way is null");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayIsNotNull() {
            addCriterion("purchaser_way is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayEqualTo(String value) {
            addCriterion("purchaser_way =", value, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayNotEqualTo(String value) {
            addCriterion("purchaser_way <>", value, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayGreaterThan(String value) {
            addCriterion("purchaser_way >", value, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayGreaterThanOrEqualTo(String value) {
            addCriterion("purchaser_way >=", value, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayLessThan(String value) {
            addCriterion("purchaser_way <", value, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayLessThanOrEqualTo(String value) {
            addCriterion("purchaser_way <=", value, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayLike(String value) {
            addCriterion("purchaser_way like", value, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayNotLike(String value) {
            addCriterion("purchaser_way not like", value, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayIn(List<String> values) {
            addCriterion("purchaser_way in", values, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayNotIn(List<String> values) {
            addCriterion("purchaser_way not in", values, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayBetween(String value1, String value2) {
            addCriterion("purchaser_way between", value1, value2, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayNotBetween(String value1, String value2) {
            addCriterion("purchaser_way not between", value1, value2, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andTargetCostIsNull() {
            addCriterion("target_cost is null");
            return (Criteria) this;
        }

        public Criteria andTargetCostIsNotNull() {
            addCriterion("target_cost is not null");
            return (Criteria) this;
        }

        public Criteria andTargetCostEqualTo(Double value) {
            addCriterion("target_cost =", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostNotEqualTo(Double value) {
            addCriterion("target_cost <>", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostGreaterThan(Double value) {
            addCriterion("target_cost >", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostGreaterThanOrEqualTo(Double value) {
            addCriterion("target_cost >=", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostLessThan(Double value) {
            addCriterion("target_cost <", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostLessThanOrEqualTo(Double value) {
            addCriterion("target_cost <=", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostIn(List<Double> values) {
            addCriterion("target_cost in", values, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostNotIn(List<Double> values) {
            addCriterion("target_cost not in", values, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostBetween(Double value1, Double value2) {
            addCriterion("target_cost between", value1, value2, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostNotBetween(Double value1, Double value2) {
            addCriterion("target_cost not between", value1, value2, "targetCost");
            return (Criteria) this;
        }

        public Criteria andFileTypeIsNull() {
            addCriterion("file_type is null");
            return (Criteria) this;
        }

        public Criteria andFileTypeIsNotNull() {
            addCriterion("file_type is not null");
            return (Criteria) this;
        }

        public Criteria andFileTypeEqualTo(String value) {
            addCriterion("file_type =", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotEqualTo(String value) {
            addCriterion("file_type <>", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeGreaterThan(String value) {
            addCriterion("file_type >", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeGreaterThanOrEqualTo(String value) {
            addCriterion("file_type >=", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeLessThan(String value) {
            addCriterion("file_type <", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeLessThanOrEqualTo(String value) {
            addCriterion("file_type <=", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeLike(String value) {
            addCriterion("file_type like", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotLike(String value) {
            addCriterion("file_type not like", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeIn(List<String> values) {
            addCriterion("file_type in", values, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotIn(List<String> values) {
            addCriterion("file_type not in", values, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeBetween(String value1, String value2) {
            addCriterion("file_type between", value1, value2, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotBetween(String value1, String value2) {
            addCriterion("file_type not between", value1, value2, "fileType");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyIsNull() {
            addCriterion("excise_money is null");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyIsNotNull() {
            addCriterion("excise_money is not null");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyEqualTo(Double value) {
            addCriterion("excise_money =", value, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyNotEqualTo(Double value) {
            addCriterion("excise_money <>", value, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyGreaterThan(Double value) {
            addCriterion("excise_money >", value, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("excise_money >=", value, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyLessThan(Double value) {
            addCriterion("excise_money <", value, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyLessThanOrEqualTo(Double value) {
            addCriterion("excise_money <=", value, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyIn(List<Double> values) {
            addCriterion("excise_money in", values, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyNotIn(List<Double> values) {
            addCriterion("excise_money not in", values, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyBetween(Double value1, Double value2) {
            addCriterion("excise_money between", value1, value2, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyNotBetween(Double value1, Double value2) {
            addCriterion("excise_money not between", value1, value2, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andTaxRatioIsNull() {
            addCriterion("tax_ratio is null");
            return (Criteria) this;
        }

        public Criteria andTaxRatioIsNotNull() {
            addCriterion("tax_ratio is not null");
            return (Criteria) this;
        }

        public Criteria andTaxRatioEqualTo(Double value) {
            addCriterion("tax_ratio =", value, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioNotEqualTo(Double value) {
            addCriterion("tax_ratio <>", value, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioGreaterThan(Double value) {
            addCriterion("tax_ratio >", value, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioGreaterThanOrEqualTo(Double value) {
            addCriterion("tax_ratio >=", value, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioLessThan(Double value) {
            addCriterion("tax_ratio <", value, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioLessThanOrEqualTo(Double value) {
            addCriterion("tax_ratio <=", value, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioIn(List<Double> values) {
            addCriterion("tax_ratio in", values, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioNotIn(List<Double> values) {
            addCriterion("tax_ratio not in", values, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioBetween(Double value1, Double value2) {
            addCriterion("tax_ratio between", value1, value2, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioNotBetween(Double value1, Double value2) {
            addCriterion("tax_ratio not between", value1, value2, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyIsNull() {
            addCriterion("tax_money is null");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyIsNotNull() {
            addCriterion("tax_money is not null");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyEqualTo(Double value) {
            addCriterion("tax_money =", value, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyNotEqualTo(Double value) {
            addCriterion("tax_money <>", value, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyGreaterThan(Double value) {
            addCriterion("tax_money >", value, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("tax_money >=", value, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyLessThan(Double value) {
            addCriterion("tax_money <", value, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyLessThanOrEqualTo(Double value) {
            addCriterion("tax_money <=", value, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyIn(List<Double> values) {
            addCriterion("tax_money in", values, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyNotIn(List<Double> values) {
            addCriterion("tax_money not in", values, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyBetween(Double value1, Double value2) {
            addCriterion("tax_money between", value1, value2, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyNotBetween(Double value1, Double value2) {
            addCriterion("tax_money not between", value1, value2, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyIsNull() {
            addCriterion("with_tax_money is null");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyIsNotNull() {
            addCriterion("with_tax_money is not null");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyEqualTo(Double value) {
            addCriterion("with_tax_money =", value, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyNotEqualTo(Double value) {
            addCriterion("with_tax_money <>", value, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyGreaterThan(Double value) {
            addCriterion("with_tax_money >", value, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("with_tax_money >=", value, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyLessThan(Double value) {
            addCriterion("with_tax_money <", value, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyLessThanOrEqualTo(Double value) {
            addCriterion("with_tax_money <=", value, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyIn(List<Double> values) {
            addCriterion("with_tax_money in", values, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyNotIn(List<Double> values) {
            addCriterion("with_tax_money not in", values, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyBetween(Double value1, Double value2) {
            addCriterion("with_tax_money between", value1, value2, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyNotBetween(Double value1, Double value2) {
            addCriterion("with_tax_money not between", value1, value2, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andTenderFilePathIsNull() {
            addCriterion("tender_file_path is null");
            return (Criteria) this;
        }

        public Criteria andTenderFilePathIsNotNull() {
            addCriterion("tender_file_path is not null");
            return (Criteria) this;
        }

        public Criteria andTenderFilePathEqualTo(String value) {
            addCriterion("tender_file_path =", value, "tenderFilePath");
            return (Criteria) this;
        }

        public Criteria andTenderFilePathNotEqualTo(String value) {
            addCriterion("tender_file_path <>", value, "tenderFilePath");
            return (Criteria) this;
        }

        public Criteria andTenderFilePathGreaterThan(String value) {
            addCriterion("tender_file_path >", value, "tenderFilePath");
            return (Criteria) this;
        }

        public Criteria andTenderFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("tender_file_path >=", value, "tenderFilePath");
            return (Criteria) this;
        }

        public Criteria andTenderFilePathLessThan(String value) {
            addCriterion("tender_file_path <", value, "tenderFilePath");
            return (Criteria) this;
        }

        public Criteria andTenderFilePathLessThanOrEqualTo(String value) {
            addCriterion("tender_file_path <=", value, "tenderFilePath");
            return (Criteria) this;
        }

        public Criteria andTenderFilePathLike(String value) {
            addCriterion("tender_file_path like", value, "tenderFilePath");
            return (Criteria) this;
        }

        public Criteria andTenderFilePathNotLike(String value) {
            addCriterion("tender_file_path not like", value, "tenderFilePath");
            return (Criteria) this;
        }

        public Criteria andTenderFilePathIn(List<String> values) {
            addCriterion("tender_file_path in", values, "tenderFilePath");
            return (Criteria) this;
        }

        public Criteria andTenderFilePathNotIn(List<String> values) {
            addCriterion("tender_file_path not in", values, "tenderFilePath");
            return (Criteria) this;
        }

        public Criteria andTenderFilePathBetween(String value1, String value2) {
            addCriterion("tender_file_path between", value1, value2, "tenderFilePath");
            return (Criteria) this;
        }

        public Criteria andTenderFilePathNotBetween(String value1, String value2) {
            addCriterion("tender_file_path not between", value1, value2, "tenderFilePath");
            return (Criteria) this;
        }

        public Criteria andTenderFileNameIsNull() {
            addCriterion("tender_file_name is null");
            return (Criteria) this;
        }

        public Criteria andTenderFileNameIsNotNull() {
            addCriterion("tender_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andTenderFileNameEqualTo(String value) {
            addCriterion("tender_file_name =", value, "tenderFileName");
            return (Criteria) this;
        }

        public Criteria andTenderFileNameNotEqualTo(String value) {
            addCriterion("tender_file_name <>", value, "tenderFileName");
            return (Criteria) this;
        }

        public Criteria andTenderFileNameGreaterThan(String value) {
            addCriterion("tender_file_name >", value, "tenderFileName");
            return (Criteria) this;
        }

        public Criteria andTenderFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("tender_file_name >=", value, "tenderFileName");
            return (Criteria) this;
        }

        public Criteria andTenderFileNameLessThan(String value) {
            addCriterion("tender_file_name <", value, "tenderFileName");
            return (Criteria) this;
        }

        public Criteria andTenderFileNameLessThanOrEqualTo(String value) {
            addCriterion("tender_file_name <=", value, "tenderFileName");
            return (Criteria) this;
        }

        public Criteria andTenderFileNameLike(String value) {
            addCriterion("tender_file_name like", value, "tenderFileName");
            return (Criteria) this;
        }

        public Criteria andTenderFileNameNotLike(String value) {
            addCriterion("tender_file_name not like", value, "tenderFileName");
            return (Criteria) this;
        }

        public Criteria andTenderFileNameIn(List<String> values) {
            addCriterion("tender_file_name in", values, "tenderFileName");
            return (Criteria) this;
        }

        public Criteria andTenderFileNameNotIn(List<String> values) {
            addCriterion("tender_file_name not in", values, "tenderFileName");
            return (Criteria) this;
        }

        public Criteria andTenderFileNameBetween(String value1, String value2) {
            addCriterion("tender_file_name between", value1, value2, "tenderFileName");
            return (Criteria) this;
        }

        public Criteria andTenderFileNameNotBetween(String value1, String value2) {
            addCriterion("tender_file_name not between", value1, value2, "tenderFileName");
            return (Criteria) this;
        }

        public Criteria andAcceptFileTimeIsNull() {
            addCriterion("accept_file_time is null");
            return (Criteria) this;
        }

        public Criteria andAcceptFileTimeIsNotNull() {
            addCriterion("accept_file_time is not null");
            return (Criteria) this;
        }

        public Criteria andAcceptFileTimeEqualTo(Date value) {
            addCriterion("accept_file_time =", value, "acceptFileTime");
            return (Criteria) this;
        }

        public Criteria andAcceptFileTimeNotEqualTo(Date value) {
            addCriterion("accept_file_time <>", value, "acceptFileTime");
            return (Criteria) this;
        }

        public Criteria andAcceptFileTimeGreaterThan(Date value) {
            addCriterion("accept_file_time >", value, "acceptFileTime");
            return (Criteria) this;
        }

        public Criteria andAcceptFileTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("accept_file_time >=", value, "acceptFileTime");
            return (Criteria) this;
        }

        public Criteria andAcceptFileTimeLessThan(Date value) {
            addCriterion("accept_file_time <", value, "acceptFileTime");
            return (Criteria) this;
        }

        public Criteria andAcceptFileTimeLessThanOrEqualTo(Date value) {
            addCriterion("accept_file_time <=", value, "acceptFileTime");
            return (Criteria) this;
        }

        public Criteria andAcceptFileTimeIn(List<Date> values) {
            addCriterion("accept_file_time in", values, "acceptFileTime");
            return (Criteria) this;
        }

        public Criteria andAcceptFileTimeNotIn(List<Date> values) {
            addCriterion("accept_file_time not in", values, "acceptFileTime");
            return (Criteria) this;
        }

        public Criteria andAcceptFileTimeBetween(Date value1, Date value2) {
            addCriterion("accept_file_time between", value1, value2, "acceptFileTime");
            return (Criteria) this;
        }

        public Criteria andAcceptFileTimeNotBetween(Date value1, Date value2) {
            addCriterion("accept_file_time not between", value1, value2, "acceptFileTime");
            return (Criteria) this;
        }

        public Criteria andSendReportTimeIsNull() {
            addCriterion("send_report_time is null");
            return (Criteria) this;
        }

        public Criteria andSendReportTimeIsNotNull() {
            addCriterion("send_report_time is not null");
            return (Criteria) this;
        }

        public Criteria andSendReportTimeEqualTo(Date value) {
            addCriterion("send_report_time =", value, "sendReportTime");
            return (Criteria) this;
        }

        public Criteria andSendReportTimeNotEqualTo(Date value) {
            addCriterion("send_report_time <>", value, "sendReportTime");
            return (Criteria) this;
        }

        public Criteria andSendReportTimeGreaterThan(Date value) {
            addCriterion("send_report_time >", value, "sendReportTime");
            return (Criteria) this;
        }

        public Criteria andSendReportTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("send_report_time >=", value, "sendReportTime");
            return (Criteria) this;
        }

        public Criteria andSendReportTimeLessThan(Date value) {
            addCriterion("send_report_time <", value, "sendReportTime");
            return (Criteria) this;
        }

        public Criteria andSendReportTimeLessThanOrEqualTo(Date value) {
            addCriterion("send_report_time <=", value, "sendReportTime");
            return (Criteria) this;
        }

        public Criteria andSendReportTimeIn(List<Date> values) {
            addCriterion("send_report_time in", values, "sendReportTime");
            return (Criteria) this;
        }

        public Criteria andSendReportTimeNotIn(List<Date> values) {
            addCriterion("send_report_time not in", values, "sendReportTime");
            return (Criteria) this;
        }

        public Criteria andSendReportTimeBetween(Date value1, Date value2) {
            addCriterion("send_report_time between", value1, value2, "sendReportTime");
            return (Criteria) this;
        }

        public Criteria andSendReportTimeNotBetween(Date value1, Date value2) {
            addCriterion("send_report_time not between", value1, value2, "sendReportTime");
            return (Criteria) this;
        }

        public Criteria andReportPathIsNull() {
            addCriterion("report_path is null");
            return (Criteria) this;
        }

        public Criteria andReportPathIsNotNull() {
            addCriterion("report_path is not null");
            return (Criteria) this;
        }

        public Criteria andReportPathEqualTo(String value) {
            addCriterion("report_path =", value, "reportPath");
            return (Criteria) this;
        }

        public Criteria andReportPathNotEqualTo(String value) {
            addCriterion("report_path <>", value, "reportPath");
            return (Criteria) this;
        }

        public Criteria andReportPathGreaterThan(String value) {
            addCriterion("report_path >", value, "reportPath");
            return (Criteria) this;
        }

        public Criteria andReportPathGreaterThanOrEqualTo(String value) {
            addCriterion("report_path >=", value, "reportPath");
            return (Criteria) this;
        }

        public Criteria andReportPathLessThan(String value) {
            addCriterion("report_path <", value, "reportPath");
            return (Criteria) this;
        }

        public Criteria andReportPathLessThanOrEqualTo(String value) {
            addCriterion("report_path <=", value, "reportPath");
            return (Criteria) this;
        }

        public Criteria andReportPathLike(String value) {
            addCriterion("report_path like", value, "reportPath");
            return (Criteria) this;
        }

        public Criteria andReportPathNotLike(String value) {
            addCriterion("report_path not like", value, "reportPath");
            return (Criteria) this;
        }

        public Criteria andReportPathIn(List<String> values) {
            addCriterion("report_path in", values, "reportPath");
            return (Criteria) this;
        }

        public Criteria andReportPathNotIn(List<String> values) {
            addCriterion("report_path not in", values, "reportPath");
            return (Criteria) this;
        }

        public Criteria andReportPathBetween(String value1, String value2) {
            addCriterion("report_path between", value1, value2, "reportPath");
            return (Criteria) this;
        }

        public Criteria andReportPathNotBetween(String value1, String value2) {
            addCriterion("report_path not between", value1, value2, "reportPath");
            return (Criteria) this;
        }

        public Criteria andReportNameIsNull() {
            addCriterion("report_name is null");
            return (Criteria) this;
        }

        public Criteria andReportNameIsNotNull() {
            addCriterion("report_name is not null");
            return (Criteria) this;
        }

        public Criteria andReportNameEqualTo(String value) {
            addCriterion("report_name =", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameNotEqualTo(String value) {
            addCriterion("report_name <>", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameGreaterThan(String value) {
            addCriterion("report_name >", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameGreaterThanOrEqualTo(String value) {
            addCriterion("report_name >=", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameLessThan(String value) {
            addCriterion("report_name <", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameLessThanOrEqualTo(String value) {
            addCriterion("report_name <=", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameLike(String value) {
            addCriterion("report_name like", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameNotLike(String value) {
            addCriterion("report_name not like", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameIn(List<String> values) {
            addCriterion("report_name in", values, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameNotIn(List<String> values) {
            addCriterion("report_name not in", values, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameBetween(String value1, String value2) {
            addCriterion("report_name between", value1, value2, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameNotBetween(String value1, String value2) {
            addCriterion("report_name not between", value1, value2, "reportName");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNull() {
            addCriterion("is_del_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNotNull() {
            addCriterion("is_del_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgEqualTo(String value) {
            addCriterion("is_del_flg =", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotEqualTo(String value) {
            addCriterion("is_del_flg <>", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThan(String value) {
            addCriterion("is_del_flg >", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_del_flg >=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThan(String value) {
            addCriterion("is_del_flg <", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThanOrEqualTo(String value) {
            addCriterion("is_del_flg <=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLike(String value) {
            addCriterion("is_del_flg like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotLike(String value) {
            addCriterion("is_del_flg not like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIn(List<String> values) {
            addCriterion("is_del_flg in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotIn(List<String> values) {
            addCriterion("is_del_flg not in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgBetween(String value1, String value2) {
            addCriterion("is_del_flg between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotBetween(String value1, String value2) {
            addCriterion("is_del_flg not between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }
    }

    /**
     * tb_pro_tender
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_pro_tender null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}