package com.hd.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbProStatementEntityExample {
    /**
     * tb_pro_statement
     */
    protected String orderByClause;

    /**
     * tb_pro_statement
     */
    protected boolean distinct;

    /**
     * tb_pro_statement
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_pro_statement
     */
    protected Integer limitStart;

    /**
     * tb_pro_statement
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_statement
     *
     * @mbg.generated
     */
    public TbProStatementEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_statement
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_statement
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_statement
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_statement
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_statement
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_statement
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_statement
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_statement
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_statement
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_statement
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_statement
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_statement
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_statement
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_statement
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_pro_statement null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStatementIdIsNull() {
            addCriterion("statement_id is null");
            return (Criteria) this;
        }

        public Criteria andStatementIdIsNotNull() {
            addCriterion("statement_id is not null");
            return (Criteria) this;
        }

        public Criteria andStatementIdEqualTo(String value) {
            addCriterion("statement_id =", value, "statementId");
            return (Criteria) this;
        }

        public Criteria andStatementIdNotEqualTo(String value) {
            addCriterion("statement_id <>", value, "statementId");
            return (Criteria) this;
        }

        public Criteria andStatementIdGreaterThan(String value) {
            addCriterion("statement_id >", value, "statementId");
            return (Criteria) this;
        }

        public Criteria andStatementIdGreaterThanOrEqualTo(String value) {
            addCriterion("statement_id >=", value, "statementId");
            return (Criteria) this;
        }

        public Criteria andStatementIdLessThan(String value) {
            addCriterion("statement_id <", value, "statementId");
            return (Criteria) this;
        }

        public Criteria andStatementIdLessThanOrEqualTo(String value) {
            addCriterion("statement_id <=", value, "statementId");
            return (Criteria) this;
        }

        public Criteria andStatementIdLike(String value) {
            addCriterion("statement_id like", value, "statementId");
            return (Criteria) this;
        }

        public Criteria andStatementIdNotLike(String value) {
            addCriterion("statement_id not like", value, "statementId");
            return (Criteria) this;
        }

        public Criteria andStatementIdIn(List<String> values) {
            addCriterion("statement_id in", values, "statementId");
            return (Criteria) this;
        }

        public Criteria andStatementIdNotIn(List<String> values) {
            addCriterion("statement_id not in", values, "statementId");
            return (Criteria) this;
        }

        public Criteria andStatementIdBetween(String value1, String value2) {
            addCriterion("statement_id between", value1, value2, "statementId");
            return (Criteria) this;
        }

        public Criteria andStatementIdNotBetween(String value1, String value2) {
            addCriterion("statement_id not between", value1, value2, "statementId");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNull() {
            addCriterion("contract_id is null");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNotNull() {
            addCriterion("contract_id is not null");
            return (Criteria) this;
        }

        public Criteria andContractIdEqualTo(String value) {
            addCriterion("contract_id =", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotEqualTo(String value) {
            addCriterion("contract_id <>", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThan(String value) {
            addCriterion("contract_id >", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThanOrEqualTo(String value) {
            addCriterion("contract_id >=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThan(String value) {
            addCriterion("contract_id <", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThanOrEqualTo(String value) {
            addCriterion("contract_id <=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLike(String value) {
            addCriterion("contract_id like", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotLike(String value) {
            addCriterion("contract_id not like", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdIn(List<String> values) {
            addCriterion("contract_id in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotIn(List<String> values) {
            addCriterion("contract_id not in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdBetween(String value1, String value2) {
            addCriterion("contract_id between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotBetween(String value1, String value2) {
            addCriterion("contract_id not between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("project_id like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("project_id not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andStatementAmountIsNull() {
            addCriterion("statement_amount is null");
            return (Criteria) this;
        }

        public Criteria andStatementAmountIsNotNull() {
            addCriterion("statement_amount is not null");
            return (Criteria) this;
        }

        public Criteria andStatementAmountEqualTo(Double value) {
            addCriterion("statement_amount =", value, "statementAmount");
            return (Criteria) this;
        }

        public Criteria andStatementAmountNotEqualTo(Double value) {
            addCriterion("statement_amount <>", value, "statementAmount");
            return (Criteria) this;
        }

        public Criteria andStatementAmountGreaterThan(Double value) {
            addCriterion("statement_amount >", value, "statementAmount");
            return (Criteria) this;
        }

        public Criteria andStatementAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("statement_amount >=", value, "statementAmount");
            return (Criteria) this;
        }

        public Criteria andStatementAmountLessThan(Double value) {
            addCriterion("statement_amount <", value, "statementAmount");
            return (Criteria) this;
        }

        public Criteria andStatementAmountLessThanOrEqualTo(Double value) {
            addCriterion("statement_amount <=", value, "statementAmount");
            return (Criteria) this;
        }

        public Criteria andStatementAmountIn(List<Double> values) {
            addCriterion("statement_amount in", values, "statementAmount");
            return (Criteria) this;
        }

        public Criteria andStatementAmountNotIn(List<Double> values) {
            addCriterion("statement_amount not in", values, "statementAmount");
            return (Criteria) this;
        }

        public Criteria andStatementAmountBetween(Double value1, Double value2) {
            addCriterion("statement_amount between", value1, value2, "statementAmount");
            return (Criteria) this;
        }

        public Criteria andStatementAmountNotBetween(Double value1, Double value2) {
            addCriterion("statement_amount not between", value1, value2, "statementAmount");
            return (Criteria) this;
        }

        public Criteria andDrawingSchemeIsNull() {
            addCriterion("drawing_scheme is null");
            return (Criteria) this;
        }

        public Criteria andDrawingSchemeIsNotNull() {
            addCriterion("drawing_scheme is not null");
            return (Criteria) this;
        }

        public Criteria andDrawingSchemeEqualTo(Double value) {
            addCriterion("drawing_scheme =", value, "drawingScheme");
            return (Criteria) this;
        }

        public Criteria andDrawingSchemeNotEqualTo(Double value) {
            addCriterion("drawing_scheme <>", value, "drawingScheme");
            return (Criteria) this;
        }

        public Criteria andDrawingSchemeGreaterThan(Double value) {
            addCriterion("drawing_scheme >", value, "drawingScheme");
            return (Criteria) this;
        }

        public Criteria andDrawingSchemeGreaterThanOrEqualTo(Double value) {
            addCriterion("drawing_scheme >=", value, "drawingScheme");
            return (Criteria) this;
        }

        public Criteria andDrawingSchemeLessThan(Double value) {
            addCriterion("drawing_scheme <", value, "drawingScheme");
            return (Criteria) this;
        }

        public Criteria andDrawingSchemeLessThanOrEqualTo(Double value) {
            addCriterion("drawing_scheme <=", value, "drawingScheme");
            return (Criteria) this;
        }

        public Criteria andDrawingSchemeIn(List<Double> values) {
            addCriterion("drawing_scheme in", values, "drawingScheme");
            return (Criteria) this;
        }

        public Criteria andDrawingSchemeNotIn(List<Double> values) {
            addCriterion("drawing_scheme not in", values, "drawingScheme");
            return (Criteria) this;
        }

        public Criteria andDrawingSchemeBetween(Double value1, Double value2) {
            addCriterion("drawing_scheme between", value1, value2, "drawingScheme");
            return (Criteria) this;
        }

        public Criteria andDrawingSchemeNotBetween(Double value1, Double value2) {
            addCriterion("drawing_scheme not between", value1, value2, "drawingScheme");
            return (Criteria) this;
        }

        public Criteria andAlterDiscussIsNull() {
            addCriterion("alter_discuss is null");
            return (Criteria) this;
        }

        public Criteria andAlterDiscussIsNotNull() {
            addCriterion("alter_discuss is not null");
            return (Criteria) this;
        }

        public Criteria andAlterDiscussEqualTo(Double value) {
            addCriterion("alter_discuss =", value, "alterDiscuss");
            return (Criteria) this;
        }

        public Criteria andAlterDiscussNotEqualTo(Double value) {
            addCriterion("alter_discuss <>", value, "alterDiscuss");
            return (Criteria) this;
        }

        public Criteria andAlterDiscussGreaterThan(Double value) {
            addCriterion("alter_discuss >", value, "alterDiscuss");
            return (Criteria) this;
        }

        public Criteria andAlterDiscussGreaterThanOrEqualTo(Double value) {
            addCriterion("alter_discuss >=", value, "alterDiscuss");
            return (Criteria) this;
        }

        public Criteria andAlterDiscussLessThan(Double value) {
            addCriterion("alter_discuss <", value, "alterDiscuss");
            return (Criteria) this;
        }

        public Criteria andAlterDiscussLessThanOrEqualTo(Double value) {
            addCriterion("alter_discuss <=", value, "alterDiscuss");
            return (Criteria) this;
        }

        public Criteria andAlterDiscussIn(List<Double> values) {
            addCriterion("alter_discuss in", values, "alterDiscuss");
            return (Criteria) this;
        }

        public Criteria andAlterDiscussNotIn(List<Double> values) {
            addCriterion("alter_discuss not in", values, "alterDiscuss");
            return (Criteria) this;
        }

        public Criteria andAlterDiscussBetween(Double value1, Double value2) {
            addCriterion("alter_discuss between", value1, value2, "alterDiscuss");
            return (Criteria) this;
        }

        public Criteria andAlterDiscussNotBetween(Double value1, Double value2) {
            addCriterion("alter_discuss not between", value1, value2, "alterDiscuss");
            return (Criteria) this;
        }

        public Criteria andVisaIsNull() {
            addCriterion("visa is null");
            return (Criteria) this;
        }

        public Criteria andVisaIsNotNull() {
            addCriterion("visa is not null");
            return (Criteria) this;
        }

        public Criteria andVisaEqualTo(Double value) {
            addCriterion("visa =", value, "visa");
            return (Criteria) this;
        }

        public Criteria andVisaNotEqualTo(Double value) {
            addCriterion("visa <>", value, "visa");
            return (Criteria) this;
        }

        public Criteria andVisaGreaterThan(Double value) {
            addCriterion("visa >", value, "visa");
            return (Criteria) this;
        }

        public Criteria andVisaGreaterThanOrEqualTo(Double value) {
            addCriterion("visa >=", value, "visa");
            return (Criteria) this;
        }

        public Criteria andVisaLessThan(Double value) {
            addCriterion("visa <", value, "visa");
            return (Criteria) this;
        }

        public Criteria andVisaLessThanOrEqualTo(Double value) {
            addCriterion("visa <=", value, "visa");
            return (Criteria) this;
        }

        public Criteria andVisaIn(List<Double> values) {
            addCriterion("visa in", values, "visa");
            return (Criteria) this;
        }

        public Criteria andVisaNotIn(List<Double> values) {
            addCriterion("visa not in", values, "visa");
            return (Criteria) this;
        }

        public Criteria andVisaBetween(Double value1, Double value2) {
            addCriterion("visa between", value1, value2, "visa");
            return (Criteria) this;
        }

        public Criteria andVisaNotBetween(Double value1, Double value2) {
            addCriterion("visa not between", value1, value2, "visa");
            return (Criteria) this;
        }

        public Criteria andAdjustPriceIsNull() {
            addCriterion("adjust_price is null");
            return (Criteria) this;
        }

        public Criteria andAdjustPriceIsNotNull() {
            addCriterion("adjust_price is not null");
            return (Criteria) this;
        }

        public Criteria andAdjustPriceEqualTo(Double value) {
            addCriterion("adjust_price =", value, "adjustPrice");
            return (Criteria) this;
        }

        public Criteria andAdjustPriceNotEqualTo(Double value) {
            addCriterion("adjust_price <>", value, "adjustPrice");
            return (Criteria) this;
        }

        public Criteria andAdjustPriceGreaterThan(Double value) {
            addCriterion("adjust_price >", value, "adjustPrice");
            return (Criteria) this;
        }

        public Criteria andAdjustPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("adjust_price >=", value, "adjustPrice");
            return (Criteria) this;
        }

        public Criteria andAdjustPriceLessThan(Double value) {
            addCriterion("adjust_price <", value, "adjustPrice");
            return (Criteria) this;
        }

        public Criteria andAdjustPriceLessThanOrEqualTo(Double value) {
            addCriterion("adjust_price <=", value, "adjustPrice");
            return (Criteria) this;
        }

        public Criteria andAdjustPriceIn(List<Double> values) {
            addCriterion("adjust_price in", values, "adjustPrice");
            return (Criteria) this;
        }

        public Criteria andAdjustPriceNotIn(List<Double> values) {
            addCriterion("adjust_price not in", values, "adjustPrice");
            return (Criteria) this;
        }

        public Criteria andAdjustPriceBetween(Double value1, Double value2) {
            addCriterion("adjust_price between", value1, value2, "adjustPrice");
            return (Criteria) this;
        }

        public Criteria andAdjustPriceNotBetween(Double value1, Double value2) {
            addCriterion("adjust_price not between", value1, value2, "adjustPrice");
            return (Criteria) this;
        }

        public Criteria andSurgePriceIsNull() {
            addCriterion("surge_price is null");
            return (Criteria) this;
        }

        public Criteria andSurgePriceIsNotNull() {
            addCriterion("surge_price is not null");
            return (Criteria) this;
        }

        public Criteria andSurgePriceEqualTo(Double value) {
            addCriterion("surge_price =", value, "surgePrice");
            return (Criteria) this;
        }

        public Criteria andSurgePriceNotEqualTo(Double value) {
            addCriterion("surge_price <>", value, "surgePrice");
            return (Criteria) this;
        }

        public Criteria andSurgePriceGreaterThan(Double value) {
            addCriterion("surge_price >", value, "surgePrice");
            return (Criteria) this;
        }

        public Criteria andSurgePriceGreaterThanOrEqualTo(Double value) {
            addCriterion("surge_price >=", value, "surgePrice");
            return (Criteria) this;
        }

        public Criteria andSurgePriceLessThan(Double value) {
            addCriterion("surge_price <", value, "surgePrice");
            return (Criteria) this;
        }

        public Criteria andSurgePriceLessThanOrEqualTo(Double value) {
            addCriterion("surge_price <=", value, "surgePrice");
            return (Criteria) this;
        }

        public Criteria andSurgePriceIn(List<Double> values) {
            addCriterion("surge_price in", values, "surgePrice");
            return (Criteria) this;
        }

        public Criteria andSurgePriceNotIn(List<Double> values) {
            addCriterion("surge_price not in", values, "surgePrice");
            return (Criteria) this;
        }

        public Criteria andSurgePriceBetween(Double value1, Double value2) {
            addCriterion("surge_price between", value1, value2, "surgePrice");
            return (Criteria) this;
        }

        public Criteria andSurgePriceNotBetween(Double value1, Double value2) {
            addCriterion("surge_price not between", value1, value2, "surgePrice");
            return (Criteria) this;
        }

        public Criteria andServiceFeeIsNull() {
            addCriterion("service_fee is null");
            return (Criteria) this;
        }

        public Criteria andServiceFeeIsNotNull() {
            addCriterion("service_fee is not null");
            return (Criteria) this;
        }

        public Criteria andServiceFeeEqualTo(Double value) {
            addCriterion("service_fee =", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeNotEqualTo(Double value) {
            addCriterion("service_fee <>", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeGreaterThan(Double value) {
            addCriterion("service_fee >", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeGreaterThanOrEqualTo(Double value) {
            addCriterion("service_fee >=", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeLessThan(Double value) {
            addCriterion("service_fee <", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeLessThanOrEqualTo(Double value) {
            addCriterion("service_fee <=", value, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeIn(List<Double> values) {
            addCriterion("service_fee in", values, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeNotIn(List<Double> values) {
            addCriterion("service_fee not in", values, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeBetween(Double value1, Double value2) {
            addCriterion("service_fee between", value1, value2, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andServiceFeeNotBetween(Double value1, Double value2) {
            addCriterion("service_fee not between", value1, value2, "serviceFee");
            return (Criteria) this;
        }

        public Criteria andTaxPriceIsNull() {
            addCriterion("tax_price is null");
            return (Criteria) this;
        }

        public Criteria andTaxPriceIsNotNull() {
            addCriterion("tax_price is not null");
            return (Criteria) this;
        }

        public Criteria andTaxPriceEqualTo(Double value) {
            addCriterion("tax_price =", value, "taxPrice");
            return (Criteria) this;
        }

        public Criteria andTaxPriceNotEqualTo(Double value) {
            addCriterion("tax_price <>", value, "taxPrice");
            return (Criteria) this;
        }

        public Criteria andTaxPriceGreaterThan(Double value) {
            addCriterion("tax_price >", value, "taxPrice");
            return (Criteria) this;
        }

        public Criteria andTaxPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("tax_price >=", value, "taxPrice");
            return (Criteria) this;
        }

        public Criteria andTaxPriceLessThan(Double value) {
            addCriterion("tax_price <", value, "taxPrice");
            return (Criteria) this;
        }

        public Criteria andTaxPriceLessThanOrEqualTo(Double value) {
            addCriterion("tax_price <=", value, "taxPrice");
            return (Criteria) this;
        }

        public Criteria andTaxPriceIn(List<Double> values) {
            addCriterion("tax_price in", values, "taxPrice");
            return (Criteria) this;
        }

        public Criteria andTaxPriceNotIn(List<Double> values) {
            addCriterion("tax_price not in", values, "taxPrice");
            return (Criteria) this;
        }

        public Criteria andTaxPriceBetween(Double value1, Double value2) {
            addCriterion("tax_price between", value1, value2, "taxPrice");
            return (Criteria) this;
        }

        public Criteria andTaxPriceNotBetween(Double value1, Double value2) {
            addCriterion("tax_price not between", value1, value2, "taxPrice");
            return (Criteria) this;
        }

        public Criteria andOtherThingIsNull() {
            addCriterion("other_thing is null");
            return (Criteria) this;
        }

        public Criteria andOtherThingIsNotNull() {
            addCriterion("other_thing is not null");
            return (Criteria) this;
        }

        public Criteria andOtherThingEqualTo(Double value) {
            addCriterion("other_thing =", value, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingNotEqualTo(Double value) {
            addCriterion("other_thing <>", value, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingGreaterThan(Double value) {
            addCriterion("other_thing >", value, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingGreaterThanOrEqualTo(Double value) {
            addCriterion("other_thing >=", value, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingLessThan(Double value) {
            addCriterion("other_thing <", value, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingLessThanOrEqualTo(Double value) {
            addCriterion("other_thing <=", value, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingIn(List<Double> values) {
            addCriterion("other_thing in", values, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingNotIn(List<Double> values) {
            addCriterion("other_thing not in", values, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingBetween(Double value1, Double value2) {
            addCriterion("other_thing between", value1, value2, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingNotBetween(Double value1, Double value2) {
            addCriterion("other_thing not between", value1, value2, "otherThing");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNull() {
            addCriterion("is_del_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNotNull() {
            addCriterion("is_del_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgEqualTo(String value) {
            addCriterion("is_del_flg =", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotEqualTo(String value) {
            addCriterion("is_del_flg <>", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThan(String value) {
            addCriterion("is_del_flg >", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_del_flg >=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThan(String value) {
            addCriterion("is_del_flg <", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThanOrEqualTo(String value) {
            addCriterion("is_del_flg <=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLike(String value) {
            addCriterion("is_del_flg like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotLike(String value) {
            addCriterion("is_del_flg not like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIn(List<String> values) {
            addCriterion("is_del_flg in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotIn(List<String> values) {
            addCriterion("is_del_flg not in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgBetween(String value1, String value2) {
            addCriterion("is_del_flg between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotBetween(String value1, String value2) {
            addCriterion("is_del_flg not between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }
    }

    /**
     * tb_pro_statement
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_pro_statement null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}