package com.hd.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbProAssessEntityExample {
    /**
     * tb_pro_assess
     */
    protected String orderByClause;

    /**
     * tb_pro_assess
     */
    protected boolean distinct;

    /**
     * tb_pro_assess
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_pro_assess
     */
    protected Integer limitStart;

    /**
     * tb_pro_assess
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_assess
     *
     * @mbg.generated
     */
    public TbProAssessEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_assess
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_assess
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_assess
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_assess
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_assess
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_assess
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_assess
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_assess
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_assess
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_assess
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_assess
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_assess
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_assess
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_assess
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_pro_assess null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAssessIdIsNull() {
            addCriterion("assess_id is null");
            return (Criteria) this;
        }

        public Criteria andAssessIdIsNotNull() {
            addCriterion("assess_id is not null");
            return (Criteria) this;
        }

        public Criteria andAssessIdEqualTo(String value) {
            addCriterion("assess_id =", value, "assessId");
            return (Criteria) this;
        }

        public Criteria andAssessIdNotEqualTo(String value) {
            addCriterion("assess_id <>", value, "assessId");
            return (Criteria) this;
        }

        public Criteria andAssessIdGreaterThan(String value) {
            addCriterion("assess_id >", value, "assessId");
            return (Criteria) this;
        }

        public Criteria andAssessIdGreaterThanOrEqualTo(String value) {
            addCriterion("assess_id >=", value, "assessId");
            return (Criteria) this;
        }

        public Criteria andAssessIdLessThan(String value) {
            addCriterion("assess_id <", value, "assessId");
            return (Criteria) this;
        }

        public Criteria andAssessIdLessThanOrEqualTo(String value) {
            addCriterion("assess_id <=", value, "assessId");
            return (Criteria) this;
        }

        public Criteria andAssessIdLike(String value) {
            addCriterion("assess_id like", value, "assessId");
            return (Criteria) this;
        }

        public Criteria andAssessIdNotLike(String value) {
            addCriterion("assess_id not like", value, "assessId");
            return (Criteria) this;
        }

        public Criteria andAssessIdIn(List<String> values) {
            addCriterion("assess_id in", values, "assessId");
            return (Criteria) this;
        }

        public Criteria andAssessIdNotIn(List<String> values) {
            addCriterion("assess_id not in", values, "assessId");
            return (Criteria) this;
        }

        public Criteria andAssessIdBetween(String value1, String value2) {
            addCriterion("assess_id between", value1, value2, "assessId");
            return (Criteria) this;
        }

        public Criteria andAssessIdNotBetween(String value1, String value2) {
            addCriterion("assess_id not between", value1, value2, "assessId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("project_id like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("project_id not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andCompileDateIsNull() {
            addCriterion("compile_date is null");
            return (Criteria) this;
        }

        public Criteria andCompileDateIsNotNull() {
            addCriterion("compile_date is not null");
            return (Criteria) this;
        }

        public Criteria andCompileDateEqualTo(Date value) {
            addCriterion("compile_date =", value, "compileDate");
            return (Criteria) this;
        }

        public Criteria andCompileDateNotEqualTo(Date value) {
            addCriterion("compile_date <>", value, "compileDate");
            return (Criteria) this;
        }

        public Criteria andCompileDateGreaterThan(Date value) {
            addCriterion("compile_date >", value, "compileDate");
            return (Criteria) this;
        }

        public Criteria andCompileDateGreaterThanOrEqualTo(Date value) {
            addCriterion("compile_date >=", value, "compileDate");
            return (Criteria) this;
        }

        public Criteria andCompileDateLessThan(Date value) {
            addCriterion("compile_date <", value, "compileDate");
            return (Criteria) this;
        }

        public Criteria andCompileDateLessThanOrEqualTo(Date value) {
            addCriterion("compile_date <=", value, "compileDate");
            return (Criteria) this;
        }

        public Criteria andCompileDateIn(List<Date> values) {
            addCriterion("compile_date in", values, "compileDate");
            return (Criteria) this;
        }

        public Criteria andCompileDateNotIn(List<Date> values) {
            addCriterion("compile_date not in", values, "compileDate");
            return (Criteria) this;
        }

        public Criteria andCompileDateBetween(Date value1, Date value2) {
            addCriterion("compile_date between", value1, value2, "compileDate");
            return (Criteria) this;
        }

        public Criteria andCompileDateNotBetween(Date value1, Date value2) {
            addCriterion("compile_date not between", value1, value2, "compileDate");
            return (Criteria) this;
        }

        public Criteria andAssessNameIsNull() {
            addCriterion("assess_name is null");
            return (Criteria) this;
        }

        public Criteria andAssessNameIsNotNull() {
            addCriterion("assess_name is not null");
            return (Criteria) this;
        }

        public Criteria andAssessNameEqualTo(String value) {
            addCriterion("assess_name =", value, "assessName");
            return (Criteria) this;
        }

        public Criteria andAssessNameNotEqualTo(String value) {
            addCriterion("assess_name <>", value, "assessName");
            return (Criteria) this;
        }

        public Criteria andAssessNameGreaterThan(String value) {
            addCriterion("assess_name >", value, "assessName");
            return (Criteria) this;
        }

        public Criteria andAssessNameGreaterThanOrEqualTo(String value) {
            addCriterion("assess_name >=", value, "assessName");
            return (Criteria) this;
        }

        public Criteria andAssessNameLessThan(String value) {
            addCriterion("assess_name <", value, "assessName");
            return (Criteria) this;
        }

        public Criteria andAssessNameLessThanOrEqualTo(String value) {
            addCriterion("assess_name <=", value, "assessName");
            return (Criteria) this;
        }

        public Criteria andAssessNameLike(String value) {
            addCriterion("assess_name like", value, "assessName");
            return (Criteria) this;
        }

        public Criteria andAssessNameNotLike(String value) {
            addCriterion("assess_name not like", value, "assessName");
            return (Criteria) this;
        }

        public Criteria andAssessNameIn(List<String> values) {
            addCriterion("assess_name in", values, "assessName");
            return (Criteria) this;
        }

        public Criteria andAssessNameNotIn(List<String> values) {
            addCriterion("assess_name not in", values, "assessName");
            return (Criteria) this;
        }

        public Criteria andAssessNameBetween(String value1, String value2) {
            addCriterion("assess_name between", value1, value2, "assessName");
            return (Criteria) this;
        }

        public Criteria andAssessNameNotBetween(String value1, String value2) {
            addCriterion("assess_name not between", value1, value2, "assessName");
            return (Criteria) this;
        }

        public Criteria andFloorSpaceIsNull() {
            addCriterion("floor_space is null");
            return (Criteria) this;
        }

        public Criteria andFloorSpaceIsNotNull() {
            addCriterion("floor_space is not null");
            return (Criteria) this;
        }

        public Criteria andFloorSpaceEqualTo(Double value) {
            addCriterion("floor_space =", value, "floorSpace");
            return (Criteria) this;
        }

        public Criteria andFloorSpaceNotEqualTo(Double value) {
            addCriterion("floor_space <>", value, "floorSpace");
            return (Criteria) this;
        }

        public Criteria andFloorSpaceGreaterThan(Double value) {
            addCriterion("floor_space >", value, "floorSpace");
            return (Criteria) this;
        }

        public Criteria andFloorSpaceGreaterThanOrEqualTo(Double value) {
            addCriterion("floor_space >=", value, "floorSpace");
            return (Criteria) this;
        }

        public Criteria andFloorSpaceLessThan(Double value) {
            addCriterion("floor_space <", value, "floorSpace");
            return (Criteria) this;
        }

        public Criteria andFloorSpaceLessThanOrEqualTo(Double value) {
            addCriterion("floor_space <=", value, "floorSpace");
            return (Criteria) this;
        }

        public Criteria andFloorSpaceIn(List<Double> values) {
            addCriterion("floor_space in", values, "floorSpace");
            return (Criteria) this;
        }

        public Criteria andFloorSpaceNotIn(List<Double> values) {
            addCriterion("floor_space not in", values, "floorSpace");
            return (Criteria) this;
        }

        public Criteria andFloorSpaceBetween(Double value1, Double value2) {
            addCriterion("floor_space between", value1, value2, "floorSpace");
            return (Criteria) this;
        }

        public Criteria andFloorSpaceNotBetween(Double value1, Double value2) {
            addCriterion("floor_space not between", value1, value2, "floorSpace");
            return (Criteria) this;
        }

        public Criteria andEstimatedCostIsNull() {
            addCriterion("estimated_cost is null");
            return (Criteria) this;
        }

        public Criteria andEstimatedCostIsNotNull() {
            addCriterion("estimated_cost is not null");
            return (Criteria) this;
        }

        public Criteria andEstimatedCostEqualTo(Double value) {
            addCriterion("estimated_cost =", value, "estimatedCost");
            return (Criteria) this;
        }

        public Criteria andEstimatedCostNotEqualTo(Double value) {
            addCriterion("estimated_cost <>", value, "estimatedCost");
            return (Criteria) this;
        }

        public Criteria andEstimatedCostGreaterThan(Double value) {
            addCriterion("estimated_cost >", value, "estimatedCost");
            return (Criteria) this;
        }

        public Criteria andEstimatedCostGreaterThanOrEqualTo(Double value) {
            addCriterion("estimated_cost >=", value, "estimatedCost");
            return (Criteria) this;
        }

        public Criteria andEstimatedCostLessThan(Double value) {
            addCriterion("estimated_cost <", value, "estimatedCost");
            return (Criteria) this;
        }

        public Criteria andEstimatedCostLessThanOrEqualTo(Double value) {
            addCriterion("estimated_cost <=", value, "estimatedCost");
            return (Criteria) this;
        }

        public Criteria andEstimatedCostIn(List<Double> values) {
            addCriterion("estimated_cost in", values, "estimatedCost");
            return (Criteria) this;
        }

        public Criteria andEstimatedCostNotIn(List<Double> values) {
            addCriterion("estimated_cost not in", values, "estimatedCost");
            return (Criteria) this;
        }

        public Criteria andEstimatedCostBetween(Double value1, Double value2) {
            addCriterion("estimated_cost between", value1, value2, "estimatedCost");
            return (Criteria) this;
        }

        public Criteria andEstimatedCostNotBetween(Double value1, Double value2) {
            addCriterion("estimated_cost not between", value1, value2, "estimatedCost");
            return (Criteria) this;
        }

        public Criteria andEstimationExParteIsNull() {
            addCriterion("estimation_ex_parte is null");
            return (Criteria) this;
        }

        public Criteria andEstimationExParteIsNotNull() {
            addCriterion("estimation_ex_parte is not null");
            return (Criteria) this;
        }

        public Criteria andEstimationExParteEqualTo(Double value) {
            addCriterion("estimation_ex_parte =", value, "estimationExParte");
            return (Criteria) this;
        }

        public Criteria andEstimationExParteNotEqualTo(Double value) {
            addCriterion("estimation_ex_parte <>", value, "estimationExParte");
            return (Criteria) this;
        }

        public Criteria andEstimationExParteGreaterThan(Double value) {
            addCriterion("estimation_ex_parte >", value, "estimationExParte");
            return (Criteria) this;
        }

        public Criteria andEstimationExParteGreaterThanOrEqualTo(Double value) {
            addCriterion("estimation_ex_parte >=", value, "estimationExParte");
            return (Criteria) this;
        }

        public Criteria andEstimationExParteLessThan(Double value) {
            addCriterion("estimation_ex_parte <", value, "estimationExParte");
            return (Criteria) this;
        }

        public Criteria andEstimationExParteLessThanOrEqualTo(Double value) {
            addCriterion("estimation_ex_parte <=", value, "estimationExParte");
            return (Criteria) this;
        }

        public Criteria andEstimationExParteIn(List<Double> values) {
            addCriterion("estimation_ex_parte in", values, "estimationExParte");
            return (Criteria) this;
        }

        public Criteria andEstimationExParteNotIn(List<Double> values) {
            addCriterion("estimation_ex_parte not in", values, "estimationExParte");
            return (Criteria) this;
        }

        public Criteria andEstimationExParteBetween(Double value1, Double value2) {
            addCriterion("estimation_ex_parte between", value1, value2, "estimationExParte");
            return (Criteria) this;
        }

        public Criteria andEstimationExParteNotBetween(Double value1, Double value2) {
            addCriterion("estimation_ex_parte not between", value1, value2, "estimationExParte");
            return (Criteria) this;
        }

        public Criteria andCostRangeIsNull() {
            addCriterion("cost_range is null");
            return (Criteria) this;
        }

        public Criteria andCostRangeIsNotNull() {
            addCriterion("cost_range is not null");
            return (Criteria) this;
        }

        public Criteria andCostRangeEqualTo(String value) {
            addCriterion("cost_range =", value, "costRange");
            return (Criteria) this;
        }

        public Criteria andCostRangeNotEqualTo(String value) {
            addCriterion("cost_range <>", value, "costRange");
            return (Criteria) this;
        }

        public Criteria andCostRangeGreaterThan(String value) {
            addCriterion("cost_range >", value, "costRange");
            return (Criteria) this;
        }

        public Criteria andCostRangeGreaterThanOrEqualTo(String value) {
            addCriterion("cost_range >=", value, "costRange");
            return (Criteria) this;
        }

        public Criteria andCostRangeLessThan(String value) {
            addCriterion("cost_range <", value, "costRange");
            return (Criteria) this;
        }

        public Criteria andCostRangeLessThanOrEqualTo(String value) {
            addCriterion("cost_range <=", value, "costRange");
            return (Criteria) this;
        }

        public Criteria andCostRangeLike(String value) {
            addCriterion("cost_range like", value, "costRange");
            return (Criteria) this;
        }

        public Criteria andCostRangeNotLike(String value) {
            addCriterion("cost_range not like", value, "costRange");
            return (Criteria) this;
        }

        public Criteria andCostRangeIn(List<String> values) {
            addCriterion("cost_range in", values, "costRange");
            return (Criteria) this;
        }

        public Criteria andCostRangeNotIn(List<String> values) {
            addCriterion("cost_range not in", values, "costRange");
            return (Criteria) this;
        }

        public Criteria andCostRangeBetween(String value1, String value2) {
            addCriterion("cost_range between", value1, value2, "costRange");
            return (Criteria) this;
        }

        public Criteria andCostRangeNotBetween(String value1, String value2) {
            addCriterion("cost_range not between", value1, value2, "costRange");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andAssessFilePathIsNull() {
            addCriterion("assess_file_path is null");
            return (Criteria) this;
        }

        public Criteria andAssessFilePathIsNotNull() {
            addCriterion("assess_file_path is not null");
            return (Criteria) this;
        }

        public Criteria andAssessFilePathEqualTo(String value) {
            addCriterion("assess_file_path =", value, "assessFilePath");
            return (Criteria) this;
        }

        public Criteria andAssessFilePathNotEqualTo(String value) {
            addCriterion("assess_file_path <>", value, "assessFilePath");
            return (Criteria) this;
        }

        public Criteria andAssessFilePathGreaterThan(String value) {
            addCriterion("assess_file_path >", value, "assessFilePath");
            return (Criteria) this;
        }

        public Criteria andAssessFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("assess_file_path >=", value, "assessFilePath");
            return (Criteria) this;
        }

        public Criteria andAssessFilePathLessThan(String value) {
            addCriterion("assess_file_path <", value, "assessFilePath");
            return (Criteria) this;
        }

        public Criteria andAssessFilePathLessThanOrEqualTo(String value) {
            addCriterion("assess_file_path <=", value, "assessFilePath");
            return (Criteria) this;
        }

        public Criteria andAssessFilePathLike(String value) {
            addCriterion("assess_file_path like", value, "assessFilePath");
            return (Criteria) this;
        }

        public Criteria andAssessFilePathNotLike(String value) {
            addCriterion("assess_file_path not like", value, "assessFilePath");
            return (Criteria) this;
        }

        public Criteria andAssessFilePathIn(List<String> values) {
            addCriterion("assess_file_path in", values, "assessFilePath");
            return (Criteria) this;
        }

        public Criteria andAssessFilePathNotIn(List<String> values) {
            addCriterion("assess_file_path not in", values, "assessFilePath");
            return (Criteria) this;
        }

        public Criteria andAssessFilePathBetween(String value1, String value2) {
            addCriterion("assess_file_path between", value1, value2, "assessFilePath");
            return (Criteria) this;
        }

        public Criteria andAssessFilePathNotBetween(String value1, String value2) {
            addCriterion("assess_file_path not between", value1, value2, "assessFilePath");
            return (Criteria) this;
        }

        public Criteria andAssessFileNameIsNull() {
            addCriterion("assess_file_name is null");
            return (Criteria) this;
        }

        public Criteria andAssessFileNameIsNotNull() {
            addCriterion("assess_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andAssessFileNameEqualTo(String value) {
            addCriterion("assess_file_name =", value, "assessFileName");
            return (Criteria) this;
        }

        public Criteria andAssessFileNameNotEqualTo(String value) {
            addCriterion("assess_file_name <>", value, "assessFileName");
            return (Criteria) this;
        }

        public Criteria andAssessFileNameGreaterThan(String value) {
            addCriterion("assess_file_name >", value, "assessFileName");
            return (Criteria) this;
        }

        public Criteria andAssessFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("assess_file_name >=", value, "assessFileName");
            return (Criteria) this;
        }

        public Criteria andAssessFileNameLessThan(String value) {
            addCriterion("assess_file_name <", value, "assessFileName");
            return (Criteria) this;
        }

        public Criteria andAssessFileNameLessThanOrEqualTo(String value) {
            addCriterion("assess_file_name <=", value, "assessFileName");
            return (Criteria) this;
        }

        public Criteria andAssessFileNameLike(String value) {
            addCriterion("assess_file_name like", value, "assessFileName");
            return (Criteria) this;
        }

        public Criteria andAssessFileNameNotLike(String value) {
            addCriterion("assess_file_name not like", value, "assessFileName");
            return (Criteria) this;
        }

        public Criteria andAssessFileNameIn(List<String> values) {
            addCriterion("assess_file_name in", values, "assessFileName");
            return (Criteria) this;
        }

        public Criteria andAssessFileNameNotIn(List<String> values) {
            addCriterion("assess_file_name not in", values, "assessFileName");
            return (Criteria) this;
        }

        public Criteria andAssessFileNameBetween(String value1, String value2) {
            addCriterion("assess_file_name between", value1, value2, "assessFileName");
            return (Criteria) this;
        }

        public Criteria andAssessFileNameNotBetween(String value1, String value2) {
            addCriterion("assess_file_name not between", value1, value2, "assessFileName");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNull() {
            addCriterion("is_del_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNotNull() {
            addCriterion("is_del_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgEqualTo(String value) {
            addCriterion("is_del_flg =", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotEqualTo(String value) {
            addCriterion("is_del_flg <>", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThan(String value) {
            addCriterion("is_del_flg >", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_del_flg >=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThan(String value) {
            addCriterion("is_del_flg <", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThanOrEqualTo(String value) {
            addCriterion("is_del_flg <=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLike(String value) {
            addCriterion("is_del_flg like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotLike(String value) {
            addCriterion("is_del_flg not like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIn(List<String> values) {
            addCriterion("is_del_flg in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotIn(List<String> values) {
            addCriterion("is_del_flg not in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgBetween(String value1, String value2) {
            addCriterion("is_del_flg between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotBetween(String value1, String value2) {
            addCriterion("is_del_flg not between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }
    }

    /**
     * tb_pro_assess
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_pro_assess null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}