package com.hd.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbProLetterEntityExample {
    /**
     * tb_pro_letter
     */
    protected String orderByClause;

    /**
     * tb_pro_letter
     */
    protected boolean distinct;

    /**
     * tb_pro_letter
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_pro_letter
     */
    protected Integer limitStart;

    /**
     * tb_pro_letter
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_letter
     *
     * @mbg.generated
     */
    public TbProLetterEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_letter
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_letter
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_letter
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_letter
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_letter
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_letter
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_letter
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_letter
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_letter
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_letter
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_letter
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_letter
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_letter
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_letter
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_pro_letter null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLetterIdIsNull() {
            addCriterion("letter_id is null");
            return (Criteria) this;
        }

        public Criteria andLetterIdIsNotNull() {
            addCriterion("letter_id is not null");
            return (Criteria) this;
        }

        public Criteria andLetterIdEqualTo(String value) {
            addCriterion("letter_id =", value, "letterId");
            return (Criteria) this;
        }

        public Criteria andLetterIdNotEqualTo(String value) {
            addCriterion("letter_id <>", value, "letterId");
            return (Criteria) this;
        }

        public Criteria andLetterIdGreaterThan(String value) {
            addCriterion("letter_id >", value, "letterId");
            return (Criteria) this;
        }

        public Criteria andLetterIdGreaterThanOrEqualTo(String value) {
            addCriterion("letter_id >=", value, "letterId");
            return (Criteria) this;
        }

        public Criteria andLetterIdLessThan(String value) {
            addCriterion("letter_id <", value, "letterId");
            return (Criteria) this;
        }

        public Criteria andLetterIdLessThanOrEqualTo(String value) {
            addCriterion("letter_id <=", value, "letterId");
            return (Criteria) this;
        }

        public Criteria andLetterIdLike(String value) {
            addCriterion("letter_id like", value, "letterId");
            return (Criteria) this;
        }

        public Criteria andLetterIdNotLike(String value) {
            addCriterion("letter_id not like", value, "letterId");
            return (Criteria) this;
        }

        public Criteria andLetterIdIn(List<String> values) {
            addCriterion("letter_id in", values, "letterId");
            return (Criteria) this;
        }

        public Criteria andLetterIdNotIn(List<String> values) {
            addCriterion("letter_id not in", values, "letterId");
            return (Criteria) this;
        }

        public Criteria andLetterIdBetween(String value1, String value2) {
            addCriterion("letter_id between", value1, value2, "letterId");
            return (Criteria) this;
        }

        public Criteria andLetterIdNotBetween(String value1, String value2) {
            addCriterion("letter_id not between", value1, value2, "letterId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("project_id like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("project_id not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andEditDateIsNull() {
            addCriterion("edit_date is null");
            return (Criteria) this;
        }

        public Criteria andEditDateIsNotNull() {
            addCriterion("edit_date is not null");
            return (Criteria) this;
        }

        public Criteria andEditDateEqualTo(Date value) {
            addCriterion("edit_date =", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateNotEqualTo(Date value) {
            addCriterion("edit_date <>", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateGreaterThan(Date value) {
            addCriterion("edit_date >", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateGreaterThanOrEqualTo(Date value) {
            addCriterion("edit_date >=", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateLessThan(Date value) {
            addCriterion("edit_date <", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateLessThanOrEqualTo(Date value) {
            addCriterion("edit_date <=", value, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateIn(List<Date> values) {
            addCriterion("edit_date in", values, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateNotIn(List<Date> values) {
            addCriterion("edit_date not in", values, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateBetween(Date value1, Date value2) {
            addCriterion("edit_date between", value1, value2, "editDate");
            return (Criteria) this;
        }

        public Criteria andEditDateNotBetween(Date value1, Date value2) {
            addCriterion("edit_date not between", value1, value2, "editDate");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNull() {
            addCriterion("file_name is null");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNotNull() {
            addCriterion("file_name is not null");
            return (Criteria) this;
        }

        public Criteria andFileNameEqualTo(String value) {
            addCriterion("file_name =", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotEqualTo(String value) {
            addCriterion("file_name <>", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThan(String value) {
            addCriterion("file_name >", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("file_name >=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThan(String value) {
            addCriterion("file_name <", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThanOrEqualTo(String value) {
            addCriterion("file_name <=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLike(String value) {
            addCriterion("file_name like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotLike(String value) {
            addCriterion("file_name not like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameIn(List<String> values) {
            addCriterion("file_name in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotIn(List<String> values) {
            addCriterion("file_name not in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameBetween(String value1, String value2) {
            addCriterion("file_name between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotBetween(String value1, String value2) {
            addCriterion("file_name not between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNumberIsNull() {
            addCriterion("file_number is null");
            return (Criteria) this;
        }

        public Criteria andFileNumberIsNotNull() {
            addCriterion("file_number is not null");
            return (Criteria) this;
        }

        public Criteria andFileNumberEqualTo(String value) {
            addCriterion("file_number =", value, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberNotEqualTo(String value) {
            addCriterion("file_number <>", value, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberGreaterThan(String value) {
            addCriterion("file_number >", value, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberGreaterThanOrEqualTo(String value) {
            addCriterion("file_number >=", value, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberLessThan(String value) {
            addCriterion("file_number <", value, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberLessThanOrEqualTo(String value) {
            addCriterion("file_number <=", value, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberLike(String value) {
            addCriterion("file_number like", value, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberNotLike(String value) {
            addCriterion("file_number not like", value, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberIn(List<String> values) {
            addCriterion("file_number in", values, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberNotIn(List<String> values) {
            addCriterion("file_number not in", values, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberBetween(String value1, String value2) {
            addCriterion("file_number between", value1, value2, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberNotBetween(String value1, String value2) {
            addCriterion("file_number not between", value1, value2, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andSendTypeIsNull() {
            addCriterion("send_type is null");
            return (Criteria) this;
        }

        public Criteria andSendTypeIsNotNull() {
            addCriterion("send_type is not null");
            return (Criteria) this;
        }

        public Criteria andSendTypeEqualTo(String value) {
            addCriterion("send_type =", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeNotEqualTo(String value) {
            addCriterion("send_type <>", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeGreaterThan(String value) {
            addCriterion("send_type >", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeGreaterThanOrEqualTo(String value) {
            addCriterion("send_type >=", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeLessThan(String value) {
            addCriterion("send_type <", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeLessThanOrEqualTo(String value) {
            addCriterion("send_type <=", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeLike(String value) {
            addCriterion("send_type like", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeNotLike(String value) {
            addCriterion("send_type not like", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeIn(List<String> values) {
            addCriterion("send_type in", values, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeNotIn(List<String> values) {
            addCriterion("send_type not in", values, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeBetween(String value1, String value2) {
            addCriterion("send_type between", value1, value2, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeNotBetween(String value1, String value2) {
            addCriterion("send_type not between", value1, value2, "sendType");
            return (Criteria) this;
        }

        public Criteria andReceiveUnitIsNull() {
            addCriterion("receive_unit is null");
            return (Criteria) this;
        }

        public Criteria andReceiveUnitIsNotNull() {
            addCriterion("receive_unit is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveUnitEqualTo(String value) {
            addCriterion("receive_unit =", value, "receiveUnit");
            return (Criteria) this;
        }

        public Criteria andReceiveUnitNotEqualTo(String value) {
            addCriterion("receive_unit <>", value, "receiveUnit");
            return (Criteria) this;
        }

        public Criteria andReceiveUnitGreaterThan(String value) {
            addCriterion("receive_unit >", value, "receiveUnit");
            return (Criteria) this;
        }

        public Criteria andReceiveUnitGreaterThanOrEqualTo(String value) {
            addCriterion("receive_unit >=", value, "receiveUnit");
            return (Criteria) this;
        }

        public Criteria andReceiveUnitLessThan(String value) {
            addCriterion("receive_unit <", value, "receiveUnit");
            return (Criteria) this;
        }

        public Criteria andReceiveUnitLessThanOrEqualTo(String value) {
            addCriterion("receive_unit <=", value, "receiveUnit");
            return (Criteria) this;
        }

        public Criteria andReceiveUnitLike(String value) {
            addCriterion("receive_unit like", value, "receiveUnit");
            return (Criteria) this;
        }

        public Criteria andReceiveUnitNotLike(String value) {
            addCriterion("receive_unit not like", value, "receiveUnit");
            return (Criteria) this;
        }

        public Criteria andReceiveUnitIn(List<String> values) {
            addCriterion("receive_unit in", values, "receiveUnit");
            return (Criteria) this;
        }

        public Criteria andReceiveUnitNotIn(List<String> values) {
            addCriterion("receive_unit not in", values, "receiveUnit");
            return (Criteria) this;
        }

        public Criteria andReceiveUnitBetween(String value1, String value2) {
            addCriterion("receive_unit between", value1, value2, "receiveUnit");
            return (Criteria) this;
        }

        public Criteria andReceiveUnitNotBetween(String value1, String value2) {
            addCriterion("receive_unit not between", value1, value2, "receiveUnit");
            return (Criteria) this;
        }

        public Criteria andReceivePeopleIsNull() {
            addCriterion("receive_people is null");
            return (Criteria) this;
        }

        public Criteria andReceivePeopleIsNotNull() {
            addCriterion("receive_people is not null");
            return (Criteria) this;
        }

        public Criteria andReceivePeopleEqualTo(String value) {
            addCriterion("receive_people =", value, "receivePeople");
            return (Criteria) this;
        }

        public Criteria andReceivePeopleNotEqualTo(String value) {
            addCriterion("receive_people <>", value, "receivePeople");
            return (Criteria) this;
        }

        public Criteria andReceivePeopleGreaterThan(String value) {
            addCriterion("receive_people >", value, "receivePeople");
            return (Criteria) this;
        }

        public Criteria andReceivePeopleGreaterThanOrEqualTo(String value) {
            addCriterion("receive_people >=", value, "receivePeople");
            return (Criteria) this;
        }

        public Criteria andReceivePeopleLessThan(String value) {
            addCriterion("receive_people <", value, "receivePeople");
            return (Criteria) this;
        }

        public Criteria andReceivePeopleLessThanOrEqualTo(String value) {
            addCriterion("receive_people <=", value, "receivePeople");
            return (Criteria) this;
        }

        public Criteria andReceivePeopleLike(String value) {
            addCriterion("receive_people like", value, "receivePeople");
            return (Criteria) this;
        }

        public Criteria andReceivePeopleNotLike(String value) {
            addCriterion("receive_people not like", value, "receivePeople");
            return (Criteria) this;
        }

        public Criteria andReceivePeopleIn(List<String> values) {
            addCriterion("receive_people in", values, "receivePeople");
            return (Criteria) this;
        }

        public Criteria andReceivePeopleNotIn(List<String> values) {
            addCriterion("receive_people not in", values, "receivePeople");
            return (Criteria) this;
        }

        public Criteria andReceivePeopleBetween(String value1, String value2) {
            addCriterion("receive_people between", value1, value2, "receivePeople");
            return (Criteria) this;
        }

        public Criteria andReceivePeopleNotBetween(String value1, String value2) {
            addCriterion("receive_people not between", value1, value2, "receivePeople");
            return (Criteria) this;
        }

        public Criteria andFileTypeIsNull() {
            addCriterion("file_type is null");
            return (Criteria) this;
        }

        public Criteria andFileTypeIsNotNull() {
            addCriterion("file_type is not null");
            return (Criteria) this;
        }

        public Criteria andFileTypeEqualTo(String value) {
            addCriterion("file_type =", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotEqualTo(String value) {
            addCriterion("file_type <>", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeGreaterThan(String value) {
            addCriterion("file_type >", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeGreaterThanOrEqualTo(String value) {
            addCriterion("file_type >=", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeLessThan(String value) {
            addCriterion("file_type <", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeLessThanOrEqualTo(String value) {
            addCriterion("file_type <=", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeLike(String value) {
            addCriterion("file_type like", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotLike(String value) {
            addCriterion("file_type not like", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeIn(List<String> values) {
            addCriterion("file_type in", values, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotIn(List<String> values) {
            addCriterion("file_type not in", values, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeBetween(String value1, String value2) {
            addCriterion("file_type between", value1, value2, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotBetween(String value1, String value2) {
            addCriterion("file_type not between", value1, value2, "fileType");
            return (Criteria) this;
        }

        public Criteria andCopyNumIsNull() {
            addCriterion("copy_num is null");
            return (Criteria) this;
        }

        public Criteria andCopyNumIsNotNull() {
            addCriterion("copy_num is not null");
            return (Criteria) this;
        }

        public Criteria andCopyNumEqualTo(String value) {
            addCriterion("copy_num =", value, "copyNum");
            return (Criteria) this;
        }

        public Criteria andCopyNumNotEqualTo(String value) {
            addCriterion("copy_num <>", value, "copyNum");
            return (Criteria) this;
        }

        public Criteria andCopyNumGreaterThan(String value) {
            addCriterion("copy_num >", value, "copyNum");
            return (Criteria) this;
        }

        public Criteria andCopyNumGreaterThanOrEqualTo(String value) {
            addCriterion("copy_num >=", value, "copyNum");
            return (Criteria) this;
        }

        public Criteria andCopyNumLessThan(String value) {
            addCriterion("copy_num <", value, "copyNum");
            return (Criteria) this;
        }

        public Criteria andCopyNumLessThanOrEqualTo(String value) {
            addCriterion("copy_num <=", value, "copyNum");
            return (Criteria) this;
        }

        public Criteria andCopyNumLike(String value) {
            addCriterion("copy_num like", value, "copyNum");
            return (Criteria) this;
        }

        public Criteria andCopyNumNotLike(String value) {
            addCriterion("copy_num not like", value, "copyNum");
            return (Criteria) this;
        }

        public Criteria andCopyNumIn(List<String> values) {
            addCriterion("copy_num in", values, "copyNum");
            return (Criteria) this;
        }

        public Criteria andCopyNumNotIn(List<String> values) {
            addCriterion("copy_num not in", values, "copyNum");
            return (Criteria) this;
        }

        public Criteria andCopyNumBetween(String value1, String value2) {
            addCriterion("copy_num between", value1, value2, "copyNum");
            return (Criteria) this;
        }

        public Criteria andCopyNumNotBetween(String value1, String value2) {
            addCriterion("copy_num not between", value1, value2, "copyNum");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andLetterFilePathIsNull() {
            addCriterion("letter_file_path is null");
            return (Criteria) this;
        }

        public Criteria andLetterFilePathIsNotNull() {
            addCriterion("letter_file_path is not null");
            return (Criteria) this;
        }

        public Criteria andLetterFilePathEqualTo(String value) {
            addCriterion("letter_file_path =", value, "letterFilePath");
            return (Criteria) this;
        }

        public Criteria andLetterFilePathNotEqualTo(String value) {
            addCriterion("letter_file_path <>", value, "letterFilePath");
            return (Criteria) this;
        }

        public Criteria andLetterFilePathGreaterThan(String value) {
            addCriterion("letter_file_path >", value, "letterFilePath");
            return (Criteria) this;
        }

        public Criteria andLetterFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("letter_file_path >=", value, "letterFilePath");
            return (Criteria) this;
        }

        public Criteria andLetterFilePathLessThan(String value) {
            addCriterion("letter_file_path <", value, "letterFilePath");
            return (Criteria) this;
        }

        public Criteria andLetterFilePathLessThanOrEqualTo(String value) {
            addCriterion("letter_file_path <=", value, "letterFilePath");
            return (Criteria) this;
        }

        public Criteria andLetterFilePathLike(String value) {
            addCriterion("letter_file_path like", value, "letterFilePath");
            return (Criteria) this;
        }

        public Criteria andLetterFilePathNotLike(String value) {
            addCriterion("letter_file_path not like", value, "letterFilePath");
            return (Criteria) this;
        }

        public Criteria andLetterFilePathIn(List<String> values) {
            addCriterion("letter_file_path in", values, "letterFilePath");
            return (Criteria) this;
        }

        public Criteria andLetterFilePathNotIn(List<String> values) {
            addCriterion("letter_file_path not in", values, "letterFilePath");
            return (Criteria) this;
        }

        public Criteria andLetterFilePathBetween(String value1, String value2) {
            addCriterion("letter_file_path between", value1, value2, "letterFilePath");
            return (Criteria) this;
        }

        public Criteria andLetterFilePathNotBetween(String value1, String value2) {
            addCriterion("letter_file_path not between", value1, value2, "letterFilePath");
            return (Criteria) this;
        }

        public Criteria andLetterFileNameIsNull() {
            addCriterion("letter_file_name is null");
            return (Criteria) this;
        }

        public Criteria andLetterFileNameIsNotNull() {
            addCriterion("letter_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andLetterFileNameEqualTo(String value) {
            addCriterion("letter_file_name =", value, "letterFileName");
            return (Criteria) this;
        }

        public Criteria andLetterFileNameNotEqualTo(String value) {
            addCriterion("letter_file_name <>", value, "letterFileName");
            return (Criteria) this;
        }

        public Criteria andLetterFileNameGreaterThan(String value) {
            addCriterion("letter_file_name >", value, "letterFileName");
            return (Criteria) this;
        }

        public Criteria andLetterFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("letter_file_name >=", value, "letterFileName");
            return (Criteria) this;
        }

        public Criteria andLetterFileNameLessThan(String value) {
            addCriterion("letter_file_name <", value, "letterFileName");
            return (Criteria) this;
        }

        public Criteria andLetterFileNameLessThanOrEqualTo(String value) {
            addCriterion("letter_file_name <=", value, "letterFileName");
            return (Criteria) this;
        }

        public Criteria andLetterFileNameLike(String value) {
            addCriterion("letter_file_name like", value, "letterFileName");
            return (Criteria) this;
        }

        public Criteria andLetterFileNameNotLike(String value) {
            addCriterion("letter_file_name not like", value, "letterFileName");
            return (Criteria) this;
        }

        public Criteria andLetterFileNameIn(List<String> values) {
            addCriterion("letter_file_name in", values, "letterFileName");
            return (Criteria) this;
        }

        public Criteria andLetterFileNameNotIn(List<String> values) {
            addCriterion("letter_file_name not in", values, "letterFileName");
            return (Criteria) this;
        }

        public Criteria andLetterFileNameBetween(String value1, String value2) {
            addCriterion("letter_file_name between", value1, value2, "letterFileName");
            return (Criteria) this;
        }

        public Criteria andLetterFileNameNotBetween(String value1, String value2) {
            addCriterion("letter_file_name not between", value1, value2, "letterFileName");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNull() {
            addCriterion("is_del_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNotNull() {
            addCriterion("is_del_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgEqualTo(String value) {
            addCriterion("is_del_flg =", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotEqualTo(String value) {
            addCriterion("is_del_flg <>", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThan(String value) {
            addCriterion("is_del_flg >", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_del_flg >=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThan(String value) {
            addCriterion("is_del_flg <", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThanOrEqualTo(String value) {
            addCriterion("is_del_flg <=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLike(String value) {
            addCriterion("is_del_flg like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotLike(String value) {
            addCriterion("is_del_flg not like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIn(List<String> values) {
            addCriterion("is_del_flg in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotIn(List<String> values) {
            addCriterion("is_del_flg not in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgBetween(String value1, String value2) {
            addCriterion("is_del_flg between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotBetween(String value1, String value2) {
            addCriterion("is_del_flg not between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }
    }

    /**
     * tb_pro_letter
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_pro_letter null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}