package com.hd.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbProAlterDetailEntityExample {
    /**
     * tb_pro_alter_detail
     */
    protected String orderByClause;

    /**
     * tb_pro_alter_detail
     */
    protected boolean distinct;

    /**
     * tb_pro_alter_detail
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_pro_alter_detail
     */
    protected Integer limitStart;

    /**
     * tb_pro_alter_detail
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_alter_detail
     *
     * @mbg.generated
     */
    public TbProAlterDetailEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_alter_detail
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_alter_detail
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_alter_detail
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_alter_detail
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_alter_detail
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_alter_detail
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_alter_detail
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_alter_detail
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_alter_detail
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_alter_detail
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_alter_detail
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_alter_detail
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_alter_detail
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_alter_detail
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_pro_alter_detail null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAlterIdIsNull() {
            addCriterion("alter_id is null");
            return (Criteria) this;
        }

        public Criteria andAlterIdIsNotNull() {
            addCriterion("alter_id is not null");
            return (Criteria) this;
        }

        public Criteria andAlterIdEqualTo(String value) {
            addCriterion("alter_id =", value, "alterId");
            return (Criteria) this;
        }

        public Criteria andAlterIdNotEqualTo(String value) {
            addCriterion("alter_id <>", value, "alterId");
            return (Criteria) this;
        }

        public Criteria andAlterIdGreaterThan(String value) {
            addCriterion("alter_id >", value, "alterId");
            return (Criteria) this;
        }

        public Criteria andAlterIdGreaterThanOrEqualTo(String value) {
            addCriterion("alter_id >=", value, "alterId");
            return (Criteria) this;
        }

        public Criteria andAlterIdLessThan(String value) {
            addCriterion("alter_id <", value, "alterId");
            return (Criteria) this;
        }

        public Criteria andAlterIdLessThanOrEqualTo(String value) {
            addCriterion("alter_id <=", value, "alterId");
            return (Criteria) this;
        }

        public Criteria andAlterIdLike(String value) {
            addCriterion("alter_id like", value, "alterId");
            return (Criteria) this;
        }

        public Criteria andAlterIdNotLike(String value) {
            addCriterion("alter_id not like", value, "alterId");
            return (Criteria) this;
        }

        public Criteria andAlterIdIn(List<String> values) {
            addCriterion("alter_id in", values, "alterId");
            return (Criteria) this;
        }

        public Criteria andAlterIdNotIn(List<String> values) {
            addCriterion("alter_id not in", values, "alterId");
            return (Criteria) this;
        }

        public Criteria andAlterIdBetween(String value1, String value2) {
            addCriterion("alter_id between", value1, value2, "alterId");
            return (Criteria) this;
        }

        public Criteria andAlterIdNotBetween(String value1, String value2) {
            addCriterion("alter_id not between", value1, value2, "alterId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("project_id like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("project_id not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNull() {
            addCriterion("contract_id is null");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNotNull() {
            addCriterion("contract_id is not null");
            return (Criteria) this;
        }

        public Criteria andContractIdEqualTo(String value) {
            addCriterion("contract_id =", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotEqualTo(String value) {
            addCriterion("contract_id <>", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThan(String value) {
            addCriterion("contract_id >", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThanOrEqualTo(String value) {
            addCriterion("contract_id >=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThan(String value) {
            addCriterion("contract_id <", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThanOrEqualTo(String value) {
            addCriterion("contract_id <=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLike(String value) {
            addCriterion("contract_id like", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotLike(String value) {
            addCriterion("contract_id not like", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdIn(List<String> values) {
            addCriterion("contract_id in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotIn(List<String> values) {
            addCriterion("contract_id not in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdBetween(String value1, String value2) {
            addCriterion("contract_id between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotBetween(String value1, String value2) {
            addCriterion("contract_id not between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andAlterNameIsNull() {
            addCriterion("alter_name is null");
            return (Criteria) this;
        }

        public Criteria andAlterNameIsNotNull() {
            addCriterion("alter_name is not null");
            return (Criteria) this;
        }

        public Criteria andAlterNameEqualTo(String value) {
            addCriterion("alter_name =", value, "alterName");
            return (Criteria) this;
        }

        public Criteria andAlterNameNotEqualTo(String value) {
            addCriterion("alter_name <>", value, "alterName");
            return (Criteria) this;
        }

        public Criteria andAlterNameGreaterThan(String value) {
            addCriterion("alter_name >", value, "alterName");
            return (Criteria) this;
        }

        public Criteria andAlterNameGreaterThanOrEqualTo(String value) {
            addCriterion("alter_name >=", value, "alterName");
            return (Criteria) this;
        }

        public Criteria andAlterNameLessThan(String value) {
            addCriterion("alter_name <", value, "alterName");
            return (Criteria) this;
        }

        public Criteria andAlterNameLessThanOrEqualTo(String value) {
            addCriterion("alter_name <=", value, "alterName");
            return (Criteria) this;
        }

        public Criteria andAlterNameLike(String value) {
            addCriterion("alter_name like", value, "alterName");
            return (Criteria) this;
        }

        public Criteria andAlterNameNotLike(String value) {
            addCriterion("alter_name not like", value, "alterName");
            return (Criteria) this;
        }

        public Criteria andAlterNameIn(List<String> values) {
            addCriterion("alter_name in", values, "alterName");
            return (Criteria) this;
        }

        public Criteria andAlterNameNotIn(List<String> values) {
            addCriterion("alter_name not in", values, "alterName");
            return (Criteria) this;
        }

        public Criteria andAlterNameBetween(String value1, String value2) {
            addCriterion("alter_name between", value1, value2, "alterName");
            return (Criteria) this;
        }

        public Criteria andAlterNameNotBetween(String value1, String value2) {
            addCriterion("alter_name not between", value1, value2, "alterName");
            return (Criteria) this;
        }

        public Criteria andProfessionalIdIsNull() {
            addCriterion("professional_id is null");
            return (Criteria) this;
        }

        public Criteria andProfessionalIdIsNotNull() {
            addCriterion("professional_id is not null");
            return (Criteria) this;
        }

        public Criteria andProfessionalIdEqualTo(String value) {
            addCriterion("professional_id =", value, "professionalId");
            return (Criteria) this;
        }

        public Criteria andProfessionalIdNotEqualTo(String value) {
            addCriterion("professional_id <>", value, "professionalId");
            return (Criteria) this;
        }

        public Criteria andProfessionalIdGreaterThan(String value) {
            addCriterion("professional_id >", value, "professionalId");
            return (Criteria) this;
        }

        public Criteria andProfessionalIdGreaterThanOrEqualTo(String value) {
            addCriterion("professional_id >=", value, "professionalId");
            return (Criteria) this;
        }

        public Criteria andProfessionalIdLessThan(String value) {
            addCriterion("professional_id <", value, "professionalId");
            return (Criteria) this;
        }

        public Criteria andProfessionalIdLessThanOrEqualTo(String value) {
            addCriterion("professional_id <=", value, "professionalId");
            return (Criteria) this;
        }

        public Criteria andProfessionalIdLike(String value) {
            addCriterion("professional_id like", value, "professionalId");
            return (Criteria) this;
        }

        public Criteria andProfessionalIdNotLike(String value) {
            addCriterion("professional_id not like", value, "professionalId");
            return (Criteria) this;
        }

        public Criteria andProfessionalIdIn(List<String> values) {
            addCriterion("professional_id in", values, "professionalId");
            return (Criteria) this;
        }

        public Criteria andProfessionalIdNotIn(List<String> values) {
            addCriterion("professional_id not in", values, "professionalId");
            return (Criteria) this;
        }

        public Criteria andProfessionalIdBetween(String value1, String value2) {
            addCriterion("professional_id between", value1, value2, "professionalId");
            return (Criteria) this;
        }

        public Criteria andProfessionalIdNotBetween(String value1, String value2) {
            addCriterion("professional_id not between", value1, value2, "professionalId");
            return (Criteria) this;
        }

        public Criteria andContentSummaryIsNull() {
            addCriterion("content_summary is null");
            return (Criteria) this;
        }

        public Criteria andContentSummaryIsNotNull() {
            addCriterion("content_summary is not null");
            return (Criteria) this;
        }

        public Criteria andContentSummaryEqualTo(String value) {
            addCriterion("content_summary =", value, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryNotEqualTo(String value) {
            addCriterion("content_summary <>", value, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryGreaterThan(String value) {
            addCriterion("content_summary >", value, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryGreaterThanOrEqualTo(String value) {
            addCriterion("content_summary >=", value, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryLessThan(String value) {
            addCriterion("content_summary <", value, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryLessThanOrEqualTo(String value) {
            addCriterion("content_summary <=", value, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryLike(String value) {
            addCriterion("content_summary like", value, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryNotLike(String value) {
            addCriterion("content_summary not like", value, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryIn(List<String> values) {
            addCriterion("content_summary in", values, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryNotIn(List<String> values) {
            addCriterion("content_summary not in", values, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryBetween(String value1, String value2) {
            addCriterion("content_summary between", value1, value2, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andContentSummaryNotBetween(String value1, String value2) {
            addCriterion("content_summary not between", value1, value2, "contentSummary");
            return (Criteria) this;
        }

        public Criteria andTalkDateIsNull() {
            addCriterion("talk_date is null");
            return (Criteria) this;
        }

        public Criteria andTalkDateIsNotNull() {
            addCriterion("talk_date is not null");
            return (Criteria) this;
        }

        public Criteria andTalkDateEqualTo(Date value) {
            addCriterion("talk_date =", value, "talkDate");
            return (Criteria) this;
        }

        public Criteria andTalkDateNotEqualTo(Date value) {
            addCriterion("talk_date <>", value, "talkDate");
            return (Criteria) this;
        }

        public Criteria andTalkDateGreaterThan(Date value) {
            addCriterion("talk_date >", value, "talkDate");
            return (Criteria) this;
        }

        public Criteria andTalkDateGreaterThanOrEqualTo(Date value) {
            addCriterion("talk_date >=", value, "talkDate");
            return (Criteria) this;
        }

        public Criteria andTalkDateLessThan(Date value) {
            addCriterion("talk_date <", value, "talkDate");
            return (Criteria) this;
        }

        public Criteria andTalkDateLessThanOrEqualTo(Date value) {
            addCriterion("talk_date <=", value, "talkDate");
            return (Criteria) this;
        }

        public Criteria andTalkDateIn(List<Date> values) {
            addCriterion("talk_date in", values, "talkDate");
            return (Criteria) this;
        }

        public Criteria andTalkDateNotIn(List<Date> values) {
            addCriterion("talk_date not in", values, "talkDate");
            return (Criteria) this;
        }

        public Criteria andTalkDateBetween(Date value1, Date value2) {
            addCriterion("talk_date between", value1, value2, "talkDate");
            return (Criteria) this;
        }

        public Criteria andTalkDateNotBetween(Date value1, Date value2) {
            addCriterion("talk_date not between", value1, value2, "talkDate");
            return (Criteria) this;
        }

        public Criteria andReceiveDateIsNull() {
            addCriterion("receive_date is null");
            return (Criteria) this;
        }

        public Criteria andReceiveDateIsNotNull() {
            addCriterion("receive_date is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveDateEqualTo(Date value) {
            addCriterion("receive_date =", value, "receiveDate");
            return (Criteria) this;
        }

        public Criteria andReceiveDateNotEqualTo(Date value) {
            addCriterion("receive_date <>", value, "receiveDate");
            return (Criteria) this;
        }

        public Criteria andReceiveDateGreaterThan(Date value) {
            addCriterion("receive_date >", value, "receiveDate");
            return (Criteria) this;
        }

        public Criteria andReceiveDateGreaterThanOrEqualTo(Date value) {
            addCriterion("receive_date >=", value, "receiveDate");
            return (Criteria) this;
        }

        public Criteria andReceiveDateLessThan(Date value) {
            addCriterion("receive_date <", value, "receiveDate");
            return (Criteria) this;
        }

        public Criteria andReceiveDateLessThanOrEqualTo(Date value) {
            addCriterion("receive_date <=", value, "receiveDate");
            return (Criteria) this;
        }

        public Criteria andReceiveDateIn(List<Date> values) {
            addCriterion("receive_date in", values, "receiveDate");
            return (Criteria) this;
        }

        public Criteria andReceiveDateNotIn(List<Date> values) {
            addCriterion("receive_date not in", values, "receiveDate");
            return (Criteria) this;
        }

        public Criteria andReceiveDateBetween(Date value1, Date value2) {
            addCriterion("receive_date between", value1, value2, "receiveDate");
            return (Criteria) this;
        }

        public Criteria andReceiveDateNotBetween(Date value1, Date value2) {
            addCriterion("receive_date not between", value1, value2, "receiveDate");
            return (Criteria) this;
        }

        public Criteria andStsIsNull() {
            addCriterion("sts is null");
            return (Criteria) this;
        }

        public Criteria andStsIsNotNull() {
            addCriterion("sts is not null");
            return (Criteria) this;
        }

        public Criteria andStsEqualTo(String value) {
            addCriterion("sts =", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsNotEqualTo(String value) {
            addCriterion("sts <>", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsGreaterThan(String value) {
            addCriterion("sts >", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsGreaterThanOrEqualTo(String value) {
            addCriterion("sts >=", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsLessThan(String value) {
            addCriterion("sts <", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsLessThanOrEqualTo(String value) {
            addCriterion("sts <=", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsLike(String value) {
            addCriterion("sts like", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsNotLike(String value) {
            addCriterion("sts not like", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsIn(List<String> values) {
            addCriterion("sts in", values, "sts");
            return (Criteria) this;
        }

        public Criteria andStsNotIn(List<String> values) {
            addCriterion("sts not in", values, "sts");
            return (Criteria) this;
        }

        public Criteria andStsBetween(String value1, String value2) {
            addCriterion("sts between", value1, value2, "sts");
            return (Criteria) this;
        }

        public Criteria andStsNotBetween(String value1, String value2) {
            addCriterion("sts not between", value1, value2, "sts");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountIsNull() {
            addCriterion("declare_amount is null");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountIsNotNull() {
            addCriterion("declare_amount is not null");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountEqualTo(Double value) {
            addCriterion("declare_amount =", value, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountNotEqualTo(Double value) {
            addCriterion("declare_amount <>", value, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountGreaterThan(Double value) {
            addCriterion("declare_amount >", value, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("declare_amount >=", value, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountLessThan(Double value) {
            addCriterion("declare_amount <", value, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountLessThanOrEqualTo(Double value) {
            addCriterion("declare_amount <=", value, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountIn(List<Double> values) {
            addCriterion("declare_amount in", values, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountNotIn(List<Double> values) {
            addCriterion("declare_amount not in", values, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountBetween(Double value1, Double value2) {
            addCriterion("declare_amount between", value1, value2, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountNotBetween(Double value1, Double value2) {
            addCriterion("declare_amount not between", value1, value2, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andAuditAmountIsNull() {
            addCriterion("audit_amount is null");
            return (Criteria) this;
        }

        public Criteria andAuditAmountIsNotNull() {
            addCriterion("audit_amount is not null");
            return (Criteria) this;
        }

        public Criteria andAuditAmountEqualTo(Double value) {
            addCriterion("audit_amount =", value, "auditAmount");
            return (Criteria) this;
        }

        public Criteria andAuditAmountNotEqualTo(Double value) {
            addCriterion("audit_amount <>", value, "auditAmount");
            return (Criteria) this;
        }

        public Criteria andAuditAmountGreaterThan(Double value) {
            addCriterion("audit_amount >", value, "auditAmount");
            return (Criteria) this;
        }

        public Criteria andAuditAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("audit_amount >=", value, "auditAmount");
            return (Criteria) this;
        }

        public Criteria andAuditAmountLessThan(Double value) {
            addCriterion("audit_amount <", value, "auditAmount");
            return (Criteria) this;
        }

        public Criteria andAuditAmountLessThanOrEqualTo(Double value) {
            addCriterion("audit_amount <=", value, "auditAmount");
            return (Criteria) this;
        }

        public Criteria andAuditAmountIn(List<Double> values) {
            addCriterion("audit_amount in", values, "auditAmount");
            return (Criteria) this;
        }

        public Criteria andAuditAmountNotIn(List<Double> values) {
            addCriterion("audit_amount not in", values, "auditAmount");
            return (Criteria) this;
        }

        public Criteria andAuditAmountBetween(Double value1, Double value2) {
            addCriterion("audit_amount between", value1, value2, "auditAmount");
            return (Criteria) this;
        }

        public Criteria andAuditAmountNotBetween(Double value1, Double value2) {
            addCriterion("audit_amount not between", value1, value2, "auditAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountIsNull() {
            addCriterion("hantten_amount is null");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountIsNotNull() {
            addCriterion("hantten_amount is not null");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountEqualTo(Double value) {
            addCriterion("hantten_amount =", value, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountNotEqualTo(Double value) {
            addCriterion("hantten_amount <>", value, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountGreaterThan(Double value) {
            addCriterion("hantten_amount >", value, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("hantten_amount >=", value, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountLessThan(Double value) {
            addCriterion("hantten_amount <", value, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountLessThanOrEqualTo(Double value) {
            addCriterion("hantten_amount <=", value, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountIn(List<Double> values) {
            addCriterion("hantten_amount in", values, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountNotIn(List<Double> values) {
            addCriterion("hantten_amount not in", values, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountBetween(Double value1, Double value2) {
            addCriterion("hantten_amount between", value1, value2, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountNotBetween(Double value1, Double value2) {
            addCriterion("hantten_amount not between", value1, value2, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andOwnerAmountIsNull() {
            addCriterion("owner_amount is null");
            return (Criteria) this;
        }

        public Criteria andOwnerAmountIsNotNull() {
            addCriterion("owner_amount is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerAmountEqualTo(Double value) {
            addCriterion("owner_amount =", value, "ownerAmount");
            return (Criteria) this;
        }

        public Criteria andOwnerAmountNotEqualTo(Double value) {
            addCriterion("owner_amount <>", value, "ownerAmount");
            return (Criteria) this;
        }

        public Criteria andOwnerAmountGreaterThan(Double value) {
            addCriterion("owner_amount >", value, "ownerAmount");
            return (Criteria) this;
        }

        public Criteria andOwnerAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("owner_amount >=", value, "ownerAmount");
            return (Criteria) this;
        }

        public Criteria andOwnerAmountLessThan(Double value) {
            addCriterion("owner_amount <", value, "ownerAmount");
            return (Criteria) this;
        }

        public Criteria andOwnerAmountLessThanOrEqualTo(Double value) {
            addCriterion("owner_amount <=", value, "ownerAmount");
            return (Criteria) this;
        }

        public Criteria andOwnerAmountIn(List<Double> values) {
            addCriterion("owner_amount in", values, "ownerAmount");
            return (Criteria) this;
        }

        public Criteria andOwnerAmountNotIn(List<Double> values) {
            addCriterion("owner_amount not in", values, "ownerAmount");
            return (Criteria) this;
        }

        public Criteria andOwnerAmountBetween(Double value1, Double value2) {
            addCriterion("owner_amount between", value1, value2, "ownerAmount");
            return (Criteria) this;
        }

        public Criteria andOwnerAmountNotBetween(Double value1, Double value2) {
            addCriterion("owner_amount not between", value1, value2, "ownerAmount");
            return (Criteria) this;
        }

        public Criteria andSymbolIsNull() {
            addCriterion("symbol is null");
            return (Criteria) this;
        }

        public Criteria andSymbolIsNotNull() {
            addCriterion("symbol is not null");
            return (Criteria) this;
        }

        public Criteria andSymbolEqualTo(String value) {
            addCriterion("symbol =", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotEqualTo(String value) {
            addCriterion("symbol <>", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolGreaterThan(String value) {
            addCriterion("symbol >", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolGreaterThanOrEqualTo(String value) {
            addCriterion("symbol >=", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLessThan(String value) {
            addCriterion("symbol <", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLessThanOrEqualTo(String value) {
            addCriterion("symbol <=", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLike(String value) {
            addCriterion("symbol like", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotLike(String value) {
            addCriterion("symbol not like", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolIn(List<String> values) {
            addCriterion("symbol in", values, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotIn(List<String> values) {
            addCriterion("symbol not in", values, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolBetween(String value1, String value2) {
            addCriterion("symbol between", value1, value2, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotBetween(String value1, String value2) {
            addCriterion("symbol not between", value1, value2, "symbol");
            return (Criteria) this;
        }

        public Criteria andAlterAnalyseIsNull() {
            addCriterion("alter_analyse is null");
            return (Criteria) this;
        }

        public Criteria andAlterAnalyseIsNotNull() {
            addCriterion("alter_analyse is not null");
            return (Criteria) this;
        }

        public Criteria andAlterAnalyseEqualTo(String value) {
            addCriterion("alter_analyse =", value, "alterAnalyse");
            return (Criteria) this;
        }

        public Criteria andAlterAnalyseNotEqualTo(String value) {
            addCriterion("alter_analyse <>", value, "alterAnalyse");
            return (Criteria) this;
        }

        public Criteria andAlterAnalyseGreaterThan(String value) {
            addCriterion("alter_analyse >", value, "alterAnalyse");
            return (Criteria) this;
        }

        public Criteria andAlterAnalyseGreaterThanOrEqualTo(String value) {
            addCriterion("alter_analyse >=", value, "alterAnalyse");
            return (Criteria) this;
        }

        public Criteria andAlterAnalyseLessThan(String value) {
            addCriterion("alter_analyse <", value, "alterAnalyse");
            return (Criteria) this;
        }

        public Criteria andAlterAnalyseLessThanOrEqualTo(String value) {
            addCriterion("alter_analyse <=", value, "alterAnalyse");
            return (Criteria) this;
        }

        public Criteria andAlterAnalyseLike(String value) {
            addCriterion("alter_analyse like", value, "alterAnalyse");
            return (Criteria) this;
        }

        public Criteria andAlterAnalyseNotLike(String value) {
            addCriterion("alter_analyse not like", value, "alterAnalyse");
            return (Criteria) this;
        }

        public Criteria andAlterAnalyseIn(List<String> values) {
            addCriterion("alter_analyse in", values, "alterAnalyse");
            return (Criteria) this;
        }

        public Criteria andAlterAnalyseNotIn(List<String> values) {
            addCriterion("alter_analyse not in", values, "alterAnalyse");
            return (Criteria) this;
        }

        public Criteria andAlterAnalyseBetween(String value1, String value2) {
            addCriterion("alter_analyse between", value1, value2, "alterAnalyse");
            return (Criteria) this;
        }

        public Criteria andAlterAnalyseNotBetween(String value1, String value2) {
            addCriterion("alter_analyse not between", value1, value2, "alterAnalyse");
            return (Criteria) this;
        }

        public Criteria andSingelIsNull() {
            addCriterion("singel is null");
            return (Criteria) this;
        }

        public Criteria andSingelIsNotNull() {
            addCriterion("singel is not null");
            return (Criteria) this;
        }

        public Criteria andSingelEqualTo(String value) {
            addCriterion("singel =", value, "singel");
            return (Criteria) this;
        }

        public Criteria andSingelNotEqualTo(String value) {
            addCriterion("singel <>", value, "singel");
            return (Criteria) this;
        }

        public Criteria andSingelGreaterThan(String value) {
            addCriterion("singel >", value, "singel");
            return (Criteria) this;
        }

        public Criteria andSingelGreaterThanOrEqualTo(String value) {
            addCriterion("singel >=", value, "singel");
            return (Criteria) this;
        }

        public Criteria andSingelLessThan(String value) {
            addCriterion("singel <", value, "singel");
            return (Criteria) this;
        }

        public Criteria andSingelLessThanOrEqualTo(String value) {
            addCriterion("singel <=", value, "singel");
            return (Criteria) this;
        }

        public Criteria andSingelLike(String value) {
            addCriterion("singel like", value, "singel");
            return (Criteria) this;
        }

        public Criteria andSingelNotLike(String value) {
            addCriterion("singel not like", value, "singel");
            return (Criteria) this;
        }

        public Criteria andSingelIn(List<String> values) {
            addCriterion("singel in", values, "singel");
            return (Criteria) this;
        }

        public Criteria andSingelNotIn(List<String> values) {
            addCriterion("singel not in", values, "singel");
            return (Criteria) this;
        }

        public Criteria andSingelBetween(String value1, String value2) {
            addCriterion("singel between", value1, value2, "singel");
            return (Criteria) this;
        }

        public Criteria andSingelNotBetween(String value1, String value2) {
            addCriterion("singel not between", value1, value2, "singel");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNull() {
            addCriterion("is_del_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNotNull() {
            addCriterion("is_del_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgEqualTo(String value) {
            addCriterion("is_del_flg =", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotEqualTo(String value) {
            addCriterion("is_del_flg <>", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThan(String value) {
            addCriterion("is_del_flg >", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_del_flg >=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThan(String value) {
            addCriterion("is_del_flg <", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThanOrEqualTo(String value) {
            addCriterion("is_del_flg <=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLike(String value) {
            addCriterion("is_del_flg like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotLike(String value) {
            addCriterion("is_del_flg not like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIn(List<String> values) {
            addCriterion("is_del_flg in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotIn(List<String> values) {
            addCriterion("is_del_flg not in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgBetween(String value1, String value2) {
            addCriterion("is_del_flg between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotBetween(String value1, String value2) {
            addCriterion("is_del_flg not between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }
    }

    /**
     * tb_pro_alter_detail
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_pro_alter_detail null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}