package com.hd.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbProContractEntityExample {
    /**
     * tb_pro_contract
     */
    protected String orderByClause;

    /**
     * tb_pro_contract
     */
    protected boolean distinct;

    /**
     * tb_pro_contract
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_pro_contract
     */
    protected Integer limitStart;

    /**
     * tb_pro_contract
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_contract
     *
     * @mbg.generated
     */
    public TbProContractEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_contract
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_contract
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_contract
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_contract
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_contract
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_contract
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_contract
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_contract
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_contract
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_contract
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_contract
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_contract
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_contract
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_contract
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_pro_contract null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andContractIdIsNull() {
            addCriterion("contract_id is null");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNotNull() {
            addCriterion("contract_id is not null");
            return (Criteria) this;
        }

        public Criteria andContractIdEqualTo(String value) {
            addCriterion("contract_id =", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotEqualTo(String value) {
            addCriterion("contract_id <>", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThan(String value) {
            addCriterion("contract_id >", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThanOrEqualTo(String value) {
            addCriterion("contract_id >=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThan(String value) {
            addCriterion("contract_id <", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThanOrEqualTo(String value) {
            addCriterion("contract_id <=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLike(String value) {
            addCriterion("contract_id like", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotLike(String value) {
            addCriterion("contract_id not like", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdIn(List<String> values) {
            addCriterion("contract_id in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotIn(List<String> values) {
            addCriterion("contract_id not in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdBetween(String value1, String value2) {
            addCriterion("contract_id between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotBetween(String value1, String value2) {
            addCriterion("contract_id not between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("project_id like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("project_id not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andTenderIdIsNull() {
            addCriterion("tender_id is null");
            return (Criteria) this;
        }

        public Criteria andTenderIdIsNotNull() {
            addCriterion("tender_id is not null");
            return (Criteria) this;
        }

        public Criteria andTenderIdEqualTo(String value) {
            addCriterion("tender_id =", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdNotEqualTo(String value) {
            addCriterion("tender_id <>", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdGreaterThan(String value) {
            addCriterion("tender_id >", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdGreaterThanOrEqualTo(String value) {
            addCriterion("tender_id >=", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdLessThan(String value) {
            addCriterion("tender_id <", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdLessThanOrEqualTo(String value) {
            addCriterion("tender_id <=", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdLike(String value) {
            addCriterion("tender_id like", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdNotLike(String value) {
            addCriterion("tender_id not like", value, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdIn(List<String> values) {
            addCriterion("tender_id in", values, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdNotIn(List<String> values) {
            addCriterion("tender_id not in", values, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdBetween(String value1, String value2) {
            addCriterion("tender_id between", value1, value2, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTenderIdNotBetween(String value1, String value2) {
            addCriterion("tender_id not between", value1, value2, "tenderId");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeIsNull() {
            addCriterion("treaty_type is null");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeIsNotNull() {
            addCriterion("treaty_type is not null");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeEqualTo(String value) {
            addCriterion("treaty_type =", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeNotEqualTo(String value) {
            addCriterion("treaty_type <>", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeGreaterThan(String value) {
            addCriterion("treaty_type >", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeGreaterThanOrEqualTo(String value) {
            addCriterion("treaty_type >=", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeLessThan(String value) {
            addCriterion("treaty_type <", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeLessThanOrEqualTo(String value) {
            addCriterion("treaty_type <=", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeLike(String value) {
            addCriterion("treaty_type like", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeNotLike(String value) {
            addCriterion("treaty_type not like", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeIn(List<String> values) {
            addCriterion("treaty_type in", values, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeNotIn(List<String> values) {
            addCriterion("treaty_type not in", values, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeBetween(String value1, String value2) {
            addCriterion("treaty_type between", value1, value2, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeNotBetween(String value1, String value2) {
            addCriterion("treaty_type not between", value1, value2, "treatyType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeIsNull() {
            addCriterion("undertake_type is null");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeIsNotNull() {
            addCriterion("undertake_type is not null");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeEqualTo(String value) {
            addCriterion("undertake_type =", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeNotEqualTo(String value) {
            addCriterion("undertake_type <>", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeGreaterThan(String value) {
            addCriterion("undertake_type >", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("undertake_type >=", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeLessThan(String value) {
            addCriterion("undertake_type <", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeLessThanOrEqualTo(String value) {
            addCriterion("undertake_type <=", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeLike(String value) {
            addCriterion("undertake_type like", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeNotLike(String value) {
            addCriterion("undertake_type not like", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeIn(List<String> values) {
            addCriterion("undertake_type in", values, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeNotIn(List<String> values) {
            addCriterion("undertake_type not in", values, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeBetween(String value1, String value2) {
            addCriterion("undertake_type between", value1, value2, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeNotBetween(String value1, String value2) {
            addCriterion("undertake_type not between", value1, value2, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andContractNameIsNull() {
            addCriterion("contract_name is null");
            return (Criteria) this;
        }

        public Criteria andContractNameIsNotNull() {
            addCriterion("contract_name is not null");
            return (Criteria) this;
        }

        public Criteria andContractNameEqualTo(String value) {
            addCriterion("contract_name =", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotEqualTo(String value) {
            addCriterion("contract_name <>", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameGreaterThan(String value) {
            addCriterion("contract_name >", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameGreaterThanOrEqualTo(String value) {
            addCriterion("contract_name >=", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLessThan(String value) {
            addCriterion("contract_name <", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLessThanOrEqualTo(String value) {
            addCriterion("contract_name <=", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLike(String value) {
            addCriterion("contract_name like", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotLike(String value) {
            addCriterion("contract_name not like", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameIn(List<String> values) {
            addCriterion("contract_name in", values, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotIn(List<String> values) {
            addCriterion("contract_name not in", values, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameBetween(String value1, String value2) {
            addCriterion("contract_name between", value1, value2, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotBetween(String value1, String value2) {
            addCriterion("contract_name not between", value1, value2, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNumIsNull() {
            addCriterion("contract_num is null");
            return (Criteria) this;
        }

        public Criteria andContractNumIsNotNull() {
            addCriterion("contract_num is not null");
            return (Criteria) this;
        }

        public Criteria andContractNumEqualTo(String value) {
            addCriterion("contract_num =", value, "contractNum");
            return (Criteria) this;
        }

        public Criteria andContractNumNotEqualTo(String value) {
            addCriterion("contract_num <>", value, "contractNum");
            return (Criteria) this;
        }

        public Criteria andContractNumGreaterThan(String value) {
            addCriterion("contract_num >", value, "contractNum");
            return (Criteria) this;
        }

        public Criteria andContractNumGreaterThanOrEqualTo(String value) {
            addCriterion("contract_num >=", value, "contractNum");
            return (Criteria) this;
        }

        public Criteria andContractNumLessThan(String value) {
            addCriterion("contract_num <", value, "contractNum");
            return (Criteria) this;
        }

        public Criteria andContractNumLessThanOrEqualTo(String value) {
            addCriterion("contract_num <=", value, "contractNum");
            return (Criteria) this;
        }

        public Criteria andContractNumLike(String value) {
            addCriterion("contract_num like", value, "contractNum");
            return (Criteria) this;
        }

        public Criteria andContractNumNotLike(String value) {
            addCriterion("contract_num not like", value, "contractNum");
            return (Criteria) this;
        }

        public Criteria andContractNumIn(List<String> values) {
            addCriterion("contract_num in", values, "contractNum");
            return (Criteria) this;
        }

        public Criteria andContractNumNotIn(List<String> values) {
            addCriterion("contract_num not in", values, "contractNum");
            return (Criteria) this;
        }

        public Criteria andContractNumBetween(String value1, String value2) {
            addCriterion("contract_num between", value1, value2, "contractNum");
            return (Criteria) this;
        }

        public Criteria andContractNumNotBetween(String value1, String value2) {
            addCriterion("contract_num not between", value1, value2, "contractNum");
            return (Criteria) this;
        }

        public Criteria andContractUnitIsNull() {
            addCriterion("contract_unit is null");
            return (Criteria) this;
        }

        public Criteria andContractUnitIsNotNull() {
            addCriterion("contract_unit is not null");
            return (Criteria) this;
        }

        public Criteria andContractUnitEqualTo(String value) {
            addCriterion("contract_unit =", value, "contractUnit");
            return (Criteria) this;
        }

        public Criteria andContractUnitNotEqualTo(String value) {
            addCriterion("contract_unit <>", value, "contractUnit");
            return (Criteria) this;
        }

        public Criteria andContractUnitGreaterThan(String value) {
            addCriterion("contract_unit >", value, "contractUnit");
            return (Criteria) this;
        }

        public Criteria andContractUnitGreaterThanOrEqualTo(String value) {
            addCriterion("contract_unit >=", value, "contractUnit");
            return (Criteria) this;
        }

        public Criteria andContractUnitLessThan(String value) {
            addCriterion("contract_unit <", value, "contractUnit");
            return (Criteria) this;
        }

        public Criteria andContractUnitLessThanOrEqualTo(String value) {
            addCriterion("contract_unit <=", value, "contractUnit");
            return (Criteria) this;
        }

        public Criteria andContractUnitLike(String value) {
            addCriterion("contract_unit like", value, "contractUnit");
            return (Criteria) this;
        }

        public Criteria andContractUnitNotLike(String value) {
            addCriterion("contract_unit not like", value, "contractUnit");
            return (Criteria) this;
        }

        public Criteria andContractUnitIn(List<String> values) {
            addCriterion("contract_unit in", values, "contractUnit");
            return (Criteria) this;
        }

        public Criteria andContractUnitNotIn(List<String> values) {
            addCriterion("contract_unit not in", values, "contractUnit");
            return (Criteria) this;
        }

        public Criteria andContractUnitBetween(String value1, String value2) {
            addCriterion("contract_unit between", value1, value2, "contractUnit");
            return (Criteria) this;
        }

        public Criteria andContractUnitNotBetween(String value1, String value2) {
            addCriterion("contract_unit not between", value1, value2, "contractUnit");
            return (Criteria) this;
        }

        public Criteria andPlanDateIsNull() {
            addCriterion("plan_date is null");
            return (Criteria) this;
        }

        public Criteria andPlanDateIsNotNull() {
            addCriterion("plan_date is not null");
            return (Criteria) this;
        }

        public Criteria andPlanDateEqualTo(String value) {
            addCriterion("plan_date =", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateNotEqualTo(String value) {
            addCriterion("plan_date <>", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateGreaterThan(String value) {
            addCriterion("plan_date >", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateGreaterThanOrEqualTo(String value) {
            addCriterion("plan_date >=", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateLessThan(String value) {
            addCriterion("plan_date <", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateLessThanOrEqualTo(String value) {
            addCriterion("plan_date <=", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateLike(String value) {
            addCriterion("plan_date like", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateNotLike(String value) {
            addCriterion("plan_date not like", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateIn(List<String> values) {
            addCriterion("plan_date in", values, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateNotIn(List<String> values) {
            addCriterion("plan_date not in", values, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateBetween(String value1, String value2) {
            addCriterion("plan_date between", value1, value2, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateNotBetween(String value1, String value2) {
            addCriterion("plan_date not between", value1, value2, "planDate");
            return (Criteria) this;
        }

        public Criteria andContractClassIsNull() {
            addCriterion("contract_class is null");
            return (Criteria) this;
        }

        public Criteria andContractClassIsNotNull() {
            addCriterion("contract_class is not null");
            return (Criteria) this;
        }

        public Criteria andContractClassEqualTo(String value) {
            addCriterion("contract_class =", value, "contractClass");
            return (Criteria) this;
        }

        public Criteria andContractClassNotEqualTo(String value) {
            addCriterion("contract_class <>", value, "contractClass");
            return (Criteria) this;
        }

        public Criteria andContractClassGreaterThan(String value) {
            addCriterion("contract_class >", value, "contractClass");
            return (Criteria) this;
        }

        public Criteria andContractClassGreaterThanOrEqualTo(String value) {
            addCriterion("contract_class >=", value, "contractClass");
            return (Criteria) this;
        }

        public Criteria andContractClassLessThan(String value) {
            addCriterion("contract_class <", value, "contractClass");
            return (Criteria) this;
        }

        public Criteria andContractClassLessThanOrEqualTo(String value) {
            addCriterion("contract_class <=", value, "contractClass");
            return (Criteria) this;
        }

        public Criteria andContractClassLike(String value) {
            addCriterion("contract_class like", value, "contractClass");
            return (Criteria) this;
        }

        public Criteria andContractClassNotLike(String value) {
            addCriterion("contract_class not like", value, "contractClass");
            return (Criteria) this;
        }

        public Criteria andContractClassIn(List<String> values) {
            addCriterion("contract_class in", values, "contractClass");
            return (Criteria) this;
        }

        public Criteria andContractClassNotIn(List<String> values) {
            addCriterion("contract_class not in", values, "contractClass");
            return (Criteria) this;
        }

        public Criteria andContractClassBetween(String value1, String value2) {
            addCriterion("contract_class between", value1, value2, "contractClass");
            return (Criteria) this;
        }

        public Criteria andContractClassNotBetween(String value1, String value2) {
            addCriterion("contract_class not between", value1, value2, "contractClass");
            return (Criteria) this;
        }

        public Criteria andMeasureStsIsNull() {
            addCriterion("measure_sts is null");
            return (Criteria) this;
        }

        public Criteria andMeasureStsIsNotNull() {
            addCriterion("measure_sts is not null");
            return (Criteria) this;
        }

        public Criteria andMeasureStsEqualTo(String value) {
            addCriterion("measure_sts =", value, "measureSts");
            return (Criteria) this;
        }

        public Criteria andMeasureStsNotEqualTo(String value) {
            addCriterion("measure_sts <>", value, "measureSts");
            return (Criteria) this;
        }

        public Criteria andMeasureStsGreaterThan(String value) {
            addCriterion("measure_sts >", value, "measureSts");
            return (Criteria) this;
        }

        public Criteria andMeasureStsGreaterThanOrEqualTo(String value) {
            addCriterion("measure_sts >=", value, "measureSts");
            return (Criteria) this;
        }

        public Criteria andMeasureStsLessThan(String value) {
            addCriterion("measure_sts <", value, "measureSts");
            return (Criteria) this;
        }

        public Criteria andMeasureStsLessThanOrEqualTo(String value) {
            addCriterion("measure_sts <=", value, "measureSts");
            return (Criteria) this;
        }

        public Criteria andMeasureStsLike(String value) {
            addCriterion("measure_sts like", value, "measureSts");
            return (Criteria) this;
        }

        public Criteria andMeasureStsNotLike(String value) {
            addCriterion("measure_sts not like", value, "measureSts");
            return (Criteria) this;
        }

        public Criteria andMeasureStsIn(List<String> values) {
            addCriterion("measure_sts in", values, "measureSts");
            return (Criteria) this;
        }

        public Criteria andMeasureStsNotIn(List<String> values) {
            addCriterion("measure_sts not in", values, "measureSts");
            return (Criteria) this;
        }

        public Criteria andMeasureStsBetween(String value1, String value2) {
            addCriterion("measure_sts between", value1, value2, "measureSts");
            return (Criteria) this;
        }

        public Criteria andMeasureStsNotBetween(String value1, String value2) {
            addCriterion("measure_sts not between", value1, value2, "measureSts");
            return (Criteria) this;
        }

        public Criteria andTargetCostIsNull() {
            addCriterion("target_cost is null");
            return (Criteria) this;
        }

        public Criteria andTargetCostIsNotNull() {
            addCriterion("target_cost is not null");
            return (Criteria) this;
        }

        public Criteria andTargetCostEqualTo(Double value) {
            addCriterion("target_cost =", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostNotEqualTo(Double value) {
            addCriterion("target_cost <>", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostGreaterThan(Double value) {
            addCriterion("target_cost >", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostGreaterThanOrEqualTo(Double value) {
            addCriterion("target_cost >=", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostLessThan(Double value) {
            addCriterion("target_cost <", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostLessThanOrEqualTo(Double value) {
            addCriterion("target_cost <=", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostIn(List<Double> values) {
            addCriterion("target_cost in", values, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostNotIn(List<Double> values) {
            addCriterion("target_cost not in", values, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostBetween(Double value1, Double value2) {
            addCriterion("target_cost between", value1, value2, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostNotBetween(Double value1, Double value2) {
            addCriterion("target_cost not between", value1, value2, "targetCost");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyIsNull() {
            addCriterion("excise_money is null");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyIsNotNull() {
            addCriterion("excise_money is not null");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyEqualTo(Double value) {
            addCriterion("excise_money =", value, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyNotEqualTo(Double value) {
            addCriterion("excise_money <>", value, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyGreaterThan(Double value) {
            addCriterion("excise_money >", value, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("excise_money >=", value, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyLessThan(Double value) {
            addCriterion("excise_money <", value, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyLessThanOrEqualTo(Double value) {
            addCriterion("excise_money <=", value, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyIn(List<Double> values) {
            addCriterion("excise_money in", values, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyNotIn(List<Double> values) {
            addCriterion("excise_money not in", values, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyBetween(Double value1, Double value2) {
            addCriterion("excise_money between", value1, value2, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andExciseMoneyNotBetween(Double value1, Double value2) {
            addCriterion("excise_money not between", value1, value2, "exciseMoney");
            return (Criteria) this;
        }

        public Criteria andTaxRatioIsNull() {
            addCriterion("tax_ratio is null");
            return (Criteria) this;
        }

        public Criteria andTaxRatioIsNotNull() {
            addCriterion("tax_ratio is not null");
            return (Criteria) this;
        }

        public Criteria andTaxRatioEqualTo(Double value) {
            addCriterion("tax_ratio =", value, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioNotEqualTo(Double value) {
            addCriterion("tax_ratio <>", value, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioGreaterThan(Double value) {
            addCriterion("tax_ratio >", value, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioGreaterThanOrEqualTo(Double value) {
            addCriterion("tax_ratio >=", value, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioLessThan(Double value) {
            addCriterion("tax_ratio <", value, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioLessThanOrEqualTo(Double value) {
            addCriterion("tax_ratio <=", value, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioIn(List<Double> values) {
            addCriterion("tax_ratio in", values, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioNotIn(List<Double> values) {
            addCriterion("tax_ratio not in", values, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioBetween(Double value1, Double value2) {
            addCriterion("tax_ratio between", value1, value2, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxRatioNotBetween(Double value1, Double value2) {
            addCriterion("tax_ratio not between", value1, value2, "taxRatio");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyIsNull() {
            addCriterion("tax_money is null");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyIsNotNull() {
            addCriterion("tax_money is not null");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyEqualTo(Double value) {
            addCriterion("tax_money =", value, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyNotEqualTo(Double value) {
            addCriterion("tax_money <>", value, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyGreaterThan(Double value) {
            addCriterion("tax_money >", value, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("tax_money >=", value, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyLessThan(Double value) {
            addCriterion("tax_money <", value, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyLessThanOrEqualTo(Double value) {
            addCriterion("tax_money <=", value, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyIn(List<Double> values) {
            addCriterion("tax_money in", values, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyNotIn(List<Double> values) {
            addCriterion("tax_money not in", values, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyBetween(Double value1, Double value2) {
            addCriterion("tax_money between", value1, value2, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andTaxMoneyNotBetween(Double value1, Double value2) {
            addCriterion("tax_money not between", value1, value2, "taxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyIsNull() {
            addCriterion("with_tax_money is null");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyIsNotNull() {
            addCriterion("with_tax_money is not null");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyEqualTo(Double value) {
            addCriterion("with_tax_money =", value, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyNotEqualTo(Double value) {
            addCriterion("with_tax_money <>", value, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyGreaterThan(Double value) {
            addCriterion("with_tax_money >", value, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("with_tax_money >=", value, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyLessThan(Double value) {
            addCriterion("with_tax_money <", value, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyLessThanOrEqualTo(Double value) {
            addCriterion("with_tax_money <=", value, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyIn(List<Double> values) {
            addCriterion("with_tax_money in", values, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyNotIn(List<Double> values) {
            addCriterion("with_tax_money not in", values, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyBetween(Double value1, Double value2) {
            addCriterion("with_tax_money between", value1, value2, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andWithTaxMoneyNotBetween(Double value1, Double value2) {
            addCriterion("with_tax_money not between", value1, value2, "withTaxMoney");
            return (Criteria) this;
        }

        public Criteria andDynamicRemarkIsNull() {
            addCriterion("dynamic_remark is null");
            return (Criteria) this;
        }

        public Criteria andDynamicRemarkIsNotNull() {
            addCriterion("dynamic_remark is not null");
            return (Criteria) this;
        }

        public Criteria andDynamicRemarkEqualTo(String value) {
            addCriterion("dynamic_remark =", value, "dynamicRemark");
            return (Criteria) this;
        }

        public Criteria andDynamicRemarkNotEqualTo(String value) {
            addCriterion("dynamic_remark <>", value, "dynamicRemark");
            return (Criteria) this;
        }

        public Criteria andDynamicRemarkGreaterThan(String value) {
            addCriterion("dynamic_remark >", value, "dynamicRemark");
            return (Criteria) this;
        }

        public Criteria andDynamicRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("dynamic_remark >=", value, "dynamicRemark");
            return (Criteria) this;
        }

        public Criteria andDynamicRemarkLessThan(String value) {
            addCriterion("dynamic_remark <", value, "dynamicRemark");
            return (Criteria) this;
        }

        public Criteria andDynamicRemarkLessThanOrEqualTo(String value) {
            addCriterion("dynamic_remark <=", value, "dynamicRemark");
            return (Criteria) this;
        }

        public Criteria andDynamicRemarkLike(String value) {
            addCriterion("dynamic_remark like", value, "dynamicRemark");
            return (Criteria) this;
        }

        public Criteria andDynamicRemarkNotLike(String value) {
            addCriterion("dynamic_remark not like", value, "dynamicRemark");
            return (Criteria) this;
        }

        public Criteria andDynamicRemarkIn(List<String> values) {
            addCriterion("dynamic_remark in", values, "dynamicRemark");
            return (Criteria) this;
        }

        public Criteria andDynamicRemarkNotIn(List<String> values) {
            addCriterion("dynamic_remark not in", values, "dynamicRemark");
            return (Criteria) this;
        }

        public Criteria andDynamicRemarkBetween(String value1, String value2) {
            addCriterion("dynamic_remark between", value1, value2, "dynamicRemark");
            return (Criteria) this;
        }

        public Criteria andDynamicRemarkNotBetween(String value1, String value2) {
            addCriterion("dynamic_remark not between", value1, value2, "dynamicRemark");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNull() {
            addCriterion("is_del_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNotNull() {
            addCriterion("is_del_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgEqualTo(String value) {
            addCriterion("is_del_flg =", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotEqualTo(String value) {
            addCriterion("is_del_flg <>", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThan(String value) {
            addCriterion("is_del_flg >", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_del_flg >=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThan(String value) {
            addCriterion("is_del_flg <", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThanOrEqualTo(String value) {
            addCriterion("is_del_flg <=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLike(String value) {
            addCriterion("is_del_flg like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotLike(String value) {
            addCriterion("is_del_flg not like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIn(List<String> values) {
            addCriterion("is_del_flg in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotIn(List<String> values) {
            addCriterion("is_del_flg not in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgBetween(String value1, String value2) {
            addCriterion("is_del_flg between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotBetween(String value1, String value2) {
            addCriterion("is_del_flg not between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andUncalibratedPriceIsNull() {
            addCriterion("uncalibrated_price is null");
            return (Criteria) this;
        }

        public Criteria andUncalibratedPriceIsNotNull() {
            addCriterion("uncalibrated_price is not null");
            return (Criteria) this;
        }

        public Criteria andUncalibratedPriceEqualTo(Double value) {
            addCriterion("uncalibrated_price =", value, "uncalibratedPrice");
            return (Criteria) this;
        }

        public Criteria andUncalibratedPriceNotEqualTo(Double value) {
            addCriterion("uncalibrated_price <>", value, "uncalibratedPrice");
            return (Criteria) this;
        }

        public Criteria andUncalibratedPriceGreaterThan(Double value) {
            addCriterion("uncalibrated_price >", value, "uncalibratedPrice");
            return (Criteria) this;
        }

        public Criteria andUncalibratedPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("uncalibrated_price >=", value, "uncalibratedPrice");
            return (Criteria) this;
        }

        public Criteria andUncalibratedPriceLessThan(Double value) {
            addCriterion("uncalibrated_price <", value, "uncalibratedPrice");
            return (Criteria) this;
        }

        public Criteria andUncalibratedPriceLessThanOrEqualTo(Double value) {
            addCriterion("uncalibrated_price <=", value, "uncalibratedPrice");
            return (Criteria) this;
        }

        public Criteria andUncalibratedPriceIn(List<Double> values) {
            addCriterion("uncalibrated_price in", values, "uncalibratedPrice");
            return (Criteria) this;
        }

        public Criteria andUncalibratedPriceNotIn(List<Double> values) {
            addCriterion("uncalibrated_price not in", values, "uncalibratedPrice");
            return (Criteria) this;
        }

        public Criteria andUncalibratedPriceBetween(Double value1, Double value2) {
            addCriterion("uncalibrated_price between", value1, value2, "uncalibratedPrice");
            return (Criteria) this;
        }

        public Criteria andUncalibratedPriceNotBetween(Double value1, Double value2) {
            addCriterion("uncalibrated_price not between", value1, value2, "uncalibratedPrice");
            return (Criteria) this;
        }

        public Criteria andTemporaryAmountIsNull() {
            addCriterion("temporary_amount is null");
            return (Criteria) this;
        }

        public Criteria andTemporaryAmountIsNotNull() {
            addCriterion("temporary_amount is not null");
            return (Criteria) this;
        }

        public Criteria andTemporaryAmountEqualTo(Double value) {
            addCriterion("temporary_amount =", value, "temporaryAmount");
            return (Criteria) this;
        }

        public Criteria andTemporaryAmountNotEqualTo(Double value) {
            addCriterion("temporary_amount <>", value, "temporaryAmount");
            return (Criteria) this;
        }

        public Criteria andTemporaryAmountGreaterThan(Double value) {
            addCriterion("temporary_amount >", value, "temporaryAmount");
            return (Criteria) this;
        }

        public Criteria andTemporaryAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("temporary_amount >=", value, "temporaryAmount");
            return (Criteria) this;
        }

        public Criteria andTemporaryAmountLessThan(Double value) {
            addCriterion("temporary_amount <", value, "temporaryAmount");
            return (Criteria) this;
        }

        public Criteria andTemporaryAmountLessThanOrEqualTo(Double value) {
            addCriterion("temporary_amount <=", value, "temporaryAmount");
            return (Criteria) this;
        }

        public Criteria andTemporaryAmountIn(List<Double> values) {
            addCriterion("temporary_amount in", values, "temporaryAmount");
            return (Criteria) this;
        }

        public Criteria andTemporaryAmountNotIn(List<Double> values) {
            addCriterion("temporary_amount not in", values, "temporaryAmount");
            return (Criteria) this;
        }

        public Criteria andTemporaryAmountBetween(Double value1, Double value2) {
            addCriterion("temporary_amount between", value1, value2, "temporaryAmount");
            return (Criteria) this;
        }

        public Criteria andTemporaryAmountNotBetween(Double value1, Double value2) {
            addCriterion("temporary_amount not between", value1, value2, "temporaryAmount");
            return (Criteria) this;
        }

        public Criteria andAlterValueIsNull() {
            addCriterion("alter_value is null");
            return (Criteria) this;
        }

        public Criteria andAlterValueIsNotNull() {
            addCriterion("alter_value is not null");
            return (Criteria) this;
        }

        public Criteria andAlterValueEqualTo(Double value) {
            addCriterion("alter_value =", value, "alterValue");
            return (Criteria) this;
        }

        public Criteria andAlterValueNotEqualTo(Double value) {
            addCriterion("alter_value <>", value, "alterValue");
            return (Criteria) this;
        }

        public Criteria andAlterValueGreaterThan(Double value) {
            addCriterion("alter_value >", value, "alterValue");
            return (Criteria) this;
        }

        public Criteria andAlterValueGreaterThanOrEqualTo(Double value) {
            addCriterion("alter_value >=", value, "alterValue");
            return (Criteria) this;
        }

        public Criteria andAlterValueLessThan(Double value) {
            addCriterion("alter_value <", value, "alterValue");
            return (Criteria) this;
        }

        public Criteria andAlterValueLessThanOrEqualTo(Double value) {
            addCriterion("alter_value <=", value, "alterValue");
            return (Criteria) this;
        }

        public Criteria andAlterValueIn(List<Double> values) {
            addCriterion("alter_value in", values, "alterValue");
            return (Criteria) this;
        }

        public Criteria andAlterValueNotIn(List<Double> values) {
            addCriterion("alter_value not in", values, "alterValue");
            return (Criteria) this;
        }

        public Criteria andAlterValueBetween(Double value1, Double value2) {
            addCriterion("alter_value between", value1, value2, "alterValue");
            return (Criteria) this;
        }

        public Criteria andAlterValueNotBetween(Double value1, Double value2) {
            addCriterion("alter_value not between", value1, value2, "alterValue");
            return (Criteria) this;
        }

        public Criteria andDrawingAdjustIsNull() {
            addCriterion("drawing_adjust is null");
            return (Criteria) this;
        }

        public Criteria andDrawingAdjustIsNotNull() {
            addCriterion("drawing_adjust is not null");
            return (Criteria) this;
        }

        public Criteria andDrawingAdjustEqualTo(Double value) {
            addCriterion("drawing_adjust =", value, "drawingAdjust");
            return (Criteria) this;
        }

        public Criteria andDrawingAdjustNotEqualTo(Double value) {
            addCriterion("drawing_adjust <>", value, "drawingAdjust");
            return (Criteria) this;
        }

        public Criteria andDrawingAdjustGreaterThan(Double value) {
            addCriterion("drawing_adjust >", value, "drawingAdjust");
            return (Criteria) this;
        }

        public Criteria andDrawingAdjustGreaterThanOrEqualTo(Double value) {
            addCriterion("drawing_adjust >=", value, "drawingAdjust");
            return (Criteria) this;
        }

        public Criteria andDrawingAdjustLessThan(Double value) {
            addCriterion("drawing_adjust <", value, "drawingAdjust");
            return (Criteria) this;
        }

        public Criteria andDrawingAdjustLessThanOrEqualTo(Double value) {
            addCriterion("drawing_adjust <=", value, "drawingAdjust");
            return (Criteria) this;
        }

        public Criteria andDrawingAdjustIn(List<Double> values) {
            addCriterion("drawing_adjust in", values, "drawingAdjust");
            return (Criteria) this;
        }

        public Criteria andDrawingAdjustNotIn(List<Double> values) {
            addCriterion("drawing_adjust not in", values, "drawingAdjust");
            return (Criteria) this;
        }

        public Criteria andDrawingAdjustBetween(Double value1, Double value2) {
            addCriterion("drawing_adjust between", value1, value2, "drawingAdjust");
            return (Criteria) this;
        }

        public Criteria andDrawingAdjustNotBetween(Double value1, Double value2) {
            addCriterion("drawing_adjust not between", value1, value2, "drawingAdjust");
            return (Criteria) this;
        }

        public Criteria andSignelAdjustIsNull() {
            addCriterion("signel_adjust is null");
            return (Criteria) this;
        }

        public Criteria andSignelAdjustIsNotNull() {
            addCriterion("signel_adjust is not null");
            return (Criteria) this;
        }

        public Criteria andSignelAdjustEqualTo(Double value) {
            addCriterion("signel_adjust =", value, "signelAdjust");
            return (Criteria) this;
        }

        public Criteria andSignelAdjustNotEqualTo(Double value) {
            addCriterion("signel_adjust <>", value, "signelAdjust");
            return (Criteria) this;
        }

        public Criteria andSignelAdjustGreaterThan(Double value) {
            addCriterion("signel_adjust >", value, "signelAdjust");
            return (Criteria) this;
        }

        public Criteria andSignelAdjustGreaterThanOrEqualTo(Double value) {
            addCriterion("signel_adjust >=", value, "signelAdjust");
            return (Criteria) this;
        }

        public Criteria andSignelAdjustLessThan(Double value) {
            addCriterion("signel_adjust <", value, "signelAdjust");
            return (Criteria) this;
        }

        public Criteria andSignelAdjustLessThanOrEqualTo(Double value) {
            addCriterion("signel_adjust <=", value, "signelAdjust");
            return (Criteria) this;
        }

        public Criteria andSignelAdjustIn(List<Double> values) {
            addCriterion("signel_adjust in", values, "signelAdjust");
            return (Criteria) this;
        }

        public Criteria andSignelAdjustNotIn(List<Double> values) {
            addCriterion("signel_adjust not in", values, "signelAdjust");
            return (Criteria) this;
        }

        public Criteria andSignelAdjustBetween(Double value1, Double value2) {
            addCriterion("signel_adjust between", value1, value2, "signelAdjust");
            return (Criteria) this;
        }

        public Criteria andSignelAdjustNotBetween(Double value1, Double value2) {
            addCriterion("signel_adjust not between", value1, value2, "signelAdjust");
            return (Criteria) this;
        }

        public Criteria andMaterialAdjustIsNull() {
            addCriterion("material_adjust is null");
            return (Criteria) this;
        }

        public Criteria andMaterialAdjustIsNotNull() {
            addCriterion("material_adjust is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialAdjustEqualTo(Double value) {
            addCriterion("material_adjust =", value, "materialAdjust");
            return (Criteria) this;
        }

        public Criteria andMaterialAdjustNotEqualTo(Double value) {
            addCriterion("material_adjust <>", value, "materialAdjust");
            return (Criteria) this;
        }

        public Criteria andMaterialAdjustGreaterThan(Double value) {
            addCriterion("material_adjust >", value, "materialAdjust");
            return (Criteria) this;
        }

        public Criteria andMaterialAdjustGreaterThanOrEqualTo(Double value) {
            addCriterion("material_adjust >=", value, "materialAdjust");
            return (Criteria) this;
        }

        public Criteria andMaterialAdjustLessThan(Double value) {
            addCriterion("material_adjust <", value, "materialAdjust");
            return (Criteria) this;
        }

        public Criteria andMaterialAdjustLessThanOrEqualTo(Double value) {
            addCriterion("material_adjust <=", value, "materialAdjust");
            return (Criteria) this;
        }

        public Criteria andMaterialAdjustIn(List<Double> values) {
            addCriterion("material_adjust in", values, "materialAdjust");
            return (Criteria) this;
        }

        public Criteria andMaterialAdjustNotIn(List<Double> values) {
            addCriterion("material_adjust not in", values, "materialAdjust");
            return (Criteria) this;
        }

        public Criteria andMaterialAdjustBetween(Double value1, Double value2) {
            addCriterion("material_adjust between", value1, value2, "materialAdjust");
            return (Criteria) this;
        }

        public Criteria andMaterialAdjustNotBetween(Double value1, Double value2) {
            addCriterion("material_adjust not between", value1, value2, "materialAdjust");
            return (Criteria) this;
        }

        public Criteria andPeopleAdjustIsNull() {
            addCriterion("people_adjust is null");
            return (Criteria) this;
        }

        public Criteria andPeopleAdjustIsNotNull() {
            addCriterion("people_adjust is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleAdjustEqualTo(Double value) {
            addCriterion("people_adjust =", value, "peopleAdjust");
            return (Criteria) this;
        }

        public Criteria andPeopleAdjustNotEqualTo(Double value) {
            addCriterion("people_adjust <>", value, "peopleAdjust");
            return (Criteria) this;
        }

        public Criteria andPeopleAdjustGreaterThan(Double value) {
            addCriterion("people_adjust >", value, "peopleAdjust");
            return (Criteria) this;
        }

        public Criteria andPeopleAdjustGreaterThanOrEqualTo(Double value) {
            addCriterion("people_adjust >=", value, "peopleAdjust");
            return (Criteria) this;
        }

        public Criteria andPeopleAdjustLessThan(Double value) {
            addCriterion("people_adjust <", value, "peopleAdjust");
            return (Criteria) this;
        }

        public Criteria andPeopleAdjustLessThanOrEqualTo(Double value) {
            addCriterion("people_adjust <=", value, "peopleAdjust");
            return (Criteria) this;
        }

        public Criteria andPeopleAdjustIn(List<Double> values) {
            addCriterion("people_adjust in", values, "peopleAdjust");
            return (Criteria) this;
        }

        public Criteria andPeopleAdjustNotIn(List<Double> values) {
            addCriterion("people_adjust not in", values, "peopleAdjust");
            return (Criteria) this;
        }

        public Criteria andPeopleAdjustBetween(Double value1, Double value2) {
            addCriterion("people_adjust between", value1, value2, "peopleAdjust");
            return (Criteria) this;
        }

        public Criteria andPeopleAdjustNotBetween(Double value1, Double value2) {
            addCriterion("people_adjust not between", value1, value2, "peopleAdjust");
            return (Criteria) this;
        }

        public Criteria andOtherThingIsNull() {
            addCriterion("other_thing is null");
            return (Criteria) this;
        }

        public Criteria andOtherThingIsNotNull() {
            addCriterion("other_thing is not null");
            return (Criteria) this;
        }

        public Criteria andOtherThingEqualTo(Double value) {
            addCriterion("other_thing =", value, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingNotEqualTo(Double value) {
            addCriterion("other_thing <>", value, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingGreaterThan(Double value) {
            addCriterion("other_thing >", value, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingGreaterThanOrEqualTo(Double value) {
            addCriterion("other_thing >=", value, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingLessThan(Double value) {
            addCriterion("other_thing <", value, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingLessThanOrEqualTo(Double value) {
            addCriterion("other_thing <=", value, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingIn(List<Double> values) {
            addCriterion("other_thing in", values, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingNotIn(List<Double> values) {
            addCriterion("other_thing not in", values, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingBetween(Double value1, Double value2) {
            addCriterion("other_thing between", value1, value2, "otherThing");
            return (Criteria) this;
        }

        public Criteria andOtherThingNotBetween(Double value1, Double value2) {
            addCriterion("other_thing not between", value1, value2, "otherThing");
            return (Criteria) this;
        }

        public Criteria andTaxAdjustIsNull() {
            addCriterion("tax_adjust is null");
            return (Criteria) this;
        }

        public Criteria andTaxAdjustIsNotNull() {
            addCriterion("tax_adjust is not null");
            return (Criteria) this;
        }

        public Criteria andTaxAdjustEqualTo(Double value) {
            addCriterion("tax_adjust =", value, "taxAdjust");
            return (Criteria) this;
        }

        public Criteria andTaxAdjustNotEqualTo(Double value) {
            addCriterion("tax_adjust <>", value, "taxAdjust");
            return (Criteria) this;
        }

        public Criteria andTaxAdjustGreaterThan(Double value) {
            addCriterion("tax_adjust >", value, "taxAdjust");
            return (Criteria) this;
        }

        public Criteria andTaxAdjustGreaterThanOrEqualTo(Double value) {
            addCriterion("tax_adjust >=", value, "taxAdjust");
            return (Criteria) this;
        }

        public Criteria andTaxAdjustLessThan(Double value) {
            addCriterion("tax_adjust <", value, "taxAdjust");
            return (Criteria) this;
        }

        public Criteria andTaxAdjustLessThanOrEqualTo(Double value) {
            addCriterion("tax_adjust <=", value, "taxAdjust");
            return (Criteria) this;
        }

        public Criteria andTaxAdjustIn(List<Double> values) {
            addCriterion("tax_adjust in", values, "taxAdjust");
            return (Criteria) this;
        }

        public Criteria andTaxAdjustNotIn(List<Double> values) {
            addCriterion("tax_adjust not in", values, "taxAdjust");
            return (Criteria) this;
        }

        public Criteria andTaxAdjustBetween(Double value1, Double value2) {
            addCriterion("tax_adjust between", value1, value2, "taxAdjust");
            return (Criteria) this;
        }

        public Criteria andTaxAdjustNotBetween(Double value1, Double value2) {
            addCriterion("tax_adjust not between", value1, value2, "taxAdjust");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNull() {
            addCriterion("total_price is null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNotNull() {
            addCriterion("total_price is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceEqualTo(Double value) {
            addCriterion("total_price =", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotEqualTo(Double value) {
            addCriterion("total_price <>", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThan(Double value) {
            addCriterion("total_price >", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("total_price >=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThan(Double value) {
            addCriterion("total_price <", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThanOrEqualTo(Double value) {
            addCriterion("total_price <=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIn(List<Double> values) {
            addCriterion("total_price in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotIn(List<Double> values) {
            addCriterion("total_price not in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceBetween(Double value1, Double value2) {
            addCriterion("total_price between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotBetween(Double value1, Double value2) {
            addCriterion("total_price not between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andPredictCloseValueIsNull() {
            addCriterion("predict_close_value is null");
            return (Criteria) this;
        }

        public Criteria andPredictCloseValueIsNotNull() {
            addCriterion("predict_close_value is not null");
            return (Criteria) this;
        }

        public Criteria andPredictCloseValueEqualTo(Double value) {
            addCriterion("predict_close_value =", value, "predictCloseValue");
            return (Criteria) this;
        }

        public Criteria andPredictCloseValueNotEqualTo(Double value) {
            addCriterion("predict_close_value <>", value, "predictCloseValue");
            return (Criteria) this;
        }

        public Criteria andPredictCloseValueGreaterThan(Double value) {
            addCriterion("predict_close_value >", value, "predictCloseValue");
            return (Criteria) this;
        }

        public Criteria andPredictCloseValueGreaterThanOrEqualTo(Double value) {
            addCriterion("predict_close_value >=", value, "predictCloseValue");
            return (Criteria) this;
        }

        public Criteria andPredictCloseValueLessThan(Double value) {
            addCriterion("predict_close_value <", value, "predictCloseValue");
            return (Criteria) this;
        }

        public Criteria andPredictCloseValueLessThanOrEqualTo(Double value) {
            addCriterion("predict_close_value <=", value, "predictCloseValue");
            return (Criteria) this;
        }

        public Criteria andPredictCloseValueIn(List<Double> values) {
            addCriterion("predict_close_value in", values, "predictCloseValue");
            return (Criteria) this;
        }

        public Criteria andPredictCloseValueNotIn(List<Double> values) {
            addCriterion("predict_close_value not in", values, "predictCloseValue");
            return (Criteria) this;
        }

        public Criteria andPredictCloseValueBetween(Double value1, Double value2) {
            addCriterion("predict_close_value between", value1, value2, "predictCloseValue");
            return (Criteria) this;
        }

        public Criteria andPredictCloseValueNotBetween(Double value1, Double value2) {
            addCriterion("predict_close_value not between", value1, value2, "predictCloseValue");
            return (Criteria) this;
        }
    }

    /**
     * tb_pro_contract
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_pro_contract null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}