package com.hd.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbProTreatyEntityExample {
    /**
     * tb_pro_treaty
     */
    protected String orderByClause;

    /**
     * tb_pro_treaty
     */
    protected boolean distinct;

    /**
     * tb_pro_treaty
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_pro_treaty
     */
    protected Integer limitStart;

    /**
     * tb_pro_treaty
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_treaty
     *
     * @mbg.generated
     */
    public TbProTreatyEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_treaty
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_treaty
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_treaty
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_treaty
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_treaty
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_treaty
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_treaty
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_treaty
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_treaty
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_treaty
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_treaty
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_treaty
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_treaty
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_treaty
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_pro_treaty null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTreatyIdIsNull() {
            addCriterion("treaty_id is null");
            return (Criteria) this;
        }

        public Criteria andTreatyIdIsNotNull() {
            addCriterion("treaty_id is not null");
            return (Criteria) this;
        }

        public Criteria andTreatyIdEqualTo(String value) {
            addCriterion("treaty_id =", value, "treatyId");
            return (Criteria) this;
        }

        public Criteria andTreatyIdNotEqualTo(String value) {
            addCriterion("treaty_id <>", value, "treatyId");
            return (Criteria) this;
        }

        public Criteria andTreatyIdGreaterThan(String value) {
            addCriterion("treaty_id >", value, "treatyId");
            return (Criteria) this;
        }

        public Criteria andTreatyIdGreaterThanOrEqualTo(String value) {
            addCriterion("treaty_id >=", value, "treatyId");
            return (Criteria) this;
        }

        public Criteria andTreatyIdLessThan(String value) {
            addCriterion("treaty_id <", value, "treatyId");
            return (Criteria) this;
        }

        public Criteria andTreatyIdLessThanOrEqualTo(String value) {
            addCriterion("treaty_id <=", value, "treatyId");
            return (Criteria) this;
        }

        public Criteria andTreatyIdLike(String value) {
            addCriterion("treaty_id like", value, "treatyId");
            return (Criteria) this;
        }

        public Criteria andTreatyIdNotLike(String value) {
            addCriterion("treaty_id not like", value, "treatyId");
            return (Criteria) this;
        }

        public Criteria andTreatyIdIn(List<String> values) {
            addCriterion("treaty_id in", values, "treatyId");
            return (Criteria) this;
        }

        public Criteria andTreatyIdNotIn(List<String> values) {
            addCriterion("treaty_id not in", values, "treatyId");
            return (Criteria) this;
        }

        public Criteria andTreatyIdBetween(String value1, String value2) {
            addCriterion("treaty_id between", value1, value2, "treatyId");
            return (Criteria) this;
        }

        public Criteria andTreatyIdNotBetween(String value1, String value2) {
            addCriterion("treaty_id not between", value1, value2, "treatyId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("project_id like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("project_id not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andTreatyNumIsNull() {
            addCriterion("treaty_num is null");
            return (Criteria) this;
        }

        public Criteria andTreatyNumIsNotNull() {
            addCriterion("treaty_num is not null");
            return (Criteria) this;
        }

        public Criteria andTreatyNumEqualTo(String value) {
            addCriterion("treaty_num =", value, "treatyNum");
            return (Criteria) this;
        }

        public Criteria andTreatyNumNotEqualTo(String value) {
            addCriterion("treaty_num <>", value, "treatyNum");
            return (Criteria) this;
        }

        public Criteria andTreatyNumGreaterThan(String value) {
            addCriterion("treaty_num >", value, "treatyNum");
            return (Criteria) this;
        }

        public Criteria andTreatyNumGreaterThanOrEqualTo(String value) {
            addCriterion("treaty_num >=", value, "treatyNum");
            return (Criteria) this;
        }

        public Criteria andTreatyNumLessThan(String value) {
            addCriterion("treaty_num <", value, "treatyNum");
            return (Criteria) this;
        }

        public Criteria andTreatyNumLessThanOrEqualTo(String value) {
            addCriterion("treaty_num <=", value, "treatyNum");
            return (Criteria) this;
        }

        public Criteria andTreatyNumLike(String value) {
            addCriterion("treaty_num like", value, "treatyNum");
            return (Criteria) this;
        }

        public Criteria andTreatyNumNotLike(String value) {
            addCriterion("treaty_num not like", value, "treatyNum");
            return (Criteria) this;
        }

        public Criteria andTreatyNumIn(List<String> values) {
            addCriterion("treaty_num in", values, "treatyNum");
            return (Criteria) this;
        }

        public Criteria andTreatyNumNotIn(List<String> values) {
            addCriterion("treaty_num not in", values, "treatyNum");
            return (Criteria) this;
        }

        public Criteria andTreatyNumBetween(String value1, String value2) {
            addCriterion("treaty_num between", value1, value2, "treatyNum");
            return (Criteria) this;
        }

        public Criteria andTreatyNumNotBetween(String value1, String value2) {
            addCriterion("treaty_num not between", value1, value2, "treatyNum");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeIsNull() {
            addCriterion("treaty_type is null");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeIsNotNull() {
            addCriterion("treaty_type is not null");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeEqualTo(String value) {
            addCriterion("treaty_type =", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeNotEqualTo(String value) {
            addCriterion("treaty_type <>", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeGreaterThan(String value) {
            addCriterion("treaty_type >", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeGreaterThanOrEqualTo(String value) {
            addCriterion("treaty_type >=", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeLessThan(String value) {
            addCriterion("treaty_type <", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeLessThanOrEqualTo(String value) {
            addCriterion("treaty_type <=", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeLike(String value) {
            addCriterion("treaty_type like", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeNotLike(String value) {
            addCriterion("treaty_type not like", value, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeIn(List<String> values) {
            addCriterion("treaty_type in", values, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeNotIn(List<String> values) {
            addCriterion("treaty_type not in", values, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeBetween(String value1, String value2) {
            addCriterion("treaty_type between", value1, value2, "treatyType");
            return (Criteria) this;
        }

        public Criteria andTreatyTypeNotBetween(String value1, String value2) {
            addCriterion("treaty_type not between", value1, value2, "treatyType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeIsNull() {
            addCriterion("undertake_type is null");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeIsNotNull() {
            addCriterion("undertake_type is not null");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeEqualTo(String value) {
            addCriterion("undertake_type =", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeNotEqualTo(String value) {
            addCriterion("undertake_type <>", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeGreaterThan(String value) {
            addCriterion("undertake_type >", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("undertake_type >=", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeLessThan(String value) {
            addCriterion("undertake_type <", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeLessThanOrEqualTo(String value) {
            addCriterion("undertake_type <=", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeLike(String value) {
            addCriterion("undertake_type like", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeNotLike(String value) {
            addCriterion("undertake_type not like", value, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeIn(List<String> values) {
            addCriterion("undertake_type in", values, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeNotIn(List<String> values) {
            addCriterion("undertake_type not in", values, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeBetween(String value1, String value2) {
            addCriterion("undertake_type between", value1, value2, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andUndertakeTypeNotBetween(String value1, String value2) {
            addCriterion("undertake_type not between", value1, value2, "undertakeType");
            return (Criteria) this;
        }

        public Criteria andTreatyNameIsNull() {
            addCriterion("treaty_name is null");
            return (Criteria) this;
        }

        public Criteria andTreatyNameIsNotNull() {
            addCriterion("treaty_name is not null");
            return (Criteria) this;
        }

        public Criteria andTreatyNameEqualTo(String value) {
            addCriterion("treaty_name =", value, "treatyName");
            return (Criteria) this;
        }

        public Criteria andTreatyNameNotEqualTo(String value) {
            addCriterion("treaty_name <>", value, "treatyName");
            return (Criteria) this;
        }

        public Criteria andTreatyNameGreaterThan(String value) {
            addCriterion("treaty_name >", value, "treatyName");
            return (Criteria) this;
        }

        public Criteria andTreatyNameGreaterThanOrEqualTo(String value) {
            addCriterion("treaty_name >=", value, "treatyName");
            return (Criteria) this;
        }

        public Criteria andTreatyNameLessThan(String value) {
            addCriterion("treaty_name <", value, "treatyName");
            return (Criteria) this;
        }

        public Criteria andTreatyNameLessThanOrEqualTo(String value) {
            addCriterion("treaty_name <=", value, "treatyName");
            return (Criteria) this;
        }

        public Criteria andTreatyNameLike(String value) {
            addCriterion("treaty_name like", value, "treatyName");
            return (Criteria) this;
        }

        public Criteria andTreatyNameNotLike(String value) {
            addCriterion("treaty_name not like", value, "treatyName");
            return (Criteria) this;
        }

        public Criteria andTreatyNameIn(List<String> values) {
            addCriterion("treaty_name in", values, "treatyName");
            return (Criteria) this;
        }

        public Criteria andTreatyNameNotIn(List<String> values) {
            addCriterion("treaty_name not in", values, "treatyName");
            return (Criteria) this;
        }

        public Criteria andTreatyNameBetween(String value1, String value2) {
            addCriterion("treaty_name between", value1, value2, "treatyName");
            return (Criteria) this;
        }

        public Criteria andTreatyNameNotBetween(String value1, String value2) {
            addCriterion("treaty_name not between", value1, value2, "treatyName");
            return (Criteria) this;
        }

        public Criteria andTreatyContentIsNull() {
            addCriterion("treaty_content is null");
            return (Criteria) this;
        }

        public Criteria andTreatyContentIsNotNull() {
            addCriterion("treaty_content is not null");
            return (Criteria) this;
        }

        public Criteria andTreatyContentEqualTo(String value) {
            addCriterion("treaty_content =", value, "treatyContent");
            return (Criteria) this;
        }

        public Criteria andTreatyContentNotEqualTo(String value) {
            addCriterion("treaty_content <>", value, "treatyContent");
            return (Criteria) this;
        }

        public Criteria andTreatyContentGreaterThan(String value) {
            addCriterion("treaty_content >", value, "treatyContent");
            return (Criteria) this;
        }

        public Criteria andTreatyContentGreaterThanOrEqualTo(String value) {
            addCriterion("treaty_content >=", value, "treatyContent");
            return (Criteria) this;
        }

        public Criteria andTreatyContentLessThan(String value) {
            addCriterion("treaty_content <", value, "treatyContent");
            return (Criteria) this;
        }

        public Criteria andTreatyContentLessThanOrEqualTo(String value) {
            addCriterion("treaty_content <=", value, "treatyContent");
            return (Criteria) this;
        }

        public Criteria andTreatyContentLike(String value) {
            addCriterion("treaty_content like", value, "treatyContent");
            return (Criteria) this;
        }

        public Criteria andTreatyContentNotLike(String value) {
            addCriterion("treaty_content not like", value, "treatyContent");
            return (Criteria) this;
        }

        public Criteria andTreatyContentIn(List<String> values) {
            addCriterion("treaty_content in", values, "treatyContent");
            return (Criteria) this;
        }

        public Criteria andTreatyContentNotIn(List<String> values) {
            addCriterion("treaty_content not in", values, "treatyContent");
            return (Criteria) this;
        }

        public Criteria andTreatyContentBetween(String value1, String value2) {
            addCriterion("treaty_content between", value1, value2, "treatyContent");
            return (Criteria) this;
        }

        public Criteria andTreatyContentNotBetween(String value1, String value2) {
            addCriterion("treaty_content not between", value1, value2, "treatyContent");
            return (Criteria) this;
        }

        public Criteria andTargetCostIsNull() {
            addCriterion("target_cost is null");
            return (Criteria) this;
        }

        public Criteria andTargetCostIsNotNull() {
            addCriterion("target_cost is not null");
            return (Criteria) this;
        }

        public Criteria andTargetCostEqualTo(Double value) {
            addCriterion("target_cost =", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostNotEqualTo(Double value) {
            addCriterion("target_cost <>", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostGreaterThan(Double value) {
            addCriterion("target_cost >", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostGreaterThanOrEqualTo(Double value) {
            addCriterion("target_cost >=", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostLessThan(Double value) {
            addCriterion("target_cost <", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostLessThanOrEqualTo(Double value) {
            addCriterion("target_cost <=", value, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostIn(List<Double> values) {
            addCriterion("target_cost in", values, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostNotIn(List<Double> values) {
            addCriterion("target_cost not in", values, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostBetween(Double value1, Double value2) {
            addCriterion("target_cost between", value1, value2, "targetCost");
            return (Criteria) this;
        }

        public Criteria andTargetCostNotBetween(Double value1, Double value2) {
            addCriterion("target_cost not between", value1, value2, "targetCost");
            return (Criteria) this;
        }

        public Criteria andContractTypeIsNull() {
            addCriterion("contract_type is null");
            return (Criteria) this;
        }

        public Criteria andContractTypeIsNotNull() {
            addCriterion("contract_type is not null");
            return (Criteria) this;
        }

        public Criteria andContractTypeEqualTo(String value) {
            addCriterion("contract_type =", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotEqualTo(String value) {
            addCriterion("contract_type <>", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeGreaterThan(String value) {
            addCriterion("contract_type >", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeGreaterThanOrEqualTo(String value) {
            addCriterion("contract_type >=", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeLessThan(String value) {
            addCriterion("contract_type <", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeLessThanOrEqualTo(String value) {
            addCriterion("contract_type <=", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeLike(String value) {
            addCriterion("contract_type like", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotLike(String value) {
            addCriterion("contract_type not like", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeIn(List<String> values) {
            addCriterion("contract_type in", values, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotIn(List<String> values) {
            addCriterion("contract_type not in", values, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeBetween(String value1, String value2) {
            addCriterion("contract_type between", value1, value2, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotBetween(String value1, String value2) {
            addCriterion("contract_type not between", value1, value2, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractWayIsNull() {
            addCriterion("contract_way is null");
            return (Criteria) this;
        }

        public Criteria andContractWayIsNotNull() {
            addCriterion("contract_way is not null");
            return (Criteria) this;
        }

        public Criteria andContractWayEqualTo(String value) {
            addCriterion("contract_way =", value, "contractWay");
            return (Criteria) this;
        }

        public Criteria andContractWayNotEqualTo(String value) {
            addCriterion("contract_way <>", value, "contractWay");
            return (Criteria) this;
        }

        public Criteria andContractWayGreaterThan(String value) {
            addCriterion("contract_way >", value, "contractWay");
            return (Criteria) this;
        }

        public Criteria andContractWayGreaterThanOrEqualTo(String value) {
            addCriterion("contract_way >=", value, "contractWay");
            return (Criteria) this;
        }

        public Criteria andContractWayLessThan(String value) {
            addCriterion("contract_way <", value, "contractWay");
            return (Criteria) this;
        }

        public Criteria andContractWayLessThanOrEqualTo(String value) {
            addCriterion("contract_way <=", value, "contractWay");
            return (Criteria) this;
        }

        public Criteria andContractWayLike(String value) {
            addCriterion("contract_way like", value, "contractWay");
            return (Criteria) this;
        }

        public Criteria andContractWayNotLike(String value) {
            addCriterion("contract_way not like", value, "contractWay");
            return (Criteria) this;
        }

        public Criteria andContractWayIn(List<String> values) {
            addCriterion("contract_way in", values, "contractWay");
            return (Criteria) this;
        }

        public Criteria andContractWayNotIn(List<String> values) {
            addCriterion("contract_way not in", values, "contractWay");
            return (Criteria) this;
        }

        public Criteria andContractWayBetween(String value1, String value2) {
            addCriterion("contract_way between", value1, value2, "contractWay");
            return (Criteria) this;
        }

        public Criteria andContractWayNotBetween(String value1, String value2) {
            addCriterion("contract_way not between", value1, value2, "contractWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayIsNull() {
            addCriterion("purchaser_way is null");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayIsNotNull() {
            addCriterion("purchaser_way is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayEqualTo(String value) {
            addCriterion("purchaser_way =", value, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayNotEqualTo(String value) {
            addCriterion("purchaser_way <>", value, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayGreaterThan(String value) {
            addCriterion("purchaser_way >", value, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayGreaterThanOrEqualTo(String value) {
            addCriterion("purchaser_way >=", value, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayLessThan(String value) {
            addCriterion("purchaser_way <", value, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayLessThanOrEqualTo(String value) {
            addCriterion("purchaser_way <=", value, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayLike(String value) {
            addCriterion("purchaser_way like", value, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayNotLike(String value) {
            addCriterion("purchaser_way not like", value, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayIn(List<String> values) {
            addCriterion("purchaser_way in", values, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayNotIn(List<String> values) {
            addCriterion("purchaser_way not in", values, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayBetween(String value1, String value2) {
            addCriterion("purchaser_way between", value1, value2, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andPurchaserWayNotBetween(String value1, String value2) {
            addCriterion("purchaser_way not between", value1, value2, "purchaserWay");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNull() {
            addCriterion("is_del_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNotNull() {
            addCriterion("is_del_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgEqualTo(String value) {
            addCriterion("is_del_flg =", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotEqualTo(String value) {
            addCriterion("is_del_flg <>", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThan(String value) {
            addCriterion("is_del_flg >", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_del_flg >=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThan(String value) {
            addCriterion("is_del_flg <", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThanOrEqualTo(String value) {
            addCriterion("is_del_flg <=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLike(String value) {
            addCriterion("is_del_flg like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotLike(String value) {
            addCriterion("is_del_flg not like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIn(List<String> values) {
            addCriterion("is_del_flg in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotIn(List<String> values) {
            addCriterion("is_del_flg not in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgBetween(String value1, String value2) {
            addCriterion("is_del_flg between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotBetween(String value1, String value2) {
            addCriterion("is_del_flg not between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }
    }

    /**
     * tb_pro_treaty
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_pro_treaty null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}