package com.hd.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbProClaimEntityExample {
    /**
     * tb_pro_claim
     */
    protected String orderByClause;

    /**
     * tb_pro_claim
     */
    protected boolean distinct;

    /**
     * tb_pro_claim
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_pro_claim
     */
    protected Integer limitStart;

    /**
     * tb_pro_claim
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    public TbProClaimEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_pro_claim null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClaimIdIsNull() {
            addCriterion("claim_id is null");
            return (Criteria) this;
        }

        public Criteria andClaimIdIsNotNull() {
            addCriterion("claim_id is not null");
            return (Criteria) this;
        }

        public Criteria andClaimIdEqualTo(String value) {
            addCriterion("claim_id =", value, "claimId");
            return (Criteria) this;
        }

        public Criteria andClaimIdNotEqualTo(String value) {
            addCriterion("claim_id <>", value, "claimId");
            return (Criteria) this;
        }

        public Criteria andClaimIdGreaterThan(String value) {
            addCriterion("claim_id >", value, "claimId");
            return (Criteria) this;
        }

        public Criteria andClaimIdGreaterThanOrEqualTo(String value) {
            addCriterion("claim_id >=", value, "claimId");
            return (Criteria) this;
        }

        public Criteria andClaimIdLessThan(String value) {
            addCriterion("claim_id <", value, "claimId");
            return (Criteria) this;
        }

        public Criteria andClaimIdLessThanOrEqualTo(String value) {
            addCriterion("claim_id <=", value, "claimId");
            return (Criteria) this;
        }

        public Criteria andClaimIdLike(String value) {
            addCriterion("claim_id like", value, "claimId");
            return (Criteria) this;
        }

        public Criteria andClaimIdNotLike(String value) {
            addCriterion("claim_id not like", value, "claimId");
            return (Criteria) this;
        }

        public Criteria andClaimIdIn(List<String> values) {
            addCriterion("claim_id in", values, "claimId");
            return (Criteria) this;
        }

        public Criteria andClaimIdNotIn(List<String> values) {
            addCriterion("claim_id not in", values, "claimId");
            return (Criteria) this;
        }

        public Criteria andClaimIdBetween(String value1, String value2) {
            addCriterion("claim_id between", value1, value2, "claimId");
            return (Criteria) this;
        }

        public Criteria andClaimIdNotBetween(String value1, String value2) {
            addCriterion("claim_id not between", value1, value2, "claimId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("project_id like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("project_id not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNull() {
            addCriterion("contract_id is null");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNotNull() {
            addCriterion("contract_id is not null");
            return (Criteria) this;
        }

        public Criteria andContractIdEqualTo(String value) {
            addCriterion("contract_id =", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotEqualTo(String value) {
            addCriterion("contract_id <>", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThan(String value) {
            addCriterion("contract_id >", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThanOrEqualTo(String value) {
            addCriterion("contract_id >=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThan(String value) {
            addCriterion("contract_id <", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThanOrEqualTo(String value) {
            addCriterion("contract_id <=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLike(String value) {
            addCriterion("contract_id like", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotLike(String value) {
            addCriterion("contract_id not like", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdIn(List<String> values) {
            addCriterion("contract_id in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotIn(List<String> values) {
            addCriterion("contract_id not in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdBetween(String value1, String value2) {
            addCriterion("contract_id between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotBetween(String value1, String value2) {
            addCriterion("contract_id not between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountIsNull() {
            addCriterion("declare_amount is null");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountIsNotNull() {
            addCriterion("declare_amount is not null");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountEqualTo(Double value) {
            addCriterion("declare_amount =", value, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountNotEqualTo(Double value) {
            addCriterion("declare_amount <>", value, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountGreaterThan(Double value) {
            addCriterion("declare_amount >", value, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("declare_amount >=", value, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountLessThan(Double value) {
            addCriterion("declare_amount <", value, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountLessThanOrEqualTo(Double value) {
            addCriterion("declare_amount <=", value, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountIn(List<Double> values) {
            addCriterion("declare_amount in", values, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountNotIn(List<Double> values) {
            addCriterion("declare_amount not in", values, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountBetween(Double value1, Double value2) {
            addCriterion("declare_amount between", value1, value2, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andDeclareAmountNotBetween(Double value1, Double value2) {
            addCriterion("declare_amount not between", value1, value2, "declareAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountIsNull() {
            addCriterion("hantten_amount is null");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountIsNotNull() {
            addCriterion("hantten_amount is not null");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountEqualTo(Double value) {
            addCriterion("hantten_amount =", value, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountNotEqualTo(Double value) {
            addCriterion("hantten_amount <>", value, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountGreaterThan(Double value) {
            addCriterion("hantten_amount >", value, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("hantten_amount >=", value, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountLessThan(Double value) {
            addCriterion("hantten_amount <", value, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountLessThanOrEqualTo(Double value) {
            addCriterion("hantten_amount <=", value, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountIn(List<Double> values) {
            addCriterion("hantten_amount in", values, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountNotIn(List<Double> values) {
            addCriterion("hantten_amount not in", values, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountBetween(Double value1, Double value2) {
            addCriterion("hantten_amount between", value1, value2, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andHanttenAmountNotBetween(Double value1, Double value2) {
            addCriterion("hantten_amount not between", value1, value2, "hanttenAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountIsNull() {
            addCriterion("confirm_amount is null");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountIsNotNull() {
            addCriterion("confirm_amount is not null");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountEqualTo(Double value) {
            addCriterion("confirm_amount =", value, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountNotEqualTo(Double value) {
            addCriterion("confirm_amount <>", value, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountGreaterThan(Double value) {
            addCriterion("confirm_amount >", value, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("confirm_amount >=", value, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountLessThan(Double value) {
            addCriterion("confirm_amount <", value, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountLessThanOrEqualTo(Double value) {
            addCriterion("confirm_amount <=", value, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountIn(List<Double> values) {
            addCriterion("confirm_amount in", values, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountNotIn(List<Double> values) {
            addCriterion("confirm_amount not in", values, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountBetween(Double value1, Double value2) {
            addCriterion("confirm_amount between", value1, value2, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountNotBetween(Double value1, Double value2) {
            addCriterion("confirm_amount not between", value1, value2, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andEstimatedAmountIsNull() {
            addCriterion("estimated_amount is null");
            return (Criteria) this;
        }

        public Criteria andEstimatedAmountIsNotNull() {
            addCriterion("estimated_amount is not null");
            return (Criteria) this;
        }

        public Criteria andEstimatedAmountEqualTo(Double value) {
            addCriterion("estimated_amount =", value, "estimatedAmount");
            return (Criteria) this;
        }

        public Criteria andEstimatedAmountNotEqualTo(Double value) {
            addCriterion("estimated_amount <>", value, "estimatedAmount");
            return (Criteria) this;
        }

        public Criteria andEstimatedAmountGreaterThan(Double value) {
            addCriterion("estimated_amount >", value, "estimatedAmount");
            return (Criteria) this;
        }

        public Criteria andEstimatedAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("estimated_amount >=", value, "estimatedAmount");
            return (Criteria) this;
        }

        public Criteria andEstimatedAmountLessThan(Double value) {
            addCriterion("estimated_amount <", value, "estimatedAmount");
            return (Criteria) this;
        }

        public Criteria andEstimatedAmountLessThanOrEqualTo(Double value) {
            addCriterion("estimated_amount <=", value, "estimatedAmount");
            return (Criteria) this;
        }

        public Criteria andEstimatedAmountIn(List<Double> values) {
            addCriterion("estimated_amount in", values, "estimatedAmount");
            return (Criteria) this;
        }

        public Criteria andEstimatedAmountNotIn(List<Double> values) {
            addCriterion("estimated_amount not in", values, "estimatedAmount");
            return (Criteria) this;
        }

        public Criteria andEstimatedAmountBetween(Double value1, Double value2) {
            addCriterion("estimated_amount between", value1, value2, "estimatedAmount");
            return (Criteria) this;
        }

        public Criteria andEstimatedAmountNotBetween(Double value1, Double value2) {
            addCriterion("estimated_amount not between", value1, value2, "estimatedAmount");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNull() {
            addCriterion("is_del_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNotNull() {
            addCriterion("is_del_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgEqualTo(String value) {
            addCriterion("is_del_flg =", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotEqualTo(String value) {
            addCriterion("is_del_flg <>", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThan(String value) {
            addCriterion("is_del_flg >", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_del_flg >=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThan(String value) {
            addCriterion("is_del_flg <", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThanOrEqualTo(String value) {
            addCriterion("is_del_flg <=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLike(String value) {
            addCriterion("is_del_flg like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotLike(String value) {
            addCriterion("is_del_flg not like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIn(List<String> values) {
            addCriterion("is_del_flg in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotIn(List<String> values) {
            addCriterion("is_del_flg not in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgBetween(String value1, String value2) {
            addCriterion("is_del_flg between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotBetween(String value1, String value2) {
            addCriterion("is_del_flg not between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }
    }

    /**
     * tb_pro_claim
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_pro_claim null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}