package com.hd.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbTaskEntityExample {
    /**
     * tb_task
     */
    protected String orderByClause;

    /**
     * tb_task
     */
    protected boolean distinct;

    /**
     * tb_task
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_task
     */
    protected Integer limitStart;

    /**
     * tb_task
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbg.generated
     */
    public TbTaskEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_task null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("task_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("task_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(String value) {
            addCriterion("task_id =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(String value) {
            addCriterion("task_id <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(String value) {
            addCriterion("task_id >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("task_id >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(String value) {
            addCriterion("task_id <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(String value) {
            addCriterion("task_id <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLike(String value) {
            addCriterion("task_id like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotLike(String value) {
            addCriterion("task_id not like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<String> values) {
            addCriterion("task_id in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<String> values) {
            addCriterion("task_id not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(String value1, String value2) {
            addCriterion("task_id between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(String value1, String value2) {
            addCriterion("task_id not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskNameIsNull() {
            addCriterion("task_name is null");
            return (Criteria) this;
        }

        public Criteria andTaskNameIsNotNull() {
            addCriterion("task_name is not null");
            return (Criteria) this;
        }

        public Criteria andTaskNameEqualTo(String value) {
            addCriterion("task_name =", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotEqualTo(String value) {
            addCriterion("task_name <>", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameGreaterThan(String value) {
            addCriterion("task_name >", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameGreaterThanOrEqualTo(String value) {
            addCriterion("task_name >=", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameLessThan(String value) {
            addCriterion("task_name <", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameLessThanOrEqualTo(String value) {
            addCriterion("task_name <=", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameLike(String value) {
            addCriterion("task_name like", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotLike(String value) {
            addCriterion("task_name not like", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameIn(List<String> values) {
            addCriterion("task_name in", values, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotIn(List<String> values) {
            addCriterion("task_name not in", values, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameBetween(String value1, String value2) {
            addCriterion("task_name between", value1, value2, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotBetween(String value1, String value2) {
            addCriterion("task_name not between", value1, value2, "taskName");
            return (Criteria) this;
        }

        public Criteria andReportNumIsNull() {
            addCriterion("report_num is null");
            return (Criteria) this;
        }

        public Criteria andReportNumIsNotNull() {
            addCriterion("report_num is not null");
            return (Criteria) this;
        }

        public Criteria andReportNumEqualTo(String value) {
            addCriterion("report_num =", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumNotEqualTo(String value) {
            addCriterion("report_num <>", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumGreaterThan(String value) {
            addCriterion("report_num >", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumGreaterThanOrEqualTo(String value) {
            addCriterion("report_num >=", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumLessThan(String value) {
            addCriterion("report_num <", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumLessThanOrEqualTo(String value) {
            addCriterion("report_num <=", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumLike(String value) {
            addCriterion("report_num like", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumNotLike(String value) {
            addCriterion("report_num not like", value, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumIn(List<String> values) {
            addCriterion("report_num in", values, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumNotIn(List<String> values) {
            addCriterion("report_num not in", values, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumBetween(String value1, String value2) {
            addCriterion("report_num between", value1, value2, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportNumNotBetween(String value1, String value2) {
            addCriterion("report_num not between", value1, value2, "reportNum");
            return (Criteria) this;
        }

        public Criteria andReportCopiesIsNull() {
            addCriterion("report_copies is null");
            return (Criteria) this;
        }

        public Criteria andReportCopiesIsNotNull() {
            addCriterion("report_copies is not null");
            return (Criteria) this;
        }

        public Criteria andReportCopiesEqualTo(String value) {
            addCriterion("report_copies =", value, "reportCopies");
            return (Criteria) this;
        }

        public Criteria andReportCopiesNotEqualTo(String value) {
            addCriterion("report_copies <>", value, "reportCopies");
            return (Criteria) this;
        }

        public Criteria andReportCopiesGreaterThan(String value) {
            addCriterion("report_copies >", value, "reportCopies");
            return (Criteria) this;
        }

        public Criteria andReportCopiesGreaterThanOrEqualTo(String value) {
            addCriterion("report_copies >=", value, "reportCopies");
            return (Criteria) this;
        }

        public Criteria andReportCopiesLessThan(String value) {
            addCriterion("report_copies <", value, "reportCopies");
            return (Criteria) this;
        }

        public Criteria andReportCopiesLessThanOrEqualTo(String value) {
            addCriterion("report_copies <=", value, "reportCopies");
            return (Criteria) this;
        }

        public Criteria andReportCopiesLike(String value) {
            addCriterion("report_copies like", value, "reportCopies");
            return (Criteria) this;
        }

        public Criteria andReportCopiesNotLike(String value) {
            addCriterion("report_copies not like", value, "reportCopies");
            return (Criteria) this;
        }

        public Criteria andReportCopiesIn(List<String> values) {
            addCriterion("report_copies in", values, "reportCopies");
            return (Criteria) this;
        }

        public Criteria andReportCopiesNotIn(List<String> values) {
            addCriterion("report_copies not in", values, "reportCopies");
            return (Criteria) this;
        }

        public Criteria andReportCopiesBetween(String value1, String value2) {
            addCriterion("report_copies between", value1, value2, "reportCopies");
            return (Criteria) this;
        }

        public Criteria andReportCopiesNotBetween(String value1, String value2) {
            addCriterion("report_copies not between", value1, value2, "reportCopies");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNull() {
            addCriterion("contract_id is null");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNotNull() {
            addCriterion("contract_id is not null");
            return (Criteria) this;
        }

        public Criteria andContractIdEqualTo(String value) {
            addCriterion("contract_id =", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotEqualTo(String value) {
            addCriterion("contract_id <>", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThan(String value) {
            addCriterion("contract_id >", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThanOrEqualTo(String value) {
            addCriterion("contract_id >=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThan(String value) {
            addCriterion("contract_id <", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThanOrEqualTo(String value) {
            addCriterion("contract_id <=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLike(String value) {
            addCriterion("contract_id like", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotLike(String value) {
            addCriterion("contract_id not like", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdIn(List<String> values) {
            addCriterion("contract_id in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotIn(List<String> values) {
            addCriterion("contract_id not in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdBetween(String value1, String value2) {
            addCriterion("contract_id between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotBetween(String value1, String value2) {
            addCriterion("contract_id not between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractTypeIdIsNull() {
            addCriterion("contract_type_id is null");
            return (Criteria) this;
        }

        public Criteria andContractTypeIdIsNotNull() {
            addCriterion("contract_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andContractTypeIdEqualTo(String value) {
            addCriterion("contract_type_id =", value, "contractTypeId");
            return (Criteria) this;
        }

        public Criteria andContractTypeIdNotEqualTo(String value) {
            addCriterion("contract_type_id <>", value, "contractTypeId");
            return (Criteria) this;
        }

        public Criteria andContractTypeIdGreaterThan(String value) {
            addCriterion("contract_type_id >", value, "contractTypeId");
            return (Criteria) this;
        }

        public Criteria andContractTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("contract_type_id >=", value, "contractTypeId");
            return (Criteria) this;
        }

        public Criteria andContractTypeIdLessThan(String value) {
            addCriterion("contract_type_id <", value, "contractTypeId");
            return (Criteria) this;
        }

        public Criteria andContractTypeIdLessThanOrEqualTo(String value) {
            addCriterion("contract_type_id <=", value, "contractTypeId");
            return (Criteria) this;
        }

        public Criteria andContractTypeIdLike(String value) {
            addCriterion("contract_type_id like", value, "contractTypeId");
            return (Criteria) this;
        }

        public Criteria andContractTypeIdNotLike(String value) {
            addCriterion("contract_type_id not like", value, "contractTypeId");
            return (Criteria) this;
        }

        public Criteria andContractTypeIdIn(List<String> values) {
            addCriterion("contract_type_id in", values, "contractTypeId");
            return (Criteria) this;
        }

        public Criteria andContractTypeIdNotIn(List<String> values) {
            addCriterion("contract_type_id not in", values, "contractTypeId");
            return (Criteria) this;
        }

        public Criteria andContractTypeIdBetween(String value1, String value2) {
            addCriterion("contract_type_id between", value1, value2, "contractTypeId");
            return (Criteria) this;
        }

        public Criteria andContractTypeIdNotBetween(String value1, String value2) {
            addCriterion("contract_type_id not between", value1, value2, "contractTypeId");
            return (Criteria) this;
        }

        public Criteria andCounselTypeIdIsNull() {
            addCriterion("counsel_type_id is null");
            return (Criteria) this;
        }

        public Criteria andCounselTypeIdIsNotNull() {
            addCriterion("counsel_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andCounselTypeIdEqualTo(String value) {
            addCriterion("counsel_type_id =", value, "counselTypeId");
            return (Criteria) this;
        }

        public Criteria andCounselTypeIdNotEqualTo(String value) {
            addCriterion("counsel_type_id <>", value, "counselTypeId");
            return (Criteria) this;
        }

        public Criteria andCounselTypeIdGreaterThan(String value) {
            addCriterion("counsel_type_id >", value, "counselTypeId");
            return (Criteria) this;
        }

        public Criteria andCounselTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("counsel_type_id >=", value, "counselTypeId");
            return (Criteria) this;
        }

        public Criteria andCounselTypeIdLessThan(String value) {
            addCriterion("counsel_type_id <", value, "counselTypeId");
            return (Criteria) this;
        }

        public Criteria andCounselTypeIdLessThanOrEqualTo(String value) {
            addCriterion("counsel_type_id <=", value, "counselTypeId");
            return (Criteria) this;
        }

        public Criteria andCounselTypeIdLike(String value) {
            addCriterion("counsel_type_id like", value, "counselTypeId");
            return (Criteria) this;
        }

        public Criteria andCounselTypeIdNotLike(String value) {
            addCriterion("counsel_type_id not like", value, "counselTypeId");
            return (Criteria) this;
        }

        public Criteria andCounselTypeIdIn(List<String> values) {
            addCriterion("counsel_type_id in", values, "counselTypeId");
            return (Criteria) this;
        }

        public Criteria andCounselTypeIdNotIn(List<String> values) {
            addCriterion("counsel_type_id not in", values, "counselTypeId");
            return (Criteria) this;
        }

        public Criteria andCounselTypeIdBetween(String value1, String value2) {
            addCriterion("counsel_type_id between", value1, value2, "counselTypeId");
            return (Criteria) this;
        }

        public Criteria andCounselTypeIdNotBetween(String value1, String value2) {
            addCriterion("counsel_type_id not between", value1, value2, "counselTypeId");
            return (Criteria) this;
        }

        public Criteria andFileNumberIsNull() {
            addCriterion("file_number is null");
            return (Criteria) this;
        }

        public Criteria andFileNumberIsNotNull() {
            addCriterion("file_number is not null");
            return (Criteria) this;
        }

        public Criteria andFileNumberEqualTo(String value) {
            addCriterion("file_number =", value, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberNotEqualTo(String value) {
            addCriterion("file_number <>", value, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberGreaterThan(String value) {
            addCriterion("file_number >", value, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberGreaterThanOrEqualTo(String value) {
            addCriterion("file_number >=", value, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberLessThan(String value) {
            addCriterion("file_number <", value, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberLessThanOrEqualTo(String value) {
            addCriterion("file_number <=", value, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberLike(String value) {
            addCriterion("file_number like", value, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberNotLike(String value) {
            addCriterion("file_number not like", value, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberIn(List<String> values) {
            addCriterion("file_number in", values, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberNotIn(List<String> values) {
            addCriterion("file_number not in", values, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberBetween(String value1, String value2) {
            addCriterion("file_number between", value1, value2, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFileNumberNotBetween(String value1, String value2) {
            addCriterion("file_number not between", value1, value2, "fileNumber");
            return (Criteria) this;
        }

        public Criteria andFormworkTypeIsNull() {
            addCriterion("formwork_type is null");
            return (Criteria) this;
        }

        public Criteria andFormworkTypeIsNotNull() {
            addCriterion("formwork_type is not null");
            return (Criteria) this;
        }

        public Criteria andFormworkTypeEqualTo(String value) {
            addCriterion("formwork_type =", value, "formworkType");
            return (Criteria) this;
        }

        public Criteria andFormworkTypeNotEqualTo(String value) {
            addCriterion("formwork_type <>", value, "formworkType");
            return (Criteria) this;
        }

        public Criteria andFormworkTypeGreaterThan(String value) {
            addCriterion("formwork_type >", value, "formworkType");
            return (Criteria) this;
        }

        public Criteria andFormworkTypeGreaterThanOrEqualTo(String value) {
            addCriterion("formwork_type >=", value, "formworkType");
            return (Criteria) this;
        }

        public Criteria andFormworkTypeLessThan(String value) {
            addCriterion("formwork_type <", value, "formworkType");
            return (Criteria) this;
        }

        public Criteria andFormworkTypeLessThanOrEqualTo(String value) {
            addCriterion("formwork_type <=", value, "formworkType");
            return (Criteria) this;
        }

        public Criteria andFormworkTypeLike(String value) {
            addCriterion("formwork_type like", value, "formworkType");
            return (Criteria) this;
        }

        public Criteria andFormworkTypeNotLike(String value) {
            addCriterion("formwork_type not like", value, "formworkType");
            return (Criteria) this;
        }

        public Criteria andFormworkTypeIn(List<String> values) {
            addCriterion("formwork_type in", values, "formworkType");
            return (Criteria) this;
        }

        public Criteria andFormworkTypeNotIn(List<String> values) {
            addCriterion("formwork_type not in", values, "formworkType");
            return (Criteria) this;
        }

        public Criteria andFormworkTypeBetween(String value1, String value2) {
            addCriterion("formwork_type between", value1, value2, "formworkType");
            return (Criteria) this;
        }

        public Criteria andFormworkTypeNotBetween(String value1, String value2) {
            addCriterion("formwork_type not between", value1, value2, "formworkType");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNull() {
            addCriterion("is_del_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNotNull() {
            addCriterion("is_del_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgEqualTo(String value) {
            addCriterion("is_del_flg =", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotEqualTo(String value) {
            addCriterion("is_del_flg <>", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThan(String value) {
            addCriterion("is_del_flg >", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_del_flg >=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThan(String value) {
            addCriterion("is_del_flg <", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThanOrEqualTo(String value) {
            addCriterion("is_del_flg <=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLike(String value) {
            addCriterion("is_del_flg like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotLike(String value) {
            addCriterion("is_del_flg not like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIn(List<String> values) {
            addCriterion("is_del_flg in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotIn(List<String> values) {
            addCriterion("is_del_flg not in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgBetween(String value1, String value2) {
            addCriterion("is_del_flg between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotBetween(String value1, String value2) {
            addCriterion("is_del_flg not between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdIsNull() {
            addCriterion("process_inst_id is null");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdIsNotNull() {
            addCriterion("process_inst_id is not null");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdEqualTo(String value) {
            addCriterion("process_inst_id =", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdNotEqualTo(String value) {
            addCriterion("process_inst_id <>", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdGreaterThan(String value) {
            addCriterion("process_inst_id >", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdGreaterThanOrEqualTo(String value) {
            addCriterion("process_inst_id >=", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdLessThan(String value) {
            addCriterion("process_inst_id <", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdLessThanOrEqualTo(String value) {
            addCriterion("process_inst_id <=", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdLike(String value) {
            addCriterion("process_inst_id like", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdNotLike(String value) {
            addCriterion("process_inst_id not like", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdIn(List<String> values) {
            addCriterion("process_inst_id in", values, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdNotIn(List<String> values) {
            addCriterion("process_inst_id not in", values, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdBetween(String value1, String value2) {
            addCriterion("process_inst_id between", value1, value2, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdNotBetween(String value1, String value2) {
            addCriterion("process_inst_id not between", value1, value2, "processInstId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyIsNull() {
            addCriterion("delegate_task_key is null");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyIsNotNull() {
            addCriterion("delegate_task_key is not null");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyEqualTo(String value) {
            addCriterion("delegate_task_key =", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyNotEqualTo(String value) {
            addCriterion("delegate_task_key <>", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyGreaterThan(String value) {
            addCriterion("delegate_task_key >", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyGreaterThanOrEqualTo(String value) {
            addCriterion("delegate_task_key >=", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyLessThan(String value) {
            addCriterion("delegate_task_key <", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyLessThanOrEqualTo(String value) {
            addCriterion("delegate_task_key <=", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyLike(String value) {
            addCriterion("delegate_task_key like", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyNotLike(String value) {
            addCriterion("delegate_task_key not like", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyIn(List<String> values) {
            addCriterion("delegate_task_key in", values, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyNotIn(List<String> values) {
            addCriterion("delegate_task_key not in", values, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyBetween(String value1, String value2) {
            addCriterion("delegate_task_key between", value1, value2, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyNotBetween(String value1, String value2) {
            addCriterion("delegate_task_key not between", value1, value2, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdIsNull() {
            addCriterion("delegate_task_id is null");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdIsNotNull() {
            addCriterion("delegate_task_id is not null");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdEqualTo(String value) {
            addCriterion("delegate_task_id =", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdNotEqualTo(String value) {
            addCriterion("delegate_task_id <>", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdGreaterThan(String value) {
            addCriterion("delegate_task_id >", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("delegate_task_id >=", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdLessThan(String value) {
            addCriterion("delegate_task_id <", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdLessThanOrEqualTo(String value) {
            addCriterion("delegate_task_id <=", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdLike(String value) {
            addCriterion("delegate_task_id like", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdNotLike(String value) {
            addCriterion("delegate_task_id not like", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdIn(List<String> values) {
            addCriterion("delegate_task_id in", values, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdNotIn(List<String> values) {
            addCriterion("delegate_task_id not in", values, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdBetween(String value1, String value2) {
            addCriterion("delegate_task_id between", value1, value2, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdNotBetween(String value1, String value2) {
            addCriterion("delegate_task_id not between", value1, value2, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIsNull() {
            addCriterion("apply_user_id is null");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIsNotNull() {
            addCriterion("apply_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdEqualTo(String value) {
            addCriterion("apply_user_id =", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotEqualTo(String value) {
            addCriterion("apply_user_id <>", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdGreaterThan(String value) {
            addCriterion("apply_user_id >", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("apply_user_id >=", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdLessThan(String value) {
            addCriterion("apply_user_id <", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdLessThanOrEqualTo(String value) {
            addCriterion("apply_user_id <=", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdLike(String value) {
            addCriterion("apply_user_id like", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotLike(String value) {
            addCriterion("apply_user_id not like", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIn(List<String> values) {
            addCriterion("apply_user_id in", values, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotIn(List<String> values) {
            addCriterion("apply_user_id not in", values, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdBetween(String value1, String value2) {
            addCriterion("apply_user_id between", value1, value2, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotBetween(String value1, String value2) {
            addCriterion("apply_user_id not between", value1, value2, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameIsNull() {
            addCriterion("apply_user_name is null");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameIsNotNull() {
            addCriterion("apply_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameEqualTo(String value) {
            addCriterion("apply_user_name =", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotEqualTo(String value) {
            addCriterion("apply_user_name <>", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameGreaterThan(String value) {
            addCriterion("apply_user_name >", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("apply_user_name >=", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameLessThan(String value) {
            addCriterion("apply_user_name <", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameLessThanOrEqualTo(String value) {
            addCriterion("apply_user_name <=", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameLike(String value) {
            addCriterion("apply_user_name like", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotLike(String value) {
            addCriterion("apply_user_name not like", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameIn(List<String> values) {
            addCriterion("apply_user_name in", values, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotIn(List<String> values) {
            addCriterion("apply_user_name not in", values, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameBetween(String value1, String value2) {
            addCriterion("apply_user_name between", value1, value2, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotBetween(String value1, String value2) {
            addCriterion("apply_user_name not between", value1, value2, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIsNull() {
            addCriterion("apply_time is null");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIsNotNull() {
            addCriterion("apply_time is not null");
            return (Criteria) this;
        }

        public Criteria andApplyTimeEqualTo(Date value) {
            addCriterion("apply_time =", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotEqualTo(Date value) {
            addCriterion("apply_time <>", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeGreaterThan(Date value) {
            addCriterion("apply_time >", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("apply_time >=", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeLessThan(Date value) {
            addCriterion("apply_time <", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeLessThanOrEqualTo(Date value) {
            addCriterion("apply_time <=", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIn(List<Date> values) {
            addCriterion("apply_time in", values, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotIn(List<Date> values) {
            addCriterion("apply_time not in", values, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeBetween(Date value1, Date value2) {
            addCriterion("apply_time between", value1, value2, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotBetween(Date value1, Date value2) {
            addCriterion("apply_time not between", value1, value2, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdIsNull() {
            addCriterion("approve_user_id is null");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdIsNotNull() {
            addCriterion("approve_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdEqualTo(String value) {
            addCriterion("approve_user_id =", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdNotEqualTo(String value) {
            addCriterion("approve_user_id <>", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdGreaterThan(String value) {
            addCriterion("approve_user_id >", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("approve_user_id >=", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdLessThan(String value) {
            addCriterion("approve_user_id <", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdLessThanOrEqualTo(String value) {
            addCriterion("approve_user_id <=", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdLike(String value) {
            addCriterion("approve_user_id like", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdNotLike(String value) {
            addCriterion("approve_user_id not like", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdIn(List<String> values) {
            addCriterion("approve_user_id in", values, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdNotIn(List<String> values) {
            addCriterion("approve_user_id not in", values, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdBetween(String value1, String value2) {
            addCriterion("approve_user_id between", value1, value2, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdNotBetween(String value1, String value2) {
            addCriterion("approve_user_id not between", value1, value2, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameIsNull() {
            addCriterion("approve_user_name is null");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameIsNotNull() {
            addCriterion("approve_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameEqualTo(String value) {
            addCriterion("approve_user_name =", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameNotEqualTo(String value) {
            addCriterion("approve_user_name <>", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameGreaterThan(String value) {
            addCriterion("approve_user_name >", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("approve_user_name >=", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameLessThan(String value) {
            addCriterion("approve_user_name <", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameLessThanOrEqualTo(String value) {
            addCriterion("approve_user_name <=", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameLike(String value) {
            addCriterion("approve_user_name like", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameNotLike(String value) {
            addCriterion("approve_user_name not like", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameIn(List<String> values) {
            addCriterion("approve_user_name in", values, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameNotIn(List<String> values) {
            addCriterion("approve_user_name not in", values, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameBetween(String value1, String value2) {
            addCriterion("approve_user_name between", value1, value2, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameNotBetween(String value1, String value2) {
            addCriterion("approve_user_name not between", value1, value2, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIsNull() {
            addCriterion("approve_time is null");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIsNotNull() {
            addCriterion("approve_time is not null");
            return (Criteria) this;
        }

        public Criteria andApproveTimeEqualTo(Date value) {
            addCriterion("approve_time =", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotEqualTo(Date value) {
            addCriterion("approve_time <>", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeGreaterThan(Date value) {
            addCriterion("approve_time >", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("approve_time >=", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeLessThan(Date value) {
            addCriterion("approve_time <", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeLessThanOrEqualTo(Date value) {
            addCriterion("approve_time <=", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIn(List<Date> values) {
            addCriterion("approve_time in", values, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotIn(List<Date> values) {
            addCriterion("approve_time not in", values, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeBetween(Date value1, Date value2) {
            addCriterion("approve_time between", value1, value2, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotBetween(Date value1, Date value2) {
            addCriterion("approve_time not between", value1, value2, "approveTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeIsNull() {
            addCriterion("complete_time is null");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeIsNotNull() {
            addCriterion("complete_time is not null");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeEqualTo(Date value) {
            addCriterion("complete_time =", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeNotEqualTo(Date value) {
            addCriterion("complete_time <>", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeGreaterThan(Date value) {
            addCriterion("complete_time >", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("complete_time >=", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeLessThan(Date value) {
            addCriterion("complete_time <", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeLessThanOrEqualTo(Date value) {
            addCriterion("complete_time <=", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeIn(List<Date> values) {
            addCriterion("complete_time in", values, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeNotIn(List<Date> values) {
            addCriterion("complete_time not in", values, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeBetween(Date value1, Date value2) {
            addCriterion("complete_time between", value1, value2, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeNotBetween(Date value1, Date value2) {
            addCriterion("complete_time not between", value1, value2, "completeTime");
            return (Criteria) this;
        }

        public Criteria andVerifyStateIsNull() {
            addCriterion("verify_state is null");
            return (Criteria) this;
        }

        public Criteria andVerifyStateIsNotNull() {
            addCriterion("verify_state is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyStateEqualTo(String value) {
            addCriterion("verify_state =", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateNotEqualTo(String value) {
            addCriterion("verify_state <>", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateGreaterThan(String value) {
            addCriterion("verify_state >", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateGreaterThanOrEqualTo(String value) {
            addCriterion("verify_state >=", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateLessThan(String value) {
            addCriterion("verify_state <", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateLessThanOrEqualTo(String value) {
            addCriterion("verify_state <=", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateLike(String value) {
            addCriterion("verify_state like", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateNotLike(String value) {
            addCriterion("verify_state not like", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateIn(List<String> values) {
            addCriterion("verify_state in", values, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateNotIn(List<String> values) {
            addCriterion("verify_state not in", values, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateBetween(String value1, String value2) {
            addCriterion("verify_state between", value1, value2, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateNotBetween(String value1, String value2) {
            addCriterion("verify_state not between", value1, value2, "verifyState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateIsNull() {
            addCriterion("current_state is null");
            return (Criteria) this;
        }

        public Criteria andCurrentStateIsNotNull() {
            addCriterion("current_state is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentStateEqualTo(String value) {
            addCriterion("current_state =", value, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateNotEqualTo(String value) {
            addCriterion("current_state <>", value, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateGreaterThan(String value) {
            addCriterion("current_state >", value, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateGreaterThanOrEqualTo(String value) {
            addCriterion("current_state >=", value, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateLessThan(String value) {
            addCriterion("current_state <", value, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateLessThanOrEqualTo(String value) {
            addCriterion("current_state <=", value, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateLike(String value) {
            addCriterion("current_state like", value, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateNotLike(String value) {
            addCriterion("current_state not like", value, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateIn(List<String> values) {
            addCriterion("current_state in", values, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateNotIn(List<String> values) {
            addCriterion("current_state not in", values, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateBetween(String value1, String value2) {
            addCriterion("current_state between", value1, value2, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateNotBetween(String value1, String value2) {
            addCriterion("current_state not between", value1, value2, "currentState");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeIsNull() {
            addCriterion("submit_node is null");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeIsNotNull() {
            addCriterion("submit_node is not null");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeEqualTo(String value) {
            addCriterion("submit_node =", value, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeNotEqualTo(String value) {
            addCriterion("submit_node <>", value, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeGreaterThan(String value) {
            addCriterion("submit_node >", value, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeGreaterThanOrEqualTo(String value) {
            addCriterion("submit_node >=", value, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeLessThan(String value) {
            addCriterion("submit_node <", value, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeLessThanOrEqualTo(String value) {
            addCriterion("submit_node <=", value, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeLike(String value) {
            addCriterion("submit_node like", value, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeNotLike(String value) {
            addCriterion("submit_node not like", value, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeIn(List<String> values) {
            addCriterion("submit_node in", values, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeNotIn(List<String> values) {
            addCriterion("submit_node not in", values, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeBetween(String value1, String value2) {
            addCriterion("submit_node between", value1, value2, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeNotBetween(String value1, String value2) {
            addCriterion("submit_node not between", value1, value2, "submitNode");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallIsNull() {
            addCriterion("is_can_recall is null");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallIsNotNull() {
            addCriterion("is_can_recall is not null");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallEqualTo(String value) {
            addCriterion("is_can_recall =", value, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallNotEqualTo(String value) {
            addCriterion("is_can_recall <>", value, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallGreaterThan(String value) {
            addCriterion("is_can_recall >", value, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallGreaterThanOrEqualTo(String value) {
            addCriterion("is_can_recall >=", value, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallLessThan(String value) {
            addCriterion("is_can_recall <", value, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallLessThanOrEqualTo(String value) {
            addCriterion("is_can_recall <=", value, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallLike(String value) {
            addCriterion("is_can_recall like", value, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallNotLike(String value) {
            addCriterion("is_can_recall not like", value, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallIn(List<String> values) {
            addCriterion("is_can_recall in", values, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallNotIn(List<String> values) {
            addCriterion("is_can_recall not in", values, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallBetween(String value1, String value2) {
            addCriterion("is_can_recall between", value1, value2, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallNotBetween(String value1, String value2) {
            addCriterion("is_can_recall not between", value1, value2, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsPassReeditIsNull() {
            addCriterion("is_pass_reedit is null");
            return (Criteria) this;
        }

        public Criteria andIsPassReeditIsNotNull() {
            addCriterion("is_pass_reedit is not null");
            return (Criteria) this;
        }

        public Criteria andIsPassReeditEqualTo(String value) {
            addCriterion("is_pass_reedit =", value, "isPassReedit");
            return (Criteria) this;
        }

        public Criteria andIsPassReeditNotEqualTo(String value) {
            addCriterion("is_pass_reedit <>", value, "isPassReedit");
            return (Criteria) this;
        }

        public Criteria andIsPassReeditGreaterThan(String value) {
            addCriterion("is_pass_reedit >", value, "isPassReedit");
            return (Criteria) this;
        }

        public Criteria andIsPassReeditGreaterThanOrEqualTo(String value) {
            addCriterion("is_pass_reedit >=", value, "isPassReedit");
            return (Criteria) this;
        }

        public Criteria andIsPassReeditLessThan(String value) {
            addCriterion("is_pass_reedit <", value, "isPassReedit");
            return (Criteria) this;
        }

        public Criteria andIsPassReeditLessThanOrEqualTo(String value) {
            addCriterion("is_pass_reedit <=", value, "isPassReedit");
            return (Criteria) this;
        }

        public Criteria andIsPassReeditLike(String value) {
            addCriterion("is_pass_reedit like", value, "isPassReedit");
            return (Criteria) this;
        }

        public Criteria andIsPassReeditNotLike(String value) {
            addCriterion("is_pass_reedit not like", value, "isPassReedit");
            return (Criteria) this;
        }

        public Criteria andIsPassReeditIn(List<String> values) {
            addCriterion("is_pass_reedit in", values, "isPassReedit");
            return (Criteria) this;
        }

        public Criteria andIsPassReeditNotIn(List<String> values) {
            addCriterion("is_pass_reedit not in", values, "isPassReedit");
            return (Criteria) this;
        }

        public Criteria andIsPassReeditBetween(String value1, String value2) {
            addCriterion("is_pass_reedit between", value1, value2, "isPassReedit");
            return (Criteria) this;
        }

        public Criteria andIsPassReeditNotBetween(String value1, String value2) {
            addCriterion("is_pass_reedit not between", value1, value2, "isPassReedit");
            return (Criteria) this;
        }

        public Criteria andIsSubmitReeditIsNull() {
            addCriterion("is_submit_reedit is null");
            return (Criteria) this;
        }

        public Criteria andIsSubmitReeditIsNotNull() {
            addCriterion("is_submit_reedit is not null");
            return (Criteria) this;
        }

        public Criteria andIsSubmitReeditEqualTo(String value) {
            addCriterion("is_submit_reedit =", value, "isSubmitReedit");
            return (Criteria) this;
        }

        public Criteria andIsSubmitReeditNotEqualTo(String value) {
            addCriterion("is_submit_reedit <>", value, "isSubmitReedit");
            return (Criteria) this;
        }

        public Criteria andIsSubmitReeditGreaterThan(String value) {
            addCriterion("is_submit_reedit >", value, "isSubmitReedit");
            return (Criteria) this;
        }

        public Criteria andIsSubmitReeditGreaterThanOrEqualTo(String value) {
            addCriterion("is_submit_reedit >=", value, "isSubmitReedit");
            return (Criteria) this;
        }

        public Criteria andIsSubmitReeditLessThan(String value) {
            addCriterion("is_submit_reedit <", value, "isSubmitReedit");
            return (Criteria) this;
        }

        public Criteria andIsSubmitReeditLessThanOrEqualTo(String value) {
            addCriterion("is_submit_reedit <=", value, "isSubmitReedit");
            return (Criteria) this;
        }

        public Criteria andIsSubmitReeditLike(String value) {
            addCriterion("is_submit_reedit like", value, "isSubmitReedit");
            return (Criteria) this;
        }

        public Criteria andIsSubmitReeditNotLike(String value) {
            addCriterion("is_submit_reedit not like", value, "isSubmitReedit");
            return (Criteria) this;
        }

        public Criteria andIsSubmitReeditIn(List<String> values) {
            addCriterion("is_submit_reedit in", values, "isSubmitReedit");
            return (Criteria) this;
        }

        public Criteria andIsSubmitReeditNotIn(List<String> values) {
            addCriterion("is_submit_reedit not in", values, "isSubmitReedit");
            return (Criteria) this;
        }

        public Criteria andIsSubmitReeditBetween(String value1, String value2) {
            addCriterion("is_submit_reedit between", value1, value2, "isSubmitReedit");
            return (Criteria) this;
        }

        public Criteria andIsSubmitReeditNotBetween(String value1, String value2) {
            addCriterion("is_submit_reedit not between", value1, value2, "isSubmitReedit");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialPathIsNull() {
            addCriterion("task_material_path is null");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialPathIsNotNull() {
            addCriterion("task_material_path is not null");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialPathEqualTo(String value) {
            addCriterion("task_material_path =", value, "taskMaterialPath");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialPathNotEqualTo(String value) {
            addCriterion("task_material_path <>", value, "taskMaterialPath");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialPathGreaterThan(String value) {
            addCriterion("task_material_path >", value, "taskMaterialPath");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialPathGreaterThanOrEqualTo(String value) {
            addCriterion("task_material_path >=", value, "taskMaterialPath");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialPathLessThan(String value) {
            addCriterion("task_material_path <", value, "taskMaterialPath");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialPathLessThanOrEqualTo(String value) {
            addCriterion("task_material_path <=", value, "taskMaterialPath");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialPathLike(String value) {
            addCriterion("task_material_path like", value, "taskMaterialPath");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialPathNotLike(String value) {
            addCriterion("task_material_path not like", value, "taskMaterialPath");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialPathIn(List<String> values) {
            addCriterion("task_material_path in", values, "taskMaterialPath");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialPathNotIn(List<String> values) {
            addCriterion("task_material_path not in", values, "taskMaterialPath");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialPathBetween(String value1, String value2) {
            addCriterion("task_material_path between", value1, value2, "taskMaterialPath");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialPathNotBetween(String value1, String value2) {
            addCriterion("task_material_path not between", value1, value2, "taskMaterialPath");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialNameIsNull() {
            addCriterion("task_material_name is null");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialNameIsNotNull() {
            addCriterion("task_material_name is not null");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialNameEqualTo(String value) {
            addCriterion("task_material_name =", value, "taskMaterialName");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialNameNotEqualTo(String value) {
            addCriterion("task_material_name <>", value, "taskMaterialName");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialNameGreaterThan(String value) {
            addCriterion("task_material_name >", value, "taskMaterialName");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialNameGreaterThanOrEqualTo(String value) {
            addCriterion("task_material_name >=", value, "taskMaterialName");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialNameLessThan(String value) {
            addCriterion("task_material_name <", value, "taskMaterialName");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialNameLessThanOrEqualTo(String value) {
            addCriterion("task_material_name <=", value, "taskMaterialName");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialNameLike(String value) {
            addCriterion("task_material_name like", value, "taskMaterialName");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialNameNotLike(String value) {
            addCriterion("task_material_name not like", value, "taskMaterialName");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialNameIn(List<String> values) {
            addCriterion("task_material_name in", values, "taskMaterialName");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialNameNotIn(List<String> values) {
            addCriterion("task_material_name not in", values, "taskMaterialName");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialNameBetween(String value1, String value2) {
            addCriterion("task_material_name between", value1, value2, "taskMaterialName");
            return (Criteria) this;
        }

        public Criteria andTaskMaterialNameNotBetween(String value1, String value2) {
            addCriterion("task_material_name not between", value1, value2, "taskMaterialName");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIsNull() {
            addCriterion("task_type is null");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIsNotNull() {
            addCriterion("task_type is not null");
            return (Criteria) this;
        }

        public Criteria andTaskTypeEqualTo(String value) {
            addCriterion("task_type =", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotEqualTo(String value) {
            addCriterion("task_type <>", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeGreaterThan(String value) {
            addCriterion("task_type >", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeGreaterThanOrEqualTo(String value) {
            addCriterion("task_type >=", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLessThan(String value) {
            addCriterion("task_type <", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLessThanOrEqualTo(String value) {
            addCriterion("task_type <=", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLike(String value) {
            addCriterion("task_type like", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotLike(String value) {
            addCriterion("task_type not like", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIn(List<String> values) {
            addCriterion("task_type in", values, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotIn(List<String> values) {
            addCriterion("task_type not in", values, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeBetween(String value1, String value2) {
            addCriterion("task_type between", value1, value2, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotBetween(String value1, String value2) {
            addCriterion("task_type not between", value1, value2, "taskType");
            return (Criteria) this;
        }

        public Criteria andIsDraftFlgIsNull() {
            addCriterion("is_draft_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDraftFlgIsNotNull() {
            addCriterion("is_draft_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDraftFlgEqualTo(String value) {
            addCriterion("is_draft_flg =", value, "isDraftFlg");
            return (Criteria) this;
        }

        public Criteria andIsDraftFlgNotEqualTo(String value) {
            addCriterion("is_draft_flg <>", value, "isDraftFlg");
            return (Criteria) this;
        }

        public Criteria andIsDraftFlgGreaterThan(String value) {
            addCriterion("is_draft_flg >", value, "isDraftFlg");
            return (Criteria) this;
        }

        public Criteria andIsDraftFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_draft_flg >=", value, "isDraftFlg");
            return (Criteria) this;
        }

        public Criteria andIsDraftFlgLessThan(String value) {
            addCriterion("is_draft_flg <", value, "isDraftFlg");
            return (Criteria) this;
        }

        public Criteria andIsDraftFlgLessThanOrEqualTo(String value) {
            addCriterion("is_draft_flg <=", value, "isDraftFlg");
            return (Criteria) this;
        }

        public Criteria andIsDraftFlgLike(String value) {
            addCriterion("is_draft_flg like", value, "isDraftFlg");
            return (Criteria) this;
        }

        public Criteria andIsDraftFlgNotLike(String value) {
            addCriterion("is_draft_flg not like", value, "isDraftFlg");
            return (Criteria) this;
        }

        public Criteria andIsDraftFlgIn(List<String> values) {
            addCriterion("is_draft_flg in", values, "isDraftFlg");
            return (Criteria) this;
        }

        public Criteria andIsDraftFlgNotIn(List<String> values) {
            addCriterion("is_draft_flg not in", values, "isDraftFlg");
            return (Criteria) this;
        }

        public Criteria andIsDraftFlgBetween(String value1, String value2) {
            addCriterion("is_draft_flg between", value1, value2, "isDraftFlg");
            return (Criteria) this;
        }

        public Criteria andIsDraftFlgNotBetween(String value1, String value2) {
            addCriterion("is_draft_flg not between", value1, value2, "isDraftFlg");
            return (Criteria) this;
        }

        public Criteria andAddDraftUserIdIsNull() {
            addCriterion("add_draft_user_id is null");
            return (Criteria) this;
        }

        public Criteria andAddDraftUserIdIsNotNull() {
            addCriterion("add_draft_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andAddDraftUserIdEqualTo(String value) {
            addCriterion("add_draft_user_id =", value, "addDraftUserId");
            return (Criteria) this;
        }

        public Criteria andAddDraftUserIdNotEqualTo(String value) {
            addCriterion("add_draft_user_id <>", value, "addDraftUserId");
            return (Criteria) this;
        }

        public Criteria andAddDraftUserIdGreaterThan(String value) {
            addCriterion("add_draft_user_id >", value, "addDraftUserId");
            return (Criteria) this;
        }

        public Criteria andAddDraftUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("add_draft_user_id >=", value, "addDraftUserId");
            return (Criteria) this;
        }

        public Criteria andAddDraftUserIdLessThan(String value) {
            addCriterion("add_draft_user_id <", value, "addDraftUserId");
            return (Criteria) this;
        }

        public Criteria andAddDraftUserIdLessThanOrEqualTo(String value) {
            addCriterion("add_draft_user_id <=", value, "addDraftUserId");
            return (Criteria) this;
        }

        public Criteria andAddDraftUserIdLike(String value) {
            addCriterion("add_draft_user_id like", value, "addDraftUserId");
            return (Criteria) this;
        }

        public Criteria andAddDraftUserIdNotLike(String value) {
            addCriterion("add_draft_user_id not like", value, "addDraftUserId");
            return (Criteria) this;
        }

        public Criteria andAddDraftUserIdIn(List<String> values) {
            addCriterion("add_draft_user_id in", values, "addDraftUserId");
            return (Criteria) this;
        }

        public Criteria andAddDraftUserIdNotIn(List<String> values) {
            addCriterion("add_draft_user_id not in", values, "addDraftUserId");
            return (Criteria) this;
        }

        public Criteria andAddDraftUserIdBetween(String value1, String value2) {
            addCriterion("add_draft_user_id between", value1, value2, "addDraftUserId");
            return (Criteria) this;
        }

        public Criteria andAddDraftUserIdNotBetween(String value1, String value2) {
            addCriterion("add_draft_user_id not between", value1, value2, "addDraftUserId");
            return (Criteria) this;
        }

        public Criteria andSeniorExecutiveIsNull() {
            addCriterion("senior_executive is null");
            return (Criteria) this;
        }

        public Criteria andSeniorExecutiveIsNotNull() {
            addCriterion("senior_executive is not null");
            return (Criteria) this;
        }

        public Criteria andSeniorExecutiveEqualTo(String value) {
            addCriterion("senior_executive =", value, "seniorExecutive");
            return (Criteria) this;
        }

        public Criteria andSeniorExecutiveNotEqualTo(String value) {
            addCriterion("senior_executive <>", value, "seniorExecutive");
            return (Criteria) this;
        }

        public Criteria andSeniorExecutiveGreaterThan(String value) {
            addCriterion("senior_executive >", value, "seniorExecutive");
            return (Criteria) this;
        }

        public Criteria andSeniorExecutiveGreaterThanOrEqualTo(String value) {
            addCriterion("senior_executive >=", value, "seniorExecutive");
            return (Criteria) this;
        }

        public Criteria andSeniorExecutiveLessThan(String value) {
            addCriterion("senior_executive <", value, "seniorExecutive");
            return (Criteria) this;
        }

        public Criteria andSeniorExecutiveLessThanOrEqualTo(String value) {
            addCriterion("senior_executive <=", value, "seniorExecutive");
            return (Criteria) this;
        }

        public Criteria andSeniorExecutiveLike(String value) {
            addCriterion("senior_executive like", value, "seniorExecutive");
            return (Criteria) this;
        }

        public Criteria andSeniorExecutiveNotLike(String value) {
            addCriterion("senior_executive not like", value, "seniorExecutive");
            return (Criteria) this;
        }

        public Criteria andSeniorExecutiveIn(List<String> values) {
            addCriterion("senior_executive in", values, "seniorExecutive");
            return (Criteria) this;
        }

        public Criteria andSeniorExecutiveNotIn(List<String> values) {
            addCriterion("senior_executive not in", values, "seniorExecutive");
            return (Criteria) this;
        }

        public Criteria andSeniorExecutiveBetween(String value1, String value2) {
            addCriterion("senior_executive between", value1, value2, "seniorExecutive");
            return (Criteria) this;
        }

        public Criteria andSeniorExecutiveNotBetween(String value1, String value2) {
            addCriterion("senior_executive not between", value1, value2, "seniorExecutive");
            return (Criteria) this;
        }
    }

    /**
     * tb_task
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_task null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}