package com.hd.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbTaskPeriodHisTaskInstExample {
    /**
     * tb_task_period_his_task_inst
     */
    protected String orderByClause;

    /**
     * tb_task_period_his_task_inst
     */
    protected boolean distinct;

    /**
     * tb_task_period_his_task_inst
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_task_period_his_task_inst
     */
    protected Integer limitStart;

    /**
     * tb_task_period_his_task_inst
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_his_task_inst
     *
     * @mbg.generated
     */
    public TbTaskPeriodHisTaskInstExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_his_task_inst
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_his_task_inst
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_his_task_inst
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_his_task_inst
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_his_task_inst
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_his_task_inst
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_his_task_inst
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_his_task_inst
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_his_task_inst
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_his_task_inst
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_his_task_inst
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_his_task_inst
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_his_task_inst
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_his_task_inst
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_task_period_his_task_inst null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHistoryIdIsNull() {
            addCriterion("history_id is null");
            return (Criteria) this;
        }

        public Criteria andHistoryIdIsNotNull() {
            addCriterion("history_id is not null");
            return (Criteria) this;
        }

        public Criteria andHistoryIdEqualTo(String value) {
            addCriterion("history_id =", value, "historyId");
            return (Criteria) this;
        }

        public Criteria andHistoryIdNotEqualTo(String value) {
            addCriterion("history_id <>", value, "historyId");
            return (Criteria) this;
        }

        public Criteria andHistoryIdGreaterThan(String value) {
            addCriterion("history_id >", value, "historyId");
            return (Criteria) this;
        }

        public Criteria andHistoryIdGreaterThanOrEqualTo(String value) {
            addCriterion("history_id >=", value, "historyId");
            return (Criteria) this;
        }

        public Criteria andHistoryIdLessThan(String value) {
            addCriterion("history_id <", value, "historyId");
            return (Criteria) this;
        }

        public Criteria andHistoryIdLessThanOrEqualTo(String value) {
            addCriterion("history_id <=", value, "historyId");
            return (Criteria) this;
        }

        public Criteria andHistoryIdLike(String value) {
            addCriterion("history_id like", value, "historyId");
            return (Criteria) this;
        }

        public Criteria andHistoryIdNotLike(String value) {
            addCriterion("history_id not like", value, "historyId");
            return (Criteria) this;
        }

        public Criteria andHistoryIdIn(List<String> values) {
            addCriterion("history_id in", values, "historyId");
            return (Criteria) this;
        }

        public Criteria andHistoryIdNotIn(List<String> values) {
            addCriterion("history_id not in", values, "historyId");
            return (Criteria) this;
        }

        public Criteria andHistoryIdBetween(String value1, String value2) {
            addCriterion("history_id between", value1, value2, "historyId");
            return (Criteria) this;
        }

        public Criteria andHistoryIdNotBetween(String value1, String value2) {
            addCriterion("history_id not between", value1, value2, "historyId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("task_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("task_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(String value) {
            addCriterion("task_id =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(String value) {
            addCriterion("task_id <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(String value) {
            addCriterion("task_id >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("task_id >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(String value) {
            addCriterion("task_id <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(String value) {
            addCriterion("task_id <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLike(String value) {
            addCriterion("task_id like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotLike(String value) {
            addCriterion("task_id not like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<String> values) {
            addCriterion("task_id in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<String> values) {
            addCriterion("task_id not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(String value1, String value2) {
            addCriterion("task_id between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(String value1, String value2) {
            addCriterion("task_id not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskPeriodIdIsNull() {
            addCriterion("task_period_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskPeriodIdIsNotNull() {
            addCriterion("task_period_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskPeriodIdEqualTo(String value) {
            addCriterion("task_period_id =", value, "taskPeriodId");
            return (Criteria) this;
        }

        public Criteria andTaskPeriodIdNotEqualTo(String value) {
            addCriterion("task_period_id <>", value, "taskPeriodId");
            return (Criteria) this;
        }

        public Criteria andTaskPeriodIdGreaterThan(String value) {
            addCriterion("task_period_id >", value, "taskPeriodId");
            return (Criteria) this;
        }

        public Criteria andTaskPeriodIdGreaterThanOrEqualTo(String value) {
            addCriterion("task_period_id >=", value, "taskPeriodId");
            return (Criteria) this;
        }

        public Criteria andTaskPeriodIdLessThan(String value) {
            addCriterion("task_period_id <", value, "taskPeriodId");
            return (Criteria) this;
        }

        public Criteria andTaskPeriodIdLessThanOrEqualTo(String value) {
            addCriterion("task_period_id <=", value, "taskPeriodId");
            return (Criteria) this;
        }

        public Criteria andTaskPeriodIdLike(String value) {
            addCriterion("task_period_id like", value, "taskPeriodId");
            return (Criteria) this;
        }

        public Criteria andTaskPeriodIdNotLike(String value) {
            addCriterion("task_period_id not like", value, "taskPeriodId");
            return (Criteria) this;
        }

        public Criteria andTaskPeriodIdIn(List<String> values) {
            addCriterion("task_period_id in", values, "taskPeriodId");
            return (Criteria) this;
        }

        public Criteria andTaskPeriodIdNotIn(List<String> values) {
            addCriterion("task_period_id not in", values, "taskPeriodId");
            return (Criteria) this;
        }

        public Criteria andTaskPeriodIdBetween(String value1, String value2) {
            addCriterion("task_period_id between", value1, value2, "taskPeriodId");
            return (Criteria) this;
        }

        public Criteria andTaskPeriodIdNotBetween(String value1, String value2) {
            addCriterion("task_period_id not between", value1, value2, "taskPeriodId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdIsNull() {
            addCriterion("process_inst_id is null");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdIsNotNull() {
            addCriterion("process_inst_id is not null");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdEqualTo(String value) {
            addCriterion("process_inst_id =", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdNotEqualTo(String value) {
            addCriterion("process_inst_id <>", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdGreaterThan(String value) {
            addCriterion("process_inst_id >", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdGreaterThanOrEqualTo(String value) {
            addCriterion("process_inst_id >=", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdLessThan(String value) {
            addCriterion("process_inst_id <", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdLessThanOrEqualTo(String value) {
            addCriterion("process_inst_id <=", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdLike(String value) {
            addCriterion("process_inst_id like", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdNotLike(String value) {
            addCriterion("process_inst_id not like", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdIn(List<String> values) {
            addCriterion("process_inst_id in", values, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdNotIn(List<String> values) {
            addCriterion("process_inst_id not in", values, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdBetween(String value1, String value2) {
            addCriterion("process_inst_id between", value1, value2, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdNotBetween(String value1, String value2) {
            addCriterion("process_inst_id not between", value1, value2, "processInstId");
            return (Criteria) this;
        }

        public Criteria andTaskKeyIsNull() {
            addCriterion("task_key is null");
            return (Criteria) this;
        }

        public Criteria andTaskKeyIsNotNull() {
            addCriterion("task_key is not null");
            return (Criteria) this;
        }

        public Criteria andTaskKeyEqualTo(String value) {
            addCriterion("task_key =", value, "taskKey");
            return (Criteria) this;
        }

        public Criteria andTaskKeyNotEqualTo(String value) {
            addCriterion("task_key <>", value, "taskKey");
            return (Criteria) this;
        }

        public Criteria andTaskKeyGreaterThan(String value) {
            addCriterion("task_key >", value, "taskKey");
            return (Criteria) this;
        }

        public Criteria andTaskKeyGreaterThanOrEqualTo(String value) {
            addCriterion("task_key >=", value, "taskKey");
            return (Criteria) this;
        }

        public Criteria andTaskKeyLessThan(String value) {
            addCriterion("task_key <", value, "taskKey");
            return (Criteria) this;
        }

        public Criteria andTaskKeyLessThanOrEqualTo(String value) {
            addCriterion("task_key <=", value, "taskKey");
            return (Criteria) this;
        }

        public Criteria andTaskKeyLike(String value) {
            addCriterion("task_key like", value, "taskKey");
            return (Criteria) this;
        }

        public Criteria andTaskKeyNotLike(String value) {
            addCriterion("task_key not like", value, "taskKey");
            return (Criteria) this;
        }

        public Criteria andTaskKeyIn(List<String> values) {
            addCriterion("task_key in", values, "taskKey");
            return (Criteria) this;
        }

        public Criteria andTaskKeyNotIn(List<String> values) {
            addCriterion("task_key not in", values, "taskKey");
            return (Criteria) this;
        }

        public Criteria andTaskKeyBetween(String value1, String value2) {
            addCriterion("task_key between", value1, value2, "taskKey");
            return (Criteria) this;
        }

        public Criteria andTaskKeyNotBetween(String value1, String value2) {
            addCriterion("task_key not between", value1, value2, "taskKey");
            return (Criteria) this;
        }

        public Criteria andIsPassIsNull() {
            addCriterion("is_pass is null");
            return (Criteria) this;
        }

        public Criteria andIsPassIsNotNull() {
            addCriterion("is_pass is not null");
            return (Criteria) this;
        }

        public Criteria andIsPassEqualTo(String value) {
            addCriterion("is_pass =", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassNotEqualTo(String value) {
            addCriterion("is_pass <>", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassGreaterThan(String value) {
            addCriterion("is_pass >", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassGreaterThanOrEqualTo(String value) {
            addCriterion("is_pass >=", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassLessThan(String value) {
            addCriterion("is_pass <", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassLessThanOrEqualTo(String value) {
            addCriterion("is_pass <=", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassLike(String value) {
            addCriterion("is_pass like", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassNotLike(String value) {
            addCriterion("is_pass not like", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassIn(List<String> values) {
            addCriterion("is_pass in", values, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassNotIn(List<String> values) {
            addCriterion("is_pass not in", values, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassBetween(String value1, String value2) {
            addCriterion("is_pass between", value1, value2, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassNotBetween(String value1, String value2) {
            addCriterion("is_pass not between", value1, value2, "isPass");
            return (Criteria) this;
        }

        public Criteria andRejectReasonIsNull() {
            addCriterion("reject_reason is null");
            return (Criteria) this;
        }

        public Criteria andRejectReasonIsNotNull() {
            addCriterion("reject_reason is not null");
            return (Criteria) this;
        }

        public Criteria andRejectReasonEqualTo(String value) {
            addCriterion("reject_reason =", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonNotEqualTo(String value) {
            addCriterion("reject_reason <>", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonGreaterThan(String value) {
            addCriterion("reject_reason >", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonGreaterThanOrEqualTo(String value) {
            addCriterion("reject_reason >=", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonLessThan(String value) {
            addCriterion("reject_reason <", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonLessThanOrEqualTo(String value) {
            addCriterion("reject_reason <=", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonLike(String value) {
            addCriterion("reject_reason like", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonNotLike(String value) {
            addCriterion("reject_reason not like", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonIn(List<String> values) {
            addCriterion("reject_reason in", values, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonNotIn(List<String> values) {
            addCriterion("reject_reason not in", values, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonBetween(String value1, String value2) {
            addCriterion("reject_reason between", value1, value2, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonNotBetween(String value1, String value2) {
            addCriterion("reject_reason not between", value1, value2, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdIsNull() {
            addCriterion("approve_user_id is null");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdIsNotNull() {
            addCriterion("approve_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdEqualTo(String value) {
            addCriterion("approve_user_id =", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdNotEqualTo(String value) {
            addCriterion("approve_user_id <>", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdGreaterThan(String value) {
            addCriterion("approve_user_id >", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("approve_user_id >=", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdLessThan(String value) {
            addCriterion("approve_user_id <", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdLessThanOrEqualTo(String value) {
            addCriterion("approve_user_id <=", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdLike(String value) {
            addCriterion("approve_user_id like", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdNotLike(String value) {
            addCriterion("approve_user_id not like", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdIn(List<String> values) {
            addCriterion("approve_user_id in", values, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdNotIn(List<String> values) {
            addCriterion("approve_user_id not in", values, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdBetween(String value1, String value2) {
            addCriterion("approve_user_id between", value1, value2, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdNotBetween(String value1, String value2) {
            addCriterion("approve_user_id not between", value1, value2, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIsNull() {
            addCriterion("approve_time is null");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIsNotNull() {
            addCriterion("approve_time is not null");
            return (Criteria) this;
        }

        public Criteria andApproveTimeEqualTo(Date value) {
            addCriterion("approve_time =", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotEqualTo(Date value) {
            addCriterion("approve_time <>", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeGreaterThan(Date value) {
            addCriterion("approve_time >", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("approve_time >=", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeLessThan(Date value) {
            addCriterion("approve_time <", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeLessThanOrEqualTo(Date value) {
            addCriterion("approve_time <=", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIn(List<Date> values) {
            addCriterion("approve_time in", values, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotIn(List<Date> values) {
            addCriterion("approve_time not in", values, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeBetween(Date value1, Date value2) {
            addCriterion("approve_time between", value1, value2, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotBetween(Date value1, Date value2) {
            addCriterion("approve_time not between", value1, value2, "approveTime");
            return (Criteria) this;
        }

        public Criteria andIsResultFileIsNull() {
            addCriterion("is_result_file is null");
            return (Criteria) this;
        }

        public Criteria andIsResultFileIsNotNull() {
            addCriterion("is_result_file is not null");
            return (Criteria) this;
        }

        public Criteria andIsResultFileEqualTo(String value) {
            addCriterion("is_result_file =", value, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileNotEqualTo(String value) {
            addCriterion("is_result_file <>", value, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileGreaterThan(String value) {
            addCriterion("is_result_file >", value, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileGreaterThanOrEqualTo(String value) {
            addCriterion("is_result_file >=", value, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileLessThan(String value) {
            addCriterion("is_result_file <", value, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileLessThanOrEqualTo(String value) {
            addCriterion("is_result_file <=", value, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileLike(String value) {
            addCriterion("is_result_file like", value, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileNotLike(String value) {
            addCriterion("is_result_file not like", value, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileIn(List<String> values) {
            addCriterion("is_result_file in", values, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileNotIn(List<String> values) {
            addCriterion("is_result_file not in", values, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileBetween(String value1, String value2) {
            addCriterion("is_result_file between", value1, value2, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileNotBetween(String value1, String value2) {
            addCriterion("is_result_file not between", value1, value2, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNull() {
            addCriterion("is_del_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNotNull() {
            addCriterion("is_del_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgEqualTo(String value) {
            addCriterion("is_del_flg =", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotEqualTo(String value) {
            addCriterion("is_del_flg <>", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThan(String value) {
            addCriterion("is_del_flg >", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_del_flg >=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThan(String value) {
            addCriterion("is_del_flg <", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThanOrEqualTo(String value) {
            addCriterion("is_del_flg <=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLike(String value) {
            addCriterion("is_del_flg like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotLike(String value) {
            addCriterion("is_del_flg not like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIn(List<String> values) {
            addCriterion("is_del_flg in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotIn(List<String> values) {
            addCriterion("is_del_flg not in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgBetween(String value1, String value2) {
            addCriterion("is_del_flg between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotBetween(String value1, String value2) {
            addCriterion("is_del_flg not between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }
    }

    /**
     * tb_task_period_his_task_inst
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_task_period_his_task_inst null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}