package com.hd.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbTableFiveRelationEntityExample {
    /**
     * tb_table_five_relation
     */
    protected String orderByClause;

    /**
     * tb_table_five_relation
     */
    protected boolean distinct;

    /**
     * tb_table_five_relation
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_table_five_relation
     */
    protected Integer limitStart;

    /**
     * tb_table_five_relation
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_five_relation
     *
     * @mbg.generated
     */
    public TbTableFiveRelationEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_five_relation
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_five_relation
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_five_relation
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_five_relation
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_five_relation
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_five_relation
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_five_relation
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_five_relation
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_five_relation
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_five_relation
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_five_relation
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_five_relation
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_five_relation
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_five_relation
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_table_five_relation null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRelationIdIsNull() {
            addCriterion("relation_id is null");
            return (Criteria) this;
        }

        public Criteria andRelationIdIsNotNull() {
            addCriterion("relation_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelationIdEqualTo(String value) {
            addCriterion("relation_id =", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotEqualTo(String value) {
            addCriterion("relation_id <>", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdGreaterThan(String value) {
            addCriterion("relation_id >", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdGreaterThanOrEqualTo(String value) {
            addCriterion("relation_id >=", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLessThan(String value) {
            addCriterion("relation_id <", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLessThanOrEqualTo(String value) {
            addCriterion("relation_id <=", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLike(String value) {
            addCriterion("relation_id like", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotLike(String value) {
            addCriterion("relation_id not like", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdIn(List<String> values) {
            addCriterion("relation_id in", values, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotIn(List<String> values) {
            addCriterion("relation_id not in", values, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdBetween(String value1, String value2) {
            addCriterion("relation_id between", value1, value2, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotBetween(String value1, String value2) {
            addCriterion("relation_id not between", value1, value2, "relationId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("task_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("task_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(String value) {
            addCriterion("task_id =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(String value) {
            addCriterion("task_id <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(String value) {
            addCriterion("task_id >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("task_id >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(String value) {
            addCriterion("task_id <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(String value) {
            addCriterion("task_id <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLike(String value) {
            addCriterion("task_id like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotLike(String value) {
            addCriterion("task_id not like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<String> values) {
            addCriterion("task_id in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<String> values) {
            addCriterion("task_id not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(String value1, String value2) {
            addCriterion("task_id between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(String value1, String value2) {
            addCriterion("task_id not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andCounselDescIsNull() {
            addCriterion("counsel_desc is null");
            return (Criteria) this;
        }

        public Criteria andCounselDescIsNotNull() {
            addCriterion("counsel_desc is not null");
            return (Criteria) this;
        }

        public Criteria andCounselDescEqualTo(String value) {
            addCriterion("counsel_desc =", value, "counselDesc");
            return (Criteria) this;
        }

        public Criteria andCounselDescNotEqualTo(String value) {
            addCriterion("counsel_desc <>", value, "counselDesc");
            return (Criteria) this;
        }

        public Criteria andCounselDescGreaterThan(String value) {
            addCriterion("counsel_desc >", value, "counselDesc");
            return (Criteria) this;
        }

        public Criteria andCounselDescGreaterThanOrEqualTo(String value) {
            addCriterion("counsel_desc >=", value, "counselDesc");
            return (Criteria) this;
        }

        public Criteria andCounselDescLessThan(String value) {
            addCriterion("counsel_desc <", value, "counselDesc");
            return (Criteria) this;
        }

        public Criteria andCounselDescLessThanOrEqualTo(String value) {
            addCriterion("counsel_desc <=", value, "counselDesc");
            return (Criteria) this;
        }

        public Criteria andCounselDescLike(String value) {
            addCriterion("counsel_desc like", value, "counselDesc");
            return (Criteria) this;
        }

        public Criteria andCounselDescNotLike(String value) {
            addCriterion("counsel_desc not like", value, "counselDesc");
            return (Criteria) this;
        }

        public Criteria andCounselDescIn(List<String> values) {
            addCriterion("counsel_desc in", values, "counselDesc");
            return (Criteria) this;
        }

        public Criteria andCounselDescNotIn(List<String> values) {
            addCriterion("counsel_desc not in", values, "counselDesc");
            return (Criteria) this;
        }

        public Criteria andCounselDescBetween(String value1, String value2) {
            addCriterion("counsel_desc between", value1, value2, "counselDesc");
            return (Criteria) this;
        }

        public Criteria andCounselDescNotBetween(String value1, String value2) {
            addCriterion("counsel_desc not between", value1, value2, "counselDesc");
            return (Criteria) this;
        }

        public Criteria andConstructScaleIsNull() {
            addCriterion("construct_scale is null");
            return (Criteria) this;
        }

        public Criteria andConstructScaleIsNotNull() {
            addCriterion("construct_scale is not null");
            return (Criteria) this;
        }

        public Criteria andConstructScaleEqualTo(String value) {
            addCriterion("construct_scale =", value, "constructScale");
            return (Criteria) this;
        }

        public Criteria andConstructScaleNotEqualTo(String value) {
            addCriterion("construct_scale <>", value, "constructScale");
            return (Criteria) this;
        }

        public Criteria andConstructScaleGreaterThan(String value) {
            addCriterion("construct_scale >", value, "constructScale");
            return (Criteria) this;
        }

        public Criteria andConstructScaleGreaterThanOrEqualTo(String value) {
            addCriterion("construct_scale >=", value, "constructScale");
            return (Criteria) this;
        }

        public Criteria andConstructScaleLessThan(String value) {
            addCriterion("construct_scale <", value, "constructScale");
            return (Criteria) this;
        }

        public Criteria andConstructScaleLessThanOrEqualTo(String value) {
            addCriterion("construct_scale <=", value, "constructScale");
            return (Criteria) this;
        }

        public Criteria andConstructScaleLike(String value) {
            addCriterion("construct_scale like", value, "constructScale");
            return (Criteria) this;
        }

        public Criteria andConstructScaleNotLike(String value) {
            addCriterion("construct_scale not like", value, "constructScale");
            return (Criteria) this;
        }

        public Criteria andConstructScaleIn(List<String> values) {
            addCriterion("construct_scale in", values, "constructScale");
            return (Criteria) this;
        }

        public Criteria andConstructScaleNotIn(List<String> values) {
            addCriterion("construct_scale not in", values, "constructScale");
            return (Criteria) this;
        }

        public Criteria andConstructScaleBetween(String value1, String value2) {
            addCriterion("construct_scale between", value1, value2, "constructScale");
            return (Criteria) this;
        }

        public Criteria andConstructScaleNotBetween(String value1, String value2) {
            addCriterion("construct_scale not between", value1, value2, "constructScale");
            return (Criteria) this;
        }

        public Criteria andCounselContentIsNull() {
            addCriterion("counsel_content is null");
            return (Criteria) this;
        }

        public Criteria andCounselContentIsNotNull() {
            addCriterion("counsel_content is not null");
            return (Criteria) this;
        }

        public Criteria andCounselContentEqualTo(String value) {
            addCriterion("counsel_content =", value, "counselContent");
            return (Criteria) this;
        }

        public Criteria andCounselContentNotEqualTo(String value) {
            addCriterion("counsel_content <>", value, "counselContent");
            return (Criteria) this;
        }

        public Criteria andCounselContentGreaterThan(String value) {
            addCriterion("counsel_content >", value, "counselContent");
            return (Criteria) this;
        }

        public Criteria andCounselContentGreaterThanOrEqualTo(String value) {
            addCriterion("counsel_content >=", value, "counselContent");
            return (Criteria) this;
        }

        public Criteria andCounselContentLessThan(String value) {
            addCriterion("counsel_content <", value, "counselContent");
            return (Criteria) this;
        }

        public Criteria andCounselContentLessThanOrEqualTo(String value) {
            addCriterion("counsel_content <=", value, "counselContent");
            return (Criteria) this;
        }

        public Criteria andCounselContentLike(String value) {
            addCriterion("counsel_content like", value, "counselContent");
            return (Criteria) this;
        }

        public Criteria andCounselContentNotLike(String value) {
            addCriterion("counsel_content not like", value, "counselContent");
            return (Criteria) this;
        }

        public Criteria andCounselContentIn(List<String> values) {
            addCriterion("counsel_content in", values, "counselContent");
            return (Criteria) this;
        }

        public Criteria andCounselContentNotIn(List<String> values) {
            addCriterion("counsel_content not in", values, "counselContent");
            return (Criteria) this;
        }

        public Criteria andCounselContentBetween(String value1, String value2) {
            addCriterion("counsel_content between", value1, value2, "counselContent");
            return (Criteria) this;
        }

        public Criteria andCounselContentNotBetween(String value1, String value2) {
            addCriterion("counsel_content not between", value1, value2, "counselContent");
            return (Criteria) this;
        }

        public Criteria andCounselGroupIsNull() {
            addCriterion("counsel_group is null");
            return (Criteria) this;
        }

        public Criteria andCounselGroupIsNotNull() {
            addCriterion("counsel_group is not null");
            return (Criteria) this;
        }

        public Criteria andCounselGroupEqualTo(String value) {
            addCriterion("counsel_group =", value, "counselGroup");
            return (Criteria) this;
        }

        public Criteria andCounselGroupNotEqualTo(String value) {
            addCriterion("counsel_group <>", value, "counselGroup");
            return (Criteria) this;
        }

        public Criteria andCounselGroupGreaterThan(String value) {
            addCriterion("counsel_group >", value, "counselGroup");
            return (Criteria) this;
        }

        public Criteria andCounselGroupGreaterThanOrEqualTo(String value) {
            addCriterion("counsel_group >=", value, "counselGroup");
            return (Criteria) this;
        }

        public Criteria andCounselGroupLessThan(String value) {
            addCriterion("counsel_group <", value, "counselGroup");
            return (Criteria) this;
        }

        public Criteria andCounselGroupLessThanOrEqualTo(String value) {
            addCriterion("counsel_group <=", value, "counselGroup");
            return (Criteria) this;
        }

        public Criteria andCounselGroupLike(String value) {
            addCriterion("counsel_group like", value, "counselGroup");
            return (Criteria) this;
        }

        public Criteria andCounselGroupNotLike(String value) {
            addCriterion("counsel_group not like", value, "counselGroup");
            return (Criteria) this;
        }

        public Criteria andCounselGroupIn(List<String> values) {
            addCriterion("counsel_group in", values, "counselGroup");
            return (Criteria) this;
        }

        public Criteria andCounselGroupNotIn(List<String> values) {
            addCriterion("counsel_group not in", values, "counselGroup");
            return (Criteria) this;
        }

        public Criteria andCounselGroupBetween(String value1, String value2) {
            addCriterion("counsel_group between", value1, value2, "counselGroup");
            return (Criteria) this;
        }

        public Criteria andCounselGroupNotBetween(String value1, String value2) {
            addCriterion("counsel_group not between", value1, value2, "counselGroup");
            return (Criteria) this;
        }

        public Criteria andCounselDutyIsNull() {
            addCriterion("counsel_duty is null");
            return (Criteria) this;
        }

        public Criteria andCounselDutyIsNotNull() {
            addCriterion("counsel_duty is not null");
            return (Criteria) this;
        }

        public Criteria andCounselDutyEqualTo(String value) {
            addCriterion("counsel_duty =", value, "counselDuty");
            return (Criteria) this;
        }

        public Criteria andCounselDutyNotEqualTo(String value) {
            addCriterion("counsel_duty <>", value, "counselDuty");
            return (Criteria) this;
        }

        public Criteria andCounselDutyGreaterThan(String value) {
            addCriterion("counsel_duty >", value, "counselDuty");
            return (Criteria) this;
        }

        public Criteria andCounselDutyGreaterThanOrEqualTo(String value) {
            addCriterion("counsel_duty >=", value, "counselDuty");
            return (Criteria) this;
        }

        public Criteria andCounselDutyLessThan(String value) {
            addCriterion("counsel_duty <", value, "counselDuty");
            return (Criteria) this;
        }

        public Criteria andCounselDutyLessThanOrEqualTo(String value) {
            addCriterion("counsel_duty <=", value, "counselDuty");
            return (Criteria) this;
        }

        public Criteria andCounselDutyLike(String value) {
            addCriterion("counsel_duty like", value, "counselDuty");
            return (Criteria) this;
        }

        public Criteria andCounselDutyNotLike(String value) {
            addCriterion("counsel_duty not like", value, "counselDuty");
            return (Criteria) this;
        }

        public Criteria andCounselDutyIn(List<String> values) {
            addCriterion("counsel_duty in", values, "counselDuty");
            return (Criteria) this;
        }

        public Criteria andCounselDutyNotIn(List<String> values) {
            addCriterion("counsel_duty not in", values, "counselDuty");
            return (Criteria) this;
        }

        public Criteria andCounselDutyBetween(String value1, String value2) {
            addCriterion("counsel_duty between", value1, value2, "counselDuty");
            return (Criteria) this;
        }

        public Criteria andCounselDutyNotBetween(String value1, String value2) {
            addCriterion("counsel_duty not between", value1, value2, "counselDuty");
            return (Criteria) this;
        }

        public Criteria andDivideWorkIsNull() {
            addCriterion("divide_work is null");
            return (Criteria) this;
        }

        public Criteria andDivideWorkIsNotNull() {
            addCriterion("divide_work is not null");
            return (Criteria) this;
        }

        public Criteria andDivideWorkEqualTo(String value) {
            addCriterion("divide_work =", value, "divideWork");
            return (Criteria) this;
        }

        public Criteria andDivideWorkNotEqualTo(String value) {
            addCriterion("divide_work <>", value, "divideWork");
            return (Criteria) this;
        }

        public Criteria andDivideWorkGreaterThan(String value) {
            addCriterion("divide_work >", value, "divideWork");
            return (Criteria) this;
        }

        public Criteria andDivideWorkGreaterThanOrEqualTo(String value) {
            addCriterion("divide_work >=", value, "divideWork");
            return (Criteria) this;
        }

        public Criteria andDivideWorkLessThan(String value) {
            addCriterion("divide_work <", value, "divideWork");
            return (Criteria) this;
        }

        public Criteria andDivideWorkLessThanOrEqualTo(String value) {
            addCriterion("divide_work <=", value, "divideWork");
            return (Criteria) this;
        }

        public Criteria andDivideWorkLike(String value) {
            addCriterion("divide_work like", value, "divideWork");
            return (Criteria) this;
        }

        public Criteria andDivideWorkNotLike(String value) {
            addCriterion("divide_work not like", value, "divideWork");
            return (Criteria) this;
        }

        public Criteria andDivideWorkIn(List<String> values) {
            addCriterion("divide_work in", values, "divideWork");
            return (Criteria) this;
        }

        public Criteria andDivideWorkNotIn(List<String> values) {
            addCriterion("divide_work not in", values, "divideWork");
            return (Criteria) this;
        }

        public Criteria andDivideWorkBetween(String value1, String value2) {
            addCriterion("divide_work between", value1, value2, "divideWork");
            return (Criteria) this;
        }

        public Criteria andDivideWorkNotBetween(String value1, String value2) {
            addCriterion("divide_work not between", value1, value2, "divideWork");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNull() {
            addCriterion("is_del_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNotNull() {
            addCriterion("is_del_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgEqualTo(String value) {
            addCriterion("is_del_flg =", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotEqualTo(String value) {
            addCriterion("is_del_flg <>", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThan(String value) {
            addCriterion("is_del_flg >", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_del_flg >=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThan(String value) {
            addCriterion("is_del_flg <", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThanOrEqualTo(String value) {
            addCriterion("is_del_flg <=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLike(String value) {
            addCriterion("is_del_flg like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotLike(String value) {
            addCriterion("is_del_flg not like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIn(List<String> values) {
            addCriterion("is_del_flg in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotIn(List<String> values) {
            addCriterion("is_del_flg not in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgBetween(String value1, String value2) {
            addCriterion("is_del_flg between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotBetween(String value1, String value2) {
            addCriterion("is_del_flg not between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }
    }

    /**
     * tb_table_five_relation
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_table_five_relation null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}