package com.hd.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbTaskUserRelationEntityExample {
    /**
     * tb_task_user_relation
     */
    protected String orderByClause;

    /**
     * tb_task_user_relation
     */
    protected boolean distinct;

    /**
     * tb_task_user_relation
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_task_user_relation
     */
    protected Integer limitStart;

    /**
     * tb_task_user_relation
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_user_relation
     *
     * @mbg.generated
     */
    public TbTaskUserRelationEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_user_relation
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_user_relation
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_user_relation
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_user_relation
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_user_relation
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_user_relation
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_user_relation
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_user_relation
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_user_relation
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_user_relation
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_user_relation
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_user_relation
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_user_relation
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_user_relation
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_task_user_relation null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRelationIdIsNull() {
            addCriterion("relation_id is null");
            return (Criteria) this;
        }

        public Criteria andRelationIdIsNotNull() {
            addCriterion("relation_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelationIdEqualTo(String value) {
            addCriterion("relation_id =", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotEqualTo(String value) {
            addCriterion("relation_id <>", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdGreaterThan(String value) {
            addCriterion("relation_id >", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdGreaterThanOrEqualTo(String value) {
            addCriterion("relation_id >=", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLessThan(String value) {
            addCriterion("relation_id <", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLessThanOrEqualTo(String value) {
            addCriterion("relation_id <=", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLike(String value) {
            addCriterion("relation_id like", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotLike(String value) {
            addCriterion("relation_id not like", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdIn(List<String> values) {
            addCriterion("relation_id in", values, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotIn(List<String> values) {
            addCriterion("relation_id not in", values, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdBetween(String value1, String value2) {
            addCriterion("relation_id between", value1, value2, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotBetween(String value1, String value2) {
            addCriterion("relation_id not between", value1, value2, "relationId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("task_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("task_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(String value) {
            addCriterion("task_id =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(String value) {
            addCriterion("task_id <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(String value) {
            addCriterion("task_id >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("task_id >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(String value) {
            addCriterion("task_id <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(String value) {
            addCriterion("task_id <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLike(String value) {
            addCriterion("task_id like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotLike(String value) {
            addCriterion("task_id not like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<String> values) {
            addCriterion("task_id in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<String> values) {
            addCriterion("task_id not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(String value1, String value2) {
            addCriterion("task_id between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(String value1, String value2) {
            addCriterion("task_id not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andIsMainDutyIsNull() {
            addCriterion("is_main_duty is null");
            return (Criteria) this;
        }

        public Criteria andIsMainDutyIsNotNull() {
            addCriterion("is_main_duty is not null");
            return (Criteria) this;
        }

        public Criteria andIsMainDutyEqualTo(String value) {
            addCriterion("is_main_duty =", value, "isMainDuty");
            return (Criteria) this;
        }

        public Criteria andIsMainDutyNotEqualTo(String value) {
            addCriterion("is_main_duty <>", value, "isMainDuty");
            return (Criteria) this;
        }

        public Criteria andIsMainDutyGreaterThan(String value) {
            addCriterion("is_main_duty >", value, "isMainDuty");
            return (Criteria) this;
        }

        public Criteria andIsMainDutyGreaterThanOrEqualTo(String value) {
            addCriterion("is_main_duty >=", value, "isMainDuty");
            return (Criteria) this;
        }

        public Criteria andIsMainDutyLessThan(String value) {
            addCriterion("is_main_duty <", value, "isMainDuty");
            return (Criteria) this;
        }

        public Criteria andIsMainDutyLessThanOrEqualTo(String value) {
            addCriterion("is_main_duty <=", value, "isMainDuty");
            return (Criteria) this;
        }

        public Criteria andIsMainDutyLike(String value) {
            addCriterion("is_main_duty like", value, "isMainDuty");
            return (Criteria) this;
        }

        public Criteria andIsMainDutyNotLike(String value) {
            addCriterion("is_main_duty not like", value, "isMainDuty");
            return (Criteria) this;
        }

        public Criteria andIsMainDutyIn(List<String> values) {
            addCriterion("is_main_duty in", values, "isMainDuty");
            return (Criteria) this;
        }

        public Criteria andIsMainDutyNotIn(List<String> values) {
            addCriterion("is_main_duty not in", values, "isMainDuty");
            return (Criteria) this;
        }

        public Criteria andIsMainDutyBetween(String value1, String value2) {
            addCriterion("is_main_duty between", value1, value2, "isMainDuty");
            return (Criteria) this;
        }

        public Criteria andIsMainDutyNotBetween(String value1, String value2) {
            addCriterion("is_main_duty not between", value1, value2, "isMainDuty");
            return (Criteria) this;
        }

        public Criteria andTaskContentIsNull() {
            addCriterion("task_content is null");
            return (Criteria) this;
        }

        public Criteria andTaskContentIsNotNull() {
            addCriterion("task_content is not null");
            return (Criteria) this;
        }

        public Criteria andTaskContentEqualTo(String value) {
            addCriterion("task_content =", value, "taskContent");
            return (Criteria) this;
        }

        public Criteria andTaskContentNotEqualTo(String value) {
            addCriterion("task_content <>", value, "taskContent");
            return (Criteria) this;
        }

        public Criteria andTaskContentGreaterThan(String value) {
            addCriterion("task_content >", value, "taskContent");
            return (Criteria) this;
        }

        public Criteria andTaskContentGreaterThanOrEqualTo(String value) {
            addCriterion("task_content >=", value, "taskContent");
            return (Criteria) this;
        }

        public Criteria andTaskContentLessThan(String value) {
            addCriterion("task_content <", value, "taskContent");
            return (Criteria) this;
        }

        public Criteria andTaskContentLessThanOrEqualTo(String value) {
            addCriterion("task_content <=", value, "taskContent");
            return (Criteria) this;
        }

        public Criteria andTaskContentLike(String value) {
            addCriterion("task_content like", value, "taskContent");
            return (Criteria) this;
        }

        public Criteria andTaskContentNotLike(String value) {
            addCriterion("task_content not like", value, "taskContent");
            return (Criteria) this;
        }

        public Criteria andTaskContentIn(List<String> values) {
            addCriterion("task_content in", values, "taskContent");
            return (Criteria) this;
        }

        public Criteria andTaskContentNotIn(List<String> values) {
            addCriterion("task_content not in", values, "taskContent");
            return (Criteria) this;
        }

        public Criteria andTaskContentBetween(String value1, String value2) {
            addCriterion("task_content between", value1, value2, "taskContent");
            return (Criteria) this;
        }

        public Criteria andTaskContentNotBetween(String value1, String value2) {
            addCriterion("task_content not between", value1, value2, "taskContent");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("start_date is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("start_date is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Date value) {
            addCriterion("start_date =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Date value) {
            addCriterion("start_date <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Date value) {
            addCriterion("start_date >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("start_date >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Date value) {
            addCriterion("start_date <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Date value) {
            addCriterion("start_date <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Date> values) {
            addCriterion("start_date in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Date> values) {
            addCriterion("start_date not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Date value1, Date value2) {
            addCriterion("start_date between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Date value1, Date value2) {
            addCriterion("start_date not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("end_date is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("end_date is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(Date value) {
            addCriterion("end_date =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(Date value) {
            addCriterion("end_date <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(Date value) {
            addCriterion("end_date >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("end_date >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(Date value) {
            addCriterion("end_date <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(Date value) {
            addCriterion("end_date <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<Date> values) {
            addCriterion("end_date in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<Date> values) {
            addCriterion("end_date not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(Date value1, Date value2) {
            addCriterion("end_date between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(Date value1, Date value2) {
            addCriterion("end_date not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andNeedHourIsNull() {
            addCriterion("need_hour is null");
            return (Criteria) this;
        }

        public Criteria andNeedHourIsNotNull() {
            addCriterion("need_hour is not null");
            return (Criteria) this;
        }

        public Criteria andNeedHourEqualTo(Integer value) {
            addCriterion("need_hour =", value, "needHour");
            return (Criteria) this;
        }

        public Criteria andNeedHourNotEqualTo(Integer value) {
            addCriterion("need_hour <>", value, "needHour");
            return (Criteria) this;
        }

        public Criteria andNeedHourGreaterThan(Integer value) {
            addCriterion("need_hour >", value, "needHour");
            return (Criteria) this;
        }

        public Criteria andNeedHourGreaterThanOrEqualTo(Integer value) {
            addCriterion("need_hour >=", value, "needHour");
            return (Criteria) this;
        }

        public Criteria andNeedHourLessThan(Integer value) {
            addCriterion("need_hour <", value, "needHour");
            return (Criteria) this;
        }

        public Criteria andNeedHourLessThanOrEqualTo(Integer value) {
            addCriterion("need_hour <=", value, "needHour");
            return (Criteria) this;
        }

        public Criteria andNeedHourIn(List<Integer> values) {
            addCriterion("need_hour in", values, "needHour");
            return (Criteria) this;
        }

        public Criteria andNeedHourNotIn(List<Integer> values) {
            addCriterion("need_hour not in", values, "needHour");
            return (Criteria) this;
        }

        public Criteria andNeedHourBetween(Integer value1, Integer value2) {
            addCriterion("need_hour between", value1, value2, "needHour");
            return (Criteria) this;
        }

        public Criteria andNeedHourNotBetween(Integer value1, Integer value2) {
            addCriterion("need_hour not between", value1, value2, "needHour");
            return (Criteria) this;
        }

        public Criteria andExecuteDateIsNull() {
            addCriterion("execute_date is null");
            return (Criteria) this;
        }

        public Criteria andExecuteDateIsNotNull() {
            addCriterion("execute_date is not null");
            return (Criteria) this;
        }

        public Criteria andExecuteDateEqualTo(Date value) {
            addCriterion("execute_date =", value, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateNotEqualTo(Date value) {
            addCriterion("execute_date <>", value, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateGreaterThan(Date value) {
            addCriterion("execute_date >", value, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateGreaterThanOrEqualTo(Date value) {
            addCriterion("execute_date >=", value, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateLessThan(Date value) {
            addCriterion("execute_date <", value, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateLessThanOrEqualTo(Date value) {
            addCriterion("execute_date <=", value, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateIn(List<Date> values) {
            addCriterion("execute_date in", values, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateNotIn(List<Date> values) {
            addCriterion("execute_date not in", values, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateBetween(Date value1, Date value2) {
            addCriterion("execute_date between", value1, value2, "executeDate");
            return (Criteria) this;
        }

        public Criteria andExecuteDateNotBetween(Date value1, Date value2) {
            addCriterion("execute_date not between", value1, value2, "executeDate");
            return (Criteria) this;
        }

        public Criteria andActualHourIsNull() {
            addCriterion("actual_hour is null");
            return (Criteria) this;
        }

        public Criteria andActualHourIsNotNull() {
            addCriterion("actual_hour is not null");
            return (Criteria) this;
        }

        public Criteria andActualHourEqualTo(Integer value) {
            addCriterion("actual_hour =", value, "actualHour");
            return (Criteria) this;
        }

        public Criteria andActualHourNotEqualTo(Integer value) {
            addCriterion("actual_hour <>", value, "actualHour");
            return (Criteria) this;
        }

        public Criteria andActualHourGreaterThan(Integer value) {
            addCriterion("actual_hour >", value, "actualHour");
            return (Criteria) this;
        }

        public Criteria andActualHourGreaterThanOrEqualTo(Integer value) {
            addCriterion("actual_hour >=", value, "actualHour");
            return (Criteria) this;
        }

        public Criteria andActualHourLessThan(Integer value) {
            addCriterion("actual_hour <", value, "actualHour");
            return (Criteria) this;
        }

        public Criteria andActualHourLessThanOrEqualTo(Integer value) {
            addCriterion("actual_hour <=", value, "actualHour");
            return (Criteria) this;
        }

        public Criteria andActualHourIn(List<Integer> values) {
            addCriterion("actual_hour in", values, "actualHour");
            return (Criteria) this;
        }

        public Criteria andActualHourNotIn(List<Integer> values) {
            addCriterion("actual_hour not in", values, "actualHour");
            return (Criteria) this;
        }

        public Criteria andActualHourBetween(Integer value1, Integer value2) {
            addCriterion("actual_hour between", value1, value2, "actualHour");
            return (Criteria) this;
        }

        public Criteria andActualHourNotBetween(Integer value1, Integer value2) {
            addCriterion("actual_hour not between", value1, value2, "actualHour");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNull() {
            addCriterion("is_del_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNotNull() {
            addCriterion("is_del_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgEqualTo(String value) {
            addCriterion("is_del_flg =", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotEqualTo(String value) {
            addCriterion("is_del_flg <>", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThan(String value) {
            addCriterion("is_del_flg >", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_del_flg >=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThan(String value) {
            addCriterion("is_del_flg <", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThanOrEqualTo(String value) {
            addCriterion("is_del_flg <=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLike(String value) {
            addCriterion("is_del_flg like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotLike(String value) {
            addCriterion("is_del_flg not like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIn(List<String> values) {
            addCriterion("is_del_flg in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotIn(List<String> values) {
            addCriterion("is_del_flg not in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgBetween(String value1, String value2) {
            addCriterion("is_del_flg between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotBetween(String value1, String value2) {
            addCriterion("is_del_flg not between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDoneIsNull() {
            addCriterion("is_done is null");
            return (Criteria) this;
        }

        public Criteria andIsDoneIsNotNull() {
            addCriterion("is_done is not null");
            return (Criteria) this;
        }

        public Criteria andIsDoneEqualTo(String value) {
            addCriterion("is_done =", value, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneNotEqualTo(String value) {
            addCriterion("is_done <>", value, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneGreaterThan(String value) {
            addCriterion("is_done >", value, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneGreaterThanOrEqualTo(String value) {
            addCriterion("is_done >=", value, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneLessThan(String value) {
            addCriterion("is_done <", value, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneLessThanOrEqualTo(String value) {
            addCriterion("is_done <=", value, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneLike(String value) {
            addCriterion("is_done like", value, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneNotLike(String value) {
            addCriterion("is_done not like", value, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneIn(List<String> values) {
            addCriterion("is_done in", values, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneNotIn(List<String> values) {
            addCriterion("is_done not in", values, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneBetween(String value1, String value2) {
            addCriterion("is_done between", value1, value2, "isDone");
            return (Criteria) this;
        }

        public Criteria andIsDoneNotBetween(String value1, String value2) {
            addCriterion("is_done not between", value1, value2, "isDone");
            return (Criteria) this;
        }

        public Criteria andCustomizeHourIsNull() {
            addCriterion("customize_hour is null");
            return (Criteria) this;
        }

        public Criteria andCustomizeHourIsNotNull() {
            addCriterion("customize_hour is not null");
            return (Criteria) this;
        }

        public Criteria andCustomizeHourEqualTo(Integer value) {
            addCriterion("customize_hour =", value, "customizeHour");
            return (Criteria) this;
        }

        public Criteria andCustomizeHourNotEqualTo(Integer value) {
            addCriterion("customize_hour <>", value, "customizeHour");
            return (Criteria) this;
        }

        public Criteria andCustomizeHourGreaterThan(Integer value) {
            addCriterion("customize_hour >", value, "customizeHour");
            return (Criteria) this;
        }

        public Criteria andCustomizeHourGreaterThanOrEqualTo(Integer value) {
            addCriterion("customize_hour >=", value, "customizeHour");
            return (Criteria) this;
        }

        public Criteria andCustomizeHourLessThan(Integer value) {
            addCriterion("customize_hour <", value, "customizeHour");
            return (Criteria) this;
        }

        public Criteria andCustomizeHourLessThanOrEqualTo(Integer value) {
            addCriterion("customize_hour <=", value, "customizeHour");
            return (Criteria) this;
        }

        public Criteria andCustomizeHourIn(List<Integer> values) {
            addCriterion("customize_hour in", values, "customizeHour");
            return (Criteria) this;
        }

        public Criteria andCustomizeHourNotIn(List<Integer> values) {
            addCriterion("customize_hour not in", values, "customizeHour");
            return (Criteria) this;
        }

        public Criteria andCustomizeHourBetween(Integer value1, Integer value2) {
            addCriterion("customize_hour between", value1, value2, "customizeHour");
            return (Criteria) this;
        }

        public Criteria andCustomizeHourNotBetween(Integer value1, Integer value2) {
            addCriterion("customize_hour not between", value1, value2, "customizeHour");
            return (Criteria) this;
        }

        public Criteria andHourReasonIsNull() {
            addCriterion("hour_reason is null");
            return (Criteria) this;
        }

        public Criteria andHourReasonIsNotNull() {
            addCriterion("hour_reason is not null");
            return (Criteria) this;
        }

        public Criteria andHourReasonEqualTo(String value) {
            addCriterion("hour_reason =", value, "hourReason");
            return (Criteria) this;
        }

        public Criteria andHourReasonNotEqualTo(String value) {
            addCriterion("hour_reason <>", value, "hourReason");
            return (Criteria) this;
        }

        public Criteria andHourReasonGreaterThan(String value) {
            addCriterion("hour_reason >", value, "hourReason");
            return (Criteria) this;
        }

        public Criteria andHourReasonGreaterThanOrEqualTo(String value) {
            addCriterion("hour_reason >=", value, "hourReason");
            return (Criteria) this;
        }

        public Criteria andHourReasonLessThan(String value) {
            addCriterion("hour_reason <", value, "hourReason");
            return (Criteria) this;
        }

        public Criteria andHourReasonLessThanOrEqualTo(String value) {
            addCriterion("hour_reason <=", value, "hourReason");
            return (Criteria) this;
        }

        public Criteria andHourReasonLike(String value) {
            addCriterion("hour_reason like", value, "hourReason");
            return (Criteria) this;
        }

        public Criteria andHourReasonNotLike(String value) {
            addCriterion("hour_reason not like", value, "hourReason");
            return (Criteria) this;
        }

        public Criteria andHourReasonIn(List<String> values) {
            addCriterion("hour_reason in", values, "hourReason");
            return (Criteria) this;
        }

        public Criteria andHourReasonNotIn(List<String> values) {
            addCriterion("hour_reason not in", values, "hourReason");
            return (Criteria) this;
        }

        public Criteria andHourReasonBetween(String value1, String value2) {
            addCriterion("hour_reason between", value1, value2, "hourReason");
            return (Criteria) this;
        }

        public Criteria andHourReasonNotBetween(String value1, String value2) {
            addCriterion("hour_reason not between", value1, value2, "hourReason");
            return (Criteria) this;
        }
    }

    /**
     * tb_task_user_relation
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_task_user_relation null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}