package com.hd.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbTaskPeriodRelationEntityExample {
    /**
     * tb_task_period_relation
     */
    protected String orderByClause;

    /**
     * tb_task_period_relation
     */
    protected boolean distinct;

    /**
     * tb_task_period_relation
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_task_period_relation
     */
    protected Integer limitStart;

    /**
     * tb_task_period_relation
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_relation
     *
     * @mbg.generated
     */
    public TbTaskPeriodRelationEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_relation
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_relation
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_relation
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_relation
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_relation
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_relation
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_relation
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_relation
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_relation
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_relation
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_relation
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_relation
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_relation
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_relation
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_task_period_relation null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRelationIdIsNull() {
            addCriterion("relation_id is null");
            return (Criteria) this;
        }

        public Criteria andRelationIdIsNotNull() {
            addCriterion("relation_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelationIdEqualTo(String value) {
            addCriterion("relation_id =", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotEqualTo(String value) {
            addCriterion("relation_id <>", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdGreaterThan(String value) {
            addCriterion("relation_id >", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdGreaterThanOrEqualTo(String value) {
            addCriterion("relation_id >=", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLessThan(String value) {
            addCriterion("relation_id <", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLessThanOrEqualTo(String value) {
            addCriterion("relation_id <=", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLike(String value) {
            addCriterion("relation_id like", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotLike(String value) {
            addCriterion("relation_id not like", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdIn(List<String> values) {
            addCriterion("relation_id in", values, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotIn(List<String> values) {
            addCriterion("relation_id not in", values, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdBetween(String value1, String value2) {
            addCriterion("relation_id between", value1, value2, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotBetween(String value1, String value2) {
            addCriterion("relation_id not between", value1, value2, "relationId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("task_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("task_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(String value) {
            addCriterion("task_id =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(String value) {
            addCriterion("task_id <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(String value) {
            addCriterion("task_id >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("task_id >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(String value) {
            addCriterion("task_id <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(String value) {
            addCriterion("task_id <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLike(String value) {
            addCriterion("task_id like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotLike(String value) {
            addCriterion("task_id not like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<String> values) {
            addCriterion("task_id in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<String> values) {
            addCriterion("task_id not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(String value1, String value2) {
            addCriterion("task_id between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(String value1, String value2) {
            addCriterion("task_id not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdIsNull() {
            addCriterion("period_id is null");
            return (Criteria) this;
        }

        public Criteria andPeriodIdIsNotNull() {
            addCriterion("period_id is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodIdEqualTo(String value) {
            addCriterion("period_id =", value, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdNotEqualTo(String value) {
            addCriterion("period_id <>", value, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdGreaterThan(String value) {
            addCriterion("period_id >", value, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdGreaterThanOrEqualTo(String value) {
            addCriterion("period_id >=", value, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdLessThan(String value) {
            addCriterion("period_id <", value, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdLessThanOrEqualTo(String value) {
            addCriterion("period_id <=", value, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdLike(String value) {
            addCriterion("period_id like", value, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdNotLike(String value) {
            addCriterion("period_id not like", value, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdIn(List<String> values) {
            addCriterion("period_id in", values, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdNotIn(List<String> values) {
            addCriterion("period_id not in", values, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdBetween(String value1, String value2) {
            addCriterion("period_id between", value1, value2, "periodId");
            return (Criteria) this;
        }

        public Criteria andPeriodIdNotBetween(String value1, String value2) {
            addCriterion("period_id not between", value1, value2, "periodId");
            return (Criteria) this;
        }

        public Criteria andTaskProcessInstIdIsNull() {
            addCriterion("task_process_inst_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskProcessInstIdIsNotNull() {
            addCriterion("task_process_inst_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskProcessInstIdEqualTo(String value) {
            addCriterion("task_process_inst_id =", value, "taskProcessInstId");
            return (Criteria) this;
        }

        public Criteria andTaskProcessInstIdNotEqualTo(String value) {
            addCriterion("task_process_inst_id <>", value, "taskProcessInstId");
            return (Criteria) this;
        }

        public Criteria andTaskProcessInstIdGreaterThan(String value) {
            addCriterion("task_process_inst_id >", value, "taskProcessInstId");
            return (Criteria) this;
        }

        public Criteria andTaskProcessInstIdGreaterThanOrEqualTo(String value) {
            addCriterion("task_process_inst_id >=", value, "taskProcessInstId");
            return (Criteria) this;
        }

        public Criteria andTaskProcessInstIdLessThan(String value) {
            addCriterion("task_process_inst_id <", value, "taskProcessInstId");
            return (Criteria) this;
        }

        public Criteria andTaskProcessInstIdLessThanOrEqualTo(String value) {
            addCriterion("task_process_inst_id <=", value, "taskProcessInstId");
            return (Criteria) this;
        }

        public Criteria andTaskProcessInstIdLike(String value) {
            addCriterion("task_process_inst_id like", value, "taskProcessInstId");
            return (Criteria) this;
        }

        public Criteria andTaskProcessInstIdNotLike(String value) {
            addCriterion("task_process_inst_id not like", value, "taskProcessInstId");
            return (Criteria) this;
        }

        public Criteria andTaskProcessInstIdIn(List<String> values) {
            addCriterion("task_process_inst_id in", values, "taskProcessInstId");
            return (Criteria) this;
        }

        public Criteria andTaskProcessInstIdNotIn(List<String> values) {
            addCriterion("task_process_inst_id not in", values, "taskProcessInstId");
            return (Criteria) this;
        }

        public Criteria andTaskProcessInstIdBetween(String value1, String value2) {
            addCriterion("task_process_inst_id between", value1, value2, "taskProcessInstId");
            return (Criteria) this;
        }

        public Criteria andTaskProcessInstIdNotBetween(String value1, String value2) {
            addCriterion("task_process_inst_id not between", value1, value2, "taskProcessInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdIsNull() {
            addCriterion("process_inst_id is null");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdIsNotNull() {
            addCriterion("process_inst_id is not null");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdEqualTo(String value) {
            addCriterion("process_inst_id =", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdNotEqualTo(String value) {
            addCriterion("process_inst_id <>", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdGreaterThan(String value) {
            addCriterion("process_inst_id >", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdGreaterThanOrEqualTo(String value) {
            addCriterion("process_inst_id >=", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdLessThan(String value) {
            addCriterion("process_inst_id <", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdLessThanOrEqualTo(String value) {
            addCriterion("process_inst_id <=", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdLike(String value) {
            addCriterion("process_inst_id like", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdNotLike(String value) {
            addCriterion("process_inst_id not like", value, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdIn(List<String> values) {
            addCriterion("process_inst_id in", values, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdNotIn(List<String> values) {
            addCriterion("process_inst_id not in", values, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdBetween(String value1, String value2) {
            addCriterion("process_inst_id between", value1, value2, "processInstId");
            return (Criteria) this;
        }

        public Criteria andProcessInstIdNotBetween(String value1, String value2) {
            addCriterion("process_inst_id not between", value1, value2, "processInstId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyIsNull() {
            addCriterion("delegate_task_key is null");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyIsNotNull() {
            addCriterion("delegate_task_key is not null");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyEqualTo(String value) {
            addCriterion("delegate_task_key =", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyNotEqualTo(String value) {
            addCriterion("delegate_task_key <>", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyGreaterThan(String value) {
            addCriterion("delegate_task_key >", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyGreaterThanOrEqualTo(String value) {
            addCriterion("delegate_task_key >=", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyLessThan(String value) {
            addCriterion("delegate_task_key <", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyLessThanOrEqualTo(String value) {
            addCriterion("delegate_task_key <=", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyLike(String value) {
            addCriterion("delegate_task_key like", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyNotLike(String value) {
            addCriterion("delegate_task_key not like", value, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyIn(List<String> values) {
            addCriterion("delegate_task_key in", values, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyNotIn(List<String> values) {
            addCriterion("delegate_task_key not in", values, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyBetween(String value1, String value2) {
            addCriterion("delegate_task_key between", value1, value2, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskKeyNotBetween(String value1, String value2) {
            addCriterion("delegate_task_key not between", value1, value2, "delegateTaskKey");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdIsNull() {
            addCriterion("delegate_task_id is null");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdIsNotNull() {
            addCriterion("delegate_task_id is not null");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdEqualTo(String value) {
            addCriterion("delegate_task_id =", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdNotEqualTo(String value) {
            addCriterion("delegate_task_id <>", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdGreaterThan(String value) {
            addCriterion("delegate_task_id >", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("delegate_task_id >=", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdLessThan(String value) {
            addCriterion("delegate_task_id <", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdLessThanOrEqualTo(String value) {
            addCriterion("delegate_task_id <=", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdLike(String value) {
            addCriterion("delegate_task_id like", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdNotLike(String value) {
            addCriterion("delegate_task_id not like", value, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdIn(List<String> values) {
            addCriterion("delegate_task_id in", values, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdNotIn(List<String> values) {
            addCriterion("delegate_task_id not in", values, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdBetween(String value1, String value2) {
            addCriterion("delegate_task_id between", value1, value2, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andDelegateTaskIdNotBetween(String value1, String value2) {
            addCriterion("delegate_task_id not between", value1, value2, "delegateTaskId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIsNull() {
            addCriterion("apply_user_id is null");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIsNotNull() {
            addCriterion("apply_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdEqualTo(String value) {
            addCriterion("apply_user_id =", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotEqualTo(String value) {
            addCriterion("apply_user_id <>", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdGreaterThan(String value) {
            addCriterion("apply_user_id >", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("apply_user_id >=", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdLessThan(String value) {
            addCriterion("apply_user_id <", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdLessThanOrEqualTo(String value) {
            addCriterion("apply_user_id <=", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdLike(String value) {
            addCriterion("apply_user_id like", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotLike(String value) {
            addCriterion("apply_user_id not like", value, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdIn(List<String> values) {
            addCriterion("apply_user_id in", values, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotIn(List<String> values) {
            addCriterion("apply_user_id not in", values, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdBetween(String value1, String value2) {
            addCriterion("apply_user_id between", value1, value2, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserIdNotBetween(String value1, String value2) {
            addCriterion("apply_user_id not between", value1, value2, "applyUserId");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameIsNull() {
            addCriterion("apply_user_name is null");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameIsNotNull() {
            addCriterion("apply_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameEqualTo(String value) {
            addCriterion("apply_user_name =", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotEqualTo(String value) {
            addCriterion("apply_user_name <>", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameGreaterThan(String value) {
            addCriterion("apply_user_name >", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("apply_user_name >=", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameLessThan(String value) {
            addCriterion("apply_user_name <", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameLessThanOrEqualTo(String value) {
            addCriterion("apply_user_name <=", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameLike(String value) {
            addCriterion("apply_user_name like", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotLike(String value) {
            addCriterion("apply_user_name not like", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameIn(List<String> values) {
            addCriterion("apply_user_name in", values, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotIn(List<String> values) {
            addCriterion("apply_user_name not in", values, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameBetween(String value1, String value2) {
            addCriterion("apply_user_name between", value1, value2, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotBetween(String value1, String value2) {
            addCriterion("apply_user_name not between", value1, value2, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIsNull() {
            addCriterion("apply_time is null");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIsNotNull() {
            addCriterion("apply_time is not null");
            return (Criteria) this;
        }

        public Criteria andApplyTimeEqualTo(Date value) {
            addCriterion("apply_time =", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotEqualTo(Date value) {
            addCriterion("apply_time <>", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeGreaterThan(Date value) {
            addCriterion("apply_time >", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("apply_time >=", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeLessThan(Date value) {
            addCriterion("apply_time <", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeLessThanOrEqualTo(Date value) {
            addCriterion("apply_time <=", value, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeIn(List<Date> values) {
            addCriterion("apply_time in", values, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotIn(List<Date> values) {
            addCriterion("apply_time not in", values, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeBetween(Date value1, Date value2) {
            addCriterion("apply_time between", value1, value2, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApplyTimeNotBetween(Date value1, Date value2) {
            addCriterion("apply_time not between", value1, value2, "applyTime");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdIsNull() {
            addCriterion("approve_user_id is null");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdIsNotNull() {
            addCriterion("approve_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdEqualTo(String value) {
            addCriterion("approve_user_id =", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdNotEqualTo(String value) {
            addCriterion("approve_user_id <>", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdGreaterThan(String value) {
            addCriterion("approve_user_id >", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("approve_user_id >=", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdLessThan(String value) {
            addCriterion("approve_user_id <", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdLessThanOrEqualTo(String value) {
            addCriterion("approve_user_id <=", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdLike(String value) {
            addCriterion("approve_user_id like", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdNotLike(String value) {
            addCriterion("approve_user_id not like", value, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdIn(List<String> values) {
            addCriterion("approve_user_id in", values, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdNotIn(List<String> values) {
            addCriterion("approve_user_id not in", values, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdBetween(String value1, String value2) {
            addCriterion("approve_user_id between", value1, value2, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserIdNotBetween(String value1, String value2) {
            addCriterion("approve_user_id not between", value1, value2, "approveUserId");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameIsNull() {
            addCriterion("approve_user_name is null");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameIsNotNull() {
            addCriterion("approve_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameEqualTo(String value) {
            addCriterion("approve_user_name =", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameNotEqualTo(String value) {
            addCriterion("approve_user_name <>", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameGreaterThan(String value) {
            addCriterion("approve_user_name >", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("approve_user_name >=", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameLessThan(String value) {
            addCriterion("approve_user_name <", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameLessThanOrEqualTo(String value) {
            addCriterion("approve_user_name <=", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameLike(String value) {
            addCriterion("approve_user_name like", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameNotLike(String value) {
            addCriterion("approve_user_name not like", value, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameIn(List<String> values) {
            addCriterion("approve_user_name in", values, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameNotIn(List<String> values) {
            addCriterion("approve_user_name not in", values, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameBetween(String value1, String value2) {
            addCriterion("approve_user_name between", value1, value2, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveUserNameNotBetween(String value1, String value2) {
            addCriterion("approve_user_name not between", value1, value2, "approveUserName");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIsNull() {
            addCriterion("approve_time is null");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIsNotNull() {
            addCriterion("approve_time is not null");
            return (Criteria) this;
        }

        public Criteria andApproveTimeEqualTo(Date value) {
            addCriterion("approve_time =", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotEqualTo(Date value) {
            addCriterion("approve_time <>", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeGreaterThan(Date value) {
            addCriterion("approve_time >", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("approve_time >=", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeLessThan(Date value) {
            addCriterion("approve_time <", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeLessThanOrEqualTo(Date value) {
            addCriterion("approve_time <=", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIn(List<Date> values) {
            addCriterion("approve_time in", values, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotIn(List<Date> values) {
            addCriterion("approve_time not in", values, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeBetween(Date value1, Date value2) {
            addCriterion("approve_time between", value1, value2, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotBetween(Date value1, Date value2) {
            addCriterion("approve_time not between", value1, value2, "approveTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeIsNull() {
            addCriterion("complete_time is null");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeIsNotNull() {
            addCriterion("complete_time is not null");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeEqualTo(Date value) {
            addCriterion("complete_time =", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeNotEqualTo(Date value) {
            addCriterion("complete_time <>", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeGreaterThan(Date value) {
            addCriterion("complete_time >", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("complete_time >=", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeLessThan(Date value) {
            addCriterion("complete_time <", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeLessThanOrEqualTo(Date value) {
            addCriterion("complete_time <=", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeIn(List<Date> values) {
            addCriterion("complete_time in", values, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeNotIn(List<Date> values) {
            addCriterion("complete_time not in", values, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeBetween(Date value1, Date value2) {
            addCriterion("complete_time between", value1, value2, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeNotBetween(Date value1, Date value2) {
            addCriterion("complete_time not between", value1, value2, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCurrentStateIsNull() {
            addCriterion("current_state is null");
            return (Criteria) this;
        }

        public Criteria andCurrentStateIsNotNull() {
            addCriterion("current_state is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentStateEqualTo(String value) {
            addCriterion("current_state =", value, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateNotEqualTo(String value) {
            addCriterion("current_state <>", value, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateGreaterThan(String value) {
            addCriterion("current_state >", value, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateGreaterThanOrEqualTo(String value) {
            addCriterion("current_state >=", value, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateLessThan(String value) {
            addCriterion("current_state <", value, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateLessThanOrEqualTo(String value) {
            addCriterion("current_state <=", value, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateLike(String value) {
            addCriterion("current_state like", value, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateNotLike(String value) {
            addCriterion("current_state not like", value, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateIn(List<String> values) {
            addCriterion("current_state in", values, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateNotIn(List<String> values) {
            addCriterion("current_state not in", values, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateBetween(String value1, String value2) {
            addCriterion("current_state between", value1, value2, "currentState");
            return (Criteria) this;
        }

        public Criteria andCurrentStateNotBetween(String value1, String value2) {
            addCriterion("current_state not between", value1, value2, "currentState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateIsNull() {
            addCriterion("verify_state is null");
            return (Criteria) this;
        }

        public Criteria andVerifyStateIsNotNull() {
            addCriterion("verify_state is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyStateEqualTo(String value) {
            addCriterion("verify_state =", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateNotEqualTo(String value) {
            addCriterion("verify_state <>", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateGreaterThan(String value) {
            addCriterion("verify_state >", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateGreaterThanOrEqualTo(String value) {
            addCriterion("verify_state >=", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateLessThan(String value) {
            addCriterion("verify_state <", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateLessThanOrEqualTo(String value) {
            addCriterion("verify_state <=", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateLike(String value) {
            addCriterion("verify_state like", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateNotLike(String value) {
            addCriterion("verify_state not like", value, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateIn(List<String> values) {
            addCriterion("verify_state in", values, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateNotIn(List<String> values) {
            addCriterion("verify_state not in", values, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateBetween(String value1, String value2) {
            addCriterion("verify_state between", value1, value2, "verifyState");
            return (Criteria) this;
        }

        public Criteria andVerifyStateNotBetween(String value1, String value2) {
            addCriterion("verify_state not between", value1, value2, "verifyState");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeIsNull() {
            addCriterion("submit_node is null");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeIsNotNull() {
            addCriterion("submit_node is not null");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeEqualTo(String value) {
            addCriterion("submit_node =", value, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeNotEqualTo(String value) {
            addCriterion("submit_node <>", value, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeGreaterThan(String value) {
            addCriterion("submit_node >", value, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeGreaterThanOrEqualTo(String value) {
            addCriterion("submit_node >=", value, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeLessThan(String value) {
            addCriterion("submit_node <", value, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeLessThanOrEqualTo(String value) {
            addCriterion("submit_node <=", value, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeLike(String value) {
            addCriterion("submit_node like", value, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeNotLike(String value) {
            addCriterion("submit_node not like", value, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeIn(List<String> values) {
            addCriterion("submit_node in", values, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeNotIn(List<String> values) {
            addCriterion("submit_node not in", values, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeBetween(String value1, String value2) {
            addCriterion("submit_node between", value1, value2, "submitNode");
            return (Criteria) this;
        }

        public Criteria andSubmitNodeNotBetween(String value1, String value2) {
            addCriterion("submit_node not between", value1, value2, "submitNode");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallIsNull() {
            addCriterion("is_can_recall is null");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallIsNotNull() {
            addCriterion("is_can_recall is not null");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallEqualTo(String value) {
            addCriterion("is_can_recall =", value, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallNotEqualTo(String value) {
            addCriterion("is_can_recall <>", value, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallGreaterThan(String value) {
            addCriterion("is_can_recall >", value, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallGreaterThanOrEqualTo(String value) {
            addCriterion("is_can_recall >=", value, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallLessThan(String value) {
            addCriterion("is_can_recall <", value, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallLessThanOrEqualTo(String value) {
            addCriterion("is_can_recall <=", value, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallLike(String value) {
            addCriterion("is_can_recall like", value, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallNotLike(String value) {
            addCriterion("is_can_recall not like", value, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallIn(List<String> values) {
            addCriterion("is_can_recall in", values, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallNotIn(List<String> values) {
            addCriterion("is_can_recall not in", values, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallBetween(String value1, String value2) {
            addCriterion("is_can_recall between", value1, value2, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andIsCanRecallNotBetween(String value1, String value2) {
            addCriterion("is_can_recall not between", value1, value2, "isCanRecall");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNull() {
            addCriterion("is_del_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNotNull() {
            addCriterion("is_del_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgEqualTo(String value) {
            addCriterion("is_del_flg =", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotEqualTo(String value) {
            addCriterion("is_del_flg <>", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThan(String value) {
            addCriterion("is_del_flg >", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_del_flg >=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThan(String value) {
            addCriterion("is_del_flg <", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThanOrEqualTo(String value) {
            addCriterion("is_del_flg <=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLike(String value) {
            addCriterion("is_del_flg like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotLike(String value) {
            addCriterion("is_del_flg not like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIn(List<String> values) {
            addCriterion("is_del_flg in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotIn(List<String> values) {
            addCriterion("is_del_flg not in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgBetween(String value1, String value2) {
            addCriterion("is_del_flg between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotBetween(String value1, String value2) {
            addCriterion("is_del_flg not between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsResultFileIsNull() {
            addCriterion("is_result_file is null");
            return (Criteria) this;
        }

        public Criteria andIsResultFileIsNotNull() {
            addCriterion("is_result_file is not null");
            return (Criteria) this;
        }

        public Criteria andIsResultFileEqualTo(String value) {
            addCriterion("is_result_file =", value, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileNotEqualTo(String value) {
            addCriterion("is_result_file <>", value, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileGreaterThan(String value) {
            addCriterion("is_result_file >", value, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileGreaterThanOrEqualTo(String value) {
            addCriterion("is_result_file >=", value, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileLessThan(String value) {
            addCriterion("is_result_file <", value, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileLessThanOrEqualTo(String value) {
            addCriterion("is_result_file <=", value, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileLike(String value) {
            addCriterion("is_result_file like", value, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileNotLike(String value) {
            addCriterion("is_result_file not like", value, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileIn(List<String> values) {
            addCriterion("is_result_file in", values, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileNotIn(List<String> values) {
            addCriterion("is_result_file not in", values, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileBetween(String value1, String value2) {
            addCriterion("is_result_file between", value1, value2, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsResultFileNotBetween(String value1, String value2) {
            addCriterion("is_result_file not between", value1, value2, "isResultFile");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreIsNull() {
            addCriterion("is_ignore is null");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreIsNotNull() {
            addCriterion("is_ignore is not null");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreEqualTo(String value) {
            addCriterion("is_ignore =", value, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreNotEqualTo(String value) {
            addCriterion("is_ignore <>", value, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreGreaterThan(String value) {
            addCriterion("is_ignore >", value, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreGreaterThanOrEqualTo(String value) {
            addCriterion("is_ignore >=", value, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreLessThan(String value) {
            addCriterion("is_ignore <", value, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreLessThanOrEqualTo(String value) {
            addCriterion("is_ignore <=", value, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreLike(String value) {
            addCriterion("is_ignore like", value, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreNotLike(String value) {
            addCriterion("is_ignore not like", value, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreIn(List<String> values) {
            addCriterion("is_ignore in", values, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreNotIn(List<String> values) {
            addCriterion("is_ignore not in", values, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreBetween(String value1, String value2) {
            addCriterion("is_ignore between", value1, value2, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsIgnoreNotBetween(String value1, String value2) {
            addCriterion("is_ignore not between", value1, value2, "isIgnore");
            return (Criteria) this;
        }

        public Criteria andIsFinishIsNull() {
            addCriterion("is_finish is null");
            return (Criteria) this;
        }

        public Criteria andIsFinishIsNotNull() {
            addCriterion("is_finish is not null");
            return (Criteria) this;
        }

        public Criteria andIsFinishEqualTo(String value) {
            addCriterion("is_finish =", value, "isFinish");
            return (Criteria) this;
        }

        public Criteria andIsFinishNotEqualTo(String value) {
            addCriterion("is_finish <>", value, "isFinish");
            return (Criteria) this;
        }

        public Criteria andIsFinishGreaterThan(String value) {
            addCriterion("is_finish >", value, "isFinish");
            return (Criteria) this;
        }

        public Criteria andIsFinishGreaterThanOrEqualTo(String value) {
            addCriterion("is_finish >=", value, "isFinish");
            return (Criteria) this;
        }

        public Criteria andIsFinishLessThan(String value) {
            addCriterion("is_finish <", value, "isFinish");
            return (Criteria) this;
        }

        public Criteria andIsFinishLessThanOrEqualTo(String value) {
            addCriterion("is_finish <=", value, "isFinish");
            return (Criteria) this;
        }

        public Criteria andIsFinishLike(String value) {
            addCriterion("is_finish like", value, "isFinish");
            return (Criteria) this;
        }

        public Criteria andIsFinishNotLike(String value) {
            addCriterion("is_finish not like", value, "isFinish");
            return (Criteria) this;
        }

        public Criteria andIsFinishIn(List<String> values) {
            addCriterion("is_finish in", values, "isFinish");
            return (Criteria) this;
        }

        public Criteria andIsFinishNotIn(List<String> values) {
            addCriterion("is_finish not in", values, "isFinish");
            return (Criteria) this;
        }

        public Criteria andIsFinishBetween(String value1, String value2) {
            addCriterion("is_finish between", value1, value2, "isFinish");
            return (Criteria) this;
        }

        public Criteria andIsFinishNotBetween(String value1, String value2) {
            addCriterion("is_finish not between", value1, value2, "isFinish");
            return (Criteria) this;
        }
    }

    /**
     * tb_task_period_relation
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_task_period_relation null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}