package com.hd.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbTableTwoRelationEntityExample {
    /**
     * tb_table_two_relation
     */
    protected String orderByClause;

    /**
     * tb_table_two_relation
     */
    protected boolean distinct;

    /**
     * tb_table_two_relation
     */
    protected List<Criteria> oredCriteria;

    /**
     * tb_table_two_relation
     */
    protected Integer limitStart;

    /**
     * tb_table_two_relation
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_two_relation
     *
     * @mbg.generated
     */
    public TbTableTwoRelationEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_two_relation
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_two_relation
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_two_relation
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_two_relation
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_two_relation
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_two_relation
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_two_relation
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_two_relation
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_two_relation
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_two_relation
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_two_relation
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_two_relation
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_two_relation
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_two_relation
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * tb_table_two_relation null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRelationIdIsNull() {
            addCriterion("relation_id is null");
            return (Criteria) this;
        }

        public Criteria andRelationIdIsNotNull() {
            addCriterion("relation_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelationIdEqualTo(String value) {
            addCriterion("relation_id =", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotEqualTo(String value) {
            addCriterion("relation_id <>", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdGreaterThan(String value) {
            addCriterion("relation_id >", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdGreaterThanOrEqualTo(String value) {
            addCriterion("relation_id >=", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLessThan(String value) {
            addCriterion("relation_id <", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLessThanOrEqualTo(String value) {
            addCriterion("relation_id <=", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLike(String value) {
            addCriterion("relation_id like", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotLike(String value) {
            addCriterion("relation_id not like", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdIn(List<String> values) {
            addCriterion("relation_id in", values, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotIn(List<String> values) {
            addCriterion("relation_id not in", values, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdBetween(String value1, String value2) {
            addCriterion("relation_id between", value1, value2, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotBetween(String value1, String value2) {
            addCriterion("relation_id not between", value1, value2, "relationId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("task_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("task_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(String value) {
            addCriterion("task_id =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(String value) {
            addCriterion("task_id <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(String value) {
            addCriterion("task_id >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("task_id >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(String value) {
            addCriterion("task_id <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(String value) {
            addCriterion("task_id <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLike(String value) {
            addCriterion("task_id like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotLike(String value) {
            addCriterion("task_id not like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<String> values) {
            addCriterion("task_id in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<String> values) {
            addCriterion("task_id not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(String value1, String value2) {
            addCriterion("task_id between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(String value1, String value2) {
            addCriterion("task_id not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andResultFileNumberIsNull() {
            addCriterion("result_file_number is null");
            return (Criteria) this;
        }

        public Criteria andResultFileNumberIsNotNull() {
            addCriterion("result_file_number is not null");
            return (Criteria) this;
        }

        public Criteria andResultFileNumberEqualTo(String value) {
            addCriterion("result_file_number =", value, "resultFileNumber");
            return (Criteria) this;
        }

        public Criteria andResultFileNumberNotEqualTo(String value) {
            addCriterion("result_file_number <>", value, "resultFileNumber");
            return (Criteria) this;
        }

        public Criteria andResultFileNumberGreaterThan(String value) {
            addCriterion("result_file_number >", value, "resultFileNumber");
            return (Criteria) this;
        }

        public Criteria andResultFileNumberGreaterThanOrEqualTo(String value) {
            addCriterion("result_file_number >=", value, "resultFileNumber");
            return (Criteria) this;
        }

        public Criteria andResultFileNumberLessThan(String value) {
            addCriterion("result_file_number <", value, "resultFileNumber");
            return (Criteria) this;
        }

        public Criteria andResultFileNumberLessThanOrEqualTo(String value) {
            addCriterion("result_file_number <=", value, "resultFileNumber");
            return (Criteria) this;
        }

        public Criteria andResultFileNumberLike(String value) {
            addCriterion("result_file_number like", value, "resultFileNumber");
            return (Criteria) this;
        }

        public Criteria andResultFileNumberNotLike(String value) {
            addCriterion("result_file_number not like", value, "resultFileNumber");
            return (Criteria) this;
        }

        public Criteria andResultFileNumberIn(List<String> values) {
            addCriterion("result_file_number in", values, "resultFileNumber");
            return (Criteria) this;
        }

        public Criteria andResultFileNumberNotIn(List<String> values) {
            addCriterion("result_file_number not in", values, "resultFileNumber");
            return (Criteria) this;
        }

        public Criteria andResultFileNumberBetween(String value1, String value2) {
            addCriterion("result_file_number between", value1, value2, "resultFileNumber");
            return (Criteria) this;
        }

        public Criteria andResultFileNumberNotBetween(String value1, String value2) {
            addCriterion("result_file_number not between", value1, value2, "resultFileNumber");
            return (Criteria) this;
        }

        public Criteria andProjectConditionIsNull() {
            addCriterion("project_condition is null");
            return (Criteria) this;
        }

        public Criteria andProjectConditionIsNotNull() {
            addCriterion("project_condition is not null");
            return (Criteria) this;
        }

        public Criteria andProjectConditionEqualTo(String value) {
            addCriterion("project_condition =", value, "projectCondition");
            return (Criteria) this;
        }

        public Criteria andProjectConditionNotEqualTo(String value) {
            addCriterion("project_condition <>", value, "projectCondition");
            return (Criteria) this;
        }

        public Criteria andProjectConditionGreaterThan(String value) {
            addCriterion("project_condition >", value, "projectCondition");
            return (Criteria) this;
        }

        public Criteria andProjectConditionGreaterThanOrEqualTo(String value) {
            addCriterion("project_condition >=", value, "projectCondition");
            return (Criteria) this;
        }

        public Criteria andProjectConditionLessThan(String value) {
            addCriterion("project_condition <", value, "projectCondition");
            return (Criteria) this;
        }

        public Criteria andProjectConditionLessThanOrEqualTo(String value) {
            addCriterion("project_condition <=", value, "projectCondition");
            return (Criteria) this;
        }

        public Criteria andProjectConditionLike(String value) {
            addCriterion("project_condition like", value, "projectCondition");
            return (Criteria) this;
        }

        public Criteria andProjectConditionNotLike(String value) {
            addCriterion("project_condition not like", value, "projectCondition");
            return (Criteria) this;
        }

        public Criteria andProjectConditionIn(List<String> values) {
            addCriterion("project_condition in", values, "projectCondition");
            return (Criteria) this;
        }

        public Criteria andProjectConditionNotIn(List<String> values) {
            addCriterion("project_condition not in", values, "projectCondition");
            return (Criteria) this;
        }

        public Criteria andProjectConditionBetween(String value1, String value2) {
            addCriterion("project_condition between", value1, value2, "projectCondition");
            return (Criteria) this;
        }

        public Criteria andProjectConditionNotBetween(String value1, String value2) {
            addCriterion("project_condition not between", value1, value2, "projectCondition");
            return (Criteria) this;
        }

        public Criteria andEmployerIsNull() {
            addCriterion("employer is null");
            return (Criteria) this;
        }

        public Criteria andEmployerIsNotNull() {
            addCriterion("employer is not null");
            return (Criteria) this;
        }

        public Criteria andEmployerEqualTo(String value) {
            addCriterion("employer =", value, "employer");
            return (Criteria) this;
        }

        public Criteria andEmployerNotEqualTo(String value) {
            addCriterion("employer <>", value, "employer");
            return (Criteria) this;
        }

        public Criteria andEmployerGreaterThan(String value) {
            addCriterion("employer >", value, "employer");
            return (Criteria) this;
        }

        public Criteria andEmployerGreaterThanOrEqualTo(String value) {
            addCriterion("employer >=", value, "employer");
            return (Criteria) this;
        }

        public Criteria andEmployerLessThan(String value) {
            addCriterion("employer <", value, "employer");
            return (Criteria) this;
        }

        public Criteria andEmployerLessThanOrEqualTo(String value) {
            addCriterion("employer <=", value, "employer");
            return (Criteria) this;
        }

        public Criteria andEmployerLike(String value) {
            addCriterion("employer like", value, "employer");
            return (Criteria) this;
        }

        public Criteria andEmployerNotLike(String value) {
            addCriterion("employer not like", value, "employer");
            return (Criteria) this;
        }

        public Criteria andEmployerIn(List<String> values) {
            addCriterion("employer in", values, "employer");
            return (Criteria) this;
        }

        public Criteria andEmployerNotIn(List<String> values) {
            addCriterion("employer not in", values, "employer");
            return (Criteria) this;
        }

        public Criteria andEmployerBetween(String value1, String value2) {
            addCriterion("employer between", value1, value2, "employer");
            return (Criteria) this;
        }

        public Criteria andEmployerNotBetween(String value1, String value2) {
            addCriterion("employer not between", value1, value2, "employer");
            return (Criteria) this;
        }

        public Criteria andBidPersonIsNull() {
            addCriterion("bid_person is null");
            return (Criteria) this;
        }

        public Criteria andBidPersonIsNotNull() {
            addCriterion("bid_person is not null");
            return (Criteria) this;
        }

        public Criteria andBidPersonEqualTo(String value) {
            addCriterion("bid_person =", value, "bidPerson");
            return (Criteria) this;
        }

        public Criteria andBidPersonNotEqualTo(String value) {
            addCriterion("bid_person <>", value, "bidPerson");
            return (Criteria) this;
        }

        public Criteria andBidPersonGreaterThan(String value) {
            addCriterion("bid_person >", value, "bidPerson");
            return (Criteria) this;
        }

        public Criteria andBidPersonGreaterThanOrEqualTo(String value) {
            addCriterion("bid_person >=", value, "bidPerson");
            return (Criteria) this;
        }

        public Criteria andBidPersonLessThan(String value) {
            addCriterion("bid_person <", value, "bidPerson");
            return (Criteria) this;
        }

        public Criteria andBidPersonLessThanOrEqualTo(String value) {
            addCriterion("bid_person <=", value, "bidPerson");
            return (Criteria) this;
        }

        public Criteria andBidPersonLike(String value) {
            addCriterion("bid_person like", value, "bidPerson");
            return (Criteria) this;
        }

        public Criteria andBidPersonNotLike(String value) {
            addCriterion("bid_person not like", value, "bidPerson");
            return (Criteria) this;
        }

        public Criteria andBidPersonIn(List<String> values) {
            addCriterion("bid_person in", values, "bidPerson");
            return (Criteria) this;
        }

        public Criteria andBidPersonNotIn(List<String> values) {
            addCriterion("bid_person not in", values, "bidPerson");
            return (Criteria) this;
        }

        public Criteria andBidPersonBetween(String value1, String value2) {
            addCriterion("bid_person between", value1, value2, "bidPerson");
            return (Criteria) this;
        }

        public Criteria andBidPersonNotBetween(String value1, String value2) {
            addCriterion("bid_person not between", value1, value2, "bidPerson");
            return (Criteria) this;
        }

        public Criteria andPlanStartDateIsNull() {
            addCriterion("plan_start_date is null");
            return (Criteria) this;
        }

        public Criteria andPlanStartDateIsNotNull() {
            addCriterion("plan_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andPlanStartDateEqualTo(Date value) {
            addCriterion("plan_start_date =", value, "planStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanStartDateNotEqualTo(Date value) {
            addCriterion("plan_start_date <>", value, "planStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanStartDateGreaterThan(Date value) {
            addCriterion("plan_start_date >", value, "planStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("plan_start_date >=", value, "planStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanStartDateLessThan(Date value) {
            addCriterion("plan_start_date <", value, "planStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanStartDateLessThanOrEqualTo(Date value) {
            addCriterion("plan_start_date <=", value, "planStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanStartDateIn(List<Date> values) {
            addCriterion("plan_start_date in", values, "planStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanStartDateNotIn(List<Date> values) {
            addCriterion("plan_start_date not in", values, "planStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanStartDateBetween(Date value1, Date value2) {
            addCriterion("plan_start_date between", value1, value2, "planStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanStartDateNotBetween(Date value1, Date value2) {
            addCriterion("plan_start_date not between", value1, value2, "planStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanEndDateIsNull() {
            addCriterion("plan_end_date is null");
            return (Criteria) this;
        }

        public Criteria andPlanEndDateIsNotNull() {
            addCriterion("plan_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andPlanEndDateEqualTo(Date value) {
            addCriterion("plan_end_date =", value, "planEndDate");
            return (Criteria) this;
        }

        public Criteria andPlanEndDateNotEqualTo(Date value) {
            addCriterion("plan_end_date <>", value, "planEndDate");
            return (Criteria) this;
        }

        public Criteria andPlanEndDateGreaterThan(Date value) {
            addCriterion("plan_end_date >", value, "planEndDate");
            return (Criteria) this;
        }

        public Criteria andPlanEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("plan_end_date >=", value, "planEndDate");
            return (Criteria) this;
        }

        public Criteria andPlanEndDateLessThan(Date value) {
            addCriterion("plan_end_date <", value, "planEndDate");
            return (Criteria) this;
        }

        public Criteria andPlanEndDateLessThanOrEqualTo(Date value) {
            addCriterion("plan_end_date <=", value, "planEndDate");
            return (Criteria) this;
        }

        public Criteria andPlanEndDateIn(List<Date> values) {
            addCriterion("plan_end_date in", values, "planEndDate");
            return (Criteria) this;
        }

        public Criteria andPlanEndDateNotIn(List<Date> values) {
            addCriterion("plan_end_date not in", values, "planEndDate");
            return (Criteria) this;
        }

        public Criteria andPlanEndDateBetween(Date value1, Date value2) {
            addCriterion("plan_end_date between", value1, value2, "planEndDate");
            return (Criteria) this;
        }

        public Criteria andPlanEndDateNotBetween(Date value1, Date value2) {
            addCriterion("plan_end_date not between", value1, value2, "planEndDate");
            return (Criteria) this;
        }

        public Criteria andActualStartDateIsNull() {
            addCriterion("actual_start_date is null");
            return (Criteria) this;
        }

        public Criteria andActualStartDateIsNotNull() {
            addCriterion("actual_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andActualStartDateEqualTo(Date value) {
            addCriterion("actual_start_date =", value, "actualStartDate");
            return (Criteria) this;
        }

        public Criteria andActualStartDateNotEqualTo(Date value) {
            addCriterion("actual_start_date <>", value, "actualStartDate");
            return (Criteria) this;
        }

        public Criteria andActualStartDateGreaterThan(Date value) {
            addCriterion("actual_start_date >", value, "actualStartDate");
            return (Criteria) this;
        }

        public Criteria andActualStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("actual_start_date >=", value, "actualStartDate");
            return (Criteria) this;
        }

        public Criteria andActualStartDateLessThan(Date value) {
            addCriterion("actual_start_date <", value, "actualStartDate");
            return (Criteria) this;
        }

        public Criteria andActualStartDateLessThanOrEqualTo(Date value) {
            addCriterion("actual_start_date <=", value, "actualStartDate");
            return (Criteria) this;
        }

        public Criteria andActualStartDateIn(List<Date> values) {
            addCriterion("actual_start_date in", values, "actualStartDate");
            return (Criteria) this;
        }

        public Criteria andActualStartDateNotIn(List<Date> values) {
            addCriterion("actual_start_date not in", values, "actualStartDate");
            return (Criteria) this;
        }

        public Criteria andActualStartDateBetween(Date value1, Date value2) {
            addCriterion("actual_start_date between", value1, value2, "actualStartDate");
            return (Criteria) this;
        }

        public Criteria andActualStartDateNotBetween(Date value1, Date value2) {
            addCriterion("actual_start_date not between", value1, value2, "actualStartDate");
            return (Criteria) this;
        }

        public Criteria andActualEndDateIsNull() {
            addCriterion("actual_end_date is null");
            return (Criteria) this;
        }

        public Criteria andActualEndDateIsNotNull() {
            addCriterion("actual_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andActualEndDateEqualTo(Date value) {
            addCriterion("actual_end_date =", value, "actualEndDate");
            return (Criteria) this;
        }

        public Criteria andActualEndDateNotEqualTo(Date value) {
            addCriterion("actual_end_date <>", value, "actualEndDate");
            return (Criteria) this;
        }

        public Criteria andActualEndDateGreaterThan(Date value) {
            addCriterion("actual_end_date >", value, "actualEndDate");
            return (Criteria) this;
        }

        public Criteria andActualEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("actual_end_date >=", value, "actualEndDate");
            return (Criteria) this;
        }

        public Criteria andActualEndDateLessThan(Date value) {
            addCriterion("actual_end_date <", value, "actualEndDate");
            return (Criteria) this;
        }

        public Criteria andActualEndDateLessThanOrEqualTo(Date value) {
            addCriterion("actual_end_date <=", value, "actualEndDate");
            return (Criteria) this;
        }

        public Criteria andActualEndDateIn(List<Date> values) {
            addCriterion("actual_end_date in", values, "actualEndDate");
            return (Criteria) this;
        }

        public Criteria andActualEndDateNotIn(List<Date> values) {
            addCriterion("actual_end_date not in", values, "actualEndDate");
            return (Criteria) this;
        }

        public Criteria andActualEndDateBetween(Date value1, Date value2) {
            addCriterion("actual_end_date between", value1, value2, "actualEndDate");
            return (Criteria) this;
        }

        public Criteria andActualEndDateNotBetween(Date value1, Date value2) {
            addCriterion("actual_end_date not between", value1, value2, "actualEndDate");
            return (Criteria) this;
        }

        public Criteria andDelayReasonIsNull() {
            addCriterion("delay_reason is null");
            return (Criteria) this;
        }

        public Criteria andDelayReasonIsNotNull() {
            addCriterion("delay_reason is not null");
            return (Criteria) this;
        }

        public Criteria andDelayReasonEqualTo(String value) {
            addCriterion("delay_reason =", value, "delayReason");
            return (Criteria) this;
        }

        public Criteria andDelayReasonNotEqualTo(String value) {
            addCriterion("delay_reason <>", value, "delayReason");
            return (Criteria) this;
        }

        public Criteria andDelayReasonGreaterThan(String value) {
            addCriterion("delay_reason >", value, "delayReason");
            return (Criteria) this;
        }

        public Criteria andDelayReasonGreaterThanOrEqualTo(String value) {
            addCriterion("delay_reason >=", value, "delayReason");
            return (Criteria) this;
        }

        public Criteria andDelayReasonLessThan(String value) {
            addCriterion("delay_reason <", value, "delayReason");
            return (Criteria) this;
        }

        public Criteria andDelayReasonLessThanOrEqualTo(String value) {
            addCriterion("delay_reason <=", value, "delayReason");
            return (Criteria) this;
        }

        public Criteria andDelayReasonLike(String value) {
            addCriterion("delay_reason like", value, "delayReason");
            return (Criteria) this;
        }

        public Criteria andDelayReasonNotLike(String value) {
            addCriterion("delay_reason not like", value, "delayReason");
            return (Criteria) this;
        }

        public Criteria andDelayReasonIn(List<String> values) {
            addCriterion("delay_reason in", values, "delayReason");
            return (Criteria) this;
        }

        public Criteria andDelayReasonNotIn(List<String> values) {
            addCriterion("delay_reason not in", values, "delayReason");
            return (Criteria) this;
        }

        public Criteria andDelayReasonBetween(String value1, String value2) {
            addCriterion("delay_reason between", value1, value2, "delayReason");
            return (Criteria) this;
        }

        public Criteria andDelayReasonNotBetween(String value1, String value2) {
            addCriterion("delay_reason not between", value1, value2, "delayReason");
            return (Criteria) this;
        }

        public Criteria andMainResultIsNull() {
            addCriterion("main_result is null");
            return (Criteria) this;
        }

        public Criteria andMainResultIsNotNull() {
            addCriterion("main_result is not null");
            return (Criteria) this;
        }

        public Criteria andMainResultEqualTo(String value) {
            addCriterion("main_result =", value, "mainResult");
            return (Criteria) this;
        }

        public Criteria andMainResultNotEqualTo(String value) {
            addCriterion("main_result <>", value, "mainResult");
            return (Criteria) this;
        }

        public Criteria andMainResultGreaterThan(String value) {
            addCriterion("main_result >", value, "mainResult");
            return (Criteria) this;
        }

        public Criteria andMainResultGreaterThanOrEqualTo(String value) {
            addCriterion("main_result >=", value, "mainResult");
            return (Criteria) this;
        }

        public Criteria andMainResultLessThan(String value) {
            addCriterion("main_result <", value, "mainResult");
            return (Criteria) this;
        }

        public Criteria andMainResultLessThanOrEqualTo(String value) {
            addCriterion("main_result <=", value, "mainResult");
            return (Criteria) this;
        }

        public Criteria andMainResultLike(String value) {
            addCriterion("main_result like", value, "mainResult");
            return (Criteria) this;
        }

        public Criteria andMainResultNotLike(String value) {
            addCriterion("main_result not like", value, "mainResult");
            return (Criteria) this;
        }

        public Criteria andMainResultIn(List<String> values) {
            addCriterion("main_result in", values, "mainResult");
            return (Criteria) this;
        }

        public Criteria andMainResultNotIn(List<String> values) {
            addCriterion("main_result not in", values, "mainResult");
            return (Criteria) this;
        }

        public Criteria andMainResultBetween(String value1, String value2) {
            addCriterion("main_result between", value1, value2, "mainResult");
            return (Criteria) this;
        }

        public Criteria andMainResultNotBetween(String value1, String value2) {
            addCriterion("main_result not between", value1, value2, "mainResult");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNull() {
            addCriterion("is_del_flg is null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIsNotNull() {
            addCriterion("is_del_flg is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgEqualTo(String value) {
            addCriterion("is_del_flg =", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotEqualTo(String value) {
            addCriterion("is_del_flg <>", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThan(String value) {
            addCriterion("is_del_flg >", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("is_del_flg >=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThan(String value) {
            addCriterion("is_del_flg <", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLessThanOrEqualTo(String value) {
            addCriterion("is_del_flg <=", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgLike(String value) {
            addCriterion("is_del_flg like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotLike(String value) {
            addCriterion("is_del_flg not like", value, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgIn(List<String> values) {
            addCriterion("is_del_flg in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotIn(List<String> values) {
            addCriterion("is_del_flg not in", values, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgBetween(String value1, String value2) {
            addCriterion("is_del_flg between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }

        public Criteria andIsDelFlgNotBetween(String value1, String value2) {
            addCriterion("is_del_flg not between", value1, value2, "isDelFlg");
            return (Criteria) this;
        }
    }

    /**
     * tb_table_two_relation
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * tb_table_two_relation null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}