package com.hd.manager.dao;

import com.hd.base.dao.BaseDao;
import com.hd.common.entity.*;
import com.hd.manager.dao.bean.*;
import com.hd.manager.vo.HTTableFiveRelationVO;
import com.hd.manager.vo.HTTableTwoRelationVO;

import java.util.List;

/**
 * 任务 持久层接口
 *
 * @author jwl
 * Created in 2019/7/22 15:31
 */
public interface HTTaskDao extends BaseDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_confirm_opinion_relation
     *
     * @mbg.generated
     */
    int insertSelective(HTFileConfirmOpinionRelationBean htFileConfirmOpinionRelationBean);

    /**
     * 为消息中心查询用户id
     * @return 用户id
     */
    List<HTTaskBean> excSearchUserIdForMessage(HTTaskBean paramBean);

    /**
     * 查询落标通知书和任务关联表详情
     */
    HTFailTenderNoticeRelationBean excSearchFailTenderNoticeRelationDetail(TbFailTenderNoticeRelationEntity paramBean);

    /**
     * 查询招标文件确认意见表和任务的关联表详情
     */
    HTFileConfirmOpinionRelationBean excSearchFileConfirmOpinionRelationDetail(TbFileConfirmOpinionRelationEntity paramBean);

    /**
     * 查询专家论证意见表详情
     */
    HTExpertOpinionRelationBean excSearchExpertOpinionRelationDetail(TbExpertOpinionRelationEntity paramBean);

    /**
     * 通过任务id修改该任务所属的项目名称
     */
    void excUpdateProjectNameByTaskId(HTTaskBean paramBean);

    /**
     * 通过任务id查询审核阶段文件
     */
    HTTaskPeriodMaterialBean excSearchMaterialByTaskPeriodId(HTTaskPeriodMaterialBean paramBean);

    /**
     * 通过任务id修改该任务下的审批中的档案编号
     */
    void excUpdateFileNumberTaskId(HTTaskArchiveBean paramBean);

    /**
     * 通过任务id修改该任务下的阶段文件提审状态
     */
    void excUpdateIsReviewByTaskId(HTTaskPeriodMaterialBean paramBean);

    /**
     * 查询该任务所属的项目是否结束
     * @return 项目状态
     */
    HTProjectBean excSearchProjectStsByTaskId(String taskId);

    /**
     * 查询重新编辑审核列表
     */
    List<HTTaskPeriodBean> excSearchTaskReeditHisTaskInst(HTTaskPeriodBean paramBean);

    /**
     * 查询该任务下的所有A3阶段信息
     * @return 所有A3阶段信息
     */
    List<TbTaskPeriodRelationEntity> excSearchAllA3PeriodInfoByTaskId(TbTaskPeriodRelationEntity paramBean);

    /**
     * 查询阶段关联文件信息
     * @return 文件信息
     */
    List<HTTaskSaveMaterialBean> excSearchTaskSaveMaterialListByProperty(TbTaskSaveMaterialRelationEntity paramBean);

    /**
     * 添加归档文件信息
     * @return 插入条数
     */
    int excInsertTaskSaveMaterialRelationInfo(TbTaskSaveMaterialRelationEntity record);

    /**
     * 查询文件类别列表
     */
    List<HTDictFileTypeBean> searchMaterialTypeList();

    /**
     * 查询任务关联成员
     */
    List<HTTaskBean> excSearchTaskUserListByTaskId(HTTaskPeriodBean paramBean);

    /**
     * 查询审核意见信息
     */
    List<HTTaskPeriodBean> excSearchHTTaskHisTaskInstInfoList(HTTaskPeriodBean paramBean);

    /**
     * 根据任务id查询部门id
     * @return 部门id
     */
    HTTaskPeriodBean excSearchDepartmentIdByTaskId(HTTaskPeriodBean paramBean);

    /**
     * 修改其审核状态
     */
    void excUpdateIsReviewType(List<String> materialIds);

    /**
     * 通过任务id查询重新编辑申请列表
     * @return 重新编辑申请列表
     */
    List<HTTaskReeditBean> excSearchTaskReeditListByRelationId(TbTaskEntity tbTaskEntity);

    /**
     * 通过任务id查询重新编辑申请详情
     * @return 重新编辑申请详情
     */
    HTTaskReeditBean excSearchTaskReeditDetailInfoByRelationId(TbTaskEntity tbTaskEntity);

    /**
     * 通过任务id查询任务归档详情
     * @return 任务归档详情
     */
    HTTaskArchiveBean excSearchTaskArchiveDetailInfoByTaskId(String taskId);

    /**
     * 通过任务id查询任务详情
     * @return 任务详情
     */
    HTTaskBean excSearchTaskDetailInfoByTaskId(String taskId);

    /**
     * 通过任务阶段id查询任务详情
     * @return 任务详情
     */
    HTTaskBean excSearchTaskDetailInfoByRelationId(String relationId);

    /**
     * 通过任务阶段id查询任务阶段详情
     * @return 任务阶段详情
     */
    HTTaskPeriodBean excSearchTaskPeriodDetailInfoByRelationId(String relationId);

    /**
     * 根据任务阶段id修改非自己任务阶段文件的审核状态
     */
    void excUpdateIsReviewByRelationId(HTTaskPeriodBean paramBean);

    /**
     * 根据任务阶段id查询非自己任务阶段的文件列表
     * @return 非自己任务阶段的文件列表
     */
    List<HTTaskPeriodMaterialBean> excSearchTaskPeriodMaterialListByTaskPeriodId(HTTaskPeriodMaterialBean paramBean);

    /**
     * 查询相关资料文件列表，当传入任务id的时候查询的是当前任务下的所有的相关资料，当传入任务阶段id的时候查询的是当前阶段的相关资料
     * @return 相关资料文件列表
     */
    List<HTTaskPeriodMaterialBean> excSearchIsReviewTaskPeriodMaterialList(HTTaskPeriodMaterialBean paramBean);

    /**
     * 查询阶段关联文件信息
     * @return 文件信息
     */
    List<HTTaskPeriodMaterialBean> excSearchTaskPeriodMaterialListByProperty(HTTaskPeriodMaterialBean paramBean);

    /**
     * 根据任务阶段id查询项目编号、合同编号和成果文件编号
     * @return 项目编号、合同编号和成果文件编号
     */
    HTTaskBean excSearchProjectNumContractNumFileNumberByTaskPeriodId(HTTaskBean paramBean);

    /**
     * 通过任务阶段id查询素材路径和关联id
     * @return 素材路径
     */
    TbTaskPeriodMaterialRelationEntity excSearchMaterialPathByTaskPeriodId(HTTaskPeriodMaterialBean paramBean);

    /**
     * 添加文件信息
     * @return 插入条数
     */
    int excInsertTaskPeriodMaterialRelationInfo(TbTaskPeriodMaterialRelationEntity record);

    /**
     * 工时列表数据的总条数
     * @return 时列表总条数
     */
    Integer excSearchHourListCount(HTTaskBean paramBean);

    /**
     * 工时列表
     * @return 工时列表
     */
    List<HTTaskBean> excSearchHourListInfo(HTTaskBean paramBean);

    /**
     * 查询是否存在今天的工时记录
     * @return 条数
     */
    Integer excSearchTodayHourInfoCount(HTTaskBean paramBean);

    /**
     * 查询我的工时
     * @return 我的工时
     */
    List<HTTaskBean> excSearchMyHourListInfo(HTTaskBean paramBean);

    /**
     * 查询任务内容
     * @return 任务内容
     */
    HTTaskBean excSearchTaskContent(HTTaskBean paramBean);

    /**
     * 查询执行人信息
     * @return 执行人信息
     */
    List<HTTaskBean> excSearchExecutorListInfo(HTTaskBean paramBean);

    /**
     * 删除用户每天实际完成工时记录信息
     * @param paramBean
     */
    void excDeleteUserScheduleRecordInfo(TbTaskEntity paramBean);

    /**
     * 查询任务详情（不包括执行人信息）
     * @return 任务详情
     */
    HTTaskBean excSearchTaskInfo(HTTaskBean paramBean);

    /**
     * 删除归档文件信息
     * @param paramBean
     */
    void excDeleteSaveMaterialRelations(TbTaskEntity paramBean);

    /**
     * 删除任务信息
     * @param paramBean
     */
    void excDeleteTaskInfo(TbTaskEntity paramBean);

    /**
     * 删除任务阶段关联信息
     * @param paramBean
     */
    void excDeleteTaskPeriodRelations(TbTaskEntity paramBean);

    /**
     * 删除任务和人员id关联信息
     * @param paramBean
     */
    void excDeleteTaskUserRelations(TbTaskEntity paramBean);

    /**
     * 删除任务归档表数据信息
     * @param paramBean
     */
    void excDeleteTaskArchiveInfo(TbTaskEntity paramBean);

    /**
     * 根据合同id查部门id
     * @return 部门id
     */
    String excSearchDepartmentIdByContractId(TbTaskEntity paramBean);

    /**
     * 添加任务阶段关联信息
     */
    void excInsertTaskPeriodRelations(HTTaskBean htTaskBean);

    /**
     * 批量插入任务和人员id关联信息
     */
    void excInsertTaskUserRelations(List<HTTaskBean> paramList);

    /**
     * 查询人员信息
     * @return 人员信息
     */
    List<HTTaskBean> excSearchUserInfo(HTTaskBean paramBean);

    /**
     * 查询拟定工作计划信息
     * @return 拟定工作计划信息
     */
    HTTableFiveRelationBean excSearchTaskWorkPlanInfo(HTTableFiveRelationVO paramVO);

    /**
     * 查询编制成果文件-A2信息
     * @return 编制成果文件-A2信息
     */
    HTTableTwoRelationBean excSearchTaskCompileResultsFileA2(HTTableTwoRelationVO paramVO);

    /**
     * 通过合同查询所有任务
     * @param contractId
     * @return
     */
    List<String> excSearchAllTaskIdByContractId(String contractId);

    /**
     * 查询开标、评标信息
     * @param paramBean
     * @return
     */
    HTOpenBidBean excSearchOpenBidInfoDetail(TbOpenBidRelationEntity paramBean);
}
