package com.hd.data.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OldDataJointRecordExample {
    /**
     * old_data_joint_record
     */
    protected String orderByClause;

    /**
     * old_data_joint_record
     */
    protected boolean distinct;

    /**
     * old_data_joint_record
     */
    protected List<Criteria> oredCriteria;

    /**
     * old_data_joint_record
     */
    protected Integer limitStart;

    /**
     * old_data_joint_record
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_data_joint_record
     *
     * @mbg.generated
     */
    public OldDataJointRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_data_joint_record
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_data_joint_record
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_data_joint_record
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_data_joint_record
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_data_joint_record
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_data_joint_record
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_data_joint_record
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_data_joint_record
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_data_joint_record
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_data_joint_record
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_data_joint_record
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_data_joint_record
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_data_joint_record
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_data_joint_record
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * old_data_joint_record null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andContractIdIsNull() {
            addCriterion("contract_id is null");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNotNull() {
            addCriterion("contract_id is not null");
            return (Criteria) this;
        }

        public Criteria andContractIdEqualTo(String value) {
            addCriterion("contract_id =", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotEqualTo(String value) {
            addCriterion("contract_id <>", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThan(String value) {
            addCriterion("contract_id >", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThanOrEqualTo(String value) {
            addCriterion("contract_id >=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThan(String value) {
            addCriterion("contract_id <", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThanOrEqualTo(String value) {
            addCriterion("contract_id <=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLike(String value) {
            addCriterion("contract_id like", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotLike(String value) {
            addCriterion("contract_id not like", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdIn(List<String> values) {
            addCriterion("contract_id in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotIn(List<String> values) {
            addCriterion("contract_id not in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdBetween(String value1, String value2) {
            addCriterion("contract_id between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotBetween(String value1, String value2) {
            addCriterion("contract_id not between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andOldDeptIdIsNull() {
            addCriterion("old_dept_id is null");
            return (Criteria) this;
        }

        public Criteria andOldDeptIdIsNotNull() {
            addCriterion("old_dept_id is not null");
            return (Criteria) this;
        }

        public Criteria andOldDeptIdEqualTo(String value) {
            addCriterion("old_dept_id =", value, "oldDeptId");
            return (Criteria) this;
        }

        public Criteria andOldDeptIdNotEqualTo(String value) {
            addCriterion("old_dept_id <>", value, "oldDeptId");
            return (Criteria) this;
        }

        public Criteria andOldDeptIdGreaterThan(String value) {
            addCriterion("old_dept_id >", value, "oldDeptId");
            return (Criteria) this;
        }

        public Criteria andOldDeptIdGreaterThanOrEqualTo(String value) {
            addCriterion("old_dept_id >=", value, "oldDeptId");
            return (Criteria) this;
        }

        public Criteria andOldDeptIdLessThan(String value) {
            addCriterion("old_dept_id <", value, "oldDeptId");
            return (Criteria) this;
        }

        public Criteria andOldDeptIdLessThanOrEqualTo(String value) {
            addCriterion("old_dept_id <=", value, "oldDeptId");
            return (Criteria) this;
        }

        public Criteria andOldDeptIdLike(String value) {
            addCriterion("old_dept_id like", value, "oldDeptId");
            return (Criteria) this;
        }

        public Criteria andOldDeptIdNotLike(String value) {
            addCriterion("old_dept_id not like", value, "oldDeptId");
            return (Criteria) this;
        }

        public Criteria andOldDeptIdIn(List<String> values) {
            addCriterion("old_dept_id in", values, "oldDeptId");
            return (Criteria) this;
        }

        public Criteria andOldDeptIdNotIn(List<String> values) {
            addCriterion("old_dept_id not in", values, "oldDeptId");
            return (Criteria) this;
        }

        public Criteria andOldDeptIdBetween(String value1, String value2) {
            addCriterion("old_dept_id between", value1, value2, "oldDeptId");
            return (Criteria) this;
        }

        public Criteria andOldDeptIdNotBetween(String value1, String value2) {
            addCriterion("old_dept_id not between", value1, value2, "oldDeptId");
            return (Criteria) this;
        }

        public Criteria andDeptNameIsNull() {
            addCriterion("dept_name is null");
            return (Criteria) this;
        }

        public Criteria andDeptNameIsNotNull() {
            addCriterion("dept_name is not null");
            return (Criteria) this;
        }

        public Criteria andDeptNameEqualTo(String value) {
            addCriterion("dept_name =", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotEqualTo(String value) {
            addCriterion("dept_name <>", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameGreaterThan(String value) {
            addCriterion("dept_name >", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameGreaterThanOrEqualTo(String value) {
            addCriterion("dept_name >=", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLessThan(String value) {
            addCriterion("dept_name <", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLessThanOrEqualTo(String value) {
            addCriterion("dept_name <=", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLike(String value) {
            addCriterion("dept_name like", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotLike(String value) {
            addCriterion("dept_name not like", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameIn(List<String> values) {
            addCriterion("dept_name in", values, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotIn(List<String> values) {
            addCriterion("dept_name not in", values, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameBetween(String value1, String value2) {
            addCriterion("dept_name between", value1, value2, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotBetween(String value1, String value2) {
            addCriterion("dept_name not between", value1, value2, "deptName");
            return (Criteria) this;
        }

        public Criteria andOldProjectIdIsNull() {
            addCriterion("old_project_id is null");
            return (Criteria) this;
        }

        public Criteria andOldProjectIdIsNotNull() {
            addCriterion("old_project_id is not null");
            return (Criteria) this;
        }

        public Criteria andOldProjectIdEqualTo(String value) {
            addCriterion("old_project_id =", value, "oldProjectId");
            return (Criteria) this;
        }

        public Criteria andOldProjectIdNotEqualTo(String value) {
            addCriterion("old_project_id <>", value, "oldProjectId");
            return (Criteria) this;
        }

        public Criteria andOldProjectIdGreaterThan(String value) {
            addCriterion("old_project_id >", value, "oldProjectId");
            return (Criteria) this;
        }

        public Criteria andOldProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("old_project_id >=", value, "oldProjectId");
            return (Criteria) this;
        }

        public Criteria andOldProjectIdLessThan(String value) {
            addCriterion("old_project_id <", value, "oldProjectId");
            return (Criteria) this;
        }

        public Criteria andOldProjectIdLessThanOrEqualTo(String value) {
            addCriterion("old_project_id <=", value, "oldProjectId");
            return (Criteria) this;
        }

        public Criteria andOldProjectIdLike(String value) {
            addCriterion("old_project_id like", value, "oldProjectId");
            return (Criteria) this;
        }

        public Criteria andOldProjectIdNotLike(String value) {
            addCriterion("old_project_id not like", value, "oldProjectId");
            return (Criteria) this;
        }

        public Criteria andOldProjectIdIn(List<String> values) {
            addCriterion("old_project_id in", values, "oldProjectId");
            return (Criteria) this;
        }

        public Criteria andOldProjectIdNotIn(List<String> values) {
            addCriterion("old_project_id not in", values, "oldProjectId");
            return (Criteria) this;
        }

        public Criteria andOldProjectIdBetween(String value1, String value2) {
            addCriterion("old_project_id between", value1, value2, "oldProjectId");
            return (Criteria) this;
        }

        public Criteria andOldProjectIdNotBetween(String value1, String value2) {
            addCriterion("old_project_id not between", value1, value2, "oldProjectId");
            return (Criteria) this;
        }
    }

    /**
     * old_data_joint_record
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * old_data_joint_record null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}