package com.hd.data.entity;

import java.util.ArrayList;
import java.util.List;

public class OldProjectInfoToArchiveExample {
    /**
     * old_project_info_to_archive
     */
    protected String orderByClause;

    /**
     * old_project_info_to_archive
     */
    protected boolean distinct;

    /**
     * old_project_info_to_archive
     */
    protected List<Criteria> oredCriteria;

    /**
     * old_project_info_to_archive
     */
    protected Integer limitStart;

    /**
     * old_project_info_to_archive
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_project_info_to_archive
     *
     * @mbg.generated
     */
    public OldProjectInfoToArchiveExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_project_info_to_archive
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_project_info_to_archive
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_project_info_to_archive
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_project_info_to_archive
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_project_info_to_archive
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_project_info_to_archive
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_project_info_to_archive
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_project_info_to_archive
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_project_info_to_archive
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_project_info_to_archive
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_project_info_to_archive
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_project_info_to_archive
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_project_info_to_archive
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_project_info_to_archive
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * old_project_info_to_archive null
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andClsidIsNull() {
            addCriterion("clsid is null");
            return (Criteria) this;
        }

        public Criteria andClsidIsNotNull() {
            addCriterion("clsid is not null");
            return (Criteria) this;
        }

        public Criteria andClsidEqualTo(Integer value) {
            addCriterion("clsid =", value, "clsid");
            return (Criteria) this;
        }

        public Criteria andClsidNotEqualTo(Integer value) {
            addCriterion("clsid <>", value, "clsid");
            return (Criteria) this;
        }

        public Criteria andClsidGreaterThan(Integer value) {
            addCriterion("clsid >", value, "clsid");
            return (Criteria) this;
        }

        public Criteria andClsidGreaterThanOrEqualTo(Integer value) {
            addCriterion("clsid >=", value, "clsid");
            return (Criteria) this;
        }

        public Criteria andClsidLessThan(Integer value) {
            addCriterion("clsid <", value, "clsid");
            return (Criteria) this;
        }

        public Criteria andClsidLessThanOrEqualTo(Integer value) {
            addCriterion("clsid <=", value, "clsid");
            return (Criteria) this;
        }

        public Criteria andClsidIn(List<Integer> values) {
            addCriterion("clsid in", values, "clsid");
            return (Criteria) this;
        }

        public Criteria andClsidNotIn(List<Integer> values) {
            addCriterion("clsid not in", values, "clsid");
            return (Criteria) this;
        }

        public Criteria andClsidBetween(Integer value1, Integer value2) {
            addCriterion("clsid between", value1, value2, "clsid");
            return (Criteria) this;
        }

        public Criteria andClsidNotBetween(Integer value1, Integer value2) {
            addCriterion("clsid not between", value1, value2, "clsid");
            return (Criteria) this;
        }

        public Criteria andClcidIsNull() {
            addCriterion("clcid is null");
            return (Criteria) this;
        }

        public Criteria andClcidIsNotNull() {
            addCriterion("clcid is not null");
            return (Criteria) this;
        }

        public Criteria andClcidEqualTo(Integer value) {
            addCriterion("clcid =", value, "clcid");
            return (Criteria) this;
        }

        public Criteria andClcidNotEqualTo(Integer value) {
            addCriterion("clcid <>", value, "clcid");
            return (Criteria) this;
        }

        public Criteria andClcidGreaterThan(Integer value) {
            addCriterion("clcid >", value, "clcid");
            return (Criteria) this;
        }

        public Criteria andClcidGreaterThanOrEqualTo(Integer value) {
            addCriterion("clcid >=", value, "clcid");
            return (Criteria) this;
        }

        public Criteria andClcidLessThan(Integer value) {
            addCriterion("clcid <", value, "clcid");
            return (Criteria) this;
        }

        public Criteria andClcidLessThanOrEqualTo(Integer value) {
            addCriterion("clcid <=", value, "clcid");
            return (Criteria) this;
        }

        public Criteria andClcidIn(List<Integer> values) {
            addCriterion("clcid in", values, "clcid");
            return (Criteria) this;
        }

        public Criteria andClcidNotIn(List<Integer> values) {
            addCriterion("clcid not in", values, "clcid");
            return (Criteria) this;
        }

        public Criteria andClcidBetween(Integer value1, Integer value2) {
            addCriterion("clcid between", value1, value2, "clcid");
            return (Criteria) this;
        }

        public Criteria andClcidNotBetween(Integer value1, Integer value2) {
            addCriterion("clcid not between", value1, value2, "clcid");
            return (Criteria) this;
        }

        public Criteria andClpidIsNull() {
            addCriterion("clpid is null");
            return (Criteria) this;
        }

        public Criteria andClpidIsNotNull() {
            addCriterion("clpid is not null");
            return (Criteria) this;
        }

        public Criteria andClpidEqualTo(Integer value) {
            addCriterion("clpid =", value, "clpid");
            return (Criteria) this;
        }

        public Criteria andClpidNotEqualTo(Integer value) {
            addCriterion("clpid <>", value, "clpid");
            return (Criteria) this;
        }

        public Criteria andClpidGreaterThan(Integer value) {
            addCriterion("clpid >", value, "clpid");
            return (Criteria) this;
        }

        public Criteria andClpidGreaterThanOrEqualTo(Integer value) {
            addCriterion("clpid >=", value, "clpid");
            return (Criteria) this;
        }

        public Criteria andClpidLessThan(Integer value) {
            addCriterion("clpid <", value, "clpid");
            return (Criteria) this;
        }

        public Criteria andClpidLessThanOrEqualTo(Integer value) {
            addCriterion("clpid <=", value, "clpid");
            return (Criteria) this;
        }

        public Criteria andClpidIn(List<Integer> values) {
            addCriterion("clpid in", values, "clpid");
            return (Criteria) this;
        }

        public Criteria andClpidNotIn(List<Integer> values) {
            addCriterion("clpid not in", values, "clpid");
            return (Criteria) this;
        }

        public Criteria andClpidBetween(Integer value1, Integer value2) {
            addCriterion("clpid between", value1, value2, "clpid");
            return (Criteria) this;
        }

        public Criteria andClpidNotBetween(Integer value1, Integer value2) {
            addCriterion("clpid not between", value1, value2, "clpid");
            return (Criteria) this;
        }

        public Criteria andClnidIsNull() {
            addCriterion("clnid is null");
            return (Criteria) this;
        }

        public Criteria andClnidIsNotNull() {
            addCriterion("clnid is not null");
            return (Criteria) this;
        }

        public Criteria andClnidEqualTo(Integer value) {
            addCriterion("clnid =", value, "clnid");
            return (Criteria) this;
        }

        public Criteria andClnidNotEqualTo(Integer value) {
            addCriterion("clnid <>", value, "clnid");
            return (Criteria) this;
        }

        public Criteria andClnidGreaterThan(Integer value) {
            addCriterion("clnid >", value, "clnid");
            return (Criteria) this;
        }

        public Criteria andClnidGreaterThanOrEqualTo(Integer value) {
            addCriterion("clnid >=", value, "clnid");
            return (Criteria) this;
        }

        public Criteria andClnidLessThan(Integer value) {
            addCriterion("clnid <", value, "clnid");
            return (Criteria) this;
        }

        public Criteria andClnidLessThanOrEqualTo(Integer value) {
            addCriterion("clnid <=", value, "clnid");
            return (Criteria) this;
        }

        public Criteria andClnidIn(List<Integer> values) {
            addCriterion("clnid in", values, "clnid");
            return (Criteria) this;
        }

        public Criteria andClnidNotIn(List<Integer> values) {
            addCriterion("clnid not in", values, "clnid");
            return (Criteria) this;
        }

        public Criteria andClnidBetween(Integer value1, Integer value2) {
            addCriterion("clnid between", value1, value2, "clnid");
            return (Criteria) this;
        }

        public Criteria andClnidNotBetween(Integer value1, Integer value2) {
            addCriterion("clnid not between", value1, value2, "clnid");
            return (Criteria) this;
        }

        public Criteria andClmidIsNull() {
            addCriterion("clmid is null");
            return (Criteria) this;
        }

        public Criteria andClmidIsNotNull() {
            addCriterion("clmid is not null");
            return (Criteria) this;
        }

        public Criteria andClmidEqualTo(Integer value) {
            addCriterion("clmid =", value, "clmid");
            return (Criteria) this;
        }

        public Criteria andClmidNotEqualTo(Integer value) {
            addCriterion("clmid <>", value, "clmid");
            return (Criteria) this;
        }

        public Criteria andClmidGreaterThan(Integer value) {
            addCriterion("clmid >", value, "clmid");
            return (Criteria) this;
        }

        public Criteria andClmidGreaterThanOrEqualTo(Integer value) {
            addCriterion("clmid >=", value, "clmid");
            return (Criteria) this;
        }

        public Criteria andClmidLessThan(Integer value) {
            addCriterion("clmid <", value, "clmid");
            return (Criteria) this;
        }

        public Criteria andClmidLessThanOrEqualTo(Integer value) {
            addCriterion("clmid <=", value, "clmid");
            return (Criteria) this;
        }

        public Criteria andClmidIn(List<Integer> values) {
            addCriterion("clmid in", values, "clmid");
            return (Criteria) this;
        }

        public Criteria andClmidNotIn(List<Integer> values) {
            addCriterion("clmid not in", values, "clmid");
            return (Criteria) this;
        }

        public Criteria andClmidBetween(Integer value1, Integer value2) {
            addCriterion("clmid between", value1, value2, "clmid");
            return (Criteria) this;
        }

        public Criteria andClmidNotBetween(Integer value1, Integer value2) {
            addCriterion("clmid not between", value1, value2, "clmid");
            return (Criteria) this;
        }

        public Criteria andPaidIsNull() {
            addCriterion("paid is null");
            return (Criteria) this;
        }

        public Criteria andPaidIsNotNull() {
            addCriterion("paid is not null");
            return (Criteria) this;
        }

        public Criteria andPaidEqualTo(Integer value) {
            addCriterion("paid =", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidNotEqualTo(Integer value) {
            addCriterion("paid <>", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidGreaterThan(Integer value) {
            addCriterion("paid >", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidGreaterThanOrEqualTo(Integer value) {
            addCriterion("paid >=", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidLessThan(Integer value) {
            addCriterion("paid <", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidLessThanOrEqualTo(Integer value) {
            addCriterion("paid <=", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidIn(List<Integer> values) {
            addCriterion("paid in", values, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidNotIn(List<Integer> values) {
            addCriterion("paid not in", values, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidBetween(Integer value1, Integer value2) {
            addCriterion("paid between", value1, value2, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidNotBetween(Integer value1, Integer value2) {
            addCriterion("paid not between", value1, value2, "paid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andClientIsNull() {
            addCriterion("client is null");
            return (Criteria) this;
        }

        public Criteria andClientIsNotNull() {
            addCriterion("client is not null");
            return (Criteria) this;
        }

        public Criteria andClientEqualTo(String value) {
            addCriterion("client =", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientNotEqualTo(String value) {
            addCriterion("client <>", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientGreaterThan(String value) {
            addCriterion("client >", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientGreaterThanOrEqualTo(String value) {
            addCriterion("client >=", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientLessThan(String value) {
            addCriterion("client <", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientLessThanOrEqualTo(String value) {
            addCriterion("client <=", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientLike(String value) {
            addCriterion("client like", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientNotLike(String value) {
            addCriterion("client not like", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientIn(List<String> values) {
            addCriterion("client in", values, "client");
            return (Criteria) this;
        }

        public Criteria andClientNotIn(List<String> values) {
            addCriterion("client not in", values, "client");
            return (Criteria) this;
        }

        public Criteria andClientBetween(String value1, String value2) {
            addCriterion("client between", value1, value2, "client");
            return (Criteria) this;
        }

        public Criteria andClientNotBetween(String value1, String value2) {
            addCriterion("client not between", value1, value2, "client");
            return (Criteria) this;
        }

        public Criteria andClientManagerIsNull() {
            addCriterion("client_manager is null");
            return (Criteria) this;
        }

        public Criteria andClientManagerIsNotNull() {
            addCriterion("client_manager is not null");
            return (Criteria) this;
        }

        public Criteria andClientManagerEqualTo(String value) {
            addCriterion("client_manager =", value, "clientManager");
            return (Criteria) this;
        }

        public Criteria andClientManagerNotEqualTo(String value) {
            addCriterion("client_manager <>", value, "clientManager");
            return (Criteria) this;
        }

        public Criteria andClientManagerGreaterThan(String value) {
            addCriterion("client_manager >", value, "clientManager");
            return (Criteria) this;
        }

        public Criteria andClientManagerGreaterThanOrEqualTo(String value) {
            addCriterion("client_manager >=", value, "clientManager");
            return (Criteria) this;
        }

        public Criteria andClientManagerLessThan(String value) {
            addCriterion("client_manager <", value, "clientManager");
            return (Criteria) this;
        }

        public Criteria andClientManagerLessThanOrEqualTo(String value) {
            addCriterion("client_manager <=", value, "clientManager");
            return (Criteria) this;
        }

        public Criteria andClientManagerLike(String value) {
            addCriterion("client_manager like", value, "clientManager");
            return (Criteria) this;
        }

        public Criteria andClientManagerNotLike(String value) {
            addCriterion("client_manager not like", value, "clientManager");
            return (Criteria) this;
        }

        public Criteria andClientManagerIn(List<String> values) {
            addCriterion("client_manager in", values, "clientManager");
            return (Criteria) this;
        }

        public Criteria andClientManagerNotIn(List<String> values) {
            addCriterion("client_manager not in", values, "clientManager");
            return (Criteria) this;
        }

        public Criteria andClientManagerBetween(String value1, String value2) {
            addCriterion("client_manager between", value1, value2, "clientManager");
            return (Criteria) this;
        }

        public Criteria andClientManagerNotBetween(String value1, String value2) {
            addCriterion("client_manager not between", value1, value2, "clientManager");
            return (Criteria) this;
        }

        public Criteria andClientManagerPhoneIsNull() {
            addCriterion("client_manager_phone is null");
            return (Criteria) this;
        }

        public Criteria andClientManagerPhoneIsNotNull() {
            addCriterion("client_manager_phone is not null");
            return (Criteria) this;
        }

        public Criteria andClientManagerPhoneEqualTo(String value) {
            addCriterion("client_manager_phone =", value, "clientManagerPhone");
            return (Criteria) this;
        }

        public Criteria andClientManagerPhoneNotEqualTo(String value) {
            addCriterion("client_manager_phone <>", value, "clientManagerPhone");
            return (Criteria) this;
        }

        public Criteria andClientManagerPhoneGreaterThan(String value) {
            addCriterion("client_manager_phone >", value, "clientManagerPhone");
            return (Criteria) this;
        }

        public Criteria andClientManagerPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("client_manager_phone >=", value, "clientManagerPhone");
            return (Criteria) this;
        }

        public Criteria andClientManagerPhoneLessThan(String value) {
            addCriterion("client_manager_phone <", value, "clientManagerPhone");
            return (Criteria) this;
        }

        public Criteria andClientManagerPhoneLessThanOrEqualTo(String value) {
            addCriterion("client_manager_phone <=", value, "clientManagerPhone");
            return (Criteria) this;
        }

        public Criteria andClientManagerPhoneLike(String value) {
            addCriterion("client_manager_phone like", value, "clientManagerPhone");
            return (Criteria) this;
        }

        public Criteria andClientManagerPhoneNotLike(String value) {
            addCriterion("client_manager_phone not like", value, "clientManagerPhone");
            return (Criteria) this;
        }

        public Criteria andClientManagerPhoneIn(List<String> values) {
            addCriterion("client_manager_phone in", values, "clientManagerPhone");
            return (Criteria) this;
        }

        public Criteria andClientManagerPhoneNotIn(List<String> values) {
            addCriterion("client_manager_phone not in", values, "clientManagerPhone");
            return (Criteria) this;
        }

        public Criteria andClientManagerPhoneBetween(String value1, String value2) {
            addCriterion("client_manager_phone between", value1, value2, "clientManagerPhone");
            return (Criteria) this;
        }

        public Criteria andClientManagerPhoneNotBetween(String value1, String value2) {
            addCriterion("client_manager_phone not between", value1, value2, "clientManagerPhone");
            return (Criteria) this;
        }

        public Criteria andConsultantIsNull() {
            addCriterion("consultant is null");
            return (Criteria) this;
        }

        public Criteria andConsultantIsNotNull() {
            addCriterion("consultant is not null");
            return (Criteria) this;
        }

        public Criteria andConsultantEqualTo(String value) {
            addCriterion("consultant =", value, "consultant");
            return (Criteria) this;
        }

        public Criteria andConsultantNotEqualTo(String value) {
            addCriterion("consultant <>", value, "consultant");
            return (Criteria) this;
        }

        public Criteria andConsultantGreaterThan(String value) {
            addCriterion("consultant >", value, "consultant");
            return (Criteria) this;
        }

        public Criteria andConsultantGreaterThanOrEqualTo(String value) {
            addCriterion("consultant >=", value, "consultant");
            return (Criteria) this;
        }

        public Criteria andConsultantLessThan(String value) {
            addCriterion("consultant <", value, "consultant");
            return (Criteria) this;
        }

        public Criteria andConsultantLessThanOrEqualTo(String value) {
            addCriterion("consultant <=", value, "consultant");
            return (Criteria) this;
        }

        public Criteria andConsultantLike(String value) {
            addCriterion("consultant like", value, "consultant");
            return (Criteria) this;
        }

        public Criteria andConsultantNotLike(String value) {
            addCriterion("consultant not like", value, "consultant");
            return (Criteria) this;
        }

        public Criteria andConsultantIn(List<String> values) {
            addCriterion("consultant in", values, "consultant");
            return (Criteria) this;
        }

        public Criteria andConsultantNotIn(List<String> values) {
            addCriterion("consultant not in", values, "consultant");
            return (Criteria) this;
        }

        public Criteria andConsultantBetween(String value1, String value2) {
            addCriterion("consultant between", value1, value2, "consultant");
            return (Criteria) this;
        }

        public Criteria andConsultantNotBetween(String value1, String value2) {
            addCriterion("consultant not between", value1, value2, "consultant");
            return (Criteria) this;
        }

        public Criteria andThridIsNull() {
            addCriterion("thrid is null");
            return (Criteria) this;
        }

        public Criteria andThridIsNotNull() {
            addCriterion("thrid is not null");
            return (Criteria) this;
        }

        public Criteria andThridEqualTo(String value) {
            addCriterion("thrid =", value, "thrid");
            return (Criteria) this;
        }

        public Criteria andThridNotEqualTo(String value) {
            addCriterion("thrid <>", value, "thrid");
            return (Criteria) this;
        }

        public Criteria andThridGreaterThan(String value) {
            addCriterion("thrid >", value, "thrid");
            return (Criteria) this;
        }

        public Criteria andThridGreaterThanOrEqualTo(String value) {
            addCriterion("thrid >=", value, "thrid");
            return (Criteria) this;
        }

        public Criteria andThridLessThan(String value) {
            addCriterion("thrid <", value, "thrid");
            return (Criteria) this;
        }

        public Criteria andThridLessThanOrEqualTo(String value) {
            addCriterion("thrid <=", value, "thrid");
            return (Criteria) this;
        }

        public Criteria andThridLike(String value) {
            addCriterion("thrid like", value, "thrid");
            return (Criteria) this;
        }

        public Criteria andThridNotLike(String value) {
            addCriterion("thrid not like", value, "thrid");
            return (Criteria) this;
        }

        public Criteria andThridIn(List<String> values) {
            addCriterion("thrid in", values, "thrid");
            return (Criteria) this;
        }

        public Criteria andThridNotIn(List<String> values) {
            addCriterion("thrid not in", values, "thrid");
            return (Criteria) this;
        }

        public Criteria andThridBetween(String value1, String value2) {
            addCriterion("thrid between", value1, value2, "thrid");
            return (Criteria) this;
        }

        public Criteria andThridNotBetween(String value1, String value2) {
            addCriterion("thrid not between", value1, value2, "thrid");
            return (Criteria) this;
        }

        public Criteria andScaleIsNull() {
            addCriterion("scale is null");
            return (Criteria) this;
        }

        public Criteria andScaleIsNotNull() {
            addCriterion("scale is not null");
            return (Criteria) this;
        }

        public Criteria andScaleEqualTo(String value) {
            addCriterion("scale =", value, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleNotEqualTo(String value) {
            addCriterion("scale <>", value, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleGreaterThan(String value) {
            addCriterion("scale >", value, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleGreaterThanOrEqualTo(String value) {
            addCriterion("scale >=", value, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleLessThan(String value) {
            addCriterion("scale <", value, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleLessThanOrEqualTo(String value) {
            addCriterion("scale <=", value, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleLike(String value) {
            addCriterion("scale like", value, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleNotLike(String value) {
            addCriterion("scale not like", value, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleIn(List<String> values) {
            addCriterion("scale in", values, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleNotIn(List<String> values) {
            addCriterion("scale not in", values, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleBetween(String value1, String value2) {
            addCriterion("scale between", value1, value2, "scale");
            return (Criteria) this;
        }

        public Criteria andScaleNotBetween(String value1, String value2) {
            addCriterion("scale not between", value1, value2, "scale");
            return (Criteria) this;
        }

        public Criteria andPlaceIsNull() {
            addCriterion("place is null");
            return (Criteria) this;
        }

        public Criteria andPlaceIsNotNull() {
            addCriterion("place is not null");
            return (Criteria) this;
        }

        public Criteria andPlaceEqualTo(String value) {
            addCriterion("place =", value, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceNotEqualTo(String value) {
            addCriterion("place <>", value, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceGreaterThan(String value) {
            addCriterion("place >", value, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceGreaterThanOrEqualTo(String value) {
            addCriterion("place >=", value, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceLessThan(String value) {
            addCriterion("place <", value, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceLessThanOrEqualTo(String value) {
            addCriterion("place <=", value, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceLike(String value) {
            addCriterion("place like", value, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceNotLike(String value) {
            addCriterion("place not like", value, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceIn(List<String> values) {
            addCriterion("place in", values, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceNotIn(List<String> values) {
            addCriterion("place not in", values, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceBetween(String value1, String value2) {
            addCriterion("place between", value1, value2, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceNotBetween(String value1, String value2) {
            addCriterion("place not between", value1, value2, "place");
            return (Criteria) this;
        }

        public Criteria andInvestSumIsNull() {
            addCriterion("invest_sum is null");
            return (Criteria) this;
        }

        public Criteria andInvestSumIsNotNull() {
            addCriterion("invest_sum is not null");
            return (Criteria) this;
        }

        public Criteria andInvestSumEqualTo(String value) {
            addCriterion("invest_sum =", value, "investSum");
            return (Criteria) this;
        }

        public Criteria andInvestSumNotEqualTo(String value) {
            addCriterion("invest_sum <>", value, "investSum");
            return (Criteria) this;
        }

        public Criteria andInvestSumGreaterThan(String value) {
            addCriterion("invest_sum >", value, "investSum");
            return (Criteria) this;
        }

        public Criteria andInvestSumGreaterThanOrEqualTo(String value) {
            addCriterion("invest_sum >=", value, "investSum");
            return (Criteria) this;
        }

        public Criteria andInvestSumLessThan(String value) {
            addCriterion("invest_sum <", value, "investSum");
            return (Criteria) this;
        }

        public Criteria andInvestSumLessThanOrEqualTo(String value) {
            addCriterion("invest_sum <=", value, "investSum");
            return (Criteria) this;
        }

        public Criteria andInvestSumLike(String value) {
            addCriterion("invest_sum like", value, "investSum");
            return (Criteria) this;
        }

        public Criteria andInvestSumNotLike(String value) {
            addCriterion("invest_sum not like", value, "investSum");
            return (Criteria) this;
        }

        public Criteria andInvestSumIn(List<String> values) {
            addCriterion("invest_sum in", values, "investSum");
            return (Criteria) this;
        }

        public Criteria andInvestSumNotIn(List<String> values) {
            addCriterion("invest_sum not in", values, "investSum");
            return (Criteria) this;
        }

        public Criteria andInvestSumBetween(String value1, String value2) {
            addCriterion("invest_sum between", value1, value2, "investSum");
            return (Criteria) this;
        }

        public Criteria andInvestSumNotBetween(String value1, String value2) {
            addCriterion("invest_sum not between", value1, value2, "investSum");
            return (Criteria) this;
        }

        public Criteria andContractSumIsNull() {
            addCriterion("contract_sum is null");
            return (Criteria) this;
        }

        public Criteria andContractSumIsNotNull() {
            addCriterion("contract_sum is not null");
            return (Criteria) this;
        }

        public Criteria andContractSumEqualTo(String value) {
            addCriterion("contract_sum =", value, "contractSum");
            return (Criteria) this;
        }

        public Criteria andContractSumNotEqualTo(String value) {
            addCriterion("contract_sum <>", value, "contractSum");
            return (Criteria) this;
        }

        public Criteria andContractSumGreaterThan(String value) {
            addCriterion("contract_sum >", value, "contractSum");
            return (Criteria) this;
        }

        public Criteria andContractSumGreaterThanOrEqualTo(String value) {
            addCriterion("contract_sum >=", value, "contractSum");
            return (Criteria) this;
        }

        public Criteria andContractSumLessThan(String value) {
            addCriterion("contract_sum <", value, "contractSum");
            return (Criteria) this;
        }

        public Criteria andContractSumLessThanOrEqualTo(String value) {
            addCriterion("contract_sum <=", value, "contractSum");
            return (Criteria) this;
        }

        public Criteria andContractSumLike(String value) {
            addCriterion("contract_sum like", value, "contractSum");
            return (Criteria) this;
        }

        public Criteria andContractSumNotLike(String value) {
            addCriterion("contract_sum not like", value, "contractSum");
            return (Criteria) this;
        }

        public Criteria andContractSumIn(List<String> values) {
            addCriterion("contract_sum in", values, "contractSum");
            return (Criteria) this;
        }

        public Criteria andContractSumNotIn(List<String> values) {
            addCriterion("contract_sum not in", values, "contractSum");
            return (Criteria) this;
        }

        public Criteria andContractSumBetween(String value1, String value2) {
            addCriterion("contract_sum between", value1, value2, "contractSum");
            return (Criteria) this;
        }

        public Criteria andContractSumNotBetween(String value1, String value2) {
            addCriterion("contract_sum not between", value1, value2, "contractSum");
            return (Criteria) this;
        }

        public Criteria andContractManagerIsNull() {
            addCriterion("contract_manager is null");
            return (Criteria) this;
        }

        public Criteria andContractManagerIsNotNull() {
            addCriterion("contract_manager is not null");
            return (Criteria) this;
        }

        public Criteria andContractManagerEqualTo(String value) {
            addCriterion("contract_manager =", value, "contractManager");
            return (Criteria) this;
        }

        public Criteria andContractManagerNotEqualTo(String value) {
            addCriterion("contract_manager <>", value, "contractManager");
            return (Criteria) this;
        }

        public Criteria andContractManagerGreaterThan(String value) {
            addCriterion("contract_manager >", value, "contractManager");
            return (Criteria) this;
        }

        public Criteria andContractManagerGreaterThanOrEqualTo(String value) {
            addCriterion("contract_manager >=", value, "contractManager");
            return (Criteria) this;
        }

        public Criteria andContractManagerLessThan(String value) {
            addCriterion("contract_manager <", value, "contractManager");
            return (Criteria) this;
        }

        public Criteria andContractManagerLessThanOrEqualTo(String value) {
            addCriterion("contract_manager <=", value, "contractManager");
            return (Criteria) this;
        }

        public Criteria andContractManagerLike(String value) {
            addCriterion("contract_manager like", value, "contractManager");
            return (Criteria) this;
        }

        public Criteria andContractManagerNotLike(String value) {
            addCriterion("contract_manager not like", value, "contractManager");
            return (Criteria) this;
        }

        public Criteria andContractManagerIn(List<String> values) {
            addCriterion("contract_manager in", values, "contractManager");
            return (Criteria) this;
        }

        public Criteria andContractManagerNotIn(List<String> values) {
            addCriterion("contract_manager not in", values, "contractManager");
            return (Criteria) this;
        }

        public Criteria andContractManagerBetween(String value1, String value2) {
            addCriterion("contract_manager between", value1, value2, "contractManager");
            return (Criteria) this;
        }

        public Criteria andContractManagerNotBetween(String value1, String value2) {
            addCriterion("contract_manager not between", value1, value2, "contractManager");
            return (Criteria) this;
        }

        public Criteria andContractTimeIsNull() {
            addCriterion("contract_time is null");
            return (Criteria) this;
        }

        public Criteria andContractTimeIsNotNull() {
            addCriterion("contract_time is not null");
            return (Criteria) this;
        }

        public Criteria andContractTimeEqualTo(Integer value) {
            addCriterion("contract_time =", value, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeNotEqualTo(Integer value) {
            addCriterion("contract_time <>", value, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeGreaterThan(Integer value) {
            addCriterion("contract_time >", value, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("contract_time >=", value, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeLessThan(Integer value) {
            addCriterion("contract_time <", value, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeLessThanOrEqualTo(Integer value) {
            addCriterion("contract_time <=", value, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeIn(List<Integer> values) {
            addCriterion("contract_time in", values, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeNotIn(List<Integer> values) {
            addCriterion("contract_time not in", values, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeBetween(Integer value1, Integer value2) {
            addCriterion("contract_time between", value1, value2, "contractTime");
            return (Criteria) this;
        }

        public Criteria andContractTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("contract_time not between", value1, value2, "contractTime");
            return (Criteria) this;
        }

        public Criteria andManagerIsNull() {
            addCriterion("manager is null");
            return (Criteria) this;
        }

        public Criteria andManagerIsNotNull() {
            addCriterion("manager is not null");
            return (Criteria) this;
        }

        public Criteria andManagerEqualTo(String value) {
            addCriterion("manager =", value, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerNotEqualTo(String value) {
            addCriterion("manager <>", value, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerGreaterThan(String value) {
            addCriterion("manager >", value, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerGreaterThanOrEqualTo(String value) {
            addCriterion("manager >=", value, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerLessThan(String value) {
            addCriterion("manager <", value, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerLessThanOrEqualTo(String value) {
            addCriterion("manager <=", value, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerLike(String value) {
            addCriterion("manager like", value, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerNotLike(String value) {
            addCriterion("manager not like", value, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerIn(List<String> values) {
            addCriterion("manager in", values, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerNotIn(List<String> values) {
            addCriterion("manager not in", values, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerBetween(String value1, String value2) {
            addCriterion("manager between", value1, value2, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerNotBetween(String value1, String value2) {
            addCriterion("manager not between", value1, value2, "manager");
            return (Criteria) this;
        }

        public Criteria andDeidIsNull() {
            addCriterion("deid is null");
            return (Criteria) this;
        }

        public Criteria andDeidIsNotNull() {
            addCriterion("deid is not null");
            return (Criteria) this;
        }

        public Criteria andDeidEqualTo(Integer value) {
            addCriterion("deid =", value, "deid");
            return (Criteria) this;
        }

        public Criteria andDeidNotEqualTo(Integer value) {
            addCriterion("deid <>", value, "deid");
            return (Criteria) this;
        }

        public Criteria andDeidGreaterThan(Integer value) {
            addCriterion("deid >", value, "deid");
            return (Criteria) this;
        }

        public Criteria andDeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("deid >=", value, "deid");
            return (Criteria) this;
        }

        public Criteria andDeidLessThan(Integer value) {
            addCriterion("deid <", value, "deid");
            return (Criteria) this;
        }

        public Criteria andDeidLessThanOrEqualTo(Integer value) {
            addCriterion("deid <=", value, "deid");
            return (Criteria) this;
        }

        public Criteria andDeidIn(List<Integer> values) {
            addCriterion("deid in", values, "deid");
            return (Criteria) this;
        }

        public Criteria andDeidNotIn(List<Integer> values) {
            addCriterion("deid not in", values, "deid");
            return (Criteria) this;
        }

        public Criteria andDeidBetween(Integer value1, Integer value2) {
            addCriterion("deid between", value1, value2, "deid");
            return (Criteria) this;
        }

        public Criteria andDeidNotBetween(Integer value1, Integer value2) {
            addCriterion("deid not between", value1, value2, "deid");
            return (Criteria) this;
        }

        public Criteria andNumberIsNull() {
            addCriterion("number is null");
            return (Criteria) this;
        }

        public Criteria andNumberIsNotNull() {
            addCriterion("number is not null");
            return (Criteria) this;
        }

        public Criteria andNumberEqualTo(String value) {
            addCriterion("number =", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotEqualTo(String value) {
            addCriterion("number <>", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThan(String value) {
            addCriterion("number >", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThanOrEqualTo(String value) {
            addCriterion("number >=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThan(String value) {
            addCriterion("number <", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThanOrEqualTo(String value) {
            addCriterion("number <=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLike(String value) {
            addCriterion("number like", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotLike(String value) {
            addCriterion("number not like", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberIn(List<String> values) {
            addCriterion("number in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotIn(List<String> values) {
            addCriterion("number not in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberBetween(String value1, String value2) {
            addCriterion("number between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotBetween(String value1, String value2) {
            addCriterion("number not between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Integer value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Integer value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Integer value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Integer value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Integer value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Integer> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Integer> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Integer value1, Integer value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andUpTimeIsNull() {
            addCriterion("up_time is null");
            return (Criteria) this;
        }

        public Criteria andUpTimeIsNotNull() {
            addCriterion("up_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpTimeEqualTo(Integer value) {
            addCriterion("up_time =", value, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeNotEqualTo(Integer value) {
            addCriterion("up_time <>", value, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeGreaterThan(Integer value) {
            addCriterion("up_time >", value, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("up_time >=", value, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeLessThan(Integer value) {
            addCriterion("up_time <", value, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeLessThanOrEqualTo(Integer value) {
            addCriterion("up_time <=", value, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeIn(List<Integer> values) {
            addCriterion("up_time in", values, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeNotIn(List<Integer> values) {
            addCriterion("up_time not in", values, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeBetween(Integer value1, Integer value2) {
            addCriterion("up_time between", value1, value2, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("up_time not between", value1, value2, "upTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andFinanceStatusIsNull() {
            addCriterion("finance_status is null");
            return (Criteria) this;
        }

        public Criteria andFinanceStatusIsNotNull() {
            addCriterion("finance_status is not null");
            return (Criteria) this;
        }

        public Criteria andFinanceStatusEqualTo(Boolean value) {
            addCriterion("finance_status =", value, "financeStatus");
            return (Criteria) this;
        }

        public Criteria andFinanceStatusNotEqualTo(Boolean value) {
            addCriterion("finance_status <>", value, "financeStatus");
            return (Criteria) this;
        }

        public Criteria andFinanceStatusGreaterThan(Boolean value) {
            addCriterion("finance_status >", value, "financeStatus");
            return (Criteria) this;
        }

        public Criteria andFinanceStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("finance_status >=", value, "financeStatus");
            return (Criteria) this;
        }

        public Criteria andFinanceStatusLessThan(Boolean value) {
            addCriterion("finance_status <", value, "financeStatus");
            return (Criteria) this;
        }

        public Criteria andFinanceStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("finance_status <=", value, "financeStatus");
            return (Criteria) this;
        }

        public Criteria andFinanceStatusIn(List<Boolean> values) {
            addCriterion("finance_status in", values, "financeStatus");
            return (Criteria) this;
        }

        public Criteria andFinanceStatusNotIn(List<Boolean> values) {
            addCriterion("finance_status not in", values, "financeStatus");
            return (Criteria) this;
        }

        public Criteria andFinanceStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("finance_status between", value1, value2, "financeStatus");
            return (Criteria) this;
        }

        public Criteria andFinanceStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("finance_status not between", value1, value2, "financeStatus");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andProjectContractNumIsNull() {
            addCriterion("project_contract_num is null");
            return (Criteria) this;
        }

        public Criteria andProjectContractNumIsNotNull() {
            addCriterion("project_contract_num is not null");
            return (Criteria) this;
        }

        public Criteria andProjectContractNumEqualTo(String value) {
            addCriterion("project_contract_num =", value, "projectContractNum");
            return (Criteria) this;
        }

        public Criteria andProjectContractNumNotEqualTo(String value) {
            addCriterion("project_contract_num <>", value, "projectContractNum");
            return (Criteria) this;
        }

        public Criteria andProjectContractNumGreaterThan(String value) {
            addCriterion("project_contract_num >", value, "projectContractNum");
            return (Criteria) this;
        }

        public Criteria andProjectContractNumGreaterThanOrEqualTo(String value) {
            addCriterion("project_contract_num >=", value, "projectContractNum");
            return (Criteria) this;
        }

        public Criteria andProjectContractNumLessThan(String value) {
            addCriterion("project_contract_num <", value, "projectContractNum");
            return (Criteria) this;
        }

        public Criteria andProjectContractNumLessThanOrEqualTo(String value) {
            addCriterion("project_contract_num <=", value, "projectContractNum");
            return (Criteria) this;
        }

        public Criteria andProjectContractNumLike(String value) {
            addCriterion("project_contract_num like", value, "projectContractNum");
            return (Criteria) this;
        }

        public Criteria andProjectContractNumNotLike(String value) {
            addCriterion("project_contract_num not like", value, "projectContractNum");
            return (Criteria) this;
        }

        public Criteria andProjectContractNumIn(List<String> values) {
            addCriterion("project_contract_num in", values, "projectContractNum");
            return (Criteria) this;
        }

        public Criteria andProjectContractNumNotIn(List<String> values) {
            addCriterion("project_contract_num not in", values, "projectContractNum");
            return (Criteria) this;
        }

        public Criteria andProjectContractNumBetween(String value1, String value2) {
            addCriterion("project_contract_num between", value1, value2, "projectContractNum");
            return (Criteria) this;
        }

        public Criteria andProjectContractNumNotBetween(String value1, String value2) {
            addCriterion("project_contract_num not between", value1, value2, "projectContractNum");
            return (Criteria) this;
        }
    }

    /**
     * old_project_info_to_archive
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * old_project_info_to_archive null
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}