package com.hd.common.dao;

import com.hd.common.entity.TbContractSaveMaterialRelationEntity;
import com.hd.common.entity.TbContractSaveMaterialRelationEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbContractSaveMaterialRelationEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_save_material_relation
     *
     * @mbg.generated
     */
    long countByExample(TbContractSaveMaterialRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_save_material_relation
     *
     * @mbg.generated
     */
    int deleteByExample(TbContractSaveMaterialRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_save_material_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_save_material_relation
     *
     * @mbg.generated
     */
    int insert(TbContractSaveMaterialRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_save_material_relation
     *
     * @mbg.generated
     */
    int insertSelective(TbContractSaveMaterialRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_save_material_relation
     *
     * @mbg.generated
     */
    List<TbContractSaveMaterialRelationEntity> selectByExample(TbContractSaveMaterialRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_save_material_relation
     *
     * @mbg.generated
     */
    TbContractSaveMaterialRelationEntity selectByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_save_material_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbContractSaveMaterialRelationEntity record, @Param("example") TbContractSaveMaterialRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_save_material_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbContractSaveMaterialRelationEntity record, @Param("example") TbContractSaveMaterialRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_save_material_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbContractSaveMaterialRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_save_material_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbContractSaveMaterialRelationEntity record);
}