package com.hd.common.dao;

import com.hd.common.entity.TbContractHisTaskInstEntity;
import com.hd.common.entity.TbContractHisTaskInstEntityExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbContractHisTaskInstEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_his_task_inst
     *
     * @mbg.generated
     */
    long countByExample(TbContractHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_his_task_inst
     *
     * @mbg.generated
     */
    int deleteByExample(TbContractHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_his_task_inst
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_his_task_inst
     *
     * @mbg.generated
     */
    int insert(TbContractHisTaskInstEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_his_task_inst
     *
     * @mbg.generated
     */
    int insertSelective(TbContractHisTaskInstEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_his_task_inst
     *
     * @mbg.generated
     */
    List<TbContractHisTaskInstEntity> selectByExample(TbContractHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_his_task_inst
     *
     * @mbg.generated
     */
    TbContractHisTaskInstEntity selectByPrimaryKey(String historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_his_task_inst
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbContractHisTaskInstEntity record, @Param("example") TbContractHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_his_task_inst
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbContractHisTaskInstEntity record, @Param("example") TbContractHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_his_task_inst
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbContractHisTaskInstEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_his_task_inst
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbContractHisTaskInstEntity record);
}