package com.hd.common.dao;

import com.hd.common.entity.TbExpertOpinionRelationEntity;
import com.hd.common.entity.TbExpertOpinionRelationEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbExpertOpinionRelationEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    long countByExample(TbExpertOpinionRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    int deleteByExample(TbExpertOpinionRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String expertOpinionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    int insert(TbExpertOpinionRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    int insertSelective(TbExpertOpinionRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    List<TbExpertOpinionRelationEntity> selectByExample(TbExpertOpinionRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    TbExpertOpinionRelationEntity selectByPrimaryKey(String expertOpinionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbExpertOpinionRelationEntity record, @Param("example") TbExpertOpinionRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbExpertOpinionRelationEntity record, @Param("example") TbExpertOpinionRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbExpertOpinionRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert_opinion_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbExpertOpinionRelationEntity record);
}