package com.hd.common.dao;

import com.hd.common.entity.TbFailTenderUserRelationEntity;
import com.hd.common.entity.TbFailTenderUserRelationEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbFailTenderUserRelationEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_user_relation
     *
     * @mbg.generated
     */
    long countByExample(TbFailTenderUserRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_user_relation
     *
     * @mbg.generated
     */
    int deleteByExample(TbFailTenderUserRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_user_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_user_relation
     *
     * @mbg.generated
     */
    int insert(TbFailTenderUserRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_user_relation
     *
     * @mbg.generated
     */
    int insertSelective(TbFailTenderUserRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_user_relation
     *
     * @mbg.generated
     */
    List<TbFailTenderUserRelationEntity> selectByExample(TbFailTenderUserRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_user_relation
     *
     * @mbg.generated
     */
    TbFailTenderUserRelationEntity selectByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_user_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbFailTenderUserRelationEntity record, @Param("example") TbFailTenderUserRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_user_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbFailTenderUserRelationEntity record, @Param("example") TbFailTenderUserRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_user_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbFailTenderUserRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_user_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbFailTenderUserRelationEntity record);
}