package com.hd.common.dao;

import com.hd.common.entity.TbFailTenderNoticeRelationEntity;
import com.hd.common.entity.TbFailTenderNoticeRelationEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbFailTenderNoticeRelationEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_notice_relation
     *
     * @mbg.generated
     */
    long countByExample(TbFailTenderNoticeRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_notice_relation
     *
     * @mbg.generated
     */
    int deleteByExample(TbFailTenderNoticeRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_notice_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String noticeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_notice_relation
     *
     * @mbg.generated
     */
    int insert(TbFailTenderNoticeRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_notice_relation
     *
     * @mbg.generated
     */
    int insertSelective(TbFailTenderNoticeRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_notice_relation
     *
     * @mbg.generated
     */
    List<TbFailTenderNoticeRelationEntity> selectByExample(TbFailTenderNoticeRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_notice_relation
     *
     * @mbg.generated
     */
    TbFailTenderNoticeRelationEntity selectByPrimaryKey(String noticeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_notice_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbFailTenderNoticeRelationEntity record, @Param("example") TbFailTenderNoticeRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_notice_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbFailTenderNoticeRelationEntity record, @Param("example") TbFailTenderNoticeRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_notice_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbFailTenderNoticeRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_fail_tender_notice_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbFailTenderNoticeRelationEntity record);
}