package com.hd.common.dao;

import com.hd.common.entity.TbFileConfirmOpinionRelationEntity;
import com.hd.common.entity.TbFileConfirmOpinionRelationEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbFileConfirmOpinionRelationEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_confirm_opinion_relation
     *
     * @mbg.generated
     */
    long countByExample(TbFileConfirmOpinionRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_confirm_opinion_relation
     *
     * @mbg.generated
     */
    int deleteByExample(TbFileConfirmOpinionRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_confirm_opinion_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String confirmOpinionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_confirm_opinion_relation
     *
     * @mbg.generated
     */
    int insert(TbFileConfirmOpinionRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_confirm_opinion_relation
     *
     * @mbg.generated
     */
    int insertSelective(TbFileConfirmOpinionRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_confirm_opinion_relation
     *
     * @mbg.generated
     */
    List<TbFileConfirmOpinionRelationEntity> selectByExample(TbFileConfirmOpinionRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_confirm_opinion_relation
     *
     * @mbg.generated
     */
    TbFileConfirmOpinionRelationEntity selectByPrimaryKey(String confirmOpinionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_confirm_opinion_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbFileConfirmOpinionRelationEntity record, @Param("example") TbFileConfirmOpinionRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_confirm_opinion_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbFileConfirmOpinionRelationEntity record, @Param("example") TbFileConfirmOpinionRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_confirm_opinion_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbFileConfirmOpinionRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_file_confirm_opinion_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbFileConfirmOpinionRelationEntity record);
}