package com.hd.common.dao;

import com.hd.common.entity.TbJobEntity;
import com.hd.common.entity.TbJobEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbJobEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_job
     *
     * @mbg.generated
     */
    long countByExample(TbJobEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_job
     *
     * @mbg.generated
     */
    int deleteByExample(TbJobEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_job
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_job
     *
     * @mbg.generated
     */
    int insert(TbJobEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_job
     *
     * @mbg.generated
     */
    int insertSelective(TbJobEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_job
     *
     * @mbg.generated
     */
    List<TbJobEntity> selectByExample(TbJobEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_job
     *
     * @mbg.generated
     */
    TbJobEntity selectByPrimaryKey(String jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_job
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbJobEntity record, @Param("example") TbJobEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_job
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbJobEntity record, @Param("example") TbJobEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbJobEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbJobEntity record);
}