package com.hd.common.dao;

import com.hd.common.entity.TbProEstimateEntity;
import com.hd.common.entity.TbProEstimateEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbProcessEstimateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_estimate
     *
     * @mbg.generated
     */
    long countByExample(TbProEstimateEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_estimate
     *
     * @mbg.generated
     */
    int deleteByExample(TbProEstimateEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_estimate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String estimateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_estimate
     *
     * @mbg.generated
     */
    int insert(TbProEstimateEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_estimate
     *
     * @mbg.generated
     */
    int insertSelective(TbProEstimateEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_estimate
     *
     * @mbg.generated
     */
    List<TbProEstimateEntity> selectByExample(TbProEstimateEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_estimate
     *
     * @mbg.generated
     */
    TbProEstimateEntity selectByPrimaryKey(String estimateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_estimate
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbProEstimateEntity record, @Param("example") TbProEstimateEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_estimate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbProEstimateEntity record, @Param("example") TbProEstimateEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_estimate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbProEstimateEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_estimate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbProEstimateEntity record);
}