package com.hd.common.dao;

import com.hd.common.entity.TbProClaimEntity;
import com.hd.common.entity.TbProClaimEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbProcessClaimMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    long countByExample(TbProClaimEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    int deleteByExample(TbProClaimEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String claimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    int insert(TbProClaimEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    int insertSelective(TbProClaimEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    List<TbProClaimEntity> selectByExample(TbProClaimEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    TbProClaimEntity selectByPrimaryKey(String claimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbProClaimEntity record, @Param("example") TbProClaimEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbProClaimEntity record, @Param("example") TbProClaimEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbProClaimEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pro_claim
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbProClaimEntity record);
}