package com.hd.common.dao;

import com.hd.common.entity.TbProjectProcessRelationEntity;
import com.hd.common.entity.TbProjectProcessRelationEntityExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbProjectProcessRelationEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_project_process_relation
     *
     * @mbg.generated
     */
    long countByExample(TbProjectProcessRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_project_process_relation
     *
     * @mbg.generated
     */
    int deleteByExample(TbProjectProcessRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_project_process_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("projectId") String projectId, @Param("processInstId") String processInstId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_project_process_relation
     *
     * @mbg.generated
     */
    int insert(TbProjectProcessRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_project_process_relation
     *
     * @mbg.generated
     */
    int insertSelective(TbProjectProcessRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_project_process_relation
     *
     * @mbg.generated
     */
    List<TbProjectProcessRelationEntity> selectByExample(TbProjectProcessRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_project_process_relation
     *
     * @mbg.generated
     */
    TbProjectProcessRelationEntity selectByPrimaryKey(@Param("projectId") String projectId, @Param("processInstId") String processInstId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_project_process_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbProjectProcessRelationEntity record, @Param("example") TbProjectProcessRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_project_process_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbProjectProcessRelationEntity record, @Param("example") TbProjectProcessRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_project_process_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbProjectProcessRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_project_process_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbProjectProcessRelationEntity record);
}