package com.hd.common.dao;

import com.hd.common.entity.TbRequestMenuHisTaskInstEntity;
import com.hd.common.entity.TbRequestMenuHisTaskInstEntityExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbRequestMenuHisTaskInstEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu_his_task_inst
     *
     * @mbg.generated
     */
    long countByExample(TbRequestMenuHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu_his_task_inst
     *
     * @mbg.generated
     */
    int deleteByExample(TbRequestMenuHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu_his_task_inst
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu_his_task_inst
     *
     * @mbg.generated
     */
    int insert(TbRequestMenuHisTaskInstEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu_his_task_inst
     *
     * @mbg.generated
     */
    int insertSelective(TbRequestMenuHisTaskInstEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu_his_task_inst
     *
     * @mbg.generated
     */
    List<TbRequestMenuHisTaskInstEntity> selectByExample(TbRequestMenuHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu_his_task_inst
     *
     * @mbg.generated
     */
    TbRequestMenuHisTaskInstEntity selectByPrimaryKey(String historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu_his_task_inst
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbRequestMenuHisTaskInstEntity record, @Param("example") TbRequestMenuHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu_his_task_inst
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbRequestMenuHisTaskInstEntity record, @Param("example") TbRequestMenuHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu_his_task_inst
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbRequestMenuHisTaskInstEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu_his_task_inst
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbRequestMenuHisTaskInstEntity record);
}