package com.hd.common.dao;

import com.hd.common.entity.TbRequestMenuEntity;
import com.hd.common.entity.TbRequestMenuEntityExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbRequestMenuEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu
     *
     * @mbg.generated
     */
    long countByExample(TbRequestMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu
     *
     * @mbg.generated
     */
    int deleteByExample(TbRequestMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String requestMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu
     *
     * @mbg.generated
     */
    int insert(TbRequestMenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu
     *
     * @mbg.generated
     */
    int insertSelective(TbRequestMenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu
     *
     * @mbg.generated
     */
    List<TbRequestMenuEntity> selectByExampleWithBLOBs(TbRequestMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu
     *
     * @mbg.generated
     */
    List<TbRequestMenuEntity> selectByExample(TbRequestMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu
     *
     * @mbg.generated
     */
    TbRequestMenuEntity selectByPrimaryKey(String requestMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbRequestMenuEntity record, @Param("example") TbRequestMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TbRequestMenuEntity record, @Param("example") TbRequestMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbRequestMenuEntity record, @Param("example") TbRequestMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbRequestMenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TbRequestMenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_request_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbRequestMenuEntity record);
}