package com.hd.common.dao;

import com.hd.common.entity.TbSaveMaterialHisTaskInstEntity;
import com.hd.common.entity.TbSaveMaterialHisTaskInstEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbSaveMaterialHisTaskInstEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_save_material_his_task_inst
     *
     * @mbg.generated
     */
    long countByExample(TbSaveMaterialHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_save_material_his_task_inst
     *
     * @mbg.generated
     */
    int deleteByExample(TbSaveMaterialHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_save_material_his_task_inst
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_save_material_his_task_inst
     *
     * @mbg.generated
     */
    int insert(TbSaveMaterialHisTaskInstEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_save_material_his_task_inst
     *
     * @mbg.generated
     */
    int insertSelective(TbSaveMaterialHisTaskInstEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_save_material_his_task_inst
     *
     * @mbg.generated
     */
    List<TbSaveMaterialHisTaskInstEntity> selectByExample(TbSaveMaterialHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_save_material_his_task_inst
     *
     * @mbg.generated
     */
    TbSaveMaterialHisTaskInstEntity selectByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_save_material_his_task_inst
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbSaveMaterialHisTaskInstEntity record, @Param("example") TbSaveMaterialHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_save_material_his_task_inst
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbSaveMaterialHisTaskInstEntity record, @Param("example") TbSaveMaterialHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_save_material_his_task_inst
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbSaveMaterialHisTaskInstEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_save_material_his_task_inst
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbSaveMaterialHisTaskInstEntity record);
}