package com.hd.common.dao;

import com.hd.common.entity.TbTableEightZbdlExpandEntity;
import com.hd.common.entity.TbTableEightZbdlExpandEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTableEightZbdlExpandEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_eight_zbdl_expand
     *
     * @mbg.generated
     */
    long countByExample(TbTableEightZbdlExpandEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_eight_zbdl_expand
     *
     * @mbg.generated
     */
    int deleteByExample(TbTableEightZbdlExpandEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_eight_zbdl_expand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_eight_zbdl_expand
     *
     * @mbg.generated
     */
    int insert(TbTableEightZbdlExpandEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_eight_zbdl_expand
     *
     * @mbg.generated
     */
    int insertSelective(TbTableEightZbdlExpandEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_eight_zbdl_expand
     *
     * @mbg.generated
     */
    List<TbTableEightZbdlExpandEntity> selectByExample(TbTableEightZbdlExpandEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_eight_zbdl_expand
     *
     * @mbg.generated
     */
    TbTableEightZbdlExpandEntity selectByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_eight_zbdl_expand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbTableEightZbdlExpandEntity record, @Param("example") TbTableEightZbdlExpandEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_eight_zbdl_expand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbTableEightZbdlExpandEntity record, @Param("example") TbTableEightZbdlExpandEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_eight_zbdl_expand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbTableEightZbdlExpandEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_table_eight_zbdl_expand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbTableEightZbdlExpandEntity record);
}