package com.hd.common.dao;

import com.hd.common.entity.TbTaskPeriodMaterialRelationEntity;
import com.hd.common.entity.TbTaskPeriodMaterialRelationEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTaskPeriodMaterialRelationEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_material_relation
     *
     * @mbg.generated
     */
    long countByExample(TbTaskPeriodMaterialRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_material_relation
     *
     * @mbg.generated
     */
    int deleteByExample(TbTaskPeriodMaterialRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_material_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_material_relation
     *
     * @mbg.generated
     */
    int insert(TbTaskPeriodMaterialRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_material_relation
     *
     * @mbg.generated
     */
    int insertSelective(TbTaskPeriodMaterialRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_material_relation
     *
     * @mbg.generated
     */
    List<TbTaskPeriodMaterialRelationEntity> selectByExample(TbTaskPeriodMaterialRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_material_relation
     *
     * @mbg.generated
     */
    TbTaskPeriodMaterialRelationEntity selectByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_material_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbTaskPeriodMaterialRelationEntity record, @Param("example") TbTaskPeriodMaterialRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_material_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbTaskPeriodMaterialRelationEntity record, @Param("example") TbTaskPeriodMaterialRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_material_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbTaskPeriodMaterialRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_period_material_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbTaskPeriodMaterialRelationEntity record);
}