package com.hd.common.dao;

import com.hd.common.entity.TbTaskSaveMaterialRelationEntity;
import com.hd.common.entity.TbTaskSaveMaterialRelationEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTaskSaveMaterialRelationEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_save_material_relation
     *
     * @mbg.generated
     */
    long countByExample(TbTaskSaveMaterialRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_save_material_relation
     *
     * @mbg.generated
     */
    int deleteByExample(TbTaskSaveMaterialRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_save_material_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_save_material_relation
     *
     * @mbg.generated
     */
    int insert(TbTaskSaveMaterialRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_save_material_relation
     *
     * @mbg.generated
     */
    int insertSelective(TbTaskSaveMaterialRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_save_material_relation
     *
     * @mbg.generated
     */
    List<TbTaskSaveMaterialRelationEntity> selectByExample(TbTaskSaveMaterialRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_save_material_relation
     *
     * @mbg.generated
     */
    TbTaskSaveMaterialRelationEntity selectByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_save_material_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbTaskSaveMaterialRelationEntity record, @Param("example") TbTaskSaveMaterialRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_save_material_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbTaskSaveMaterialRelationEntity record, @Param("example") TbTaskSaveMaterialRelationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_save_material_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbTaskSaveMaterialRelationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_save_material_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbTaskSaveMaterialRelationEntity record);
}