package com.hd.common.dao;

import com.hd.common.entity.TbTenderTaskPeriodMaterialEntity;
import com.hd.common.entity.TbTenderTaskPeriodMaterialEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTenderTaskPeriodMaterialEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_period_material
     *
     * @mbg.generated
     */
    long countByExample(TbTenderTaskPeriodMaterialEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_period_material
     *
     * @mbg.generated
     */
    int deleteByExample(TbTenderTaskPeriodMaterialEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_period_material
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_period_material
     *
     * @mbg.generated
     */
    int insert(TbTenderTaskPeriodMaterialEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_period_material
     *
     * @mbg.generated
     */
    int insertSelective(TbTenderTaskPeriodMaterialEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_period_material
     *
     * @mbg.generated
     */
    List<TbTenderTaskPeriodMaterialEntity> selectByExample(TbTenderTaskPeriodMaterialEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_period_material
     *
     * @mbg.generated
     */
    TbTenderTaskPeriodMaterialEntity selectByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_period_material
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbTenderTaskPeriodMaterialEntity record, @Param("example") TbTenderTaskPeriodMaterialEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_period_material
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbTenderTaskPeriodMaterialEntity record, @Param("example") TbTenderTaskPeriodMaterialEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_period_material
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbTenderTaskPeriodMaterialEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_period_material
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbTenderTaskPeriodMaterialEntity record);
}