package com.hd.common.dao;

import com.hd.common.entity.TbTenderTaskHisTaskInstEntity;
import com.hd.common.entity.TbTenderTaskHisTaskInstEntityExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbTenderTaskHisTaskInstEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_his_task_inst
     *
     * @mbg.generated
     */
    long countByExample(TbTenderTaskHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_his_task_inst
     *
     * @mbg.generated
     */
    int deleteByExample(TbTenderTaskHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_his_task_inst
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_his_task_inst
     *
     * @mbg.generated
     */
    int insert(TbTenderTaskHisTaskInstEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_his_task_inst
     *
     * @mbg.generated
     */
    int insertSelective(TbTenderTaskHisTaskInstEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_his_task_inst
     *
     * @mbg.generated
     */
    List<TbTenderTaskHisTaskInstEntity> selectByExample(TbTenderTaskHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_his_task_inst
     *
     * @mbg.generated
     */
    TbTenderTaskHisTaskInstEntity selectByPrimaryKey(String historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_his_task_inst
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbTenderTaskHisTaskInstEntity record, @Param("example") TbTenderTaskHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_his_task_inst
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbTenderTaskHisTaskInstEntity record, @Param("example") TbTenderTaskHisTaskInstEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_his_task_inst
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbTenderTaskHisTaskInstEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tender_task_his_task_inst
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbTenderTaskHisTaskInstEntity record);
}