package com.hd.common.dao;

import com.hd.common.entity.TbTechnicalStandardEntity;
import com.hd.common.entity.TbTechnicalStandardEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTechnicalStandardEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technical_standard
     *
     * @mbg.generated
     */
    long countByExample(TbTechnicalStandardEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technical_standard
     *
     * @mbg.generated
     */
    int deleteByExample(TbTechnicalStandardEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technical_standard
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String standardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technical_standard
     *
     * @mbg.generated
     */
    int insert(TbTechnicalStandardEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technical_standard
     *
     * @mbg.generated
     */
    int insertSelective(TbTechnicalStandardEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technical_standard
     *
     * @mbg.generated
     */
    List<TbTechnicalStandardEntity> selectByExample(TbTechnicalStandardEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technical_standard
     *
     * @mbg.generated
     */
    TbTechnicalStandardEntity selectByPrimaryKey(String standardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technical_standard
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbTechnicalStandardEntity record, @Param("example") TbTechnicalStandardEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technical_standard
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbTechnicalStandardEntity record, @Param("example") TbTechnicalStandardEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technical_standard
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbTechnicalStandardEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_technical_standard
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbTechnicalStandardEntity record);
}