package com.hd.common.dao;

import com.hd.common.entity.TbUserScheduleRecordEntity;
import com.hd.common.entity.TbUserScheduleRecordEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbUserScheduleRecordEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_schedule_record
     *
     * @mbg.generated
     */
    long countByExample(TbUserScheduleRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_schedule_record
     *
     * @mbg.generated
     */
    int deleteByExample(TbUserScheduleRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_schedule_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_schedule_record
     *
     * @mbg.generated
     */
    int insert(TbUserScheduleRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_schedule_record
     *
     * @mbg.generated
     */
    int insertSelective(TbUserScheduleRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_schedule_record
     *
     * @mbg.generated
     */
    List<TbUserScheduleRecordEntity> selectByExample(TbUserScheduleRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_schedule_record
     *
     * @mbg.generated
     */
    TbUserScheduleRecordEntity selectByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_schedule_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbUserScheduleRecordEntity record, @Param("example") TbUserScheduleRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_schedule_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbUserScheduleRecordEntity record, @Param("example") TbUserScheduleRecordEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_schedule_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbUserScheduleRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_schedule_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbUserScheduleRecordEntity record);
}